Yanã sanin abin da ke a cikin sammai da ƙasã.
Allah Yãna halitta abin da Yake so, lalle Allah, a kan kõwane abu, Mai ĩkon yi ne.
Haƙĩƙa idan ba ku, hanu ba, haƙĩƙa, zã mu jẽfe ku, kuma haƙĩƙa wata azãba mai raɗaɗi daga gare mu zã ta shãfe ku."
"Ku tafi da rĩgãta wannan, sa'an nan ku jẽfa ta a kan fuskar mahaifina, zai kõma mai gani.
Ya ce: "Bã zã ka gan Ni ba, kuma amma ka dũba zuwa ga dũtse, to, idan ya tabbata a wurinsa, to, zã ka gan Ni."
Kuma mugun nufin Fir'auna bai zama ba fãce yanã a cikin hasãra."
Sunã tambayar ka daga Sa'a, a yaushe tabbatarta take?
Wato su yi iƙrãri da laifinsu.
Kuma ku yi ɗã'a ga Allah da ManzonSa, kuma kada ku yi jãyayya har ku raunana kuma iskarku ta tafi, kuma ku yi haƙuri.
"Kuma lalle ne mũ mun tabbatã bã zã mu buwãyi Allah ba, a cikin ƙasa, kuma bã zã mu buwãye Shi da gudu ba."
Kuma daga inda ka fita, to, sai ka jũyar da fuskarka a wajen Masallãci Tsararre kuma lalle tabbas, shi ne gaskiya daga Ubangijinka.
Kuma zuwa ga Madyana (Mun aika) ɗan'uwansu Shu'aibu. Ya ce: "Ya Mutãnena!
Lalle Allah Mai iyar da umurninSa ne.
Kuma idan kuka yãfe, kuma kuka kau da kai, kuma kuka gãfarta, to, lalle Allah Mai gãfara ne, Mai jin ƙai.
Ana sanya su, su gajũna, mai laifi na gũrin dã zai iya yin fansa, daga azãbar rãnar nan, da ɗiyansa,
Ka ce: "Lalle ne, shiriya ita ce shiriyar Allah.
"Kuma mun kasance muna kũtsãwa tãre da mãsu kũtsãwa."
"Ku ci kuma ku sha daga arziƙin Ubangijinku, kuma kada ku yi fasadi, a cikin ƙasa, kuna mãsu ɓarna."
Kuma ba Mu aika ba a gabãninka fãce mazãje, Munã wahayi zuwa gare su, daga mutãnen ƙauyuka.
Abin karantãwa ne na Lãrabci, ba mai wata karkata ba, ɗammãninsu, su yi taƙawa.
(Allah) Ya ce: "Wuta ce mazaunarku, kunã madawwama acikinta, sai abin da Allah Ya so.
Kamar wannan ne mutãnen da suke a gabãninsu suka ƙaryata, har suka ɗanɗani azãbarMu.
To, ku kau da kai daga gare su don kõ sũ ƙarantã ne, kuma Jahannama ce matattararsu bisa ga sãkamakon abin da suka kasance sunã tsirfatãwa.
Sa'an nan lalle ne aikinMu ne Mu yi musu hisãbi.
Shin akwai wani abin bautawa tãre da Allah?
Lalle zã a tãyar da ku haƙĩƙatan, sa'an nan kuma lalle anã bã ku lãbãri game da abin da kuka aikata.
Kuma bã dõmin wata masĩfa ta sãme su ba sabõda abin da hannayensu suka gabãtar, su ce: "Yã Ubangijinmu! Don me ba Ka aiko wani Manzo zuwa gare mu ba, har mu dinga bĩn ãyõyinKa, kuma mu kasance daga mũminai?"
"Yã abõkaina biyu, na kurkuku! Amma ɗayanku, to, zai shãyar da uban gidansa giya, kuma gudan, to, zã a tsĩrẽ shi, sa'an nan tsuntsãye su ci daga kansa.
Sai (a ce masa) aminci ya tabbata a gare ka daga mazõwa dãma.
"Lalle ne wata ãyã tã kasance a gare ku a cikin ƙungiyõyi biyu da suka haɗu; ƙungiya guda tana yãƙi a cikin hanyar Allah, da wata kãfira, suna ganin su ninki biyu nãsu, a ganin ido. Kuma Allah Yana ƙarfafa wanda Yake so da taimakonSa.
To, Shin, akwai mai tunãni
Shin, sunã jiran (wani abu), fãce dai malã'iku su je musu kõ kuwa Ubangijinka Ya je, kõ kuwa sãshen ãyõyin Ubangijinka ya je.
Lalle ne, shĩ yã kasance, ga ãyõyinMu, mai tsaurin kai.
An wajabta, a kanku, yin ƙisãsi a cikin kasassu. ɗa da ɗa kuma bãwa da bãwa, kuma mace da mace, to, wanda aka yi rangwamen wani abu gare shi daga ɗan'uwansa to a bi da alhẽri da biya zuwa gare, shi da kyautatãwa.
Kuma Yanã da misãli wanda ya fi ɗaukaka a cikin sammai da ƙasã kuma Shĩ ne Mabuwãyi, Mai jin ƙai.
Kuma gari mai kyau, tsirinsa yanã fita da iznin Ubangijinsa, kuma wanda ya mũnana, (tsirinsa) bã ya fita, fãce da wahala; kamar wannan ne, Muka sarrafa ãyõyi dõmin mutãne waɗanda suke gõdẽwa.
A lõkacin da ya kirãyi Ubangijinsa, kira ɓõyayye.
Kuma idan Muka ɗanɗana wa mutãne wata rahama, sai su yi farin ciki da ita kuma idan cũta ta sãme su, sabõda abin da hannayensu suka gabãtar, sai gã su sunã yanke ƙauna,
Lalle ne Allah Yã kasance Mai yãfẽwa Mai gãfara.
"Kuma kada ka kirãyi, baicin Allah, abin da bã ya amfãnin ka kuma bã ya cũtar ka.
Ko sunã da kunnuwa da suke saurãre da su?
Ta ce: "Mẽnene sakamakon wanda ya yi nufin cũta game da iyãlinka? Fãce a ɗaure shi, ko kuwa a yi masa wata azãba mai raɗaɗi."
Sai suka jẽfa igiyõyinsu, da sandunansu, kuma suka ce: "Da ƙarfin Fir'auna lalle ne mũ, haƙĩƙa, mũ ne marinjãya."
Ko a cikin waɗannan akwai abin rantsuwa ga mai hankali (da yake kange shi daga zunubi)?
Allah Yã yãfe laifi daga gare su, Allah Mai gãfara ne, Mai haƙuri.
Sã'an nan ya yi ƙuri'a, sai ya kasance a cikin waɗanda aka rinjaya.
Ku bi Ubangijinku da taƙawa.
Sai Muka fahimtar da ita (mats'alar) ga Sulaiman. Kuma dukansu Mun bã su hukunci da ilmi kuma Muka hõre duwatsu tãre da Dãwũda, sunã tasbĩhi, da tsuntsãye.
Kuma aka ce: "Yã ƙasa!
Suka ce: "Kaitonmu! Lalle mũ ne muka kasance mãsu zãlunci."
Abin sani kawai, wanda ake bautãwa guda ne, sa'an nan sai kuji tsõroNa, Ni kawai."
Kuma idan kuka sãka wa uƙũba to ku sãka wa uƙũba da misãlin abin da aka yi muku uƙũbar da shi.
(Shin, mãsu wannan ni'ima nã daidaita) kamar wanda yake madawwami ne a cikin wutã kuma an shãyar da su wani ruwa mai zãfi har ya kakkãtse hanjinsu?
Waɗannan suna da ijãrarsu a wurin Ubangijinsu.
Kuma ka tambayi waɗanda Muka aika a gabãninka daga Manzannin Mu, "Shin, Mun sanya waɗansu gumãka, wasun (Allah), Mai rahama, anã bauta musu?"
Lalle ne kũ, haƙĩƙa, kunã faɗar magana mai girma!
Lalle ne Allah Yã kasance Mai kaɓar tũba ne, Mai jin ƙai
Yã kũ waɗanda aka bai wa Littãfi! Ku yi ĩmãni da abinda Muka saukar, yana mai gaskatãwa ga abin da yake tãre da ku, tun gabanin Mu shãfe wasu fuskõki, sa'an nan Mu mayar da su a kan bãyayyakinsu, ko Mu la'ane su kamar yadda Muka la'ani masu Asabar.
Lalle wa'adin Allah gaskiya ne. Sabõda haka, kada wata rãyuwa ta kusa ta rũde ku, kuma kada marũɗin nan ya rũɗẽ ku game da Allah.
To, a lõkacin da ya farka, ya ce: "TsarkinKa ya tabbata! Nã tũba zuwa gare Ka, kuma ni ne farkon mũminai."
Shin, kuma a kõ da yaushe suka ƙulla wani alkawari sai wani ɓangare daga gare su ya, yi jĩfa da shi?
Kamar haka Ya hõre su sabõda ku dõmin ku girmama Allah sabõda shiriyar da Ya yi muku.
Kuma Shi ne Ya halitta mutum daga ruwa, sai Ya sanya shi nasaba da surukuta, kuma Ubangijinka Ya kasance Mai ĩkon yi.
To, me ya sãmi waɗannan mutãne, bã su kusantar fahimtar magana?
Kuma Allah ne masani ga azzãlumai
Jahannama ita ce mai isarsu, zã su shigeta. Sabõda haka makõmarsu ta mũnana.
Sa'an nan Allah Ya karɓi tũbarsu, dõmin su tabbata a kan tũba.
Shin, ba zã ku yi tunãni ba?"
Kuma da Mun so, haƙĩƙa dã Mun aika da mai gargaɗi a ciƙin kõwace alƙarya.
Lalle ne shi, daga bãyinMu zaɓaɓɓu yake.
Suka ce: "Tsarki ya tabbata ga Ubangijinmu!
To, wãne ne zai shiryar da shi bãyan Allah?
Waɗanda suke warware alƙawarin Allah daga bãyan ƙulla shi, kuma su yanke abin da Allah Ya yi umurni da shi a sãdar, kuma suna ɓarna a cikin ƙasa, waɗannan sũ ne mãsu hasãra.
Kuma lalle ne haƙĩƙa Mun halittã ku sa'an nan kuma Mun sũrantã ku, sa'an nan kumaMun ce wa malã'iku: "Ku yi sujada ga Ãdam."
Kada ku yi Mini magana."
Shin sunã jiran wani abu? Fãce malã'iku su jẽ musu kõ kuwa umurnin Ubangijinka.
Kuma Mun yi wa mutum wasiyyar kyautatãwa ga uwayensa, kuma idan sun tsananta maka dõmin ka yi shirki da Ni game da abin da bã ka da ilmi gare shi, to, kada ka yi musu ɗã'ã.
Lalle ne Mũ, Munã yi maka bushãra da wani yãro, sunansa Yahaya.
Lalle Shi Mai gãfara ne, Mai gõdiya.
Kuma dõmin (Allah) Ya cika musu (sakamakon) ayyukansu, alhãli kuwa sũ, bã zã a zãlunce su ba.
Kuma kun bar abin da Muka mallaka muku a bayan bayayyakinku, kuma ba Mu gani a tãre da kũ ba, macẽtanku waɗanda kuka riya cẽwa lalle ne sũ, a cikinku mãsu tãrayya ne.
Mai nẽma da wanda ake nẽman gare shi sun raunana."
Ka karanta abin da ake yin wahayi zuwa gare ka daga Littãfi, kuma ka tsayar da salla.
"Ku zama mãsu shã irin shan rãƙuma mãsu ƙishirwa."
Sabõda haka kada ku zãlunci kanku a cikinsu.
Kuma ga Sulaimãn, Mun hõre masa iska, tafiyarta ta safiya daidai da wata, kuma ta maraice daidai da wata. Kuma Muka gudãnar masa da marmaron gaci, kuma daga aljannu (Muka hõre masa) waɗanda ke aiki a gaba gare shi, da iznin Ubangijinsa.
"Abin da dai kuke bautãwa, baiein Allah, gumaka ne, kuma kun ƙirƙira ƙarya. Lalle waɗannan da kuke bauta wa baicin Allah, bã su mallakã muku arziki.
Kuma Allah Ya bayyana shi a gare shi, ya sanar da sãshensa kuma ya kau da kai daga wani sãshe.
Zuriyya ce sãshensu daga sãshe, kuma Allah Mai ji ne, Masani.
Har idan sun zo, (Allah) zai ce, "Ashe kun ƙaryata ãyõyinNa, kuma ba ku kẽwaye su da sani ba?
Lalle nĩ inã tsõrata muku azãbar yini mai girma."
Ka kwaɗaitar da mũminai a kan yãƙi.
Lalle, Allah Ya kasance Mai gãfara, Mai jin ƙai.
Ya ce: "Ga kõwane akwai ninki; kuma amma ba ku sani ba."
Ganinsa bai karkata ba, kuma bai ƙetare haddi ba.
Lalle ne Mũ, Mun halitta ku daga namiji da mace, kuma Muka sanya ku dangõgi da kabĩlõli, dõmin ku san jũna.
Zaɓi wani launi
Kada mũminai su riƙi kãfirai masõya, baicin mũminai.
Lalle wannan (Mai wannan aiki), tabbas, Mai rãyar da halitta ne, kuma Shi Mai ikon yi ne a kan kõme.
Idan sama ta tsãge.
(Allah Ya karɓa) "Yã zakariyya!
Bã ya kasancẽwa ga Allah Ya riƙi wani ɗã. Tsarki ya tabbata a gare shi!
Kuma ba ya halatta a gare ku (maza) ku karɓe wani abu daga abin da kuka bã su, fãce fa idan su (ma'auran) na tsõron bã zã su tsayar da iyãkõkin Allah ba, Idan kun (danginsu) ji tsõron bã zã su tsayar da iyãkõkin Allah ba, to, bãbu laifi a kansu a cikin abin da ta yi fansa da shi.
Bã zã ta zo muku ba fãce kwatsam." sunã tambayar ka, kamar kai masani ne gare ta.
Waɗanda ke yin zihãri daga cikinku game da mãtansu, sũmãtan nan bã uwãyensu ba ne, bãbu uwayensu fãce waɗanda suka haife su.
Lalle ne, Muna ganin jujjũyãwar fuskarka a cikin sama.
Kuma bãbu mai tunãni fãce ma'abũta hankula.
Idan kunã iya zarcẽwa daga sãsannin sammai da ƙasã to ku zarce. Bã za ku iya zarcẽwaba fãce da wani dalĩli.
Lalle ne, wata hujja bayyananniya daga Ubangijinku tã zõ muku! Sai ku cika mũdu da sikeli kumakada ku nakasa wa mutãne kãyansu, kuma kada ku yi fasãdi a cikin ƙasa a bãyan gyaranta.
Sabõda haka kada ku riƙi wasu masõya daga cikinsu, sai sun yõ hijira a cikin hanyar Allah.
Ka ce: "Lalle Ubangijina Yanã jẽfa gaskiya.
Ku tuna ni'imar Allah a kanku a lõkacin da wasu mutãne suka yi niyyar su shimfiɗa hannuwansu zuwa gare ku sai Ya kange hannuwansu daga gare ku, kuma ku bi Allah da taƙawa.
Kuma waɗanda suka ƙãfirta ayyukansu sunã kamar ƙawalwalniyã ga faƙo, mai ƙishirwa yanã zaton sa ruwa, har idan ya jẽ masa bai iske shi kõme ba, kuma ya sãmi Allah a wurinsa, sai Ya cika masa hisãbinsa.
Kuma lalle ne Mun halicci mutum daga ƙeƙasasshiyar lãka, daga baƙin yumɓu wanda ya canja.
Kuma Ubangijinka ne Mafi sani game da wanda yake a cikin sammai da ƙasa.
Kuma idan an ce muku, "Ku kõma."
Kuma lbrãhĩm ya yi wasiyya da ita ga ɗiyansa, kuma Ya'aƙũbu (ya yi wasiyya, suka ce:) "Yã ɗiyãna!
Lalle masihirci, bã ya cin nasara."
Kuma malã'iku sunã shaida.
(Kowannenku) Yanã da waɗansu malã'iku mãsu maye wa jũna a gaba gare shi da bãya gare shi, sunã tsare shi daga umurnin Allah.
Ku hanu (daga faɗin haka) yã fi zama alhẽri a gare ku.
Kamar wancan ne Allah Yake bayyana muku ãyõyinSa, tsammãninku ku yi hankali.
Lalle a cikin wancan akwai ãyõyi ga dukan mai yawan haƙuri, mai yawan gõdiya.
Shin fa, kuna ĩmãni da sãshen Littãfin ne, kuma ku kãfirta da sãshe? To, mẽne ne sakamakon wanda ke aikata wancan daga gare ku fãce wulãkanci a cikin rãyuwar dũniya?
Suka ce: "Yã bãbanmu!
"Kuma waccan ni'ima ce, kanã gõrint a kaina, dõmin kã bautar da Banĩ Isrã'ĩla."
Ba ta zama ba fãce fitinarKa Kanã ɓatarwa, da ita, wanda Kake so kuma kanã shiryarwa da ita, wanda Kake so; Kai ne Majiɓincinmu.
Allah Ya rubũta cẽwa," Lalle zan rinjãya, Nĩ da ManzanniNa." Lalle Allah Mai ƙarfi ne, Mabuwãyi.
"Ashe, idan muka zama ƙasusuwa rududdugaggu?"
Wancan sababinsa, dõmin sũ Manzanninsu sun kasance sunã zuwa gare su da hujjõji bayyanannu, sai suka kãfirta, sai Allah Ya kãmã su.
Kuma ku bi Allah da taƙawa. Kuma ku sani cẽwa lalle ne Allah, ga abin da kuke aikatawa, Mai gani ne.
"Dõmin Ya san lalle, sun iyar da sãƙonnin Ubangijinsu, kuma (Shi Ubangijin) Yã kẽwaye su da sani, kuma Yã lissafe dukan kõme da ƙididdiga."
To, lalle ƙungiyar Shaiɗan, sũ ne mãsu hasãra.
Tsarkinsa, ya tabbata!
Kuma shĩ, ne wanda Ya shimfiɗa kasa, kuma Ya sanya duwãtsu da kõguna a cikinta, kuma daga dukan 'ya'yan itãce Ya sanya ma'aura biyu cikinsu.
Lalle ne Allah Yanã sanin waɗanda ke sancẽwa daga cikinku da saɗãɗe.
"Kuma ka jẽfa abin da ke a cikin hannun dãmanka, ta cafe abin da suka aikata.
Kuma ka ce: "Gaskiya tã zo, kuma ƙarya ta lãlãce.
To, idan sun tũba zai kasance mafi alhẽri gare su, kuma idan sun jũya bãya, Allah zaiazabtã su da azãba mai raɗaɗi a cikin dũniya da Lãhira, kuma bã su da wani masõyi kõ wani mataimaki a cikin kasa.
Shin, sũ ne ke raba rahamar Ubangijinka?
Kuma ya fizge hannunsa, sai ga shi fari ga mãsu dũbi!
Idan suka ga wata ãyã, sai su dinga yin izgili.
Ba ka ga yadda Ubangijinka Ya aikata da Ãdãwa ba?
Ya ce: "Yã ku mashãwarta! Wannenku zai zo mini da gadonta a gabãnin su zo, sunã mãsu sallamãwa?"
Kuma waɗanda bã su da sani suka ce: "Don me Allah bã Ya yi mana magana, ko wata ãyã ta zo mana?"
Kuma lalle ne, haƙĩƙa, Mun bai (wa Bãnĩ Isrã'ĩla Littãfi da hukunci da Annabci, Kuma Mun azurta su daga abũbuwa mãsudãɗi, Kuma Mun fĩfta su a kan mutãnen dũniya (a zãmaninsu).
Suka ce: "Yanzu kã zo da gaskiya.
To, ku ɗanɗana sabõda abin da kuka manta na haɗuwa da ranarku wannan. Lalle Mũ mã Mun manta da ku, kuma ku dãnɗani azãbar dawwama sabõda abin da kuka kasance kunã aikatãwa.
Lalle ne zã a jẽfa shi a cikin Huɗama.
Kuma bã dõmin tunkuɗẽwar Allah ga mutãne sãshensu da sãshe ba lalle ne dã ƙasa tã ɓãci; kuma amma Allah Ma'abũcin falala ne a kan tãlikai.
Ya ce: "Ka tafi.
"Kuma Ka tsare su daga mũnãnan ayyuka, kuma wanda Ka tsare shi daga mũnãnan ayyuka a rãnarnan, to, lalle, Ka yi masa rahama kuma wancan shi ne babban rabo mai girma."
To! Haƙĩƙa wa'adin Allah gaskiya ne.
Ka Ƙiƙiro Mai Gabatar da
Lalle ne mubazzarai sun kasance 'yan'uwan shaiɗanu.
"Lalle ne mu munã kwaɗayin Ubangijinmu, Ya gãfarta mana kurakuranmu dõmin mun kasance farkon mãsu ĩmãni."
Kuma waɗanda suke, sũdaga barin yasassar magana, mãsu kau da kai ne.
Sabõda haka, ku yi ĩmãni da Allah da manzanninSa, kuma kada ku ce, "Uku". Ku hanu (daga faɗin haka) yã fi zama alhẽri a gare ku.
Kuma Lalle ne, wanda ya yi haƙuri kuma ya gãfarta (wa wanda ya zãlunce shi), to shĩ wancan aiki haƙĩƙa, yanã daga manyan al'amura (da Allah ke so).
"Waɗanda aikinsu ya ɓace a cikin rãyuwar dũniya, alhãli kuwa sunã zaton lalle ne sũ, sunã kyautata, (abin da suke gani) aikin ƙwarai?"
Sai Ka yi mini jinkiri zuwa rãnar da ake tãshin su."
Ka ce: "Idan kun ɓõye abin da ke a cikin ƙirãzanku, kõ kuwa kun bayyana shi, Allah Yana sanin sa.
Allah Yã yi alkawarinta ga waɗanda suka kãfirta. Kuma makõmarsu ta mũnana.
To, bone yã tabbata ga waɗanda suka yi zãlunci daga azãbar yini mai raɗaɗi!
Harshen wanda suke karkatai da maganar zuwa gare shi, Ba'ajame ne, kuma wannan (Alƙur'ãni) harshe ne Balãrabe bayyananne.
Ka bi Allah da taƙawa, kuma kada ka yi ɗã'ã ga kãfirai da munãfukai. Lalle, Allah Ya kasance Mai ilmi, Mai hikima.
Lalle shi mai farin ciki ne, mai alfahari.
Kuma lalle haƙĩƙa Mun bai wa Luƙmãn hikima.
Kuma wanda ya sãɓã wa Allah da ManzonSa, kuma ya ƙẽtare iyãkõkinSa, zai shigarda shi wuta, yana madawwami a cikinta, kuma yana da wata azãba mai walãkantarwa.
Ya ce: "Dã dai inã da wani ƙarfi game da ku, kõ kuwa inã da gõyon bãya daga wani rukuni mai ƙarfi?"
Kuma kada ku yi gurin abin da Allah Ya fifita sãshenku da shi a kan sãshe; maza suna da rabo daga abin da suka tsirfanta, kuma mãtã suna da rabo daga abin da suka tsirfanta. Ku rõƙi Allah daga falalarSa.
Lalle shi, Mai ilmi ne, Mai ĩkon yi.
Shin, ba a karɓi alkawarin Littãfi ba a kansu cẽwa kada su faɗa ga Allah, fãce gaskiya, alhãli kuwa sun karanta abin da yake a cikinsa, kuma Gidan Lãhira ne mafi alhẽriga wanda ya yi taƙawa?
Kuma ka abũce su a cikin dũniya gwargwadon sharĩ'a, kuma ka bi hanyar wanda ya mayar da al'amari zuwa gare Ni, sa'an nan zuwa gare Ni makõmarku take sa'an nan In bã ku lãbãri game da abin da kuka kasance kunã aikatãwa."
Ya halicci sammai da ƙasa da gaskiya. Ya ɗaukaka daga abin da suke yi na shirka.
To, wãne ne mafi zãlunci daga wanda ya ƙãga ƙarya ga Allah?"
Kuma Shi ne Mai gãfara, Mai bayyana sõyayya.
Ya ce: "Idan na tambaye ka daga wani abu a bãyanta, to, kada ka abũce ni.
Ã'a, sun ɓace musu Kuma wannan shi ne ƙiren ƙaryarsu da abin da suka kasance sunã ƙirƙirãwa.
Sunã mãsu jin dãɗi da abin da Ubangijinsu Ya ba su, kuma Ubangijinsu Ya tsãre musu azãbar Jahĩm.
Waɗanda malã'iku suke karɓar rãyukansu sunã mãsu jin dãɗin rai, malã'ikun sunã cẽwa.
Kuma daga ƙauyãwã akwai waɗanda suke riƙon abin da suke ciyarwa a kan tãra ce, kuma sunã saurãron aukuwar masĩfa a gare ku, aukuwar mummunar masĩfa ta tabbata a kansu.
Kuma idan watanni, mãsu alfarma suka shige, to, ku yãki mushirikai inda kuka sãmẽ su, kuma ku kãmã su, kuma ku tsare su, kuma ku zaune musu dukkan madãkata. To, idan sun tũba, kuma suka tsayar da salla, kuma suka bãyar da zakka to ku sakar musu da hanyarsu.
Yanã azurta wanda yake so, alhãli kuma Shĩ ne Maiƙarfi, Mabuwãyi.
Ga waɗanda ba su yi ĩmãni da Lãhira ba akwai sifar cũta kuma ga Allah akwai sifa mafi ɗaukaka. Kuma shi ne Mabuwãyi, Mai hikima.
Gaisuwarsu a rãnar da suke haɗuwa da shi "Salãm", kuma Yã yi musu tattalin wani sakamako na karimci.
Lalle ne Ubangijinka Shĩ neMai ƙarfi, Mabuwãyi.
Sabõda haka, ka bar su!
Ga kõwanne daga gare ku Mun sanya sharĩa da hanya (ta bin ta).
Sai aka katse ƙarshen mutãnen, waɗanda suka yi zãlunci.
Sa'an nan kuma, idan sun yi muku ɗa'a, to, kada ku nẽmiwata hanya a kansu.
Lalle ne salla tã kasance a kan mũminai, farilla mai ƙayyadaddun lõkuta.
Kuma lalle ne Sa'ar Tãshin ¡iyãma mai zuwa ce, bãbu shakka a cikinta kuma lalle ne Allah Yanã tãyar da waɗanda suke a cikin ƙaburbura.
Ã'a ba su dai yi ĩmãni ba.
Godiya ta tabbata ga Allah, Ubangijin halittu;
Kuma kõwannensu Mun buga masa misãlai, kuma kõwanne Mun halakar da (shi), halakarwa.
Kuma ma'abũta zumunta, sãshensu ne waliyyan sãshe a cikin Littãfin Allah.
Lalle Shi ne Mabuwãyi, Mai hikima.
Don haka sai ku ɗanɗani azãba sabõda abin da kuka kasance kuna yi na kãfirci."
Kuma Mun sanya abũbuwan rufi a kan zukãtansu dõmin kada su fahimcẽ shi kuma a cikin kunnuwansu (Mun sanya) wani nauyi. Kuma idan sun ga kõwace ãyã bã zã su yi ĩmãni da ita ba har idan sunjẽ maka sunã jãyayya da kai, waɗanda suka kãfirta sunã cẽwa: "Wannan bai zama ba fãce tãtsũniyõyin mutãnen farko."
Da jujjuyãwarka a cikin mãsu yin sujada.
Idan aka ce musu: "Mẽne ne Ubangijinku Ya saukar?" Sai su ce: "Tãtsũniyõyin mutãnen farko."
Lalle ne, Allah nã shigar da waɗanda suka yi ĩmani kuma suka aikata ayyukan ƙwarai a gidãjen Aljanna, kõgunan ruwa na gudana daga ƙarƙashinsu, kuma waɗanda suka kãfirta sunã jin ɗan daɗi (adũniya) kuma sunã ci, kamar yadda dabbõbi ke ci, kuma wutã ita ce mazauni a gare su.
Kuma haƙĩƙa, manzanninMu sun je wa Ibrãhim da bushãra suka ce: "Aminci."
Sannan gare su wulakanci ne a cikin rãyuwar duniya, kuma a Lãhira sunã da wata azãba mai girma.
Bã su iya yãƙar ku gabã ɗaya, fãce a cikin garũruwa mãsu gãnuwa da gãruna, kõ kuma daga bãyan katangu. Yãkinsu a tsãkaninsu mai tsanani ne, kanã zaton su a haɗe, alhãli kuwa zukãtansu dabam- dabam suke.
Kuma lalle ne kanã sãmun mafiya kusantarsu a sõyayya ga waɗanda suka yi ĩmãni su ne waɗanda suka ce: "Lalle mu ne Nasãra."
Kuma lalle ne Ubangijinka, haƙĩƙa, Yanã yin hukunci a tsakaninsu a Rãnar ¡iyãma a cikin abin da suka kasance a cikinsa sunã sãɓã wa jũnã.
Shin, ba a karɓi alkawarin Littãfi ba a kansu cẽwa kada su faɗa ga Allah, fãce gaskiya, alhãli kuwa sun karanta abin da yake a cikinsa, kuma Gidan Lãhira ne mafi alhẽriga wanda ya yi taƙawa?
Kuma waɗandra suka kãfirta kuma suka ƙaryata, game da ãyõyinMu, to, waɗannan sunã da azãba mai wulãkantarwa.
Sabõda haka ku bauta Masa kuma Shi ne wakĩli a kan dukan, kõme.
Kaɗan ƙwarai kuke yin tunãni.
Kada lalle ka yi zaton waɗanda suke yin farin ciki da abin da suka bãyar, kuma suna son a yabe su da abin da ba su aikatã ba. To, kada lalle ka yi zaton su da tsĩra daga azãba.
A lõkacin da mãtar Imrãna ta ce: "Ya Ubangijina! Lalle ni, nã yi bãkancen abin da ke cikin cikĩna gare Ka; ya zama 'yantacce, sai Ka karɓa daga gare ni.
Sa'an nan kuma ku, bãyan wannan, lalle ne masu mutuwa ne.
Kõ kunã zaton a bar ku, tun Allah bai bayyana waɗanda suka yi jihãdi ba daga gare ku, kuma sũ ba su riƙi wani shigeba, baicin Allah da ManzonSa da mũminai?
Kuma hananne ne a kan wata alƙarya da Muka halakar cẽwa lalle sũ, bã su kõmõwa.
Kuma mãtã waɗanda aka saki aurensu, suna jinkiri da kansu tsarki uku.
Shin, Yã zãɓi 'yã'ya mãtã ne a kan ɗiya maza?
Kuma ba ku zama mãsu buwãya ba a cikin ƙasa kuma bã ku da wani majiɓinci, wanin Allah, kuma bã ku da wani mataimaki.
Ã'a, su dai sunã cikin shakka daga hukunciNa Ã'a, ba su i da ɗanɗanar azãba ba.
Ambaton rahamar Ubangijinka ne ga BawanSa Zakariyya.
Kuma suka ce: "Ba ta zama ba, fãce rayuwarmu ta duniya, kuma ba mu zama waɗanda ake tãyarwa ba."
(Ita ce) Wuta."
Abõkin haɗinsa ya ce: "Ya Ubangijinmu!
Ya ce: "Ya Ubangijĩna!
Sai (wannan magana) ta ƙara musu ĩmãni, kuma suka ce: "Mai isarmu Allah ne kuma mãdalla da wakili Shĩ."
Lalle ne Kai Kanã sanin abin da muke ɓõyẽwa, da abin da muke bayyanãwa. Kuma bãbu abin da yake ɓõyẽwa ga A1lah, daga wani abu a cikin ƙasa, kuma bãbu a cikin sama."
Ga waɗanda suka karɓa wa Ubangijinsu akwai abu mafi kyau a gare su, kuma waɗanda suke ba su karɓa Masa ba, to, lalle dã sunã da abin da yake a cikin ƙasa gaba ɗaya da misãlinsa tãre da shi, haƙĩƙa, dã sun yi fansa da shi.
Kuma a wurinsu akwai mãtan aure mãsu gajarta ganinsu ga mazansu, tsãrar jũna.
Kuma suka yi addu'ar alfãnu.
Misãlin abin da suke ciyarwa, a cikin wannan rãyuwar dũniya, kamar misãlin iska ce (wadda) a cikinta akwai tsananin sanyi, ta sãmi shukar wasu mutãne waɗanda suka zãlunci kansu, sai ta halakar da ita.
Kuma wanda Allah Ya ɓatar, to, bã shi da wani mai shiryarwa.
Sai mutãnen Fir'auna suka tsince shi, dõmin ya kasance maƙiyi da baƙin ciki a gare su. Lalle ne Fir'auna da Hãmãna da rundunõninsu, sun kasance mãsu aikin ganganci.
A rãnar nan, zã ta faɗi lãbãrinta.
Lalle sãshen zato laifi ne. Kuma kada ku yi rahõto, kuma kada sãshenku yã yi gulmar sãshe.
Kuma a cikin halittarku da abin da ke watsuwa na dabba akwai ãyõyi ga mutãne mãsu yaƙĩni.
Saukar Littãfi daga Allah Mabuwãyi Mai hikima yake.
"Kuma bãbu abin da ya ɓatar da mu fãce mãsu laifi."
Lalle ne Mun bayyana ãyõyi daki-daki ga mutãne mãsu karɓar tunãtarwa.
Lalle ne, a cikin halittar sammai da ƙasa, da sãɓãwar dare da yini, da jirãge wadaɗnda suke gudana a cikin tẽku (ɗauke) da abin da yake amfãnin mutãne, da abin da Allah Ya saukar daga sama daga ruwa, sai Ya rãyar da ƙasa da shi a bãyan mutuwarta, kuma Ya wãtsa, a cikinta, daga dukan dabba, kuma da jũyãwar iskõki da girgije hõrarre a tsakãnin sama da ƙasa; haƙĩƙa, akwaiãyõyi ga mutãne mãsu yin hankali.
"Kada ku yi gudu. Ku kõmo zuwa ga abin da aka ni'imtar da ku a cikinsa da gidãjenku tsammãninku anã tambayar ku."
Kuma sarkin ya ce: "Ku zo mini da shi in kẽɓe shi ga kaina."
Sunã ƙõnuwa a wutar jahannama, kuma tir da matabbatarsu.
Kuma duffai bã su daidaita, kuma haske bã ya daidaita.
(Nũhu) ya ce: "Bãbu mai tsarẽwa a yau daga umurnin Allah fãce wanda Ya yi wa rahama."
Lalle a cikin wancan, haƙĩƙa, akwai ãyõyi ga mutãne waɗanda ke yin tunãni.
(Su kuma) suka ce: "Mun kasance waɗanda aka raunana a cikin ƙasa."
A Rãnar da kõwane rai yake sãmun abin da ya aikata daga alhẽri, a halarce, da kuma abin da ya aikata daga sharri, alhãli yana gũrin, dã dai lalle a ce akwai fage mai nĩsa a tsakãninsa da abin daya aikata na sharrin!
Bãbu kõme a gare ka game da al'amarin (shiryar da su banda iyar da manzanci). Ko Allah Ya karɓi tũbarsu, kõ kuwa Ya yimusu azãba, to lalle ne sũ, mãsu zãlunci ne.
"Lalle ne nĩ inã nufin ka kõma da zunubina game da zunubinka, har ka kasance daga abõkan wuta. Kuma wannan shĩ ne sakamakon azzãlumai."
Shin, kuwa hujjar abin da ke a cikin littattafan farko, ba ta jẽ musu ba?
(Sãmiri) ya ce: "Nã ga abin da ba su gan shi ba shi, sai na yi damƙa, damƙa guda daga kufan sãwun Manzon, sa'an nan na jẽfa ta.
Kuma bã su da wani ilmi game da shi, bã su bin kõme fãce zato alhãli kuwa lalle zato bã ya amfãnar da kõme daga gaskiya.
Bã haka ba, abin da suka kasance suna aikatãwa dai, yã yi tsãtsa a cikin zukãtãnsu.
Lalle ne shi ya kasance wani bãwa mai gõdiya.
Munã karantãwa a kanka daga lãbarin Mũsã da Fir'auna da gaskiya dõmin mutãne waɗanda suke yin ĩmãni.
Lalle Shĩ, Shĩ ne Mai gãfara, Mai jin ƙai."
Babbar mazaɓen GNOME
Wannan yana daga falalar Allah a kanmu da mutãne, amma mafi yawan mutãne bã su gõdewa."
Tsarkin Ubangijin sammai da ƙasa, Ubangijin Al'arshi, ya tabbata daga abin da suke sifantãwa.
Sa'an nan kuma makõmarku zuwa ga Ubangijinku take, dõmin Ya bã ku lãbãri game da abin da kuka kasance kunã aikatãwa.
Mũsã ya ce masa, "Lalle kai ɓatacce ne, bayyananne."
Suna nẽman ɓõyewa daga mutãne kuma bã su nẽmanɓõyewa daga Allah, alhãli kuwa Shi Yana tãre da su a lõkacin da suke kwãna da niyyar yin abin da bã Ya yarda da shi daga maganar.
Sabõda haka kada ka yi ɗã'ã ga kãfirai, ka yãke su, da shi, yãƙi mai girma.
Daga gare su akwai wata al'umma mai tsakaitãwa kuma mãsu yawa daga gare su, abin da suke aikatawa yã munana.
Kuma zuwa Madayana ɗan'uwansu Shu'aibu, ya ce: "Ya mutãnena!
Ka ce: "Yã Ubangijina!
Kuma tabbas haƙĩƙa, Mun aika mãsu gargaɗi a cikinsu.
Kuma ta ce: "Ashe, akwai wani ƙãri?"
Sabõda wata rahama ce daga Allah ka yi sanyin hali a gare su.
Kuma Mũsã ya ce: "Ubangijĩna ne Mafi sanin wanda ya zo da shiriya daga gare Shi, da wanda ãƙibar gida take kasancẽwa agare shi.
Allah yanã nufin cẽwa, bã zai sanya musu wani rabo ba a cikin Lãhira kuma suna da wata azãba mai girma.
To, daga gare su akwai wanda Allah Ya shiryar, kuma daga cikinsu akwai wanda ɓata ta wajaba a kansa.
Sai muka ƙarfafa waɗanda suka yi ĩmãni a kan maƙiyansu, sabõda haka suka wãyi gari marinjãya.
Me ya hana Ka jinkirta mana zuwa ga wani ajali na kusa?"Ka ce: "Jin dãɗin dũniya kaɗan ne, kuma Lãhira ce mafi alhẽri ga wanda ya yi taƙawa. Kuma bã a zãluntar ku da sĩlĩlin hancin gurtsun dabĩno!
Kuma a lõkacin da Muka cẽ wa malã'iku, "Ku yi sujada ga Ãdamu," sai suka yi sujada, fãce Ibilĩsa, ya ce: "shin, zan yi sujada ga wanda ka halitta shi yanã lãka?"
Wanda yake a wurinsa akwai wani ilmi daga Littafin ya ce: "Ni inã zo maka da shi a gabãnin ƙyaftãwar ganinka ta kõma gare ka."
Idan aka girgiza ƙasã girgizwa.
Ashe, ba ka ga cẽwa lalle Allah Yanã sane da abin da yake a cikin sammai da abin da ke cikin ƙasa ba?
Shin zã Kahalaka mu, sabõda abin da wãwãyen daga gare mu suka aikata? Ba ta zama ba fãce fitinarKa Kanã ɓatarwa, da ita, wanda Kake so kuma kanã shiryarwa da ita, wanda Kake so; Kai ne Majiɓincinmu.
Sa'an nan kuma fitinarsu ba ta kasance ba, fãce dõmin sun ce: "Munã rantsuwa da Allah Ubangijinmu, ba mu kasance mãsu yin shirki ba."
Kada dũkiyõyinku da ɗiyanku su shagaltar da ku daga ambaton Allah. Kuma wanda ya yi haka, to, waɗannan sũ ne mãsu hasãra.
Lalle wɗdanda suka yi ĩmãni, Kuma suka aikata ayyukan ƙwarai, sunã da wani sakamako wanda bai yankẽwa.
Kuma Allah bai zãlunce su ba, kuma amma kansu suka kasance sunã zãlunta.
Lalle a cikin wancan akwai ãyõyi! Dõmin mutãne waɗanda suka yi ĩmãni.
Kuma an biyar musu da la'ana a cikin wannan dũniyada Rãnar Kiyãma. To!
Allah Yãna halitta abin da Yake so, lalle Allah, a kan kõwane abu, Mai ĩkon yi ne.
Kuma lalle ne shĩ, haƙĩƙa, yanã daga mãsu gaskiya.
Sai ku bar ta ta ci a cikin ƙasar Allah, kuma kada ku shãfe ta da wata cũta kar azãba makusanciya ta kãma ku."
Ã'a, sun ƙaryata game da abin da ba su kẽwaye da saninsa ba, kuma fassararsa ba ta riga ta jẽ musu ba.
Kuma kamar wancan ne Muka saukar da shi, Hukunci a cikin Lãrabci.
Sunã da kunya a cikin duniya, kuma sunã da wata azãba mai girma a cikin 1ãhira.
To, shin, akwai wata hanya zuwa ga fita?"
Kuma Ubangijinka, a kan kõme, Mai tsaro ne.
A kanta akwai waɗansu malã'iku mãsu kauri, mãsu ƙarfi. Bã su sãɓã wa Allah ga abin da Ya umurce su, kuma sunã aikata abin da ake umunin su.
Ashe, kun ji tsõron ku gabãtar da sadakõki a gabãnin gãnãwarku?
To, idan ba ku aikata ba to, ku sani fa da akwai yãƙi daga Allah da ManzonSa.
Da Gidan da aka rãyar da shi (da ibãda).
To idan wa'adin na farkonsu yajẽ, za Mu aika, a kanku waɗansu bãyi Nãmu, ma'abũta yãƙi mafĩ tsanani, har su yi yãwo a tsakãnin gidãjenku, kuma yã zama wa'adi abin aikatawa.
Kuma Allah ne Ya halitta ku daga turɓãya, sa'an nan daga ɗigon maniyyi, sa'an nan Ya sanya ku surkin maza da mãtã.
Na Kowa
Kuma wani namiji mũmini daga dangin Fir'auna, yanã bõye ĩmãninsa, ya ce: "Ashe, za ku kashe mutum dõmin ya ce Ubangijina Allah ne, alhãli kuwa haƙĩƙa ya zo muku da hujjõji bayyanannu daga Ubangijinku?
Kuma sun kasance sunã sassaƙa gidãje daga duwãtsu, alhãli sunã amintattu.
Ku bi Ubangijinku da taƙawa Wanda Ya halitta ku daga rai guda, kuma Ya halitta, daga gare shi, ma'auransa, kuma Ya watsa daga gare su maza mãsu yawa da mãtã.
Waɗanda magana ta wajaba a kansu, su ce: "Yã Ubangijinmu! Waɗannan sũ ne waɗanda muka halakar mun halakar da su kamar yadda muka halaka.
Ka karanta abin da aka yi wahayi zuwa gare ka, na littãfin Ubangijinka.
"Ya taimake ku da dabbõbin ni'ima da ɗiya."
Kuma (ka ambaci) lõkacin da Ibrãhĩm ya ce wa ubansada mutãnensa, "Lalle nĩ mai barranta ne daga abin da kuke bautãwa."
Ã'a, an dai ƙawãta wa waɗanda suka kafirta mãkircinsu kuma an kange su daga hanya. Kuma wanda Allah Ya ɓatar to, bãbu wani mai shiryarwa a gare shi!"
Kuma ga Allah, sai mũminai su dõgara."
To, lalle ne sun jẽ wa zãlunci da karkacẽwar magana.
Kuma ku yi haƙuri shi ne mafi alhẽri a gare ku. Kuma Allah Mai gãfara ne Mai jin ƙai.
Kãfirai ba su a cikin kõme fãce rũɗu.
Kuma dukansu sun kasance ne mãsu zãlunci.
Kuma ku aurar da gwaurãye daga gare ku, da sãlihai daga bãyinku, da kuyanginku.
Haba! Me ya same su, suka zama mãsu bijirewa daga wa'azin gaskiya.
Kuma wanda ya ƙirƙira ƙarya, yã tãɓe."
Kuma lalle ne, zã ka sãme su mafiya kwaɗayin mutãne a kan rãyuwa, kuma sũ ne mafiya kwaɗayin rãyuwa daga waɗanda suka yi shirka. ¦ayansu yana son dã zã a rãyar da shi shekara dubu, kuma bã ya zama mai nĩsantar da shi daga azãba dõmin an rãyar da shi.
"Sa'an nan ki ci daga dukan 'ya'yan itãce, sabõda haka ki shiga hanyõyin Ubangijinka, sunã hõrarru."
An dõka ƙasƙanci a kansu a inda duk aka sãme su fãce da wani alkawari daga Allah, da alkawari daga mutãne. Kuma sun kõma da fushi daga Allah, kuma aka dõka talauci a kansu.
Lalle ne Allah Yã kasance Masani ne, Mai hikima.
Lalle ne, a cikinta akwai wasu mutãne mãsu ƙarfi kuma lalle ne bã zã mu shige ta ba sai sun fice daga gare ta, to, idan sun fice daga gare ta, to, lalle ne mu, masu shiga ne."
Wani marmaro ne, a cikinta, ana kiran sa salsabil.
Sai haƙuri mai kyãwo, akwai tsammãnin Allah Ya zo mini da su gabã ɗaya (Yũsufu da 'yan'uwansa). Lalle ne Shĩ ne Masani, Mai hikima."
Lalle Allah Yã kasance Mai tausasãwa Mai labartawa.
Shĩ ne Allah, Makaɗaici, Mai tĩlastãwa.
Kuma ka yi musu gargaɗi da rãnar nadãma a lõkacin da aka hukunta al'amari alhãli kuwa sunã a cikin ɓãta, kuma sũ bã su yin ĩmãni.
Kõ kanã tambayar su wani harãji ne (a kan iyar da Manzanci a gare su)?
"Lalle dã mun kasance bãyin Allah waɗanda aka tsarkake."
Sai aka ɗimautar da wanda yakãfirta.
Wancan yã kasance a cikin Littafi, rubũtacce.
Kunã tsare su daga bãyan salla har su yi rantsuwa da Allah; idan kun yi shakka: "Bã mu sayen kuɗi da shi, kõ dã ya kasance ma'abucin zumunta kuma bã mu ɓõye shaidar Allah. Lalle ne mu, a lõkacin, haƙĩƙa, munã daga mãsu zunubi."
Lalle Allah, Mai ji ne, Mai gani.
Kuma ba su dõge a kan abin da suka aikata ba, alhãli kuwa suna sane.
Kuma ga Allah gaibin sammai da ƙasa yake. Kuma zuwa gare Shi ake mayar da dukan al'amari.
Kuma idan aka ce musu, "Ku ciyar daga abin da Allah Ya azurta ku," sai waɗanda suka kãfirta su ce ga waɗanda suka yi ĩmãni, "Ashe, zã mu ciyar da wanda idan Allah Ya so Yanã ciyar da shi?
Lalle ne, Mũminai sun sãmi babban rabõ.
Lalle, mãsu taƙawa, sunã a cikin gidãjen Aljanna da wata ni'ima.
Lalle nĩ, na zãlunci kaina, kuma nã sallama al'amari tãre da Sulaiman ga Allah, Ubangijin halittu."
Suka ce: "Muna bauta wa Abin bautawarka kuma Abin bautawar ubanninka lbrãhĩm da lsmã'ĩla da Is'hãƙa, Ubangiji Guda, kuma mu a gare Shi mãsu miƙa wuya ne."
Waɗanda suka ce: "Lalle ne Allah Yã yi alkawari zuwa gare mu, kada mu yi ĩmãni sabõda wani Manzo sai yã zo mana da Baiko wadda wuta za ta ci." Ka ce: "Lalle ne wasu manzanni sun je muku, a gabãnĩna, da hujjõji bayyanannu, kuma da abin da kuka faɗa, to, don me kuka kashe su, idan kun kasance mãsu gaskiya?"
To, idan sun yi wanka sai ku je musu daga inda Allah Ya umurce ku.
Shi ne Wanda Ya halitta mutuwa da rãyuwa domin Ya jarraba ku, Ya nũna wãye daga cikinku ya fi kyãwon aiki, Shi ne Mabuwãyi, Mai gafara.
Kuma idan ma'abũta zumunta da marãyu da matalauta suka halarci rabon, to, ku azurta su daga gare shi, kuma ku faɗa musu magana sananniya ta alhẽri.
Sa'an nan bãbu wanda ya yi ĩmãni da Mũsa fãce zuriya daga mutãnensa, a kan tsõron kada Fir'auna da shũgabanninsu su fitinẽ su.
Kuma ba ya halatta ga mũmini kuma haka ga mũmina, a lõkacin da Allah da Manzonsa Ya hukunta wani umurni, wani zãɓi daga al'amarinsu ya kasance a gare su. Kuma wanda ya sãɓã wa Allah da ManzonSa, to, yã ɓace, ɓacẽwa bayyananna.
Sa'an nan a Rãnar ¡iyãma (Allah) Yanã kunyatã su, kuma Yanã cẽwa: "Inã abõkan tãrayyaTa, waɗanda kuka kasance kunã gãbã a cikin ɗaukaka sha'aninsu?"
Lalle ne Ubangijinka Shĩ neMai ƙarfi, Mabuwãyi.
Shin fa, bã zã ku hankalta ba?
Nĩ ce nã nẽme shi daga kansa. Kuma lalle ne shĩ, haƙĩƙa, yanã daga mãsu gaskiya.
Babbar ƙarfin GMOME itace jama'ar mu mai aminci. Kowa zasu iya ƙari ga GNOME ko da sun iya tsari ko idan basu iya ba, don GNOME ta ƙara kyau.
Suka ce: "Ka rõƙa mana Ubangijinka Ya bayyana mana abin da yake launinta."
Kuma lalle ne, idan ka tambaye, su haƙĩƙa, sunã cẽwa, "Abin sani kawai, mun kasance munã hĩra kuma munã wãsã.
¦.
Kuma Ubangijinika Wadãtacce ne Ma'abũcin rahama. Idan Yã so zai tafi da ku, kuma Ya musanya daga bãyanku, abin da Yake so, kamar yadda Ya ƙãga halittarku daga zũriyar wasu mutãne na dabam.
Dukkan wanda yake a cikin sammai da ƙasa bai zama ba fãce mai jẽ wa Mai rahama ne yanã bãwã.
Kuma a lõkacin da wata ƙungiya daga gare su, ta ce, "Ya mutãnen Yasriba! Bã ku da wani matsayi, sabõda haka ku kõma."
Sa'an nan Allah Ya ɓatar da wanda Yake so kuma Ya shiryar da wanda Yake so, Kuma shĩ ne Mabuwãyi, Mai hikima.
Yã ku waɗanda suka yi ĩmãni! Lalle ne, Allah zai jarraba ku da wani abu, daga farauta, hannuwanku da mãsunku sunã sãmun sa dõmin Allah Ya san wanda yake tsoron Sa a fake.
(Nan gaba) zã ku sani.
Suna yaudarayya da Allah da waɗanda suka yi ĩmãni, alhãli bã su yaudarar kõwa fãce kansu, kuma bã su sakankancẽwa!
Kuma waɗanda suka yi zãlunci suka bin abin da aka ni'imtar da su a cikinsa, suka kasance mãsu laifi.
Kamar wancan alhãli kuwa haƙĩƙa, Mun kẽwaye da jarrabãwa ga abin da ke gunsa.
Kuma suka yi kira, "Ya Mãliku!
To, sai ya fãra (bincike) da jikunansu a gabãnin jakar ɗan'uwansa. Sa'an nan ya fitar da ita daga jakar ɗan'uwansa.
Abin da aka sani kawai, Allah Ubangiji ne Guda.
Shin, sunã da wani abin bautãwa ne wanda bã Allah ba?
Ka azurta mu, kuma Kai ne Mafĩfĩcin mãsu azurtawa."
Sabõda haka, kada ka kira wani abin bautãwa na dabam tãre da Allah, sai ka kasance daga waɗanda ake yi wa azãba.
TsarkinSa yã tabbata kuma Ya ɗaukaka daga abin da suke faɗã, ɗaukaka mai girma.
Kuma waɗanda suka yi ĩmãni da Allah da MazanninSa waɗannan sũ ne kamãlar gaskatãwa kuma su ne mãsu shahãda awurin Ubangjinsu. sunã da sakamakonsu da haskensu. waɗanda suka kafirta kuma suka ƙaryata game da ãyõyinMu, waɗannan su ne'yan Jahĩm.
Wancan sababinsa, dõmin sũ Manzanninsu sun kasance sunã zuwa gare su da hujjõji bayyanannu, sai suka kãfirta, sai Allah Ya kãmã su.
Lalle shĩ ya kasance daga mãsu ɓarna.
Kuma lalle ne, haƙĩƙa, Mun zãɓe shi, a cikin dũniya, kuma lalle ne shi, a cikin Lãhira, haƙĩƙa, yana daga sãlihai.
Kuma aka ce: "Yã ƙasa! Ki haɗiye ruwanki, kuma yã sama!
Ka ce: "Bãbu abin da yake sãmun mu fãce abin da Allah Ya rubũta sahõda mu. Shĩ ne Majiɓincinmu.
Tsarki ya tabbata ga Allah daga abin da suke yi na shirki!
Kuma Allah ne Mabuwãyi, Mai hikima.
Lalle a cikin wancan, haƙĩƙa, akwai ãyõyi ga mutãne waɗanda ke yin tunãni.
Allah Yã riƙi Ibrãhĩm badãɗayi.
"Kuma bã ni kuɓutar da kaina. Lalle ne rai, haƙĩƙa, mai yawan umurni ne da mummũnan aiki, fãce abin da Ubangjina Ya yi na; rahama.
Lalle ni, Manzo ne amintacce zuwa gare ku."
Lalle ne zato bã ya wadãtar da kõme daga gaskiya.
Kuma tun da ba su shiryu game da shĩ ba, to, zã su ce, "Wannan ƙiren ƙarya ne daɗaɗɗe."
"Lalle ne nĩ, na fuskantar da fuskata ga wanda, Ya ƙãga halittar sammai da ƙasa, inã mai karkata zuwa ga gaskiya, kuma bã ni cikin mãsu shirki."
Kuma ka dõgara a kan Rãyayye wanda bã Ya mutuwa, kuma ka yi tasbĩhi game da gõde Masa. Kuma Yã isa zama Mai ƙididdigewa ga laifuffukan bãyinSa.
Ya ce: "Lalle ne, Shi, Yana cewa: "Lalle ne ita sãniya ce; bã tsõfuwa ba, bã kuma budurwa ba, tsakãtsaki ce a tsakãnin wancan,' sai ku aikata abin da ake umurninku."
Kuma ku tabbata a cikin gidãjenku, kuma kada ku yi fitar gãye-gãye irin fitar gãye-gãye ta jãhiliyyar farko.
Don me Ka tãyar da ni makãho alhãli kuwa nã kasance mai gani?"
Da wanda ke a cikin dũniya duka gabã ɗaya, sa'an nan fansar, ta tsĩrar da shi.
TsarkinSa ya tabbata kuma Yã ɗaukaka daga gabin da duk suke yin shirki da Shi."
"Kuma amma bangon, to, yã kasance na waɗansu yãra biyu ne, marãyu a cikin birnin, kuma akwai wata taska tãsu a ƙarƙashinsa, kuma ubansu ya kasance sahĩhin mutum ne, dõmin haka Ubangijinka Ya yi nufin su isa iyãkar ƙarfinsu, kuma sũ, su fitar da taskarsu, sabõda rahama ne daga Ubangijinka. Kuma ban yi shi ba daga umurnĩna.
"Kuma bã ni zaton sa'a mai tsayuwa ce, kuma lalle ne, idan an mayar da ni zuwa ga Ubangijiĩna, to, lalle ne, zan sãmi abin da yake mafi alhẽri daga gare ta ya zama makõma."
Kuma sai mũminai su dogara ga Allah.
Wancan Shĩ ne Allah Ubangijĩna, a gare Shi na dõgara, kuma zuwa gare Shi nake mayar da al'amarĩna.
_Juya kan fanel masu tsaiwa
Shin suna jira, fãce dai Allah Ya je musu a cikin wasu inuwõyi na girgije, da malã'iku, kuma an hukunta al'amarin?
Ashe, ba ku gani ba, cẽwa Allah Yã hõre muku abin da ke a cikin sammai da abin da ke a cikin ƙasã, kuma Ya zuba ni'imõminsa a kanku, bayyanannu da ɓõyayyu?
Ya ce: "Yã Ubangijina! Yãya yãro zai sãmu a gare ni, alhãli kuwa, lalle tsũfa ya sãme ni, kuma mãtãta bakarãriya ce?"
Gaskiya ta auku, kuma abin da suke aikatãwa ya ɓãci.
"Ka saki Banĩ Isrã'ila tãre da mu."
Wannan shĩ ne halittar Allah.
Lalle ne Allah Yã kasance ga dukkan kõme, Masani.
To, a, lõkacinda suka yi mãsa alkawari, ya ce: "Allah ne wakĩli a kan abin da muke faɗa."
"Zuwa ga yinin lõkaci sananne."
Kuma Allah Ya isa Ya zama Mai bincike.
To, mẽne ne a bãyan gaskiya fãce ɓãta?
Waɗancan suna da wata gãfara da wani arziki mai karimci.
Kuma azzãlumai bã su da wasu mataimaka.
Ko suna hãsadar mutãne ne a kan abin da Allah Ya bã su daga falalarSa?
A rãnar da wasu fuskõki suke yin fari kuma wasu fuskõki suke yin baƙi (zã a ce wa waɗanda fuskokinsu suke yin baƙin): "Shin kun kãfirta a bayan ĩmãninku?
Da ƙwãya mai sõshiya da ƙamshi.
Kuma Allah ne Ya fitar da ku daga cikunan iyãyenku, ba da kunã sanin kõme ba, kuma Ya sanya muku ji da gannai da zukãta, tsammãninku zã ku gõde.
Sai mũnãnan abũbuwan da suka aikata ya sãme su, kuma abin da suka kasance sunã yi na izgili ya wajaba a kansu.
Kada ku haramta abubuwa mãsu dãɗi da Allah Ya halatta muku, kuma kada ku ƙetare haddi.
Labarai
An wajabta, a kanku, yin ƙisãsi a cikin kasassu. ɗa da ɗa kuma bãwa da bãwa, kuma mace da mace, to, wanda aka yi rangwamen wani abu gare shi daga ɗan'uwansa to a bi da alhẽri da biya zuwa gare, shi da kyautatãwa. Wancan sauƙaƙewa ne daga Ubangijinku, kuma rahama ce.
Abin da kuke kira zuwa gare shi, ya yi nauyi a kan mãsu shirki.
Ka ce: "Lalle mãsu hasãra, sũ ne waɗanda suka yi hasarar rãyukansu da iyãlansu, a Rãnar ¡iyãma.
Lallai ne ƙidãyayyun watanni a wurin Allah watã gõma shã biyu ne a cikin Littãfin Allah, a Rãnar da Ya halicci sammai da ƙasa daga cikinsu akwai huɗu mãsu alfarma. Wannan ne addini madaidaici.
Ka ce: "Shin makãho da mai gani sunã daidaita?
Kuma gaskiya ta zo maka a cikin wannan da wa'azi da tunãtarwã ga mãsu ĩmãni.
Lalle ne waɗanda suka kãfirta, lalle dã sunã da abin da ke a cikin ƙasa gabã ɗaya da misãlinsa tãre da shi, dõmin su yi fansa da shi daga azãbar Rãnar ¡iyãma, bã a karɓarsa daga gare su, kuma sunã da azãba mai raɗadi.
Suka ce: "Ubangijinku ne Mafi sani ga abin da kuka zauna.
Lalle ne a cikin wancan akwai ãyõyi ga mãsu tsõkaci da hankali.
Kuma wãne ne mafi gaskiya daga Allah ga 1ãbãri.
Kuma lalle, haƙĩƙa, gargaɗin ya jẽ wa mabiyan Fir'auna.
Kuma Fir'auna ya ɓatar da mutãnensa, kuma bai shiryar (dasu) ba.
Ka haƙurtar da ranka tãre da waɗanda ke kiran Ubangijinsu, sãfe da maraice, sunã nufin yardarSa.
To, a lõkacin da suka kõma zuwa ga ubansu, suka ce: "Yã bãbanmu! An hana mu awo sai ka aika ɗan'uwanmu tãre da mu.
Shin, ba ka gani ba zuwa ga waɗanda aka ce musu: "Ku kange hannuwanku, kuma ku tsayar da salla, kuma ku bãyar da zakka."?
Sabõda yã kasance mai dũkiya da ɗiya.
Kuma a lokacin da Mũsa ya nemi shãyarwa domin mutãnensa, Muka ce; "Ka dõki dũtsen da sandarka."
Ka bã mu sanyin idãnu daga mãtanmu da zũriyarmu, kuma Ka sanya mu shũgabanni ga mãsu taƙawa."
To, a lõkacin da, suka gan shi, suka girmamã shi, kuma suka yanyanke hannãyensu, kuma suka ce: "Tsarki yanã ga Allah! Wannan bã mutum ba ne!
Abin sani kawai, Allah Yanã nufin Ya yi musu azãba da su a cikin dũniya, kuma rãyukansu su fita alhãli kuwa sunã kãfirai.
Lalle ne shĩ, azzalumai bã zã su ci nasara ba.
Lalle Shĩ, Maɗaukaki ne Mai hikima.
To, ka yi masa bushara da azãba mai raɗaɗi.
Kuma Mu, Muna ganin ta a kusa.
Kuma lalle ne Mun girmama 'yan Adam, kuma Muka ɗauke su a cikin ƙasa da tẽku kuma Muka azurta su daga abũbuwa mãsu dãɗi kuma Muka fĩfĩta su a kan mãsu yawa daga waɗanda Muka halitta, fĩfĩtãwa.
Kuma ka ce wa waɗanda aka bai wa littãfi da Ummiyyai: "Shin kun sallama?"
Lalle wannan, haƙĩƙa, abu ne mai ban mãmãki."
Kuma mafi yawansu bã su biyar kõme fãce zato. Lalle ne zato bã ya wadãtar da kõme daga gaskiya.
Ya ce: "Ya Mũsã! Lalle ne Nĩ, Nã zãɓe ka bisa ga mutãne da manzanciNa, kuma da maganãTa.
"Ya sako (girgijen) sama a kanku da ruwa mai ɓuɓɓuga."
"Dõmin ku shiga a cikinta, hanyõyi mãsu fãɗi."
Kuma abin da yake a gare ku na ni'ima, to, daga Allah ne.
Kuma lalle ne gidan Lãhira shĩ ne mafi alhẽri ga waɗanda suka yi taƙawa?
Lalle ne mu, munã a nan zaune."
Ya shar'anta muku, game da addini, abin da Ya yi wasiyya da shi ga Nũhu da abin da Muka yi wahayi da shi zuwa gare ka, da abin da Muka yi wasiyya da shi ga Ibrãhĩm da Mũsã da Ĩsã, cẽwa ku tsayar da addini sõsai kuma kada ku rarrabu a cikinsa.
To, halaka ta tabbata ga Madyana kamar yadda Samũdãwa suka halaka.
Daga waɗanda suka tũba (Yahũdu), akwai wasu sunã karkatar da magana daga wurãrenta suna cẽwa: "Munjiya kuma mun ƙiya, kuma ka jiya a wani wurin jiyãwa, kuma rã'ina (da ma'anar 'ruɓaɓɓe'), ka tsare mu," dõmin karkatarwa da harsunansu, kuma dõmin sũkã a cikin addini.
Wancan ya fi sauƙi ga a gane su dõmin kada a cũce su.
Lalle wannan, haƙiƙa, wani abu ne ake nufi!"
Shi ne wanda Yake suranta ku a cikin mahaifu yadda Yake so.
Kuma Shĩ ne da gõdiya, a cikin sammai da ƙasã kuma da lõkacin yamma da lõkacin zawãli.
Allah Ya yãfe maka laifi.
Kuma wanda Allah Ya ɓatar, to, bã shi da wani mai shiryarwa.
Kuma idan kuka sãka wa uƙũba to ku sãka wa uƙũba da misãlin abin da aka yi muku uƙũbar da shi.
Manzanninsu sun jẽ musu da ãyõyayi bayanannu.
Ka ce: "Lalle ne ni, an hana ni in bauta wa waɗanda kuke kira daga baicin Allah."
Kuma ga Allah mulkin sammai da ƙasa yake.
Waɗancan alƙaryu Munã gaya maka daga lãbãransu, kuma lalle ne, haƙĩƙa manzanninMu sun jẽ musu da hujjõji bayyanannnu; to, ba su kasance sunã yin ĩmãnida abin da suka ƙaryata daga gabãni ba.
Sunã kãwo uzurinsu zuwa gare ku idan kun kõma zuwa gare su Ka ce: "Kada ku kãwo wani uzuri, bã zã mu amince muku ba.
Lalle ne, mutãnen kirki zã su sha daga finjãlin giya abin gaurayarta yã kãsance kãfur ne.
Wãne ne mafi zãlunci daga wanda yake ƙirƙira karya ga Allah, kõ kuwa ya ƙaryata game da ãyõyinsa?
Shin bã ku hankalta?
Sa'an nan bã zai mutu ba a cikinta, kuma bã zai rãyu ba.
Kumaku bi Allah da takƙawa, kuma Allah Ya sanar da ku. Kuma Allah ga dukan kõme Masani ne.
Dã ka lẽka (a kan) su (dã) lalle ne, ka jũya daga gare su a guje kuma (dã) lalle ne ka cika da tsõro daga gare su.
Kuma idan suka nẽme ku taimako a cikin addini, to taimako yã wajaba a kanku, fãce a kan mutãne waɗanda a tsakãninku da tsakãninsu akwai wani alkwari.
Yanã kiran baicin Allah, abin da bã ya cũtarsa da abin da bã ya amfãninsa! waccan ita ce ɓata mai nĩsa.
Lalle ne Kai Masanin abubuwan fake ne."
Ya ce: "Kamar wancan Ubangijinka Ya ce.
"Shin, kuma kun yi mãmãki cẽwa ambato daga Ubangijinku ya zo muku a kan wani namiji daga gare ku, dõmin ya yi muku gargaɗi?
(Suna cẽwa): "Munã ciyar da ku ne dõmin nẽman yardar Allah kawai, bã mu nufin sãmun wani sakamako daga gare ku, kuma bã mu nufin gõdiya.
To, a lõkacin da aka wajabta yãƙin a kansu, suka jũya, sai kaɗan daga gare su. Kuma Allah Masani ne ga azzãlumai.
Da Mun yi nufin Mu riƙi wani abin wãsa dã Mun riƙe shi daga gunMu, idan Mun kasance mãsu aikatãwa.
Suka ce, "Lalle mũ dai mãsu kafirta ne game da abin da aka aiko ku da shi."
Ka ce: "To, ku tunkuɗe mutuwa daga rãyukanku, idan kun kasance mãsu gaskiya."
Lalle ne, Allah Ya saya daga mummunai, rãyukansu da dũkiyõyinsu, da cẽwa sunã da Aljanna, sunã yin yãƙi a cikin hanyar Allah, sabõda haka sunã kashẽwa anã kashẽ su.
Lalle ne sũ, bã zã su wadãtar da kai da kõme ba daga Allah.
To, ga Allah mãkircin yake gabã ɗaya.
Rãnar da zã a yi bũsa a cikin ƙaho, sai ku zo, jama'a jama'a.
Kuma idan kun yi tafiya a cikin ƙasa to, bãbu laifi a kanku ku rage daga salla idan kun ji tsõron waɗanda suka kãfirta su fitine ku.
Allah Ya ce: "Wanda ya kãfirta ma Ina jiyar da shi dãɗi kaɗan, sa'an nan kuma Ina tĩlastã shi zuwa ga azãbar Wuta. Kuma makõmar, ta munana."
Ya ce: "Yã Ãdam!
Kuma wãne ne mafi zãlunci daga wanda ya ƙirƙira ƙarya ga Allah, kõ kuwa ya ce: "An yi wahayi zuwa gare ni," alhãli kuwa ba a yi wahayin kõme ba zuwa gare shi, da wanda ya ce: "zan saukar da misãlin abin da Allah Ya saukar?"
Kuma kada waɗannan da suke yin rõwa da abin da Allah Ya bã su daga falalarSa su yi zaton shĩ ne mafi alhẽri a gare su A'a, shĩ mafi sharri ne a gare su. Zã a yi musu saƙandami da abin da suka yi rõwa da Shi a Rãnar ¡iyãma Kuma ga Allah gãdon sammai da ƙasa yake, kuma Allah, ga abin da kuke aikatãwa, Masani ne.
Waɗannan sunã da azãba Mai raɗaɗi.
Sa'an nan, su zama mãsu gaugãwa (da umurnin Allah) kamar suna tsẽre.
"Kamar al'ãdar mutãnen Fir'auna da waɗanda suke gabãninsu, sun kãfirta da ãyõyin Allah, sai Allah Ya kãma su da zunubansu. Lalle Allah ne Mai ƙarfi, Mai tsananin uƙũba.
Kamar haka Muke sãka wa kõwane mai yawan kãfirci.
Fãce wanda ya sãci saurãre sai wutar yũlã bayyananniya ta bĩ shi.
Kuma a lõkacin da ya kai ƙarfinsa, kuma ya daidaita, Mun bã shi hukunci da ilmi kuma kamar haka Muke sãka wa mãsu kyautatãwa.
"Bã zan bautã wa abin da kuke bautã wa ba."
Allah ne Wanda ke aika iskõki, sai su mõtsar da girgije, sa'an nan Ya shimfiɗa shi a cikin sama yadda Yake so, kuma Ya sanya shi wani ɓaɓɓake, sa'an nan ka ga ruwa na fita daga tsakãninsa.
Waɗanda suka rinjãya a kan al'amarinsu suka ce: "Lalle mu riƙi masãllãci a kansu."
Sũ ne maƙiyan, sai ka yi saunarsu.
Gaisuwarsu a rãnar da suke haɗuwa da shi "Salãm", kuma Yã yi musu tattalin wani sakamako na karimci.
Ya ce: "Za mu dũba shin kã yi gaskiya ne, kõ kuwa kã kasance daga maƙaryata?"
Kuma sai mutãnen injĩla su yi hukunci da abin da Allah ya saukar a cikinta.
Lalle Ubangijinka Mai aikatãwa ne ga abin da Yake nufi.
Kuma Allah Ya buga misãli, wata alƙarya ta kasance amintacciyã, natsattsiyã, arzikinta yanã je mata a wadãce daga kõwane wuri sai ta kãfirta da ni'imõmin Allah, sabõda haka Allah ya ɗanɗana mata tufãfin yunwa da tsõro, sabõda abin da suka kasance sunã sanã'antãwa.
Lalle Allah ne Ubangijinku wanda Ya halicci sammai da ƙasa a cikin kwãna shida, sa'an nan kuma Ya daidaita a kan Al'arshi Yanã gudãnar da al'amari.
Kuma idan sun auna musu da zakka ko da sikẽli, suna ragẽwa
Haƙĩƙa, waɗanda suka ƙaryata game da gamuwa da Allah sun yi hasãra. Kuma ba su kasance mãsu shiryuwa ba.
Yanã sanin abin da ke gaba gare su da abin da ke bãyansu, kuma zuwa ga Allah ake mayar da al'amura.
Sai Muka karɓa masa kuma Muka tsĩrar da shi daga baƙin ciki.
Lalle ne haƙĩƙa abin kula yã kasance a cikin ƙissoshinsu ga masu hankali.
Kuma mũ, zuwa gare Shi mãsu sallamãwa ne."
Lalle ne nĩ, inã tsõron ya musanya addininku, kõ kuwa ya bayyana ɓarna a cikin kasã."
"Ya Mũsã! Ka fuskanto, kuma kada ka ji tsõro lalle ne kanã daga waɗanda ke amintattu."
Ga marãya ma'abũcin zumunta.
An hukunta al'amarin, wanda a cikinsa kuke yin fatawa."
Mũne ne ya yi ganinSa da jinSa!
Ku yi ĩmani da Allah da ManzonSa, kuma ku yi jihãdi ga ɗaukaka kalmar Allah game da dũkiyõyinku da rãyukanku.
Shin, kuma daga wannan lãbãri kuke mãmãki?
Ka ce: "Bã ni mallaka wa raina wani amfãni, kuma haka ban tunkuɗe wata cũta, fãceabin da Allah Ya so.
Lalle ne ãyõyiNa sun jẽ maka, sai ka ƙaryata a game da su, kuma ka yi girman kai, kuma ka kasance daga kãfirai."
Zã ya shiga wuta mai hũruwa.
Lalle NĨ Mai karɓar ranka ne, kuma Mai ɗauke ka ne zuwa gare Ni, kuma Mai tsarkake ka daga waɗanda suka kãfirta, kuma Mai sanya waɗanda suka bĩ ka a bisa waɗanda suka kãfirta har Rãnar ¡iyãma. Sa'an nan kuma zuwa gare Ni makõmarku take, sa'an nan in yi hukunci a tsakãninku, a cikin abin da kuka kasance kuna sãɓã wa jũna.
Sun ƙaryata game da ãyõyinMu, dukansu sai Muka kãma su, irin kãmun Mabuwãyi, Mai ĩkon yi.
Suka ce: "Ba ku zama ba fãce mutãne misãlinmu kuma nufinku ku kange mu daga abin da iyãyenmu suka kasance sunã bautãwa sai ku zo mana da dalĩli mabayyani."
Kuma a gittã su ga Ubangijinka sunã sahu guda, (Mu ce musu), "Lalle ne haƙĩƙa kun zo Mana, kamar yadda Muka halitta ku a farkon lõkaci.
Yinin da mutãne ke tãshi zuwa ga Ubangijin halitta?
A'aha!
Al'amarin Allah yã zo, sabõda haka kada ku nẽmi hanzartãwarsa.
"Su zõ maka da duka matsafi, mai ilmi."
Kuma idan kã gan su, sai jikunansu su bã ka sha'awa kuma idan sun faɗa, zã ka saurãra ga maganarsu.
Waɗannan ne abõkan wuta, sunã madawwama a cikinta.
Suna madawwama a cikinta, bã su nẽman makarkata daga barinta.
"In dã dai ita, tã kasance mai halakã ni gabã ɗaya ce!
Kuma Yanã da misãli wanda ya fi ɗaukaka a cikin sammai da ƙasã kuma Shĩ ne Mabuwãyi, Mai jin ƙai.
Kuma albarkar wanda ke da mulkin sammai da ƙasã abin da ke a tsakãninsu tã bayyana, kuma a wurinSa ne ilmin Sa'a yake, kuma zuwa gare Shi ake mayar da ku.
Lalle ne Shi shĩ ne Mai ji, Mai gani.
Kuma amma sũ mutãne ne mãsu tsõro.
Lalle ne Safã da Marwa suna daga wurãren ibãdar Allah, to, wanda ya yi hajin ¦ãki kõ kuwa ya yi Umra, to, bãbu laifi a kansa ga ya yi ɗawãfi gare su, su biyu.
Waɗanda magana ta wajaba a kansu, su ce: "Yã Ubangijinmu! Waɗannan sũ ne waɗanda muka halakar mun halakar da su kamar yadda muka halaka.
Kun yi hujjacẽwa a cikin abin da yake kunã da wani ilmi game da shi, to, don me kuma kuke yin hujjacẽwa a cikin abin da bã ku da wani ilmi game da shi?
Haƙĩƙa mun kasance a cikin gafala daga wannan!
Sabõda haka, ka tsarkake sũnan Ubangijinka, Mai karimci.
Kuma Muka yi tattali, dõmin kãfirai, azãba mai raɗaɗi.
Waɗanda suke yin rõwa, kuma sunã umurnin mutãne da yin rõwa, kuma suna ɓõyewar abin da Allah Ya bã su na falalarSa.
Kuma bã dõmin kalmar hukunci ba, da lalle, an yi hukunci a tsakãninsu.
Ya kai Annabi! Ma'ishinka Allah ne, kai da wanda ya biye maka daga mũminai.
Ka ce: "Ĩ, ina rantsuwa da Ubangijĩna.
Kuma suka ce: "Godiya ta tabbata ga Allah Wanda Ya tafiyar da baƙin ciki daga gare mu.
Allah Ya yãfe maka laifi.
Ka dũba yadda Muke sarrafaãyõyi, Sa'an nan kuma sũ, sunã finjirẽwa.
To, Nĩsa ya tabbata ga Samũdãwa.
Lalle, waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, sunã da gidãjen Aljannar ni'ima.
Ba ku da wani abin bautãwa fãce shi kuma kada ku rage mũdu da sikẽli.
Ku kasance mãsu tsayin daka dõmin Allah mãsu shaida da ãdalci. Kuma kada ƙiyayya da wasu mutane ta ɗauke ku a kan bã zã ku yi ãdalci ba.
Kuma waɗannan suna cikin sãlihai.
Abin sani kawai, an sanya Asabar a kan waɗanda suka sãɓã wajũna a cikin sha'aninsa.
Ã'a, ku mutãne ne mãsu ƙẽtarẽwa!"
Dõmin su ɗauki zunubansu cikakku a Rãnar ¡iyãma, kuma daga zunuban waɗanda suke ɓatarwa bã da wani ilmi ba.
Kuma aka ce wa waɗanda suka yi taƙawa, "Mẽne ne Ubangijinku Ya saukar?"
Lalle Shĩ, Mai ƙididdigewa ne ga abin da suke aikatãwa.
Jerin wasu shiryoyin ayuka da aka sani
To, wãne ne mafi zãlunci daga wanda ya ƙãga ƙarya ga Allah?"
Watan Ramalãna ne wanda aka saukar da Alƙur'ãni a cikinsa yana shiriya ga mutãne da hujjõji bayyanannu daga shiriya da rarrabẽwa.
Suka ce: "Ba mu kasance munã a cikin mãsu salla ba."
Kuma babu wani abu daga hisãbinsu (mãsu kutsãwa a cikin ayõyin Allah (a kan mãsu taƙawa amma akwai tunãtarwa (a kansu), tsãmmãninsu (mãsu kutsawar) zã su yi taƙawa.
Kuma Ya jẽfa, a cikin ƙasa, tabbatattun duwatsu dõmin kada ta karkata da ku, da kõguna da hanyõyi, ɗammãninku kunã shiryuwa.
Suna ɓõyẽwa a cikin zukatansu, abin da bã su bayyana shi a gare ka.
Kuma lalle, haƙĩƙa, Ubangijinka Mai cika wa kõwa (sakamakon) ayyukansa ne. Lalle Shĩ, Mai ƙididdigewa ne ga abin da suke aikatãwa.
Kuma da yawa Muka halakar da wata alƙarya wadda ta yi butulci ga rãyuwarta.
Kuma amma waɗanda suka kãfirtã (Allah zai ce musu): "Shin, ãyõyĩNã ba su kasance anã karãnta su ã kanku ba sai kuka kangare, Kuma kuka kasance mutãne mãsu laifi?"
Alhãli bã ya kamata ga Mai rahama ya riƙi wani ɗã.
Lalle ne yanã da wani ubã, tsoho mai daraja, sabõda haka ka kãma ɗayanmu amatsayinsa. Lalle ne mũ, muna ganin ka daga mãsu kyautatãwa."
Shi ne Masanin fake da bayyane, Mai girma, Maɗaukaki.
Ka nĩsantar da tsakãnin tafiyõyinmu," kuma suka zãlunci kansu, sabõda haka Muka sanya su lãbãran hĩra kuma Muka kekkẽce su kõwace, irin kekkẽcewa.
wanda ke a cikin sammai da ƙasã yanã rõƙon Sa (Allah), a kullum Allah na a cikin wani sha'ani.
Wani mai tambaya yã yi tambaya game da azãba, mai aukuwa.
Kuma ku yi haƙuri shi ne mafi alhẽri a gare ku.
Shin kũ ne kuke halitta shi, kõ kuwa mũ ne Mãsu halittãwa?
Kuma kada ƙiyayya da wasu mutãne ta ɗauke ku, dõmin sun kange ku daga Masallãci Mai alfarma, ga ku yi zãlunci.
Kuma idan tãguwar ruwa, kamar duwatsu, ta rufe su, sai su kira Allah sunã tsarkakẽwar addini a gare shi.
"Kuma ku bi Allah da taƙawa, kuma kada ku sanya ni a baƙin ciki."
"Sai ku haɗa dabãrarku sa'an nan kuma ku tafi a sahu guda, kuma haƙĩƙa, wanda ya rinjãya, a yau, ya rabbanta."
Kuma suka sãmi abin da suka aikata halarce.
Lalle ne, ãyõyĩNa sun kasance anã karãtun su a kanku, sai kuka kasance, a kan dugãduganku, kunã kõmãwa bãya.
Kuma ka yi musu gargaɗi kan rãnar (Sã'a) makusanciya, a lõkacin da zukãta suke mãsu cika da bakin ciki, ga maƙõsansu.
Ashe, wanda Ya yi halitta bã zai iya saninta ba, alhãli kuwa shi Mai tausasãwa ne, kuma Mai labartawa?
Mu ne ke arzũta su, su da ku.
Watan alfarma da wani watan alfarma alfarmõmi mãsu dũkar jũna ne. Sabõda haka wanda ya yi tsõkana a kanku, sai ku yi tsokana a kansa da misãlin abin da ya yi tsõkana a kanku.
(Maganarsa) ba ta zamo ba, fãce wahayi ne da ake aikõwa.
Kuma idan sun gan su sai su ce: "Lalle waɗannan ɓatattu ne."
Allah Ya rubũta cẽwa," Lalle zan rinjãya, Nĩ da ManzanniNa."
Haƙĩƙa, Nĩ Inã yi maka gargaɗi kada ka kasance daga jãhilai."
Kuma wanda ya kãfirta, to, kada kãfircinsa ya baƙanta maka rai, zuwa gare Mu makõmarsu take, sa'an nan Mu bã su lãbari game da abin da suka aikata.
Lalle shĩ, Mai gani ne ga abin da kuke aikatãwa.
Sa'an nan kuma Ya jũyar da ku daga gare su, dõmin Ya jarrabe ku. Kuma lalle ne, haƙĩƙa, Ya yãfe muku laifinku.
Shin fa, bã ku tunãwa?
Allah ne Ubangijinmu, kuma Shĩ ne Ubangijinku, ayyukanmu nã gare mu, kuma ayyukanku nã gare ku, kuma bãbu wata hujja a tsakãninmu da tsakãninku. Allah zai tara mu, kuma zuwa gare Shi makõma take."
Kuma wanɗanda suka kãfirta, sunã cẽwa, "Don me ba a saukar da wata ãyã ba a kansa daga Ubangijinsa?"
Waɗancan, waɗanda suke kiran, sunã nẽman tsãni zuwa ga Ubangijinsu.
To, waɗanda suka yi ĩmãni, kuma suka aikata ayyuka na ƙwarai, sunã da gãfara da arziki na karimci.
Lalle Mun bayyanamuku ãyõyi da fatan zã ku yi hankali.
A rãnar nan zã a bijirã ku (dõmin hisãbi), bãbu wani rai, mai ɓoyewa, daga cikinku, wanda zai iya ɓõyẽwa.
Waɗanda malãiku suke karɓar rãyukansu sunã mãsu zãluntar kansu. Sai suka jẽfa nẽman sulhu (suka ce) "Ba mu kasance muna aikata wani mummũnan aiki ba."
Kuma bã zã su yi gũrinta ba har abadã sabõda abin da hannãyen su suka gabãtar.
Ya ce: "Za ka sãme ni, in Allah Yã so mai haƙuri kuma bã zan sãɓa maka ba ga wani umurni."
Kuma bãbu laifi a kanku a cikin abin da kuka gitta da shi daga nẽman auren mãtãko kuwa kuka ɓõye a cikin zukatanku.
Kuma Ubangijinika Wadãtacce ne Ma'abũcin rahama.
Abin da ke cikin sammai da abin da ke cikin ƙasã ya yi tasbihi ga Allah, alhãli kuwa, Shĩ ne Mabuwãyi, Mai hikima.
fãce wanda Allah Ya yi wa rahama.
Ka ce: "Wanda Ya ƙaga halittarku a fabkon lõkaci."
Kuma waɗanda aka bai wa Littafi ba su sãɓã ba, fãce a bãyan ilmi ya je musu, bisa zãlunci a tsakãninsu.
Kamar dai sũ ƙyami ne wanda aka jingine. Sunã zaton kõwace tsãwa a kansu take.
"To, don me, ba a jẽfa mundãye na zĩnãriya a kansaba, kõ kuma malã'iku su taho tãre da shi haɗe?"
Waɗannan rabonsu daga Littãfi yanã sãmunsu, har a lõkacin da ManzanninMu suka je musu, sunã karɓar rãyukansu, su ce: "Ĩnã abin da kuka kasance kunã kira, baicin Allah?"
Kuma Shĩ ne Mafi alhẽrin mãsu hukunci.
To, a lõkacin da, suka gan shi, suka girmamã shi, kuma suka yanyanke hannãyensu, kuma suka ce: "Tsarki yanã ga Allah! Wannan bã mutum ba ne!
"Allah bãbu abin bautãwa fãce shĩ Ubangijin Al'arshi, mai girma."
Lalle mutum, haƙĩƙa, mai kãfirci ne.
"Wanda Ya halitta ni, sa'an nan Yanã shiryar da ni."
Ya ce: "Lalle, haƙĩƙa, kun kasance kũ da Ubanninku a cikin ɓata bayyananna."
Kuma ga Samũdãwa, a lõkacin da aka ce musu: "Ku ji ɗan dãɗi har wani ɗan lõkaci,"
Lalle Shi Yã kasance Mai haƙuri, Mai gãfara.
Kuma bãbu abin da ya hana a karɓi ciyarwarsu daga gare su fãce dõmin sũ, sun kãfirta da Allah da ManzonSa, kuma bã su zuwa ga salla fãce Luma sunã mãsu kasãla, kuma bã su ciyarwa fãce sunã mãsu ƙyãma.
Kuma Allah Mayalwaci ne, Mai ilmi.
Kuma lalle ne haƙĩƙa Mun zaunar da Banĩ Isrã'ilamazaunar gaskiya kuma Muka arzũta su daga abũbuwa mãsu dãɗi.
Waɗannan ne abõkan wuta, sunã madawwama a cikinta.
Yanã sanya dare ya rufe yini.
Kõ zã Ya ɗauki 'ya'ya mãtã daga abin da Yake halittawa ne, kuma Ya zãɓe ku da ɗiya maza?
Bã zã su iya saurãre zuwa ga jama'a mafi ɗaukaka (Malã'iku) ba, kuma anã jĩfar su daga kõwane gẽfe.
Sa'an nan kuma ku kunã yin shakka.
Ashe, ba ka sani ba, lalle ne Allah Yanã sanin abin da yake a cikin sama da ƙasa?
Idan sun kasance mãtã ne fiye da biyu kuwa, to, suna da biyu daga kashi uku ɗin abin da ya bari, kuma idan ta zama guda ce (kawai) to, tana da rabi.
Shin, kunã ganin wani laifi daga gare mu? Fãce dai dõmin mun yi ĩmãni da Allah da abin da aka Saukar zuwa gare mu da abin da aka saukar daga gabãni, kuma dõmin mafi yawanku fãsiƙai ne."
To, wane ɓangare daga sãshen biyu ne mafi cancanta da aminci, idan kun kasance kunã sani?"
Kõ sunã da idãnu da suke gani da su?
Kuma bãbu abin da yake ɓõyẽwa ga A1lah, daga wani abu a cikin ƙasa, kuma bãbu a cikin sama."
Wannan yãro ne."
Kuma lalle ne, idan ka tambaye, su haƙĩƙa, sunã cẽwa, "Abin sani kawai, mun kasance munã hĩra kuma munã wãsã.
Sai Muka ce: "Ya Ãdamu!
Sa'an nan lalle ne za a tambaye ku, a rãnar nan lãbãrin ni'imar (da aka yi muku).
Shin akwai wani abin bautawa tãre da Allah?
Kuma Lalle ne, wanda ya nẽmi taimakon rãmãwa a bãyan an zãlunce shi, to waɗannan bãbu wata hanyar zargi a kansu.
MadaidaiciSize
Kuma amma idan ya kasance daga mazõwa dãma,
Lalle ne waɗanda suka kãfirta, sunã ciyar da dũkiyõyinsu, dõmin su kange daga hanyar Allah; to, zã a su ciyar da ita, sa' an nan kuma ta kasance nadãma a kansu, sa'an nan kuma a rinjãye su. Kuma waɗanda suka kãfirta zuwa ga Jahannama ake tãra su;
Lalle ne, ManzonMu yã je muku, yanã bayyana muku abu mai yawa daga abin da kuka kasance kunã ɓõyewa daga Littãfi, kuma yanã rangwame daga abu mai yawa.
Shĩ (Alƙur'ãni) bai zama ba fãce tunãtarwa ga tãlikai."
Kuma Yahũdu bã zã su yarda da kõme daga gare ka ba, kuma Nasãra bã zã su yarda ba, sai kã bi irin aƙidarsu.
(Mai maganar) ya ce: "Shin, kõ ku, mãsu tsinkãya ne (mu gan shi)?"
Shin fa, bã ku gani?"
Ka ce: "Allah nake bautã wa, inã mai tsarkake addinĩna a gare Shi.
Waɗanda ke yin zihãri game da mãtansu, sa'an nan su kõma wa abin da suka faɗa, to, akwai 'yanta wuya a gabãnin su shãfi jũna.
Kuma ku yi guzuri. To, mafi alhẽrin guzuri yin taƙawa.
Shin, akwai ilmin gaibi a wurinsa, Sabõda haka yanã ganin gaibin?
Ka ce: "Ku ambaci sũnãyensu."Ko kunã bai wa Allah lãbãri ne game da abin da bai sani ba a cikin ƙasa? Kõ da bayyananniyar magana kuke yin shirka, (banda a cikin zũciya)?
Suka ce: "Lalle ne mũ, da abin daaka aiko shi, mãsu ĩmãni ne."
Kuma ku sani cẽwa lalle nekũ mãsu haɗuwa da Shi ne. Kuma ka bãyar da bishãra ga mũminai.
Kada ku fitar da su daga gidãjensu, kuma kada su fita fãce idan sunã zuwa da wata alfãshã bayyananna.
Kada Ka sanyã mu tãre da mutãne azzãlumai."
Kuma a lõkacin da ManzanninMu suka jẽ wa Ibrãhĩm da bushãra suka ce: "Lalle mu mãsu halaka mutãnen, wannan alƙarya ne. Lalle mutãnenta sun kasance mãsu zãlunci."
Ka ce: "Wannan ce hanyãta; inã kira zuwa ga Allah a kan basĩra, nĩ da waɗanda suka bĩ ni, kuma tsarki ya tabbata ga Allah!
A. L̃.R. Littãfi ne mun saukar da shi zuwa gare ka dõmin ka fitar da mutãne daga duhunhuna zuwa ga haske, da iznin Ubangijinsu, zuwa ga tafarkin Mabuwãyi, Abin gõdẽwa.
Allah Yã yarda da su, kuma sun yarda da Shi.
Har a lõkacin da suka je a kan rãfin turũruwa wata turũruwa ta ce, "Yã kũ jama'ar turũruwa!
Yanã yi musu alkawari, kuma yanã sanya musu gũri, alhãli Shaiɗan bã ya yi musu wani wa'adĩn kõme face ruɗi.
Wannan yã fi kusantar da sanyaya idãnunsu, kuma bã zã su yi baƙin ciki ba, kuma su yarda da abin da ka bã su, sũ duka.
"Kuma lalle ne, haƙĩƙa, Yusufu ya zo muku daga gabãni, da hujjõji bayyanannu, ba ku gushe ba kunã a cikin shakka daga abin da ya zo muku da shi, har a lõkacin da ya halaka kuka ce, 'Allah bã zai aiko wani Manzo ba, a bãyansa.'
Haƙĩƙa, da kuna da sani sani na yaƙĩni.
Makangara suka ce wa maraunana, "Ashe, mũ ne muka kange ku daga shiriya a bãyan ya zo muku?
Ka ce: "To, ku tunkuɗe mutuwa daga rãyukanku, idan kun kasance mãsu gaskiya."
Ku shiga kofõfin Jahannama kunã madawwama a cikinta. To, mazaunin mãsu girman kai yã mũnana.
Kuma lalle, aikinsa zã a gan shi.
A lõkacin da waɗanda suka kãfirta suka sanya hanãnar ƙabĩ lanci a cikin zukãtansu hanãnar ƙabĩlanci irin na Jãhiliyya sai Allah Ya saukar da natsuwarSa a kan ManzonSa, kuma da a kan mũminai kuma Ya lazimta musu kalmar taƙawa alhãli kuwa sun kasance mafi dãcẽwa da ita kuma ma'abutanta.
Kuma Muka sanar da shi sana'ar wata tufa sabõda ku dõmin ya tsare ku daga makãminku.
Kuma idan ya jũya sai ya yi gaggawa a cikin ƙasa dõmin ya yi ɓarna a cikinta, kuma ya halaka shũka da 'ya'yan dabbõbi.
Bãbu laifi a kan waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, a cikin abin da suka ci, idan sun yi taƙawa kuma suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, sa'an nan suka yi taƙawa kuma suka yi ĩmãni, sa'an nan kuma suka yi taƙawa kuma suka kyautata. Kuma Allah Yana son mãsu kyautatãwa.
Kuma wani yankin jama, a daga mũminai, su halarci azãbarsu.
Waɗanda suka kãfirta suna da azãba mai tsanani kuma waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, sunã da wata gãfara da sakamako mai girma.
Kuma Allah, ga abin da kuke aikatãwa, Mai labartawa ne.
Bã ku da wani abin bautãwa, sai Shi.
Wancan, dõmin lalle ne sun ce: "Ciniki kamar riba yake."Kuma Allah Ya halatta ciniki kuma Ya haramta riba.
Kuma idan Muka ɗanɗanã wa mutãne wata rahama, a bãyan wata cũta tã shãfe su, sai gã su da mãkirci a cikin ãyõyinMu.
Allah Ya buga wani misãli dõmin waɗanda suka kãfirta: mãtar Nũhu da mãtar Lũɗu, sun kasance a ƙarƙashin wasu bãyi biyu daga bãyinMu sãlihai, saisuka yaudare su, sabõda haka ba su wadãtar musu da kõme daga Allah ba.
Dukan wancan mli mũninsa yã kasance abin ƙyãma a wurin Ubangijinka.
(A ce musu) "A yau anã sãka muku da abin da kuka kasance kunã aikatãwa."
Wancan ne. Kuma wanda ya girmama hukunce-hukuncen Allah to shĩ ne mafĩfĩci a gare shi, a wurin Ubangijinsa.
Zai nũna muku ãyõyinSa, har ku sansu."
Kuma waɗannan abõkan Wuta ne, sũ a cikinta madawwama ne.
Sa'an nan kuma, idan sun yi muku ɗa'a, to, kada ku nẽmiwata hanya a kansu.
Wanda ya kasance maƙiyi ga Allah da malã'ikunSa da manzanninSa da Jibirĩla da Mĩkã'ĩla to, lalle ne, Allah Maƙiyi ne ga kãfirai.
Abin sani kawai, majiɓincinku Allah ne da ManzonSa da waɗanda suka yi ĩmãni, waɗanda suke sunã tsayar da salla kuma sunã bãyar da zakka kuma sunã ruku'i,
Ka ce: "Kõwa ya yi aiki a kan hanyarsa.
Zã su ce: "Ta Allah ne."
Ashe, bai kasance ãyã ba a gare su, ya zama Mãlaman Banĩ Isrã'ĩla sun san shi?
Shĩ ne Mafi sani ga abin da kuke kũtsãwa a cikinsa na magana.
Sabõda haka, ka yi haƙuri, haƙuri mai kyãwo.
Lallai ne ƙidãyayyun watanni a wurin Allah watã gõma shã biyu ne a cikin Littãfin Allah, a Rãnar da Ya halicci sammai da ƙasa daga cikinsu akwai huɗu mãsu alfarma.
Kuma Allah Mabuwãyi ne, Mai hikima.
Jerin wasu shiryoyin ayuka da aka sani
Waɗancan iyãkõkin Allah ne sabõda haka kada ku kẽtare su.
Ka Ƙiƙiro Mai Gabatar da
Lalle ne a cikin wannan, hakĩƙa, akwai abin kula ga maabũta basĩra.
Abin sani kawai Allah Yanã jarrabar ku da shi, kuma lalle ne yanã bayyana muku a Rãnar ¡iyãma, abin da kuka kasance, a cikinsa, kunã sãɓã wajũna.
Sa'an nan daga cikinsu akwai shaƙiyyi da mai arziki.
Kuma aka halaka dukan 'ya'yan itãcensa, sai ya wãyi gari yanã jũyar da tãfunansa biyu, sabõda abin da ya kashe a cikinta, alhãli kuwa ita tanã kwance a kan rassanta, kuma yanã cẽwa, "Kaitõna, dã dai ban tãra wani da Ubangijina ba!"
Lalle Allah bã Ya son kafirai.
Lalle ne sũ, suna ƙulla kaidi na sõsai.
Sai suka kãfirta kuma suka jũya bãya, kuma Allah Ya wadãtu (daga gare su).
To lalle sũ, sunã a cikin shakka daga gamuwa da Ubangijinsu.
Yanã yi muku gargaɗi, ɗammãnin ku, kunã tunãwa.
Kuma babu wani abu daga hisãbinsu (mãsu kutsãwa a cikin ayõyin Allah (a kan mãsu taƙawa amma akwai tunãtarwa (a kansu), tsãmmãninsu (mãsu kutsawar) zã su yi taƙawa.
Kuma idan an jũyar da gannansu wajen abõkan wuta, su ce: "Yã Ubangijinmu!
Lalle ne inã gani, a ciki barci, lalle inã yanka ka.
Kuma dã sun yi nufin fita, dã sun yi wani tattali sabõda shi, kuma amma Allah Ya ƙi zãburarsu, sai Ya nauyayar da zamansu.
Bãbu wani alhẽri a cikin mãsu yawa daga gãnawarsu fãce wanda ya yi umurni da wata sadaka kõ kuwa wani alhẽri kõ kuwa gyãra a tsakãnin mutãne. Wanda ya aikata haka dõmin nẽman yardõdin Allah to zã Mu bã shi lãda mai girma.
In da gaske, za'a ƙyale maɓallin x kuma a saka fanel a tsakiyar x-axis na fuskar kwamfyuta. In a sake girmar fanel, zai ci gaba da zama wurin - misali, gafukan fanel guda biyu zasu ƙara girma. Idan ƙarya ne, maɓallin x zai ƙayyade wurin da za'a sa fanel.
Kuma idan an karanta ãyõyinMu bayyanannu a kansu, sai su ce: "Wannan bai zama ba fãce namiji ne yanã son ya kange ku daga abin da ubanninku suka kasance sunã bauta wa."
Munã sãmun wanda Muke so da rahamar Mu, kuma bã Mu tõzartar da lãdar mãsu kyautatawa.
Kuma dã kã gani, a lõkacin da Malã'iku suke karɓar rãyukan waɗanda suka kãfirta, sunã dukar fuskõkinsu da ɗuwãwunsu, kuma suna cẽwa: "Ku ɗanɗani azãbar Gõbara."
"Amma ni, shĩ ne Allah Ubangijina, kuma bã zan tãra kõwa da Ubangijina ba"
A Rãnar da ake hũrãwa a cikin ƙãho kuma Munã tãra mãsu laifi, a rãnar nan, sunã mãsu shũɗãyen idãnu.
Kuma ka yi kira zuwa ga Ubangijinka lalle kai kana a kan shiriya madaidaiciya.
Sabõda haka Ubangijinsu Ya darkãke su, sabõda zunubinsu. Sa'an nan Ya daidaita ta (azãbar ga mai laifi da maras laifi).
Kuma idan kun ji tsõron bã zã ku yi ãdalci ba a cikin marãyu, to, (akwai yadda zã a yi) ku auri abin da ya yi muku dãɗi daga mãtã; biyu-biyu, da uku-uku, da huɗu-huɗu. Sa'an nan idan kun ji tsõron bã zã ku yi ãdalci ba, to, (ku auri) guda ko kuwa abin da hannayenku na dama suka mallaka.
Ana ciyar da su.
Ka tunkuɗe cũta da wadda take ita ce mafi kyau.
Lalle Allah ba Ya shiryar da wanda yake mai ƙarya, mai kãfirci.
Lalle shĩ haƙĩƙa ma'abũcin rabo babba ne."
Ya ce: "Ã'a, ku jẽfa."
Zã Mu sãka wa waɗanda suke finjirẽwa daga barin ãyõyinMu da mugunyar azãba, sabõda abin da suka kasance sunã yi na hinjirẽwa.
Ã'a, sun ƙaryata game da abin da ba su kẽwaye da saninsa ba, kuma fassararsa ba ta riga ta jẽ musu ba.
Kuma ba ya umurnin ku da ku riƙi malã'iku da annabãwa lyãyengiji.
Mun yi ĩmãni, sai Ka gãfarta mana, kuma Ka yi mana rahama, kuma Kai ne Mafi alhẽrin mãsu tausayi."
Sabõda haka ku karanta abin da ya sauƙaƙa daga gare shi, kuma ku tsai da salla kuma ku bãyar da zakka, kumaa ku bai wa Allah rance, rance mai kyãwo.
Ya ce: "Kuna nẽman musanya abin da yake mafi ƙasƙanci da wanda yake mafi alhẽri?
Kuma idan kuka sake su daga gabãnin ku shãfe su, alhãli kuwa kun yanka musu sadãki, to, rabin abin da kuka yanka fãce idan sun yãfe, kõ wanda ɗaurin auren yake ga hannunsa ya yãfe.
Kunã da wani alhẽri babba a cikinsu.
Sa'an nan idan kun malãlo daga Arafãt, sai ku yi ta ambatar Allah a wurin Mash'aril Harãmi kuma ku tuna Shi kamar shiriyar da Ya yi muku kuma lalle ne kun kasance a gabãninsa, haƙĩƙa, daga ɓatattu.
"Amma Jirgin, to, ya zama na waɗansu matalauta ne sunã aiki a cikin tẽku, sai na yi niyyar in aibanta shi, alhãli kuwa wani sarki ya kasance a gaba gare su, yanã karɓẽwar kõwane jirgi (lãfiyayye) da ƙwãce.
Lalle ne a cikin wancan akwai ãyã ga wanda ya ji tsõron azãbar Lãhira. Wancan yini ne wanda ake tãra mutãne a cikinsa kuma wancan yini ne abin halarta.
Amma kuma bãbu waɗanda suka yi ĩmãni tãre da shi fãce kaɗan."
Da dare a lõkacin da ya jũyar da baya.
Kunã barin ta ƙarshen (Lãhira).
Sun riƙi rantsuwõwinsu garkuwa, sabõda haka suka kange (mũminai) daga jihãdin ɗaukaka tafarkin Allah.
Kuma Allah Masani ne ga abin da ke cikin ƙirãza.
Kuma bã ni tsõron abin da kuke yin shirki da shi, fãce idan Ubangijina Yã so wani abu.
Lalle Allah Masani ne Mai ƙididdidigẽwa.
Kuma wata jama'a ba ta kasance a gare shi ba, waɗanda ke taimakon sa, baicin Allah, kuma bai kasance mai taimakon kansa ba.
Sabo da haka Allah ba Ya yiwuwa Ya zãlunce su, amma kansu suka kasance sunã zãlunta.
Ya ce: "Ina nẽman tsari daga Allah da in kasance daga jãhilai."
Dã waɗannan (abũbuwanbautãwar) sun kasance abũbuwan bautãwar gaskiya ne, dã ba su tusga mata ba, alhãli kuwa dukansu madawwama a cikinta ne.
Ko mafi tsananin ƙeƙashewa. kuma lalle ne daga duwãtsu, haƙĩka, akwai abin da maremari suke ɓuɓɓuga daga gare shi, kuma lalle ne daga gare su, haƙĩƙa, akwai abin da yake tsatstsagewa har ruwa ya fita daga gare shi, kuma lalle ne, haƙĩƙa, daga gare su, haƙĩƙa, akwai da yake fãɗõwa dõmin tsõron Allah, kuma Allah bai zama gãfili ba daga barin abin da kuke aikatãwa.
Fãce wanda ya tũba, kuma ya yi ĩmãni, kuma ya aikata aiki na ƙwarai.
"Shin, idan mun mutu, kuma muka kasance turɓaya da kasũsuwa, ashe, lalle mũ tabbas waɗandaake tãyarwa ne?
A. L̃. M̃.
Kuma malã'iku (su bayyana) a kan sãsanninta, kuma wasu (malã'iku) takwas na ɗauke da Al'arshin Ubangijinka, a sama da su, a wannan rãnar.
Sa'an nan kuma zuwa gare Mu makõmarku take, sa'an nan Mu bã ku lãbãri game da abin da kuka kasance kunã aikatãwa,
Ka ce, "Kada ku rantse, ɗã'ã sananna ce!
Wanin Allah, sabõda haka ku shiryar da su zuwa ga hanyar Jahĩm.
In da gaske, za'a ƙyale maɓallin x kuma a saka fanel a tsakiyar x-axis na fuskar kwamfyuta. In a sake girmar fanel, zai ci gaba da zama wurin - misali, gafukan fanel guda biyu zasu ƙara girma. Idan ƙarya ne, maɓallin x zai ƙayyade wurin da za'a sa fanel.
"Wannan littãfinMu ne yanã yin magana a kanku da gas, kiya.
Lalle ne, Allah ba Ya gãfarta a yi shirki da Shi, kuma Yana gãfarta abin da yake bãyan wannan, ga wanda Yake so.
Sunã dawwama a cikinsu Allah Yã yi alkawarin, Ya tabbatar da shi.
Sa'an nan idan ya sake ta (na uku), to, bã ta halatta a gare shi, daga bãya, sai tã yi jima'i da wani miji waninsa.
Kuma Munã nufin Mu yi falala ga waɗanda aka raunanar a cikin ƙasar, kuma Mu sanya su shugabanni, kuma Mu sanya su magãda.
Suka ce: "Allah, Wanda ke sanya kõwane abu ya yi furuci, Shĩ ne Ya sanya mu mu yi furuci, kuma Shĩ ne Ya halitta ku can da farko, kuma zuwa gare Shi ake mayar da ku."
To, idan kun yi ɗã'a, Allah zai kãwo muku wata ijãra mai kyau, kuma idan kuka jũya bãya kamar yadda kuka jũya a gabãnin wancan, zai azãbtã ku, azãba mai raɗadi."
To, mẽne ne ya sãme ku a cikin munãfukai kun zama ƙungiya biyu, alhãli kuwa Allah ne Ya mayar da su sabõda abin da suka tsirfanta?
Ya ce: "Aminci ya tabbata a gare ka! zan nẽmi Ubangijina Ya gãfarta maka.
Kuma wadda yake a cikin ɗãkinta, ta nẽme shi ga kansa, kuma ta kukkulle ƙõfõfi, kuma ta ce, "Yã rage a gare ka!" ya ce: "Ina neman tsarin Allah!
Ga kõwane ajali akwai littãfi.
Sai suka ce: "Shin, zã Mu yi ĩmãni sabõda wasu mutãne biyu misãlinmu, alhãli kuwa mutãnensu a gare mu, mãsu bauta ne."
Kuma Munã tãra su a Rãnar ¡iyãma a kan fuskõkinsu, sunã makãfi, kuma bẽbãye da kurãme.
To, wanda ya kasance majinyaci daga cikinku, kõ kuwa akwai wata cũta daga kansa (ya yi aski) sai fansa (fidiya) daga azumi ko kuwa sadaka ko kuwa yanka. To, idan kuna cikin aminci to, wanda ya ji dãdi da umra zuwa haji, sai ya biya abin da ya sauƙaƙa daga hadaya, sa'an nan wanda bai sãmu ba, sai azumin yini uku a cikin haji da bakwai idan kun kõma, waɗancan gõma ne cikakku.
Ya ce: "To, ka sauka daga gare ta; dõmin bã, ya kasancẽwa a gare ka ga ka yi girman kai a cikinta.
"Sai wanda ya yi zãlunci, sa'an nan ya musanya kyau a bãyan cũta, to, lalle Nĩ, Mai gãfara ne, Mai jin ƙai."
Kuma lalle ne wanda ya turbuɗe shi (da laifi) ya tãɓe.
Kuma wanda bãshin yake a kansa sai ya yi shibta, kuma ya ji tsõron Allah, Ubangijinsa, da taƙawa, kuma kada ya rage wani abu daga gare shi.
Kuma kãfirai, sunã da azãba mai raɗadi.
Ya ce: "Ka tafi.
Ka ce: "Shin, makãho da mai gani sunã daidaita?
"Kuma ya mutãnẽna!
Yã Ubangijinmu! Kada Ka sanyã mu fitina ga mutãne azzãlumai.
Ka ce: "Shin, wancan ne mafi alhẽri, kõ kuwa Aljannar dawwama wadda aka yi wa'adi ga mãsu taƙawa?
Kuma a lõkacin da lbrãhĩm ya ce: "Yã Ubangijĩna! Ka sanya wannan gari amintacce, Ka azurta mutãnensa, daga 'ya'yan itãcen, wanda ya yi ĩmãni, daga gare su, da Allah da Ranar Lãhira."
Bãbu laifia gare ku ga abin da kuka yi yardatayya da shi a bãyan farillar sadãki.
Tanã kiran wanda ya jũya bãya (daga addini) kuma ya kau da kai.
Ya ce: "Shin, ban ce maka ba, lalle ne kai bã zã ka iya yin haƙuri tãre da nĩ ba?"
Ya ce: "Ashe, akwai tsammãninku idan an wajabta yãƙi a kanku cẽwa bã zã ku yi yãƙin ba?"
Waɗanda suke ciyarwa a cikin sauƙi da tsanani kuma suke mãsu haɗiyẽwar fushi, kuma mãsu yãfe wa mutãne laifi. Kuma Allah Yana son mãsu kyautatãwa.
Allah Mamallaki gaskiya, Yã ɗaukaka.
Shi ne Ubangijin sammai da ƙasa da abin da yake a tsakãninsu. sai ka bauta Masa, kuma ka yi haƙuri ga bautarsa.
Kuma haƙĩƙa mũ, munã cikin shakka daga abin da kake kiran mu gare shi, mai sanya kõkanto."
Lalle ne Mun aiki Nũhu zuwa ga mutãnensa, cẽwa ka yi gargaɗi ga mutãnenka gabãnin wata azãba mai raɗaɗi ta zo musu.
"Kuma yã mutãnena!
Waɗanda suke jiran dãko game da ku; har idan wata nasara daga Allah ta kasance a gare ku, sai su ce: "Ashe, ba mu kasance tãre da kũ ba?"
Kuma Lalle ne, wanda ya nẽmi taimakon rãmãwa a bãyan an zãlunce shi, to waɗannan bãbu wata hanyar zargi a kansu.
Kuma suka ce: "Gõdiya ta tabbata ga Allah Wanda Ya yi mana gaskiya ga wa'adinSa, kuma Ya gãdar da mu ƙasã, munã zama a cikin Aljanna a inda muke so."
Sa'an nan idan kun ji tsõron bã zã ku yi ãdalci ba, to, (ku auri) guda ko kuwa abin da hannayenku na dama suka mallaka.
Sa'an nan idan sun hanu, to, lalle Allah Mai gãfara ne, Mai jin ƙai.
Suka ce: "Ya mutãnenmu!
Lalle ne Mun saukar da wata tufa a kanku, tanã rufe muku al'aurarku, kuma da ƙawã.
Ku kira su ga ubanninsu, shi ne mafi ãdalci a wurin Allah.
Idan Ya so, zai yi muku rahama, kõ kuwa idan Yã so zai azabtãku. Kuma ba Mu aika ka kanã wakĩli a kansu ba.
Waɗannan ne ba su kasance mabuwãya ba a cikin ƙasa, kuma waɗansu masõya ba su kasance ba a gare su, baicin Allah.
Sai ya ce: "Kuji dãɗi a cikin gidãjenku kwãna uku.
Shin, lãbãrin Mũsã ya zo maka?
Kuma lalle ne idan Mun jinkirta da azãba gare su zuwa ga wani lõkaci ƙidãyayye, haƙĩƙa sunãcẽwa me yake tsare ta?
Ka ce: "Nĩ mutum kawai ne kamarku, ãnã yin wahayi zuwa gare ni cẽwa abin bautãwarku, abin bautãwa guda ne.
Lalle ne, Allah Mai tãra munãfukai da kãfirai ne a cikin Jahannama gabã ɗaya.
Kuma kada ku sassauta a cikin nẽman mutãnen idankun kasance kuna jin zõgi, to, lalle sũ ma, suna jin zõgi kamar yadda kuke jin zõgi. Kuma kuna tsammãni, daga Allah, abin da bã su tsammãni.
Idan sharri ya shãfe shi, ya kãsa haƙuri.
Sai suka ƙaryata shi.
Lalle Allah ba Ya shiryar da wanda yake mai ƙarya, mai kãfirci.
Yanã halitta abin da Yake so.
Kuma kanã ganin malã'iku sunã mãsu tsayãwa da haƙƙoƙin da aka ɗõra musu daga kẽwayen Al'arshi, sunã tasbĩhi game da gõde wa Ubangijinsu. Kuma aka yi hukunci a tsakãninsu da gaskiya.
Kuma amma waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, sai (Allah) Ya cikã musu ijãrõrinsu.
¡asƙantattu ga idanunsu zã su fito daga kaburburansu, kamar dai sũ fãri ne waɗandasuka wãtse.
Kuma Muka kiyãye ta daga dukan Shaiɗani wanda ake jĩfa.
Wancan ɗinku ne mafi alhẽri a gare ku idan kun kasance kunã sani.
To, wanda aka matsã, wanin ɗan tãwãye, kuma banda mai zãlunci, to bãbu laifi a kansa.
Kuma Ubangijinka bã Ya zãluntar kõwa.
Lalle sũ, sun kasance mãsu hasãra.
Kuma da yawa Muka karya wata alƙarya tã kasance mai zãlunci, kuma Muka ƙãga halittar waɗansu mutãne na dabam a bãyanta.
Ã'a, yã ƙirƙira shi ne. Ã'a, shi mawãƙi ne.
Abin bautawarku, abin bautãwa ne guda, to, waɗanda ba su yin ĩmãni da Lãhira, zukãtansu mãsu musu ne, kuma su makangara ne.
Kuma bã ni tsõron abin da kuke yin shirki da shi, fãce idan Ubangijina Yã so wani abu.
Lalle ne, Allah Mai gaggãwar hisãbi ne.
Sabõda haka ku bi Allah da taƙawa, yã ma'abũta hankula, waɗanda suka yi ĩmãni! Haƙĩƙa Allah Ya saukar da wata tunãtarwa zuwa gare ku.
Kamar misãlin waɗanda ke a gabãninsu, bã da daɗẽwa ba, sun ɗanɗani kũɗar al'amarinsu, kuma sunã da wata azãba mai raRaɗi.
Ka ce: "Bã ni tambayar ku wata ijãra, a kansa kuma bã ni daga mãsu ƙãƙalen faɗarsa."
Ba Mu yi sakacin barin kõme ba a cikin Littãfi, sa'an nan kuma zuwa ga Ubangjinsu ake tãra su.
Kuma a rãnar da ba su yi Asabar ba, bã su zuwa gare su; Kamar wancan ne Muke jarraba su da abin da suka kasance sunã yi na fãsiƙanci.
Sabõda haka ku bi Allah da taƙawa, yã ma'abuta hankula ko la'alla zã ku ci nasara."
Alhãli sũ, bisa ga abin da suke aikatãwa ga mũminai, sunã halarce.
A kan sakamakon, dõmin abin da suka kasance sunã aikatãwa.
Kuma suka yi musunsu, alhãli zukãtansu sun natsu da su dõmin zãlunci da girman kai.
Sai Na kãmã su. To, yãya azãbãTa take?
Wannan ya kasance wa'adi abin tambaya a kan Ubangijinka."
Sabõda haka ku nẽmi arziki a wurin Allah kawai, kuma ku bauta Masa, kuma ku yi gõdiya zuwa gare Shi. Zuwa gare Shi ake mayar da ku.
Ka dũba yadda suka ƙaryata kansu! Kuma abin da suka kasance sunã ƙirƙira ƙaryarsa, ya ɓace daga gare su.
Kuma lalle ne idan Mun ɗanɗana masa ni'ima a bãyan cũta ta shãfe shi, Yana cẽwa mũnanan halaye sun tafi daga wurina. Lalle shi mai farin ciki ne, mai alfahari.
"Ya Ubangijĩna!
Kuma a lõkacin da Ibrãhĩm ya ce: "Ya Ubangijina! Ka nũna mini yadda Kake rãyar da matattu."
To, a lõkacin da suka jẽfa, Mũsa ya ce: "Abin da kuka zo da shi sihiri ne.
Suka ce: "Yã Shu'aibu! Bã mu fahimta da yawa daga abin da kake faɗi, kuma munã ganin ka mai rauni a cikinmu.
Sabõda falala daga Ubangijinka.
Lalle ne, Ubangijinka Mai gaggãwar uƙkũba ne, kuma lalle ne Shi, haƙĩƙa, Mai gãfara ne, Mai jin ƙai.
Allah Shĩ ne mafi sani ga ĩmãninsu.
Lalle ne, waɗanda suke cĩn dũkiyar marãyu da zãlunci, to, wuta kawai suke ci a cikin cikkunansu, kuma za su shiga cikin wata wuta mai tsanani.
A yau an halatta muku abũbuwa mãsu dãɗi kuma abincin waɗanda aka bai wa Littãfi halal ne a gare ku, kuma abincinku halal ne a gare su, da mãtã mãsu kãmun kai daga muminai da mãtã 'yã'ya daga waɗanda aka bai wa Littãfi a gabãninku idan kun je musu da sadãkõkinsu, kuna mãsu yin aure, ba masu yin zina ba, kuma bã mãsu riƙon abõkai ba. Kuma wanda ya kãfirta da ĩmãni to, lalle ne aikinsa yã ɓãci, kuma shĩ, a cikin Lãhira, yanã daga mãsu hasãra.
Allah Ya yi musu tattalin wata azãba mai tsanani.
Lalle ne haƙĩƙa, zan kakkãtse hannuwanku da kafãfunku a tarnaƙi, kuma haƙĩƙa, zan tsĩrẽ ku gabã ɗaya."
Kuma Allah Yanã buga misãli ga mutãne, mai yiwuwã ne, sunã tunãwa.
Sa'an nan Mu rarrabe a tsakãninsu, kuma abũbuwan shirkinsu su ce: "Bã mũ kuka kasance kunã bauta wa ba."
Dõmin Allah Ya rarrabe mummũna daga mai kyau, kuma Ya sanya mummũnan, sãshensa a kan sãshe, sa'an nan Ya shirga shi gabã daya, sa'an nan Ya sanyã shi a cikin Jahannama.
A rãnar nan, waɗanda suka kãfirta kuma suka sãɓã wa Manzo, sunã gũrin dã an baje ƙasa dasu, kuma bã su ɓõye wa Allah wani labãri.
Fir'auna ya ce: "Bã ni nũnamuku kõme face abin da na gani, kuma ba ni shiryar da ku, sai ga hanyar shiryuwa."
Ka ce: "Bãbu wanda ya san gaibi a cikin sammai da ƙasa fãce Allah. Kuma bã su sansancẽwar a yaushe ne zã a tãyar da su."
Ya ce: "Shin, ban gaya muku ba, lalle ne, ni inã sanin abin da ba ku sani ba, daga Allah?"
Lalle ne, a cikinta akwai wasu mutãne mãsu ƙarfi kuma lalle ne bã zã mu shige ta ba sai sun fice daga gare ta, to, idan sun fice daga gare ta, to, lalle ne mu, masu shiga ne."
Kõ shin duhu da haske sunã daidaita? ko sun sanya ga Allah waɗansu abõkan tãrayya waɗanda suka yi halitta kamar halittarSa sa'an nan halittar ta yi kama da jũna a gare su?"
Kuma waɗanda suka kãfirta da ãyõyin Allah, waɗannan sũ nemãsu hasãra.
Mulki a gare shi yake.
To, mẽne ne sakamakon wanda ke aikata wancan daga gare ku fãce wulãkanci a cikin rãyuwar dũniya? Kuma a Rãnar ¡iyãma ana mayar da su zuwa ga mafi tsananin azãba.
Kuma kada ku riƙe auren mãtã kãfirai, kuma ku tambayi abin da kuka ɓatar daga dũkiya, su kuma kãfirai su tambayi abin da suka ɓatar na dũkiya.
(Sai mai gargaɗin) ya ce: "Shin, ban zo muku da abin da ya fi zama shiriya daga abin da kuka sãmi ubanninku a kansa ba?"
Kuma Allah, ga abin da kuke aikatãwa, Mai labartawa ne.
"Kuma lalle ne mũ mun tabbatã bã zã mu buwãyi Allah ba, a cikin ƙasa, kuma bã zã mu buwãye Shi da gudu ba."
Suka ce: "Ya Musa!
Yãya aka karkatar da su?
Bã su ɗanɗanar mutuwa, a cikinsu, fãce mutuwar farko, kuma (Allah), Ya tsare musu azãbar Jahĩm.
Lalle ne, mãsu ɗã'ã ga Allah, dãhir, suna cikin ni'ima.
Shin, ba su sani ba cẽwa "Lalle ne wanda ya sãɓa wa Allah da ManzonSa, haƙĩƙa Yanã da wutar Jahannama, Yanã madawwami a cikinta?
Lalle ne, ManzonMu yã je muku, yanã bayyana muku abu mai yawa daga abin da kuka kasance kunã ɓõyewa daga Littãfi, kuma yanã rangwame daga abu mai yawa.
Ku karɓã wa Ubangijinku tun gabãnin wani yini ya zo, bãbu makawa gare shi daga Allah, bã ku da wata mafaka a rãnar nan, kuma bã ku iya yin wani musu.
"Lalle ne ni, nã tabbata cewa ni mai haɗuwa da hisãbina ne."
Lalle ne Ubangijĩna ne Masani game da kaidinsu."
Shin, yanã daidaita, shi da (namiji na biyu) wanda yake umurni da a yi ãdalci kuma yanã a kan tafarki madaidaici?
Shin fa, wanin Allah kuke bĩ da taƙãwa?
Zã su yi rantsuwa da Allah a gare ku idan kun jũya zuwa gare su, dõmin ku kau da kai daga gare su.
To, lalle zã Mu bã da lãbãri ga waɗanda suka kãfirta game da abin da suka aikata, kuma lalle Munã ɗanɗana musu daga azãba, Mai kauri.
Ka buga musu misãlin rãyuwar dũniya, kamar ruwane wanda Muka saukar da shi daga sama sa'an nan tsirin ƙasa ya garwaya da shi, sa'an nan ya wãyi gari dudduga, iska tanã shiƙar sa.
Shin, zã su daidaita ga misãli?
Suka ce: "Ubangijinku ne Mafi sani ga abin da kuka zauna.
Kuma ba su rarraba ba fãce bãyan da ilmi ya jẽ musu, dõmin zãlunci a tsakãninsu kuma bã dõmin wata kalma tã gabata ba daga Ubangijinka, zuwa ga wani ajali ambatacce, dã an yi hukunci a tsakaninsu.
Kuma Ya gãdar da ku gõnakinsu da gidãjensu da dũkiyõyinsu, da wata ƙasa wadda ba ku taɓa tãkarta bã.
Na rantse da alƙalami da abin da (marubũta) suke rubũtãwa.
Kuma imma wata fizga daga Shaiɗan ta fizge ka, sai ka nẽmi tsari ga Allah.
Shĩ ne da mulkin abin da ke a gaba gare mu da abin da ke a bãyanmu da abin da ke a tsakãnin wannan." Kuma (Ubangijinka bai kasance wanda ake mantãwa ba.
Kõkuwã sunã cẽwa: "Yã ƙirƙira shi (Alƙur'ãni) ne?"
Allah Yanã tabbatar da waɗanda suka yi ĩmãni da magana tabbatacciya a cikin rãyuwar dũniya, da cikin Lãhira, Kuma Allah Yanã ɓatar da azzãlumai, kuma Allah Yanã aikata abin da Yake so.
Saboda haka, ka yi musu bushãra da azãba mai raɗaɗi.
Tsarki ya tabbata ga wanda Ya yi tafiyar dare da bãwanSa da dare daga Masallaci mai alfarma zuwa ga Masallaci mafi nĩsa wanda Muka sanya albarka a gefensa dõmin Mu nũna masa daga ãyõyinMu.
Shin, ba su yi tafiya ba, a cikin ƙasa, dõmin su gani yadda ãƙibar waɗanda ke a gabãninsu ta kasance? Allah Ya darkãke a kansu.
Lalle Mũ Mun saukar da Littãfi zuwa gare ka, da gaskiya. Sabõda haka, ka bauta wa Allah kanã mai tsarkake addini a gare Shi.
A can taimako da jiɓinta ga Allah yake.
Aminci ya tabbata ga Mũsã da Hãruna.
Sai ku tãra al'amarinku, kũ da abũbuwan shirkinku, sa'annan kuma kada al'amarinku ya kasance rufaffe a kanku, sa'an nan kuma ku kashe ni, kada ku yi mini jinkiri."
Kuma mene ne ya sanar da kai abin da ake cẽ wa Aƙabã?
Sun mance Allah, sai Ya mantã da su.
Kuma a sã'ilin da Annabi ya asirta wani lãbãri zuwa ga sãshen mãtansa, to, a lõkacin da ta bã da lãbari da shi.
To, a lõkacin da suka kõma zuwa ga ubansu, suka ce: "Yã bãbanmu!
Yã ku waɗanda suka yi ĩmãni! Ku bi Allah da taƙawa, kuma ku nemi tsari zuwa gare shi, kuma ku yi jihãdi a cikin hanyarsa, tsammãninku, za ku ci nasara.
Sa'an nan bãbu abin da ya kasance jawãbin mutãnensa (Ibrãhĩm) fãce dai suka ce: "Ku kashe shi kõ, ku ƙõnã shi," Sai Allah Ya tsĩrar da shi daga wutã.
Ashe, ba ka gani ba, lalle Allah, wanda yake a cikin sammai da wanda yake a cikin ƙasa yanã yin sujada a gare shi, da kuma rãna da watã da taurãri da duwãtsu da itãce da dabbõbi, da kuma mãsu yawa daga mutãne?
Kuma zuciyar uwar Mũsã ta wãyi gari yõfintatta.
Kamar wancan ne! Muka shigar da shi a cikin zukãtan mãsu laifi.
An wajabta yãƙi a kanku, alhãli kuwa shi abin ƙi ne a gare ku, akwai fãtar cẽwa ku ƙi wani abu, alhãli shi ne mafi alhẽri a gare ku, kumaakwai fãtar cẽwa kuna son wani abu alhãli kuwa shi ne mafi sharri a gare ku.
Ka ce: "Kõwa mai tsumãye ne. Sai ku yi tsumãye.
Lalle a cikin wancan akwai ãyõyi ga mutãne waɗanda ke yin ĩmãni.
Dukan wancan mli mũninsa yã kasance abin ƙyãma a wurin Ubangijinka.
Sunã da waɗansu inuwõwi na wutã daga samansu, kuma daga ƙasansu akwai waɗansu inuwõwi.
Rãnar da zã ka ga mũminai maza da mũminai mãtã haskensu nã tafiya a gaba gare su, da kuma dãma gare su. (Anã ce musu) "Bushãrarku a yau, ita ce gidajen Aljanna."
Kuma ku yãƙe su inda kuka sãme su, kuma ku fitar da su daga inda suka fitar da ku. Kuma fitina ita ce mafi tsanani daga kisa.
Ya ce: "Wannan aikin Shaiɗan ne, dõmin shi maƙiyi ne mai ɓatarwa, bayyananne!"
Kuma ba ya halatta a gare ku (maza) ku karɓe wani abu daga abin da kuka bã su, fãce fa idan su (ma'auran) na tsõron bã zã su tsayar da iyãkõkin Allah ba, Idan kun (danginsu) ji tsõron bã zã su tsayar da iyãkõkin Allah ba, to, bãbu laifi a kansu a cikin abin da ta yi fansa da shi.
Ka ce wa waɗanda suka yi ĩmãni, su yi gãfara ga waɗanda bã su fãtan rahama ga kwãnukan Allah, dõmin (Allah) Ya sãka wa mutãne da abin da suka kasance sunã aikatãwa.
Ka ce: "Shin, daga abũbuwan shirkinku akwai wanda yake fãra halitta, sa'an nan kuma ya mayar da ita?"
Sabõda haka, ka yi haƙuri kamar yadda mãsu ƙarfin niyya daga Manzanni suka yi haƙuri.
Canza tsari da kulawan na'ura
Yã nadãma a kan bãyĩNa!
Ku yi haƙuri kuma ku yi dauriya, kuma ku yi zaman dãko, kuma ku yi taƙawa, tsammãninku zã ku ci nasara.
Mũsã ya ce musu, "Kaitõnku!
Lalle ne munã tsõron ya yi gaggawa a kanmu, kõ ya ƙẽtare haddi."
Lalle ne Allah, ga abin da kuke aikatãwa Mai gani ne.
Lalle Mũ, kõwane irin abu Mun halitta shi a kan tsãri.
Annabi ne mafi cancanta ga mũminai bisa ga su kansu, kuma mãtansa uwãyensu ne.
Kuma lalle ne gidan Lãhira shĩ ne mafi alhẽri ga waɗanda suka yi taƙawa?
Ijãrata ba ta zama ba fãce daga Allah, kuma shi Mahalarci ne a kan dukan kõme."
Shin fa, bã ku tunãwa?
Kuma idan ba su hanu daga abin da suke faɗa ba, haƙĩƙa, wata azãba mai raɗaɗi tãnã shãfar waɗanda suka kãfirta daga gare su.
Kuma idan sun zo muku sai su ce: "Mun yi ĩmãni."
Sunã da bushãra a cikin rãyuwar dũniya da ta Lãhira.
Kuma kada ma'abũta falala daga gare ku da mawadãta su rantse ga rashin su bãyar da alhẽri ga ma'abũta zumunta da miskĩnai da muhãjirai, a cikin hanyar Allah.
Allah Ya yi wa'adi ga waɗanda suka yi ĩmãni daga gare. Ku, kuma suka aikata ayyukan ƙwarai, lalle zai shugabantar da su a cikin ƙasa kamar yadda Ya shugabantar da waɗanda suke daga gabãninsu, kuma lalle ne zai tabbatar musu da addininsu wanda Ya yardar musu, kuma lalle ne Yanã musanya musu daga bãyan tsõronsu da aminci, sunã bauta Mini bã su haɗa kõme da Nĩ.
"Babu wani abu sai mutuwarmu ta farko, kuma ba mu zama waɗanda ake tãyarwa ba."
Lalle sũ, sun kasance waɗansu irin mutãne ne fãsiƙai.
Sa'an nan zã su ce: "Ã'a, kunã dai hãssadar mu ne."
Sa'an nan, ya jũya bãya, kuma ya bunƙãsa,
Kuma lalle ne haƙĩƙa Mun saukar, zuwa gare ka, ãyõyi bayyanannu, kuma ba wanda yake kãfirta da su fãce fãsikai.
Har idan sun ga abin da ake yi musu gargaɗi da shi, to, zã su san wanda ya zama mafi raunin mataimaki da mafi ƙarancin adadi.
A lõkacin da suka ce: "Yã Allah!
"Ya Ubangijinmu! Ka aiko, a cikinsu, wani manzo daga gare su, yana karanta musu ãyõyinKa, kuma yana karantar da su Littãfin da hikimar, kuma yana tsarkake su.
To, a lõkacin da suka ga azãbar, kumar hadari mai fuskantar rãfukansu, suka ce: "Wannan hadari ne mai yi mana ruwa.
Fãce waɗanda aka raunana daga maza da mãtã da yãra waɗanda bã su iya yin wata dabãra, kuma bã su shiryuwa ga hanya.
Haƙĩƙa mun kasance a cikin gafala daga wannan! Ã'a, mun kasance dai mãsu zãlunci!"
Kuma Muka murtsuke abin da Fir'auna da mutãnensa suka kasance sunã sanã'antawa, da abin da suka kasance sunã shimfiɗãwa.
Idan wani namiji ya kasance ana gãdon sa bisa kalãla, ko kuwa wata mace alhãli kuwa yana da ɗan'uwa kõ 'yar'uwa to, kõwane ɗaya daga cikinsu yana da sudusi (ɗaya daga cikin kashi shida), sai idan sun kasance mafi yawa daga wannan, to, sũ abõkan tãrayya ne a cikinsulusi (ɗaya bisa uku), daga bãyan wasiyya wadda aka yi kõ kuma bãshi. Bã da yana mai cũtarwa ba, ga wasiyya, daga Allah.
Kuma waɗanda suke ga zakka mãsu aikatãwa ne.
Kuma Ya arzũta shi daga inda bã ya zato.
Allah Mafi sanin inda Yake sanya manzancinSa.
Abar da take tũba kawai ga Allah, ita ce ga waɗanda suke aikatãwar mugun aiki da jãhilci sa'an nan su tũba nan kusa to, waɗannan Allah Yanã karɓar tũ barsu kuma Allah Yã kasance Masani ne, Mai hikima.
Sabõda haka ku bauta Masa kuma Shi ne wakĩli a kan dukan, kõme.
Sai ya jẽfa sandarsa, sai gã ta kumurci bayyananne!
To, a lõkacin da firgita ta tafi daga Ibrãhĩm, kuma bushãra tã je masa, Yanã mai jayayya a gare Mu, sabõda mutãnen Lũɗu!
Ya ce: "To, ka zõ da shi idan ka kasance daga, mãsu gaskiya."
Lalle Mũ, Mun halitta su daga lãkã mai ɗauri.
Kuma wanda ya kashe mũmini bisa ga kuskure, sai ya 'yanta wuya mũmina tare da mĩƙa diyya ga mutãnensa, ãce idan sun bari sadaka.
Lalle ne, a cikinta akwai wasu mutãne mãsu ƙarfi kuma lalle ne bã zã mu shige ta ba sai sun fice daga gare ta, to, idan sun fice daga gare ta, to, lalle ne mu, masu shiga ne."
Mãsu kai-kawo ne a tsakãnin wancan; bã zuwa ga waɗannan ba, kuma bã zuwa ga waɗannan ba.
Kuma lalle, Mun bar ta ta zama ãyã.
Ya ce: "Haƙĩƙa azãba da fushi sun auku a kanku daga Ubangijinku!
Ku tafo zuwa ga kalma mai daidaitãwa a tsakã ninmu da ku; kada mu bauta wa kõwa fã ce Allah. Kuma kada mu haɗa kõme da Shi, kuma kada sãshenmu ya riƙi sãshe Ubangiji, baicin Allah."
Suka ce: "Shin, kã zo mana ne dõmin ka karkatar da mu daga gumãkaumu?
Ka shigar, da ni shigar gaskiya, kuma Ka fitar da ni fitar gaskiya. Kuma Ka sanya mini, daga gunKa, wani ƙarfi mai taimako."
Sa'an nan idan (wanda aka kashe) ya kasance daga wasu mutãne maƙiya a gare ku, kuma shi mũminine, sai ya 'yanta wuya mũmina.
Sai su kirãye su, sai bã zã su karɓa musu ba, kuma Mu sanya Maubiƙa (Mahalaka) a tsakãninsu,
To zã su ce "Wãne ne zai mayar da mu?"
To, shimfiɗar tã mũnana, ita.
Wancan shi ne babban rabo, mai girma.
Wanda ya yi ɗã'a ga Manzo, to, haƙĩƙa, yã yi ɗã'a ga Allah. Kuma wanda ya jũya bãya, to, ba Mu aike ka ba don ka zama mai tsaro a kansu.
_Shirya Mazaɓa
Kuma lalle ne, haƙiƙa Mun sauƙaƙe Alƙur'ani, dõmin tunãwa. To, shin, akwai mai tunãwa?
Kuma lalle ne, haƙĩƙa, Mun zãɓe shi, a cikin dũniya, kuma lalle ne shi, a cikin Lãhira, haƙĩƙa, yana daga sãlihai.
Kamar haka, kuma Mun aurar da su da mãtã mãsu kyaun idãnu, mãsu girmansu.
To, Nĩsa ya tabbata ga Samũdãwa.
_Juya kan fanel masu tsaiwa
Ka ce: "Allah," sa'an nan ka bar su a cikin sharhõliyarsu sunã wãsã.
Lalle a cikin wancan haƙĩƙa akwai rahama da tunãtawa ga mutanen da ke yin ĩmãni.
(Allah) Ya ce: "To, lalle ne ita abar haramtãwa ce a gare su, shekara arba'in, sunã yin ɗimuwa a cikin ƙasa. Sabõda haka kada ka yi baƙin ciki a kan mutãne fãsiƙai."
Alkawarin Allah.
Kuma Yanã karɓa wa waɗannan da suka yi ĩmãni kuma suka aikata ayyukan ƙwarai, kuma Yanã ƙãra musu (sakamako) daga falalarSa.
A rãnar da wasu fuskõki suke yin fari kuma wasu fuskõki suke yin baƙi (zã a ce wa waɗanda fuskokinsu suke yin baƙin): "Shin kun kãfirta a bayan ĩmãninku?
Kuma Allah Yã la'ance su, kuma sunã da azãba zaunanniya.
Tsarki ya tabbata a gare Ka. Lalle ne nĩ, na kasance daga azzãlumai."
Shĩ ne wanda ke sassaukar da ãyõyi bayyanannu ga BãwanSa, dõmin Ya fitar da ku daga duffai zuwa ga haske, kuma lalle Allah haƙĩƙa Mai tausayi ne gare ku, Mai jin ƙai.
Kuma Muka gabãta zuwa ga abin da suka aikata daga aiki, sai Muka sanya shi ƙũra wãtsattsiya.
Shin fa, ba ku tunãni?
Zuwa ga Allah makõmarku take, kuma Shĩ a kan kõmeMai ĩkon yi ne.
A can ne kõwane rai yake jarraba abin da ya bãyar bãshi, kuma aka mayar da su zuwa ga Allah, Majiɓincinsu Tabbatacce kuma, abin da suka kasance sunã ƙirƙirãwa ya ɓace musu.
Kuma imma lalle Mu nũna maka sãshen abin da Muke yi musu wa'adi, kõ kuwa lalle Mu karɓi ranka to abin sani kawai iyarwa ce a kanka, kuma hisãbi yana gare Mu.
To, amma waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai, to, Ubangijinsu zai sanya su a cikin rahamarsa.
Manzanni mãsu bãyar da bushãra kuma mãsu gargaɗi dõmin kada wata hujja ta kasance ga mutãne a kan Allah bãyan Manzannin.
Kuma aka kõra waɗanda suka kãfirta zuwa Jahannama, jama'a-jama'a har a lõkacin da suka je mata, sai aka buɗe ƙõfõfinta, kuma matsaranta suka ce musu, "Ashe, waɗansu Manzanni, daga cikinku ba su je muku ba, sunã karanta ãyõyin Ubangijinku a kanku, kuma sunã yi muku gargaɗin gamuwa da yininku wannan?"
Kuma Allah Mai gãfara ne, Mai jin ƙai."
Kuma ka ce: "Gaskiya tã zo, kuma ƙarya ta lãlãce.
Lalle ne, mãsu ɗã'ã ga Allah tabbas suna cikin ni'ima.
Shĩ ne wanda Ya fitar da waɗanda suka kãfirta daga Mazõwa Littãfi, daga gidãjẽnsu da kõra ta farko.
Ubangijinku ne Mafi sani game da ku. Idan Ya so, zai yi muku rahama, kõ kuwa idan Yã so zai azabtãku.
Kuma ka umurci iyãlanka da salla, kuma ka yi haƙuri a kanta.
Bã ta da mai tunkuɗẽwa.
Kuma me ya sanar da kai abin da ake ce wa Huɗama?
To idan sun kãwo shaida kada ka yi shaida tãre da su.
Wannan yana daga falalar Allah a kanmu da mutãne, amma mafi yawan mutãne bã su gõdewa."
Kuma bãbu wani dalĩli a gare ni a kanku fãce na kirã ku, sa'an nan kun karɓã mini.
Kuma wanda ya yi yãki a cikin hanyar Allah to a kashe shi ko kuwa ya rinjãya, sa'an nan zã Mu ba shi ijãra mai girma.
Mãtanku gõnaki ne a gare ku, sabõda haka ku je wa gõnakinku yadda kuka so. Kuma ku gabãtar (da alheri) sabõda kanku, ku bi Allah da taƙawa.
"Ka dũba yadda Muke sarrafa ãyõyi, tsammãninsu sunã fahimta!"
Suka ce: "Yã Shu'aibu!
Lalle wannan, ga Allah, mai sauƙi ne.
Shin, kuna umurnin mutãne da alhẽri, kuma ku manta da kanku alhãli kuwa kuna karatun littãfi?
Suna mãsu farin ciki sabõda abin da Allah Ya bã su daga falalarSa, kuma suna yin bushãra ga waɗanda ba su risku da su ba, daga bayansu; "Bãbu tsõro a kansu kuma ba su zama suna yin baƙin ciki ba."
Ya ce: "Yã Ubangijĩna! Lalle nã kashe wani rai daga gare su, dõmin haka inã tsõron kada su kashe ni."
Idan Allah Ya taimake ku, to, bãbu marinjayi a gare ku.
Kuma idan kun kasance majinyata, ko kuwa a kan tafiya ko kuwa wani daga cikinku, idan ya zo daga kãshi, kõ kuwa kun shãfi mãtã ba ku sãmi ruwa ba, to ku nufi, fuskar ƙasa mai kyau, ku yi shãfa ga fuskokinku da hannuwanku. Lalle ne Allah Yã kasance Mai yãfẽwa Mai gãfara.
A lõkacin da suka ce: "Yã Allah!
Waɗanda suke a cikin sallarsu mãsu tawãli'u ne.
Suka ce: "Ya Ubangijinmu! Wanda ya gabãtar da wannan a gare mu, to, Ka ƙãra masa azãba, ninki, a cikin wutã."
To, a, lõkacinda suka yi mãsa alkawari, ya ce: "Allah ne wakĩli a kan abin da muke faɗa."
Allah ba Ya kallafa wa rai fãce ikon yinsa, yana da lãdar abin da ya tsirfanta, kuma a kansa akwai zunubin abin da ya yi ta aikatãwa: "Yã Ubangijinmu! Kada Ka kãmã mu, idan mun yi mantuwa, ko kuma mun yi kuskure.
Ban kasance ba fãce mutum, Manzo."
"Da sharrin dare, idan ya yi duhu."
Kuma a sa'an nan, haƙĩƙa, dã Mun bã su, lãda mai girma, daga gunMu.
Yãya kuke hukuntãwa (wannanhukunci)?
Fãce Iblĩs, ya ƙi kasancẽwa daga mãsu yin sujadar.
Kuma idan kun yi sulhu, kuma kuka yi taƙawa, to, lalle ne Allah Yã kasance Mai gãfara, Mai jin ƙai.
"Kuma (an ce mini): Ka tsayar da fuskarka ga addini, kanã karkatl zuwa ga gaskiya, kuma kada ka kasance daga mãsu shirka.
Ya ce: "Yaya Allah zai rãyar da wannan a bãyan mutuwarta."
"Kuma mẽne ne a gare mu, bã zã mu dõgara ga Allah ba, alhãli kuwa haƙĩƙa Yã shiryar da mu ga hanyõyinmu?
To, a'aha! Ina rantsuwa da Ubangijinka, ba za su yi ĩmãni ba, sai sun yarda da hukuncinka ga abin da ya sãɓa a tsakãninsu, sa'an nan kuma ba su sãmi wani ƙunci a cikin zukãtansu ba, daga abin da ka hukunta, kuma su sallama sallamãwa.
Dã Mun so, dã Mun mayar da shi ruwan zartsi.
Kuma waɗanda suka yi fãsiƙanci to makõmarsu ita ce wuta, kõ da yaushe suka yi nufin su fita daga gare ta, sai a mayar da su a cikinta, kuma a ce musu: "Ku ɗanɗana azãbai wutã, wadda kuka kasance kunã ƙaryatãwa game da ita."
Lalle ne, haƙĩƙa, gaskiya tã jẽ maka daga Ubangijinka dõmin haka kada ka kasance daga mãsu kõkanto.
"Yã Ubangijimu!
To, shin, kũ mãsu sallamãwa ne?,
Kada Ka bar ni makaɗaici alhãli kuwa Kai ne Mafi alhẽrin mãsu gãdo."
Ka yi kira zuwa ga Ubangijinka, kuma kada lalle ka kasance daga mãsu shirka.
Ã'a, su game da gamuwa da Ubangijinsu kãfirai
A inda taken, nan Aljannar makoma take.
Allah nã ɗaukaka waɗanda suka yi ĩmãni daga cikinku da waɗanda aka bai wa ilim wasu darajõji mãsu yawa, kuma, Allah Mai ƙididdigewa ne ga dukan kõme.
"A sa'ad da 'yar'uwrka ke tafiya har ta ce, shin, in shiryar da ku ga wanda ke rẽnonsa?'
Ã'a ku mutãne ne daga waɗanda Ya halitta, Yanã gãfartãwa ga wanda Yake so, kuma Yanã azabta wanda Yake so. Kuma Allah ne da mulkin sammai da ƙasa da abin da ke tsakãninsu kuma zuwa gare shi makomã take."
Ka ce: "Na wãne ne abin da yake a cikin sammai da ƙasa?"
Da inabi da ciyãwa.
Ka ce: "Sũ, dõmin waɗanda suka yi ĩmani suke a cikin rãyuwar dũniya, suna keɓantattu a Rãnar Kiyãma.
A lõkacin da Hawarãyãwa suka ce: "Ya Ĩsa ɗan Maryam! shin, Ubangijinka Yanã iyãwa Ya saukar da kaɓaki a kanmu daga samã?"
Suka ce: "An cũtar da mu daga gabãnin ka zõ mana, kuma daga bãyan da kã zõ mana."
Bã ya kasancewa ga wani annabi, kãmammu su kasance a gare shi sai (bãyan) yã zubar da jinainai a cikin ƙasa.
Wanda ya ciyar a gabãnin cin nasara, kuma ya yi yãƙi daga cikinku, bã ya zama daidai (da wanda bai yi haka ba). waɗancan ne mafĩfĩta girman daraja bisa ga waɗanda suka ciyar daga bãya kuma suka yi yãƙi.
Lalle ne kãfirai sun kasance, a gare ku, maƙiyi bayyananne.
Mũ neMafi sani game da abin da suke siffantãwa.
Lalle ne shi (Alƙur'ãni) haƙƙan, maganar wani manzon (Allah) ne mai girma ga Allah.
Sai suka ci daga gare ta, sabõda haka al'aurunsu suka bayyana, kuma suka shiga sunã lulluɓãwa a kansu daga ganyen Aljanna.
Ka ce: "Yã ku mutãnena! Ku yi aiki a kan halinku, lalle ne nĩ mai aiki ne, sa'an nan da sannu zã ku san wanda ãƙibar gida zã ta kasance a gare shi.
"Shin, waɗannan ne waɗanda kuka yi rantsuwa, Allah bã zai sãme su da rahama ba?
Abin sani kawai, mushirikai najasa ne, sabõda haka kada su kusanci Masallaci Mai alfarma a bãyan shẽkararsu wannan.
Yã ku waɗanda suka yi ĩmãni! Shaidar tsakãninku, idan mutuwa ta halarci ɗayanku, a lõkacin wasiyya, maza biyu ne ma'abuta ãdalci daga gare ku, kõ kuwa wasu biyu daga wasunku idan kun tafi a cikin ƙasa sa'an nan masĩfarmutuwa ta sãme ku.
Idan kun yi ɗa'aga waɗanda suka kãfirta zã su mayar da ku a kan dugãduganku, har ku jũya kunã mãsu hasãra.
Kuma idan kã gan su, sai jikunansu su bã ka sha'awa kuma idan sun faɗa, zã ka saurãra ga maganarsu.
Waɗanda suke yin ĩmãnida Allah da Rãnar Lãhira, bã zã su nẽmi izininka ga yin, jihãdida dũkiyõyinsu da rãyukansu ba.
Bã ya yiwuwa ga Allah Ya zãlunce su, amma sun kasance kansu suke zãlunta.
Lalle ni, Manzo ne amintacce zuwa gare ku."
Sabõda haka Ka tsare mu daga azãbar wuta.
Lalle ne alfarma ga Allah take gaba ɗaya.
An buga wani misãli, sai ku saurãra zuwa gare shi. Lalle ne waɗanda kuke kira baicin Allah, bã zã su halitta ƙudã ba, kõ da sun tãru gare shi, kuma idan ƙudãn ya ƙwãce musu wani abu, bã zã su kuɓutar da shi ba daga gare shi.
Kuma lalle, Shĩ, Shi ne Ubangijin Shi'ira.
Kuma wanda ya sãɓã wa Allah da ManzonSa, kuma ya ƙẽtare iyãkõkinSa, zai shigarda shi wuta, yana madawwami a cikinta, kuma yana da wata azãba mai walãkantarwa.
A lõkacin da ya ga wata wuta, sai ya ce wa iyãlinsa, "Ku dãkata. Lalle ne nĩ, na tsinkãyi wata wuta tsammãnĩna in zo mukuda makãmashi daga gare ta, kõ kuwa in sãmi wata shiriya a kan wutar."
To, ba sai Nã rantse da shafaƙi ba.
(Allah) Ya ce: "Wuta ce mazaunarku, kunã madawwama acikinta, sai abin da Allah Ya so.
Ya ce: "Ku tafi (da wulãkanci) a cikinta. Kada ku yi Mini magana."
Launin bango
Ã'a ita wannan (magana) fitina ce, kuma amma mafi yawansu ba su sani ba.
Ka ce: "Yã ku mutãne! Lalle ne gaskiya, ta zo muku daga Ubangijinku.
Munã karantãwa a kanka daga lãbarin Mũsã da Fir'auna da gaskiya dõmin mutãne waɗanda suke yin ĩmãni.
Allah Yana bayyanawa a gare ku, dõmin kada ku ɓace.
Idan Yã hukunta wani al'amari sai kawai Ya ce masa, "Kasance." Sai ya dinga kasan cẽwa.
Shin kã san wani takwara a gare shi?
Kuma lalle ne, Munã sãka wa waɗanda suka yi haƙuri da lãdarsu da mafi kyãwun abin da suka kasance sunã aikatãwa.
Ya ce: "Shin, ba mu yi rẽnonka ba a cikinmu kanã jãrĩri, kuma ka zauna a cikinmu shẽkarudaga lõkacin rãyuwarka?"
Kamar wannan ne mutãnen da suke a gabãninsu suka ƙaryata, har suka ɗanɗani azãbarMu.
To, idan sun bijire sai ka ce: "Nã yi muku gargaɗi ga wata tsãwa kamar irin tsãwar Ãdãwa da samũdãwa."
Aminci ya tabbata ga Ilyãs.
Lalle ne Kai Mai jin addu'a Kake."
Rantsuwar Allah! Lalle ne haƙĩƙa Mun aika zuwa ga al'ummomi daga gabãninka, sai Shaiɗan ya ƙawãce musu ayyukansu, sabõda haka shĩ ne majiɓincinsu, a yau, kuma sunã da azãba mai raɗaɗi.
A'aha! Lalle ne, shi (Alƙur'ãni) tunãtarwa ce.
Mai twãle fãtar goshi.
Kuma wani rai bã ya yin tsirfa fãce dõmin kansa, kuma mai ɗaukar nauyi, bã ya ɗaukar nauyin wani, sa'an nan kuma kõmawarku zuwa ga Ubangijinku take; Sa'an nan Yã bã ku lãbãri ga abin da kuka kasance, a cikinsa, kunã sãɓã wa jũnã?"
Yanã azurta wanda yake so, alhãli kuma Shĩ ne Maiƙarfi, Mabuwãyi.
Ka ce, "Allah Yã isa zama shaida a tsakãnina da tsakãninku da wanda yake a wurinsa akwai ilmin Littãfi."
Waɗannan ne waɗanda ayyukansu suka ɓãci a cikin dũniya da Lãhira, kuma bã su da wasu mataimaka.
Kuma idan aka ambaci Allah Shi kaɗai zukãtan waɗanda ba su yi ĩmãni ba da Lãhira, su yi ƙiyãma, kuma idan an ambaci waɗanda suke kiran, wasunSa, sai gãsu sunã yin bushãrar farin ciki.
Alhãli kuwa a gabãninsa akwai littãfin Mũsã, wanda ya kasance abin kõyi, kuma rahama.
Ã'a kun yi zaton Annabi da mũminai, bã za su kõmo zuwa ga iyãlansu ba, har abada. Kuma an ƙawãta wannan (tunãni) a cikin zukãtanku, kuma kun yi zato, zaton mugunta, kuma kun kasance mutãne halakakku.
Kuma dã waɗanda suka kãfirta sun yãke ku, dã sun jũyar da ɗuwaiwai (dõmin gudu) sa'an nan bã zã su sãmi majiɓinci ba, kuma bã zã su sãmi mataimaki ba.
Allah, bãbu wani Ubangiji fãce Shi, Rãyayye, Mai tsayuwa da kõme, gyangyaɗi bã ya kãma Shi, kuma barci bã ya kãma Shi, Shi ne da abin da yake a cikin sammai da abin da yake a cikin ƙasa.
Lalle ne waɗanda suka kãfirta sa'an nan kuma suka kange (mutãne) daga tafarkin Allah, sa'an nan suka mutu, alhãli kuwa sunã kãfirai, to, Allah bã zai yi gãfara ba a gare su.
To, a rãnar da zã ta je musu, ba ta zama abin karkatarwa ba daga gare su. Kuma abin da suka kasance suna yin izgili da shi, yã wajaba a kansu.
Jahannama ita ce mai isarsu, zã su shigeta. Sabõda haka makõmarsu ta mũnana.
Lalle ne, haƙĩƙa, waɗanda suka ce: "Allah na ukun uku ne," sun kãfirta, kuma babu wani abin bautãwa fãce Ubangji Guda.
Kuma waɗanda suka yi zãlunci suka bin abin da aka ni'imtar da su a cikinsa, suka kasance mãsu laifi.
Lalle Kai, a kan dukkan kõme, Yã kai Mai ikon yi ne."
Gõdiya ta tabbata ga Allah, Mai fãra halittar sammai da ƙasã, Mai sanya malã'iku manzanni mãsu fukãfukai, bibbiyu, da uku-uku da hurhuɗu.
Ya ce: "Lalle ne inã nufin in aurar da kai ɗayan 'yã'yãna biyu, waɗannan, a kan ka yi mini aikin ijãra shẽkara takwas to, idan ka cika gõma, to, daga, gare ka yake.
To, idan sun tũba, kuma suka tsayar da salla, kuma suka bãyar da zakka to ku sakar musu da hanyarsu.
Kuma bã ku da wani masõyi, kuma bã ku da mataimaki, baicin Allah.
Kuma bã Mu halakar da wata alƙarya ba fãce tanã da mãsu gargaɗi.
Kuma mutum ya ce "Mẽ neya same ta?"
Me ya hana Ka jinkirta mana zuwa ga wani ajali na kusa?"Ka ce: "Jin dãɗin dũniya kaɗan ne, kuma Lãhira ce mafi alhẽri ga wanda ya yi taƙawa.
Lalle ne, wata hujja bayyananniya daga Ubangijinku tã zõ muku!
Ka ce: "Bãbu abin da yake sãmun mu fãce abin da Allah Ya rubũta sahõda mu.
Da mãsu Madyana, kuma an ƙaryata Mũsã.
"Haƙĩƙa, ni na dõgara ga Allah, Ubangijĩna kuma Ubangijinku.
Idan kun kyautata, kun kyautata dõmin kanku, kuma idan kun mũnana to dõmĩnsu.
Kuma kada ku manta da falala a tsakãninku.
Kuma sunã cẽwa, "A yaushe wannan wa'adi zai auku, idan kun kasance mãsu gaskiya?"
Kuma waɗanda suka riƙi waɗansu majiɓinta waɗanda bã Shĩ ba Allah ne Mai tsaro a kansu, kuma kai, bã wakili ne a kansu ba.
Lalle ne sun kangara a cikin rãyukansu, kuma suka yi tsaurin kai, tsaurin kai mai girma.
Shin sunã da ƙafãfu da suke yin tafia da su?
Wannan ita ce hanya madaidaiciya."
Kuma Muka murtsuke abin da Fir'auna da mutãnensa suka kasance sunã sanã'antawa, da abin da suka kasance sunã shimfiɗãwa.
Kuma zuwa ga Ãdãwa, (Mun aika) ɗan'uwansu Hũdu. Ya ce: "Yã kũ mutãnena!
Wannan ya kasance wa'adi abin tambaya a kan Ubangijinka."
Lalle ne haƙĩƙa Mun saukar da ãyõyi, mãsu bayyanãwa.
Shĩ ne wanda Ya fitar da waɗanda suka kãfirta daga Mazõwa Littãfi, daga gidãjẽnsu da kõra ta farko.
Kada ku riƙi rantsuwõyinku dõmin yaudara a tsakãninku, har ƙafa ta yi sulɓi a bãyan tabbatarta, kuma ku ɗanɗani azãba sabõda abin da kuka kange daga hanyar Allah. Kuma kunã da wata azãba mai girma.
Shin, ba su sani ba cẽwa lallai Allah, ne Yake karɓar tũbã daga bãyinSa, kuma Yanã karɓar sadakõkinsu, kuma lalle Allah ne Mai karɓar tũba, Mai jin ƙai?
To, wanda ya yi ta'addi a bãyan wannan, to, yanã da azãba mai raɗaɗi.
Lalle ne haƙĩƙa waɗanda suka ce: "Lalle ne Allah, shĩne Masĩhu, ɗan Maryama," sun kãfirta.
Lalle Ubangijinka Mai aikatãwa ne ga abin da Yake nufi.
Kuma sunã cẽwa: "Don me ba a saukar da wata ãyã ba a gare shi, daga Ubangijinsa?"
Lalle ne Mu, Mun yi wahayi zuwa gare ka, kamar yadda Muka yi wahayi zuwa ga Nũhu da annabãwa daga bãyansa. Kuma Mun yi wahayi zuwa ga Ibrãhĩma da Ismã'ĩla da Is'hãƙa da Yaƙũbu da jĩkõki da ĩsa da Ayũba da Yũnusa da Hãruna da Sulaimãn.
Ma'abũta ƙunci sun ƙaryata Manzanni.
Kuma kamar wannan ne, Muka fitini sãshensu da sãshe, dõmin su ce: "Shin waɗannan ne Allah Ya yi falala a kansu daga tsakãninmu?"
Sai muka ƙarfafa waɗanda suka yi ĩmãni a kan maƙiyansu, sabõda haka suka wãyi gari marinjãya.
To, a yau bã zã su fita daga gare ta ba, Kuma bã zã su zama waɗanda ake nẽman yardarsu ba."
Bã su da wani majiɓinci baicinSa kuma bã Ya tãrayya da kõwa a cikin hukuncinsa."
Ya ce: "Shin kun bã ni bushãra ne a kan tsũfa yã shãfe ni?
Kuma kunã yin dãriya, kuma bã ku yin kũka?
Lalle ne yã yi zaton bã zai kõmo ba.
Mai aikatãwa ga abin da Yake nufi.
Kuma ba su sanar da kõwa ba balle su ce: "Mũ fitina kawai ne, sabõda haka kada ka kãfirta," balle har su yi ta nẽman ilmin abin da suke rarrabẽwa tsakãnin mutum da mãtarsa da shi daga gare su.
Haƙĩƙa, wani haske da wani Littafi mai bayyanãwa yã je muku daga Allah.
Ashe to ba ku kasance kunã yin hankali ba?"
Kuma ka ambaci bãwanMu Ayyũba a lõkacin da ya kirãyi Ubangijinsa, ya ce: "Lalle nĩ, Shaiɗan yã shãfe ni da wahala da kuma wata azãba."
Lalle ne wannan Alƙur'ãni yanã gaya wa Banĩ Isrãĩla mafi yawan abin da sũ suke sãɓa wa jũnansu a ciki.
Suka ce: "Munã nẽman ma'aunin sarki. Kuma wanda ya zo da shi, yanã da kãyan rãkumi ɗaya, kuma ni ne lãmuni game da shi."
Wasu huskõki a rãnar nan ƙasƙantattu ne.
Lalle ne mãsu yawa daga Ahbãr da Ruhbãnãwa haƙĩƙa sunã cin dũkiyar mutãne da ƙarya, kuma sunã kangẽwa daga hanyar Allah.
Kuma suka ce: "Bãbu kõme fãce rãyuwarmu ta dũniya; munã mutuwa kuma munã rãyuwa (da haihuwa) kuma bãbu abin da ke halaka mu sai zãmani."
Kuma ba a umurce su ba fãce da su bautã wa Ubangiji Guda.
Shin, ba su yi tunãni ba a cikin zukãtansu cẽwa Allah bai halitta sammai da ƙasa ba da abin da ke tsakãninsu, fãce da gaskiya da ajali ambatacce?
Kuma haƙĩƙa Mũ, Mãsu cika musu rabon su ne, bã tãre da nakasãwa ba.
Sai ku yi jira. Lalle ne nĩ, tãre da ku, inã daga mãsu jira."
Kuma Shi ne Ya aika iskõkin bushãra gaba ga rahamarSa, kuma Muka saukar da ruwa mai tsarkakẽwa daga sama.
Bãbu shakka lalle ne sunã da wuta, kuma lalle sũ, waɗanda ake ƙyãlẽwa ne (a cikinta).
Kuma (Ya sanya shi) manzo zuwa ga Bani Isrãila'ĩla (da sãko, cẽwa), Lalle ne, ni haƙĩƙa nã zõ muku, da wata ãyã daga Ubangijinku.
Kamar haka Muke sãkã wa azzãlumai.
Kuma kada ka yi gaggãwa da Alƙur'ãni a gabãnin a ƙãre wahayinsa zuwa gare ka.
Sa'an nan Ya bã ku lãbari ga abin da kuka kasance kunã aikatãwa.
Suka ce: "Ã'a, ku ne bãbu marãba a gare ku, kũ ne kuka gabãtar da shi a gare mu."
Ku bauta wa Allah.
Yi Haɗi Zuwa Sava...
Sai ku tafi ku nẽmo lãbãrin Yũsufu da ɗan'uwansa. Kada ku yanke tsammãni daga rahamar Allah.
Kuma kamar wancan Mun aika wani rũhi (rai mai haɗa jama'a) zuwa gare ka, daga gare Mu.
Kuma a lõkacin da umurninmu ya je, Muka kuɓutar da Hũdu da waɗanda suka yi ĩmãni tãre da shi, sabõdawata rahama daga gare Mu.
Bã Mu tambayar ka wani arziki Mu ne Muke azurta ka.
Ã'a, saninsu ya kai a cikin Lãhira Ã'a, sunã cikin shakka daga gare ta. Ã'a, sũ da gare ta makãfin zũci ne.
Kuma a lõkacin da suka bũɗe kãyansu, suka sãmi hajjarsu an mayar musu da ita, suka ce: "Yã bãbanmu!
Kuma amma idan ya kasance daga mãsu ƙaryatãwar, ɓatattun,
"Kuma ka rikitar da wanda ka sãmi ĩko a kansa, daga gare su, da sautinka, kuma ka yi hari a kansu da dawãkinka da dãkãrunka kuma ka yi tãrẽwa da su a cikin dũkiyõyi da ɗiyã, kumaka yi musu wa'adi.
Sai Allah Ya ɗanɗana musu azãbar wulãkanci a cikin rãyuwar dũniya, kuma lalle azãbar Lãhira ita ce mafi girma, dã sun kasance sunã da sani.
"Ku shigẽ ta da aminci, kunã amintattu."
Waɗancan ne waɗanda kalmar azãba ta wajaba a kansu, a cikin al'ummõmi waɗanda suka shũɗe, (bã da daɗẽwa ba), a gabãninsu, daga aljannu da mutãne. Lalle sũ, sun kasance mãsu hasãra.
Allah ne Wanda ke aika iskõki, sai su mõtsar da girgije, sa'an nan Ya shimfiɗa shi a cikin sama yadda Yake so, kuma Ya sanya shi wani ɓaɓɓake, sa'an nan ka ga ruwa na fita daga tsakãninsa.
Kuma haƙĩƙa, Mun bai wa Mũsã littãfi, sai aka sãɓã wa jũna a cikinsa. Kuma bã dõmin wata kalma wadda ta gabãta daga Ubangijinka ba, haƙĩƙa, dã an yi hukunci a tsakãninsu.
Wannan kuwa dõmin sãɓãwar da suka yi ne, kuma sun kasance suna yin ta'adi.
Kuma wanda ya riƙi Shaiɗan majiɓinci, baicin Allah, to, haƙĩƙa yã yi hasara, hasara bayyananniya.
Kuma dã Allah Yã so dã bã zã su yãƙi jũna ba, kuma amma Allah Yana aikata abin da Yake nufi.
"To, a yau bã zã a karɓi fansa daga gare ku ba. Kuma bã zã a karɓa daga waɗanda suka kãfirta ba.
Kuma waɗansu 'yã'yan itãce bã su fita daga kwasfõfinsu, kuma wata mace bã ta yin ciki, kuma bã ta haihuwa, fãce da saninSa, kuma a rãnar da Yake kiran su (Ya ce): "Inã abõkan tãrayyaTa?" Sai su ce, "Mun sanar da Kai bãbu mai bãyar da shaida da haka nan daga gare mu."
Umarni
Kuma kalmar Ubangijinka tã cika, tanã gaskiya da ãdalci.
Rãnar da ƙasã ke tsattsãgẽwa daga gare su, sunã mãsu gaggãwa.
"Aminci," da magana, daga Ubangiji Mai jin ƙai.
Sunã aikata masa abin da yake so, na masallatai da mutummutumai da akussa kamar kududdufai, da tukwãne kafaffu. Ku aikata gõdiya, yã ɗiyan Dãwũda, kuma kaɗan ne mai gõdiya daga bãyĩNa.
Kuma ba ku zama mãsu buwãya ba a cikin ƙasa kuma bã ku da wani majiɓinci, wanin Allah, kuma bã ku da wani mataimaki.
Kuma haƙĩƙa mũ, munã cikin shakka daga abin da kake kiran mu gare shi, mai sanya kõkanto."
Ba ka kasance kã san abin da yake littãfi ba, kõ abin da Yake ĩmãni, kuma amma Mun sanya shi (rũhin, watau Alƙur'ãni) wani haske ne, Munã shiryar da wanda Muke so daga cikin bãyĩnMu game da shi.
Mãsu son mazansu, a cikin tsãrã ɗaya.
Nĩ ce nã nẽme shi daga kansa. Kuma lalle ne shĩ, haƙĩƙa, yanã daga mãsu gaskiya.
Ku fita da yãƙi kunã mãsu sauƙãƙan kãyã da mãsu nauyi, kuma ku yi jihãdi da dũkiyõyinku da kuma rãyukanku a cikin hanyar Allah.
Kuma suka ce: "Ya Ubangijinmu!
Lallai ne Allah bã Ya tõzarta lãdar mãsu kyautatãwa.
Sabõda haka, kada ku tsarkake kanku, Shĩ ne Mafi sani ga wanda ya yi taƙawa.
Sabõda haka, ka yi hakunci a tsakãninmu da gaskiya. Kada ka ƙẽtare haddi kuma ka shiryar da mu zuwa, ga tsakar hanya."
Ya ce: "Shin kun bã ni bushãra ne a kan tsũfa yã shãfe ni?
Shin zã Kahalaka mu, sabõda abin da wãwãyen daga gare mu suka aikata? Ba ta zama ba fãce fitinarKa Kanã ɓatarwa, da ita, wanda Kake so kuma kanã shiryarwa da ita, wanda Kake so; Kai ne Majiɓincinmu.
Kuma ku tunã a lõkacin da Ya sanyã ku mãsu mayẽwa daga bãyan mutãnen Nũhu, kuma Ya ƙãra muku zãti a cikin halitta.
Kuma amma ni'imar Ubangijinka, sai ka faɗa (dõmin gõdiya).
Lalle mũ, manzannin Ubangijinka ne.
Sai dai jnsu bai amfãne su ba, kuma zukãtansu ba su amfãne su ba ga kõme, dõmin sun kasance sunã musu game da ãyõyin Allah, kuma abin da suka kasance sunã aikatãwa na izgili game da shi ya wajaba a gare su.
Mũsã ya ce musu, "Kaitõnku!
Kuma Ubangijinmu Mai rahama ne Wanda ake nẽman taimakonSa a kan abinda kuke siffantãwa."
Waɗanda Muka bã su Littãfi, suna saninsa kamar yadda suke sanin ɗiyansu.
Lalle wannan da Ya rãya ta, haƙĩƙa, Mai rãyar da matattu ne.
Sai ya wãyi gari a cikin birnin yanã mai tsõro, yanã sauna. Sai ga wanda ya nẽmi taimako daga gare shi a jiya, yanã nẽman ãgajinsa.
Da Ibrãhĩm wanda ya cika alkawari?
Kuma ka sassaƙa jirgi da kyau a kan idanunMu da wahayinMu, kuma kada ka yi Mini magana a cikin sha'anin waɗanda suka kãfirta, lalle ne sũ, waɗanda akenutsarwa ne.
Kuma ga kõwane nau'i, yanã da darajõji daga abinda suka aikata. Kuma dõmin (Allah) Ya cika musu (sakamakon) ayyukansu, alhãli kuwa sũ, bã zã a zãlunce su ba.
Ya ce: "To, lalle ne kanã daga waɗanda ake yi wa jinkiri."
Lalle ne nĩ, manzo ne daga Ubangijin halittu."
"Fãce mãtarsa mun ƙaddara cẽwa lalle ne ita, haƙĩƙa, tanã daga mãsu halaka."
Dã dai lalle su sun kasance snnã shiryuwa!
Kuma ku shaidar da shaidu biyu daga mazanku, to, idan ba su zama maza biyu ba, to, namiji guda da mãtã biyu, daga waɗanda kuke yarda da su daga shaidun dõmin mantuwar ɗayansu, sai gudarsu ta mazãkũtar da ɗayar.
Lalle shi, Mai ilmi ne, Mai ĩkon yi.
"Kuma in shiryar da kai zuwa ga Ubangijinka domin ka ji tsoronSa?"
"Ku shigẽ ta.
Allah Ya yarda da su, kuma su, sun yarda da Shi. wannan sakamako ne ga wanda ya ji tsõron Ubangijinsa.
A lõkacin da waɗanda aka bi suka barranta daga waɗanda suka bi, kuma suka ga azãba, kuma sabubba suka yanke da su.
Masanin fake da bayyane ne, Kuma Shi ne Mai hikima Masani.
A rãnar da sãshen ãyõyin Ubangijinka yake zuwa, ĩmãnin rai wanda bai kasance yã yi ĩmãnin ba a gabãni, kõ kuwa ya yi tsiwirwirin wani alhẽri, bã ya amfãninsa.
To, zã ku san yadda (ãƙibar) gargaɗiNa take.
A kan sakamakon, dõmin abin da suka kasance sunã aikatãwa.
Kuma idan an jũyar da gannansu wajen abõkan wuta, su ce: "Yã Ubangijinmu! Kada Ka sanyã mu tãre da mutãne azzãlumai."
Kuma daga cikinsu akwai mai cẽwa, "Ka yi mini izinin zama, kuma kada ka fitine ni."
Lalle ne, haƙĩƙa, gaskiya tã jẽ maka daga Ubangijinka dõmin haka kada ka kasance daga mãsu kõkanto.
Kuma ba Mu shiryar da shi ga hanyõyi biyu ba?
A lõkacin da kuke hawan dũtse, gudãne. Kuma ba ku karkata a kan kõwa ba, alhãli kuwa Manzon Allah nã kiran ku a cikin na ƙarshenku.
Kuma ka ce: "Gõdiya ta tabbata ga Allah.
Sai matarsa ta fuskanta cikin ƙyallõwa, har ta mari fuskarta kuma ta ce: "Tsõhuwa bakarãriya (zã ta haihu)!"
Lalle ne waɗanda suka yi ĩmãni, da waɗanda suka tũba, da Nasãra da Makarkata, wana ya yi ĩmani da Allah da Yinin Lãhira, kuma ya aikata aikin ƙwarai, to, suna da ijãrarsu a wurin Ubangijinsu, kuma bãbu tsõro a kansu, kuma ba su zama suna yin baƙin ciki ba.
Kuma Allah ba Ya shiryar da mutãne kãfirai.
Kuma Allah Ya kasance Mai yawan ĩkon yi ne a kan dukan kõme.
Mun sanya wa ɗayansu gõnaki biyu na inabõbi, kuma Muka kẽwayesu da itãcen dabĩnai, kuma Muka sanya shũka a tsakãninsu (sũ gõnakin).
Kuma daga cikinsu akwai waɗanda suke saurare zuwa gare ka. Shin fa, kai kana jiyar da kurma, kuma kõ dã sun kasance bã su hankalta?
Sai wata liyãfa ta ruwan zãfi.
Ka ce: "Dã Allah Ya so dã ban karanta shi ba a kanku, kuma dã ban sanar da kũ ba gameda shi, dõmin lalle ne nã zauna a cikinku a zãmani mai tsawo daga gabãnin (fãra saukar) sa.
Kuma dũbi dai Munã bã da lãbãri a gare ka daga lãbarun Manzanni, abin da Muke tabbatar da zuciyarka da shi. Kuma gaskiya ta zo maka a cikin wannan da wa'azi da tunãtarwã ga mãsu ĩmãni.
Lalle Mun jarrabe su kamar yadda Muka jarrabi mãsu gonar lambu, a lokacin da suka yi rantsuwa, wai lalle zã su girbe amfãninta, suna mãsu asubanci.
To, wadanda sikẽlinsu ya yi nauyi, to, waɗannan sũ ne mãsu babban rabo.
Sa'an nan a lõkacin da ta ji lãbãri game da mãkircinsu, sai ta aika kiran liyafa zuwa gare su, kuma ta yi tattalin abincin da ake dõgara wajen cinsa, kuma ta bai wa kõwace ɗaya daga cikinsu wuƙa, kuma ta ce: "Ka fito a kansu."
Zaɓuɓɓuka na Zaman Shawara
Kuma, Muka sanya, a cikinta, kafaffun duwãtsu maɗaukaka, kuma Muka shayar da ku ruwa mai dãɗi?
Kuma zã su yi ta yin rantsuwa da Allah, "Dã mun sãmi dãma, dã mun tafi tare da ku."
Kuma idan kun kasance a kan tafiya, kuma ba ku sami marubũci ba, to, a bãyar da jingina karɓaɓɓiya (ga hannu).
Sai marmaro gõma sha biyu suka ɓuɓɓugo, haƙĩƙa, kõwaɗanne mutãne sun san wurin shansu.
Sanã mãsu shagaltacin zukãtansu, kuma su asirta gãnãwa: Waɗanda suka yi zãlunce (sunã cẽwa) "Wannan bã Kõwa ba ne fãce mutum misãlinku.
Kuma ku bi Allah da taƙawa. Lalle Allah Mai karɓar tũba ne, Mai jin ƙai.
Ya ce: "Nĩ ina rãyarwa kuma ina matarwa."
To, wãne ne mafi zãlunci daga wanda ya ƙirƙira ƙarya ga Allah, dõmin ya ɓatar da mutãne bã da wani ilmi ba?
Ã'a, waɗancan sũ ne azzãlumai.
(Allah) Ya ce "Alãmarka ita ce ba zã ka iya yi wa mutãne magana ba har yini uku face da ishãra. Sai ka ambaci Ubangijinka da yawa.
Ya ce: "Lalle ne, Allah Yã zãɓe shi a kanku, kuma Ya ƙãra masa yalwa a cikin ilmi da jiki. Kuma Allah Yana bãyar da mulkinSa ga wanda Yake so, kuma Allah Mawadaci ne, Masani.
Sun kasance sũ ne mafi tsananin ƙarfi daga gare su, da kufaifan aiki a cikin ƙasã, sai Allah Ya kãmã su da laifuffukansu. Kuma bã su da wani mai tsarẽwa daga Allah.
Lalle ne Yanã tãra ku zuwa ga Rãnar ¡iyãma, babu shakka a gare Shi.
Su biyu suka ce: "Ya Ubangijinmu!
Jahannama ita ce mai isarsu, zã su shigeta. Sabõda haka makõmarsu ta mũnana.
Ka ce: Shin kũ ne kuke mafi sani kõAllah?
Suka ce: "Mun zauna a yini ɗaya ko rabin yini, sai ka tambayi mãsu ƙidãyãwa."
Kuma gaisuwarsu a cikinta,"Salãmun", kuma ƙarshen kiransu, cẽwa, "Gõdiya ta tabbata ga Allah Ubangijin halittu."
Kuma idan kuka jũya (daga yi Masa ɗã'a), zai musanya waɗansu mutãne waɗansunku sa'an nan bã zã su kasance kwatankwacinku ba.
Ka ce: "Shi ne Ubangijĩna, bãbu abin, bautãwa fãce Shi, a gare Shi na dõgara, kuma zuwa gare Shi tũbãta take."
Kuma mũ, zuwa gare Shi mãsu sallamãwa ne."
Sa'an nan suka jũya baya daga gare shi, Kuma suka ce: "Wanda ake gayãwa ne, mahaukaci."
Kuma bãbu mai tunãni fãce ma'abuta hankula.
Kuma suka ce: "Don me ba a saukar da wannan Alƙur'ãni a kan wani mutum mai girma daga alƙaryun nan biyu ba?"
Wannan shĩ ne! To, su ɗanɗane shi: ruwan zãfi ne da ruɓaɓɓen jini.
Ã'a, Mun yalwata wa waɗannan da ubanninsu ni'imarMu, har rãyuwa ta yi tsawo a kansu. Shin, to, bã su ganin cẽwa lalle Mũ, Munã je wa ƙasarsu, Munã rage ta daga sãsanninta?
Ka cc: "Ba ni bin son zũciyõyinku, (dõmin in nã yi haka) lalle ne, nã ɓace. A sa'an nan, kuma ban zama daga shiryayyu ba."
A lõkacin da Allah Yake nũna maka sũ sunã kaɗan, a cikin barcinka, kuma dã Ya nũna maka su sunã da, yawa, lalle ne dã kun ji tsõro, kuma lalle ne dã kun yi jãyayya a cikin al'amarin, kuma amma Allah Yã tsare ku: Lalle Shĩ ne Masani ga abin da yake a cikin ƙirãza.
(Ciyarwar a yĩ ta) ga matalautan nan waɗanda aka tsare a cikin hanyar Allah, ba su iya tafiyar fatauci a cikin ƙasa, jãhilin hãlinsu yana zaton su wadãtattu sabõda kãmun kai kana sanin su da alãmarsu, ba su rõƙon mutãne da nãcẽwa.
Waɗanda aka bari sun yi farin ciki da zamansu a bãyan Manzon Allah, kuma suka ƙi su yi jihãdi da dũkiyõyinsu da rãyukansu a cikin hanyar Allah, kuma suka ce: "Kada ku fita zuwa yãƙi a cikin zãfi."Ka ce: "Wutar Jahannama ce mafi tsanlnin zãfi."
Kuma ka yi gargaɗi ga danginka mafiya kusanci.
Sai mũnãnan abũbuwan da suka aikata ya sãme su, kuma abin da suka kasance sunã yi na izgili ya wajaba a kansu.
Kõ kuma sun tukka wani al'amari ne?
Game da mãsu laifi.
Lalle ne Ubangijinka Yanã yin hukunci a tsakãninsu a Rãnar Kiyãma a cikin abin da suka kasance sunã sãɓa wa jũna.
Ya ce: "Shin kã zo mana ne dõmin ka fitar da mu daga ƙasarmu game da sihirinka, yã Mũsã?"
Allah ne, da abin da yake a cikin sammai da abin da yake a cikin ƙasa, kuma idan kun bayyana abin da yake a cikin zukatanku (na shaida), ko kuka ɓõye shi, Allah zai bincike ku da shi, sa'an nan Ya yi gãfara ga wanda Yake so, kuma Ya azabta wanda Yake so.
Sai suka ƙaryata shi, sa'an nan Muka kuɓutar da shi da wanda yake tãre da shi, a cikin jirgi, kuma Muka sanya su mãsu mayẽwa, kuma Muka nutsar da waɗanda suka ƙaryata ãyõyinMu.
Har a lõkacin da aka kuranye tsõro daga zukãtansu, sai su ce, 'Mẽne ne Ubangijinku Ya ce?'
Sa'an nan ka zauna shẽkaru a cikin mutãnen Madyana. Sa'an nan kuma ka zo a kan wata ƙaddara, yã Mũsã!
TsarkinSa yã tabbata! Kuma Ya ɗaukaka daga abin da suke sifantãwa.
To, yãya uƙũbãta take?
Ya ce: "Allah Ya tsare mu daga mu kãma wani fãce wanda muka sãmi kãyanmu a wurinsa. Lalle ne mũ, a lõkacin nan, haƙĩƙa, azzãlumai ne."
Kuma a lõkacin da suka yi nadãma, kuma suka ga cẽwalalle ne sũ haƙĩƙa sun ɓace, suka ce: "Haƙĩƙa, idan UbangijinMu bai yi mana rahama ba, kuma Ya gãfarta mana, lalle ne munã kasancẽwa daga mãsu hasãra."
Lalle ne, Allah bã ya shiryar da mutãne azzãlumai.
Suka ce: "Kaitonmu! Lalle, mũ ne muka kasance mãsu ƙẽtare iyãka."
Nĩ ce nã nẽme shi daga kansa.
To, amma idan (mai mutuwar) ya kasance daga makusanta,
Ka zõ mana da abin da kake yi mana wa'adi da shi, idan kã kasance daga manzanni!"
Kuma ina warkar da wanda aka haifa makãho da kuturu, kuma ina rãyar da matottu, da izibin Allah.
Lalle ne Ubangijinka Shĩ neMai ƙarfi, Mabuwãyi.
Kuma sunã cẽwa: "Don me ba a saukar da wata ãyã ba a gare shi, daga Ubangijinsa?" To, ka ce: "Abin sani kawai, gaibi ga Allah yake.
Kuma bã ya kasancẽwã ga muminai su fita zuwa yãƙi gabã ɗaya. Sabõda haka, don me ne wata jama'a daga kowane ɓangare daga gare su ba ta fita (zuwa nẽman ilimi ba) dõmin su nẽmi ilimi ga fahimtar addĩni kuma dõmin su yi gargaɗi ga mutãnensu idan sun kõma zuwa gare su, tsammãninsu, sunã yin sauna?
Kuma shĩ ne Mabuwãyi, Mai hikima.
Da wannan gari amintacce.
Waccan kõmowa ce mai nĩsa."
Lalle ne, idan ba ka hanu ba, haƙĩ ƙa, zan jẽfe ka.
Kuma har idan ya san wani abu daga ãyõyinMu, sai ya rika su da izgili.
Lalle ne Ubangijinku Allah ne, wanda Ya halitta sammai da ƙasa a cikin kwãnaki shida, sa'an nan kuma Ya daidaita a kan Al'arshi, Yanã sanya dare ya rufa yini, yanã nẽman sa da gaggawa, kuma rãnã da watã da taurãri hõrarru ne da umurninSa.
Wani Manzo bã ya zuwa gare su fãce sun kasance sunã mãsu yi masa izgili.
Lalle ne, Mun bayyana ãyõyi ga mutãne masu sakankancewa.
Sa'an nan Mu rarrabe a tsakãninsu, kuma abũbuwan shirkinsu su ce: "Bã mũ kuka kasance kunã bauta wa ba."
"Kada ku yi ĩmãni fãce da wanda ya bi addininku."
Sa'an nan Ya sanya ɗiyansa daga wani asali na wani ruwa wulãkantacce.
Har a lõkacin da umurninMu ya je, kuma tandã ta ɓulɓula.
To, lalle sũ haƙĩƙa mãsu ci ne daga gare ta. Sa'an nan mãsu cika cikuna ne daga gare ta.
Ka ce: "Wãne ne yake tsare ku a dare da yini daga Mai rahama?"
Kuma idan aka saukar da wata sũra cẽwa; Ku yi ĩmãni da Allah kuma ku yi jihãdi tãre da ManzionSa. Sai mawadãta daga gare su su nẽmi izninka, kuma su ce: Ka bar mu mu kasance tãre da mazauna.
Sai suka ce: "Ya Ubangijinmu! Ka nĩsantar da tsakãnin tafiyõyinmu," kuma suka zãlunci kansu, sabõda haka Muka sanya su lãbãran hĩra kuma Muka kekkẽce su kõwace, irin kekkẽcewa.
Sunã zaton kõwace tsãwa a kansu take.
Kuma sun kasance sunã cẽwa: "Shin idan mun mutukuma muko kasance turɓãya da ƙasũsuwa shin lalle mũ waɗanda zã a kõma rãyarwa ne haƙĩƙatan?"
Kuma lalle ne, haƙĩƙa, mun aika zuwa Samũdãwa da ɗan'uwansu, Salihu (ya ce), "Ku bauta wa Allah."
Sabõda haka, ka tsayar da fuskarka ga addini, kanã mai karkata zuwa ga gaskiya, halittar Allah da Ya halitta mutãne a kanta.
Kuma wanda ya yi ĩmãni da Allah, kuma ya aikata aikin ƙwarai, zai kankare masa mũnãnan ayyukansa, kuma Yashigar da shi gidãjen Aljanna, ƙoramu na gudãna daga ƙarƙashinsu, sunã madawwama a cikinsu har abada.
Kuma lalle ne haƙĩƙa Mun sarrafa shi (Alƙur'ãni) a tsakãninsu, dõmin su yi tunãni, sai dai mafi yawan mutãnen sun ƙi fãce kãfirci.
Kuma lalle ne, tã kasance haƙĩƙa, mai girma, sai a kan waɗanda Allah Ya shiryar.
Kuma idan ƙungiyõyin kãfirai sun zo, sunã gũrin da dai sun zama a karkara a cikin ƙauyãwa, sunã tambayar lãbãranku.
Yanã shirya al'amari, Yanã rarrabe ãyõyi daki-daki, mai yiwuwa ne ku yi yaƙĩni da haɗuwa da Ubangijinku.
"Kuma ka bar tẽku rarrabe.
Kuma daga dabbõbi (Ya ƙãga halittar) mai ɗaukar kãya da ƙanãna; Ku ci daga abin da Allah Ya azurta ku, kuma kada ku bi zambiyõyin shaiɗan: LalLe ne shi, a gare ku, maƙiyi ne bayyananne.
Ku yi rukũ'i, kuma ku yi sujada, kuma ku bauta wa Ubangijinku, kuma ku aikata alhẽri, tsammãninku, ku sami babban rabo.
Sabõda haka ku tsayar da salla kuma ku bãyar da zakka kuma ku amince da Allah, Shi ne Majiɓincinku.
To, wanda ya ji tsõron karkata ko kuwa wani zunubi daga mai wasiyyar, sai ya yi sulhi a tsakãninsu to bãbu laifi a kansa.
Kuma mashawarta daga mutãnen Fir'auna suka ce: "Shin, zã ka bar Mũsã da mutãnensa dõmin su yi ɓarna a cikin ƙasa, kuma ya bar ka, kai da gumãkanka?"
Lalle ne a dã sun kasance anã kiran su zuwa, yin sujũdar, alhãli kuwa sunã lãfiya lau, (suka ƙi yi).
Ya ce: "Yã Ubangijĩna!
Haƙĩƙa mun kasance a cikin gafala daga wannan! Ã'a, mun kasance dai mãsu zãlunci!"
Kuma Ubangijinka bã Ya zãluntar kõwa.
Lalle nĩ, inã ganin ku da wadãta.
Lalle Mũ, Mun sãme shi mai haƙuri.
Ku bauta wa Allah Ubangijina, kuma Ubangijinku." Lalle ne shĩ, wanda ya yi shirki da Allah, to, lalle ne, Allah Yã haramta masa Aljanna.
Ka ce: "Ku kãwo dalilinku idan kun kasance mãsu gaskiya."
To, ku yi jira.
Ko kuwa wãne ne zai kasance wakĩli a kansu?
Mun yi ĩmãni, sai ka rubuta mu tãre da mãsu shaida.
Dã waɗannan (abũbuwanbautãwar) sun kasance abũbuwan bautãwar gaskiya ne, dã ba su tusga mata ba, alhãli kuwa dukansu madawwama a cikinta ne.
Ka tunkuɗe cũta da abin da yake mafi kyau, sai ga shi wanda akwai ƙiyayya a tsakaninka da tsakaninsa, kamar dai shi majibinci ne, masoyi.
Lalle ne, Allah ba Ya gãfarta a yi shirki da Shi, kuma Yana gãfarta abin da yake bãyan wannan, ga wanda Yake so. Kuma wanda ya yi shirki da Allah, to, lalle ne ya ɓace ɓata mai nĩsa.
Ya Ubangijinmu! Ka kuranye mana azãba.
Ka ce: "Shin, kun gani, idan azãbarSa ta zo muku da dare ko da rãna?
Sabõda haka ku tsayar da salla kuma ku bãyar da zakka kuma ku amince da Allah, Shi ne Majiɓincinku.
Wurin mai gabatar da shiri
Kuma ku bar bayyanannen zunubi da ɓõyayyensa.
Kuma Shĩ ne Ya hõrẽ tẽku dõmin ku ci wani nama sãbõ daga gare shi, kuma kunã fitarwa, daga gare shi, ƙawã wadda kuke yin ado da ita.
Fãce bãyin Allah waɗanda aka tsarkake.
Dõmin ku yi ĩmani da Allah da ManzonSa, kuma ku ƙarfafa shi, kuma ku girmama Shi, kuma ku tsarkake Shi (Allah) sãfiya da maraice.
Kuma lalle ne Allah bai zama mai zãlunci ga bãyinsa ba."
Suka ce, "Na'am, "kuma amma kalmar azãba ita ce ta wajaba a kan kãfirai!"
Kuma ku yi jihãdi a cikin (al'amarin) Allah, hakkin JihãdinSa. shĩ ne Ya zãɓe ku alhãli kuwa bai sanya wani ƙunci ba a kanku a cikin addĩni. Bisa ƙudurcẽwar ubanku Ibrãhĩm, shĩ ne ya yi muku sũna Musulmi daga gabãnin haka.
(Nũhu) ya ce: "Bãbu mai tsarẽwa a yau daga umurnin Allah fãce wanda Ya yi wa rahama."
Lalle Allah Mai tausasawa ne, Mai ƙididdigewa.
Sunã tambayar ka ga Sã'a.
Mai kyautata halittar sammai da ƙasa, kuma idan Ya hukunta wani al'amari, sai kawai Ya ce masa: "Kasance." Sai ya yi ta kasancewa.
Kuma wanda ya kãfirta, to, kada kãfircinsa ya baƙanta maka rai, zuwa gare Mu makõmarsu take, sa'an nan Mu bã su lãbari game da abin da suka aikata.
"Lalle ne bãyĩNa, bã ka da ĩkõ a kansu, fãce wanda ya bĩ ka daga ɓatattu."
A kan Mu musanya waɗansu (mutãne) kamarku, kuma Mu mayar da ku a cikin wata halitta da ba ku sani ba.
Haƙĩƙa, lalle Mun aiko ManzanninMu da hujjõji bayyanannu, kuma Muka saukar da Littãfi da sikẽli tãre da su dõmin mutãne su tsayu da ãdalci, kuma Mun saukar da baƙin ƙarfe, a cikinsa akwai cutarwa mai tsanani da amfãni ga mutãne, kuma dõmin Allah Ya san mai taimakonSa da ManzanninSa a fake.
Shi ne Wanda ke rayarwa kuma Yana kashewa.
Bã su iya yãƙar ku gabã ɗaya, fãce a cikin garũruwa mãsu gãnuwa da gãruna, kõ kuma daga bãyan katangu.
Kuma ga kãfirai akwai azãba mai wulãƙantarwa.
Kuma kamar wancan ne, Muka nũna su (gare su) dõmin su san lalle wa'adin Allah gaskiya ne, kuma lalle ne Sa'a bãbu shakka a cikinta.
Kuma idan an karanta Alkur'ãni a kansu, bã su yin tawãli'u?
Lalle ne wannan maƙiyi ne gare ka da kuma ga mãtarka, sabõda haka kada ya fitar da ku daga Aljanna har ku wahala."
Kuma Allah a kan dukan kõme Mai ĩkon yi ne.
Kuma in ka ji tsõron wata yaudara daga wasu mutãne, to, ka jẽfar da alkawarin, zuwa gare su, a kan daidaita: Lalle ne Allah, bã Ya son mayaudara.
Kuma ba ya halatta a gare ku (maza) ku karɓe wani abu daga abin da kuka bã su, fãce fa idan su (ma'auran) na tsõron bã zã su tsayar da iyãkõkin Allah ba, Idan kun (danginsu) ji tsõron bã zã su tsayar da iyãkõkin Allah ba, to, bãbu laifi a kansu a cikin abin da ta yi fansa da shi.
"Kuma lalle ne shi, wãwanmu ya kasance yana faɗar abin da ya ƙetare haddi ga Allah."
Ka ce: "Dã akwai waɗansu abũbuwan bautãwa tãre da shi, kamar yadda suka faɗa, a lõkacin, dã (abũbuwan bautãwar) sun nẽmi wata hanya zuwa ga Ma'abũcin Al'arshi."
Lalle ne Ubangijĩna ne Masani game da kaidinsu."
Kuma wani yankin jama, a daga mũminai, su halarci azãbarsu.
Yã kũ jama'a!
To, mẽne ne ya sãme ku a cikin munãfukai kun zama ƙungiya biyu, alhãli kuwa Allah ne Ya mayar da su sabõda abin da suka tsirfanta?
Mãsu kai-kawo ne a tsakãnin wancan; bã zuwa ga waɗannan ba, kuma bã zuwa ga waɗannan ba. Kuma wanda Allah Ya ɓatar, to, bã za ka sãmar masa wata hanya ba.
Ka zuba haƙuri a kanmu kuma Ka tabbatar da sãwayenmu, kuma Ka taimake mu a kan mutãnen nan kãfirai."
Kuma kada ku yi rabo da kibiyoyi na cãca wannan fãsiƙanci ne, A yau waɗanda suka kãfirta sun yanke ƙauna daga addininku.
"Shin, kunã mãmãkin cẽwa ambato yã zo muku daga Ubangijinku a kan wani namiji, daga gare ku, dõmin ya yi muku gargaɗi, kuma dõmin ku yi taƙawa, kuma tsammãninku anã jin ƙanku?"
Lalle ne Allah haƙĩƙa Mai yãfẽwa ne, Mai gãfara.
Kuma Muka sanar da shi sana'ar wata tufa sabõda ku dõmin ya tsare ku daga makãminku. To, shin, ku mãsu gõdẽwa ne?
"Bãbu abõkin tãrayya a gare Shi.
Kuma Allah ne Masani ga mãsu taƙawa.
Kuma makõmarsu wuta ce, kuma tir da mazaunin azzãlumai!
Kuma Shĩ ne Mai rinjãya bisa ga bãyinSa, kuma Yanã aikan mãsu tsaro a kanku, har idan mutuwa ta jẽ wa ɗayanku, sai manzanninMu su karɓi ransa alhãli su ba su yin sakaci.
Kuma wannan (Alƙur'ãni) littafi ne mai gaskatãwa (ga littafin Mũsã), a harshe na Larabci dõmin ya gargaɗi waɗanda suka yi zãlunci, kuma ya zama bushãra ga mãsu kyautatãwa.
Haƙĩƙa, kã kasance a cikinmu, wanda ake fatan wani alhẽri da shi a gabãnin wannan.
To, waɗanda suke sãɓãwa daga umurninSa, su yi saunar wata fitina ta sãme su, kõ kuwa wata azãba mai raɗãɗi ta sãme su.
Kuma da waɗansu waɗanda aka jinkirtar ga umurnin Allah, kõ dai Ya yi musu azãba kõ kuma Ya karɓi tũba a kansu.
Suka ce: "Ya Musa! Lalle ne mu, bã za mu shige ta ba har abada matuƙar sun dawwama a cikinta sai ka tafi kai da Ubangijinka dõmin ku yi yãƙi.
"Kuma Shĩ ne wanda Ya sanya ku mãsu maye wa jũnaga ƙasa. Kuma Ya ɗaukaka sãshenku bisa ga sãshe da darajõji; dõmin Ya jarraba ku a cikin abin da Ya bã ku."
Kuma a lõkacin da lbrãhĩm ya ce: "Yã Ubangijĩna! Ka sanya wannan gari amintacce, Ka azurta mutãnensa, daga 'ya'yan itãcen, wanda ya yi ĩmãni, daga gare su, da Allah da Ranar Lãhira."
Yanã shigar da dare a cikin yini, kuma Yanã shigar da yini a cikin dare, kuma Shi Masani ne ga abin da yake a cikin ƙirãza.
Kuma ya ce: "Yã ɗiyana!
Waɗancan, gidãjensu ne, wõfintattu sabõda zãluncin da suka yi, lalle ne a wancan akwai ãyã ga mutãne waɗanda suke sani.
Wani marmaro ne, a cikinta, ana kiran sa salsabil.
Kuma, mãsu watsa rahama wãtsãwa.
Babu komai cikin bishiyar mazaɓa
Ka ce: "Wãne ne ya haramta ƙawar Allah, wadda Ya fitar sabõda bãyinSa, da mãsu dãɗi daga abinci?"
Bã ya kasancewa ga wani annabi, kãmammu su kasance a gare shi sai (bãyan) yã zubar da jinainai a cikin ƙasa.
A lõkacin da waɗanda suka kãfirta suka sanya hanãnar ƙabĩ lanci a cikin zukãtansu hanãnar ƙabĩlanci irin na Jãhiliyya sai Allah Ya saukar da natsuwarSa a kan ManzonSa, kuma da a kan mũminai kuma Ya lazimta musu kalmar taƙawa alhãli kuwa sun kasance mafi dãcẽwa da ita kuma ma'abutanta. Kuma Allah ya kasance Masani game da dukan kõme.
Kuma shi (abin wahayin) ambato (na ɗaukaka) ne a gare ka da kuma ga mutãnenka, kuma zã a tambaye ku.
Kuma Allah Yanã tãre da mãsu haƙuri.
Dõmin haka wanda Allah Ya yi nufin ya shiryar da shi sai ya bũɗa ƙirjinsa dõmĩn Musulunci, kuma wanda Ya yi nufin Ya ɓatar da shi, sai Ya sanya ƙirjinsa mai ƙunci matsattse, kamar dai yanã tãkãwa ne a ckin sama.
Sunã kãwo uzurinsu zuwa gare ku idan kun kõma zuwa gare su Ka ce: "Kada ku kãwo wani uzuri, bã zã mu amince muku ba.
Kuma wani rai mai ɗaukar nauyi, bai ɗaukar nauyin wani rai. Kuma idan ran da aka nauyaya wa kãya ya yi kira (ga wani mataimaki) zuwa ga kãyansa, bã zã a dauki kõme ba daga gare shi, kuma kõ dã (wanda ake kiran) yã kasance makusancin zumunta ne.
"Yã Ubangijinmu! Ka bã mu abin da Ka yi mana wa'adi (alkawari) a kan manzanninKa, kuma kada Ka tozarta mu a Rãnar ¡iyãma.
Suka ce: "Na'am." Sai mai sanarwa ya yi yẽkuwa, cẽwa: "La'anar Allah ta tabbata a kan azzãlumai."
Bã ni tambayar ku wata ijãra a kansa, ijãrata ba ta zama ba, fãce ga wanda Ya ƙãga halittata.
Kai ne ke yin hukunci a tsakãnin bãyinKa a cikin abin da suka kasance sunã sãɓa wa jũna a cikinsa."
Yanã jin ãyõyin Allah anã karanta su a kansa, sa'an nan ya dõge yanã makãngari, kamar bai jĩ su ba.
Kuma wata ƙungiya daga gare su na nẽman izni ga Annabi sunãcẽwa, "Lalle gidãjenmu kuranye suke," alhãli kuwa bã kuranye suke ba, bã su da nufin kome fãce gudu.
Ka yi mini gãfara (ni) da mahaifana biyu, da wanda ya shiga gidana, yana mai ĩmãni, da mũminai maza da mũminai mãtã, kuma kada Ka ƙãrã wa azzãlumai kõme sai halaka."
Kuma waɗanda suka ƙãfirta ayyukansu sunã kamar ƙawalwalniyã ga faƙo, mai ƙishirwa yanã zaton sa ruwa, har idan ya jẽ masa bai iske shi kõme ba, kuma ya sãmi Allah a wurinsa, sai Ya cika masa hisãbinsa. Kuma Allah Mai gaggãwar sakamako ne.
Kuma kamar wancan ne kãmun Ubangijinka, idan Ya kãma alƙaryõyi alhãli kuwa sunã mãsu zãlunci. Lalle kamũnSa mai raɗaɗi ne, mai tsanani.
Kuma bã dõmin falalar Allah ba a kanku da rahamarSa a cikin dũniya da Lãhira. Lalle ne, dã azãba mai girma ta shãfe ku a cikin abin da kuka kũtsa da magana a cikinsa.
Yã ku waɗanda suka yi ĩmãni! Idan kun haɗu da wata ƙungiyar yãƙi, to, ku tabbata, kuma ku ambaci Allah da yawa, tsammãninku kunã cin nasara.
To, idan aka gane cewa lalle sũ, sun cancanci zunubi to sai wasu biyu su tsayu matsayibsu daga waɗanda suka karɓa daga gare su, mutãne biyu mafiya cancanta, sa'an nan su yi rantsuwa da Allah: "Lalle ne shaidarmu ce mafi gaskiya daga shaidarsu, kuma ba mu yi zãlunci ba.
Waɗannan ne abõkan wuta, sunã madawwama a cikinta.
Kuma su ce, "Wannnan bã kõme ba, fãce sihiri, ne bayyananne."
Kuma da yawa Muka halakar da al'ummomi a bãyan Nũhu.
Bã ya kasancewa ga wani annabi, kãmammu su kasance a gare shi sai (bãyan) yã zubar da jinainai a cikin ƙasa.
Kuma Muka yi wahayi zuwa ga Mũsã da ɗan'uwansa, cẽwa: Kũ biyu, ku zaunar da mutãnenku a Masar a cikin wasu gidãje. Kuma ku sanya gidãjenku su fuskanci Alƙibla, kuma ku tsayar da salla.
Abin da ke cikin sammai da ƙasa yã yi tasbĩhi ga Allah.
Ka ce: "Allah".
Lalle Allah nã yin umurni da ãdalci da kyautatãwa, da bai wa ma'abũcin zumunta, kuma yanã hani ga alfãsha da abin da aka ƙi da rarrabe jama'a.
To, a'aha! Ina rantsuwa da Ubangijinka, ba za su yi ĩmãni ba, sai sun yarda da hukuncinka ga abin da ya sãɓa a tsakãninsu, sa'an nan kuma ba su sãmi wani ƙunci a cikin zukãtansu ba, daga abin da ka hukunta, kuma su sallama sallamãwa.
Kada ka kira wani abin bautãwa na dabam tãre da Allah. Bãbu abin bautãwa fãce Shi.
Wanda ya aikata wancan bisa ta'adi da zãlunci, to, zã Mu ƙõne shi da Wuta. Kuma wannan yã kasance ga Allah (abu ne) mai sauƙi.
Gidãjen Aljannar zama sunã shigarsu, sũ da waɗandasuka kyautatu daga iyãyensu, da mãtansu da zũriyarsu.
Kuma aka ce ku zauna tãre da mãsu zama.
Kuma idan Muka musanya wata ãyã a matsayin wata ãyã, kuma Allah ne Mafi sani ga abin da Yake saukarwa sai su ce: "Abin sani kawai, kai, aƙirƙiri ne."
Kuma Ya arzũta shi daga inda bã ya zato.
Kuma lalle ne haƙĩƙa a gabaninsu, Mun fitini mutãnen Fir'auna, kuma wani Manzo karĩmi ya jẽ musu.
Lalle a cikin wancan akwai ãyõyi ga mutãne mãsu yin ĩmãni.
Kuma Muka fitar da abin da yake a cikin ƙirãzansu, daga ƙiyayya, ƙõramu sunã gudãna daga ƙarƙashinsu, kuma suka ce: "Gõdiya ta tabbata ga Allah, wanda Ya shiryar da mu ga wannan.
Sai suka ƙaryata shi. Sabõda haka sũ lalle waɗanda zã a halartãwa ne (a wutã).
Kuma dã dai lalle su, sun tsayar da Attaura da Injĩla da abin da aka saukar zuwa gare su daga Ubangijinsu, haƙĩƙa, dã sun ci daga bisansu da kuma daga ƙarƙashin ƙafãfunsu.
Ku yi ãdalci Shĩ ne mafi kusa ga taƙawa.
Kuma lalle ne waɗanda aka gãdar wa Littafi daga bãyansu, haƙiƙa, sunã cikin shakka a gare shi, mai sanya kokanto.
Abin sani kawai, wanda ake bautãwa guda ne, sa'an nan sai kuji tsõroNa, Ni kawai."
Kuma lalle ne, haƙĩƙa, Mun bã ka bakwai waɗanda ake maimaita karatunsu da Alƙur'ãni mai girma.
Sunã a gidan dawwama a cikinta, dõmin sakamako ga abin da suka kasance sunã yin musu game da ãyõyinMu.
Kuma suka yi tsẽre zuwa ga ƙõfa. Sai ta tsãge rigarsa daga bãya, kuma suka iske mijinta a wurin ƙõfar.
A cikin Allo tsararre.
Ta ce: "Kamar dai shĩne.
Bãbu majiɓintanSa fãce mãsu taƙawa. Kuma mafi yawansu ba su sani ba.
Lalle ne Kai Kanã sanin abin da muke ɓõyẽwa, da abin da muke bayyanãwa. Kuma bãbu abin da yake ɓõyẽwa ga A1lah, daga wani abu a cikin ƙasa, kuma bãbu a cikin sama."
Kuma Shi ne Ya saukar da ruwa daga sama, Muka fitar da tsiron dukkan kõme game dã shi, sa'an nan Muka fitar da kõre daga gare shi, Muna fitar da kwãya ɗamfararriya daga gare shi (kõren), kuma daga dabĩno daga hirtsinta akwai dumbuje-dumbuje makusanta, kuma (Muka fitar) da gõnaki na inabõbi da zãitũni da rummãni, mãsu kamã da jũna da wasun mãsu kama da jũna. Ku dũba zuwa 'ya'yan itãcensa, idan ya yi 'ya'yan, da nunarsa.
Kuma idan kun kwance harama, to, ku yi farauta.
Suka ce: "Kuma mẽne ne a gare mu, ba zã mu yi yãƙi ba, a cikin hanyar Allah, alhãli kuwa, haƙiƙa, an fitar da mu daga gidãjenmu da ɗiyanmu?"
Kuma ka yi bushãra ga mãsu kyautata yi.
Kuma kada ka kõri waɗanda suke kiran Ubangijinsu sãfe da maraice, sunã nufin yardarSa, babu wani abu daga hisãbinsu a kanka, kuma babu wani abu daga hisãbinka a kansu, har ka kõre su ka kasance daga azzãlumai.
Allah Ya yi musu tattalin wata azãba mai tsanani. Sabõda haka ku bi Allah da taƙawa, yã ma'abũta hankula, waɗanda suka yi ĩmãni!
(Ĩsã) Ya ce: "Tsarkinka yã tabbata!
"Yã Yũsufu!
Sai ya ce: "Kuji dãɗi a cikin gidãjenku kwãna uku.
Kuma Wanda Ya ƙaddara (abin da Ya so) sannan Ya shiryar, (da mutum ga hanyar alhẽri da ta sharri).
Na'am, lalle Shi, Mai ĩkon yi ne a kan kõme.
Sabõda haka sai su bauta wa Ubangijin wannan Gida (Ka'abah).
Sabõda haka wanda ya so, to, ya yi ĩmãni, kuma wanda ya so, to, ya kãfirta.
Allah, bãbu wani Ubangiji fãce Shi, Rãyayye, Mai tsayuwa da kõme, gyangyaɗi bã ya kãma Shi, kuma barci bã ya kãma Shi, Shi ne da abin da yake a cikin sammai da abin da yake a cikin ƙasa.
To, shin, ku mãsu gõdẽwa ne?
Kuma idan kun kãfirta, to, Allah Yanã da abin da ke cikin sammai da ƙasa. Kuma Allah Yã kasance Masani, Mai hikima.
Waccan fa ita ce falala mai girma.
Kuma waɗanda aka bai wa ilmi da ĩmãni suka ce: "Lalle, haƙĩƙa kun zauna a cikin Littãfin Allah, har zuwa rãnar tãyarwa, to, kuma wannan ita ce rãnar tãyarwar, kuma amma kũ, kun kasance ba ku sani ba."
Lalle Shi Ya kasance ga bãyinsa, mai ƙididdigewa ne Mai gani."
Ya ce: "Amma wanda ya yi zãlunci, to zã mu azabta shi, sa'an nan a mayar da shi zuwa ga Ubangijinsa, sai kuma Ya yi masa azãba, azãba abar ƙyãma."
"Yanã son ya fitar da ku daga ƙasarku game da sihirinSa.
Sa'an nan kuma Allah Ya kyautata ãyõyinSa.
"Kuma lalle ne ni, kõ da yaushe na kirãye su dõmin Ka gãfarta musu, sai su sanya yatsunsu a cikin kunnuwansu, su lulluɓe da tufãfinsu, su dõge ga yin laifi. Sun yi girman kai iyãkar girman kai."
Lalle wannan, haƙĩƙa, abu ne mai ban mãmãki."
Munã ɗaukaka darajõji ga wanda Muka so, kuma a saman kõwane ma'abũcin ilmi akwai wani masani.
Kuma lalle ne haƙĩƙa, kun zo Mana ɗai ɗai, kamar yadda Muka halittã ku a farkon lõkaci.
Kuma aka ce: "A yau zã Mu manta da ku, kamar yadda kuka manta da gamuwa da yininku wannan.
Lalle ne mutum, haƙĩƙa, mai yawan zãlunci ne, mai yawan kãfirci.
Ɓoye shirin ayukan tagogi kuma ka nuna kwamfytan tebur
"Kada ku yi girman kai a gare ni, kuma ku zo mini kunã mãsu sallamãwa."
Ka ce: "Ku zo, in karanta abin da Ubangijinku Ya haramta." wãjibi ne a kanku kada ku yi shirkin kõme da Shi, kuma ga mahaifa biyu (ku kyautata) kyautatãwa, kuma kada ku kashe ɗiyanku sabõda talauci, Mũ ne Muke azurta ku, kũ da su, kuma kada ku kusanci abũbuwa alfãsha, abin da ya bayyana daga gare ta da abin da ya ɓõyu, kada ku kashe rai wanda Allah Ya haramta, fãce da hakki.
Lalle shĩ ya ƙẽtare haddi (ga girman kai)."
Lalle ne Allah Yana bã ki bushãra da wata kalma daga gare Shi; sũnansa Masĩhu ĩsa ɗan Maryama, yana mai daraja a dũniya da Lãhira kuma daga Makusanta.
Kuma Allah bã Ya shiryar da mutãne fasiƙai.
"Wannan shĩ ne abin da ake yi muku wa'adi da shi ga dukan mai yawan kõmawa ga Allah, mai tsarewar (umurninSa).
Kamar haka Allah Yake shãfe haske a kan zukãtan waɗanda ba su sani ba.
Sunã madawwamã a cikinsu, har abada.
Sa'an nan a lõkacin da ya yi nauyi, sai suka rõƙi Allah, Ubangijinsu: "Lalle ne idan Ka bã mu abin ƙwarai, haƙĩƙa, zã mu kasance dagamãsu gõdiya."
Dã Yanã kãma su sabõda abin da suka sanã'anta, lalle ne, dã Ya gaggauta azãba a gare su. Ã'a, sunã da lõkacin alkawari, (wanda) bã zã su sãmi wata makõma ba, baicinSa.
Kuma kada ku kasance kamar waɗanda suka manta Allah shi kuma Ya mantar da su rãyu, kansu.
Da wasu dabbõbi an hana bãyayyakinsu, da wasu dabbõbi bã su ambatar sũnan Allah a kansu, bisa ƙirƙiren ƙarya gare Shi.
Dõmin haka kawai Muka sauƙaƙar da shi (Alƙur'ãni) da harshenka, tsammãninsu, su riƙa tunãwa.
Kuma ku ciyar a cikin hanyar Allah. Kuma kada ku jefa kanku da hannayenku, zuwa ga halaka.
Kuma wanda bai yi hukunci ba da abin da Allah ya saukar, to, waɗannan su ne fãsiƙai.
Shĩ ne wanda Ya aiki ManzonSa da shiriya da addinin gaskiya dõmin Ya rinjãyar da shi a kan addinai dukansu.
A lõkacin da samarin suka tattara zuwa ga kõgon, sai suka ce: "Ya Ubangijinmu! Ka bã mu wata rahama daga gare Ka, kuma Ka sauƙaƙe mana (sãmun) shiriya daga al'amarinmu."
Kuma shĩ bã bananci bane
Waɗancan, waɗanda suke kiran, sunã nẽman tsãni zuwa ga Ubangijinsu. Waɗanne ne suke mafĩfĩta a kusanta?
"Kuma yana yi wa mutãne magana a cikin shimfiɗar jariri, da kuma lõkacin da yana dattijo, kuma yana daga sãlihai."
Kuma ga kõwace al'umma Mun sanya ibãdar yanka, dõmin su ambaci sũnan Allah a kan abin da Ya azurta su da shi daga dabbõbin ni'ima.
Kuma dã Ubangijinka Yã so, dã ba su aikatã shi ba, don haka ka bar su da abin da, suke ƙirƙirãwa.
Kuma Dãwũda da Sulaimãn sa'ad da suke yin hukunci a cikin sha'anin shũka a lõkacin da tumãkin mutãne suka yi kiĩwon dare a cikinsa.
Wannan maɓalli na ƙayyade yawan sakan da za'a nuna ko wacca firam.
Allah ne Wanda Ya saukar da Littãfi da gaskiya, da sikeli.
Kuma daga inda ka fita, to, ka jũyar da fuskarka a wajen Masallãci Tsararre kuma inda kuke duka, to, ku jũyar da fuskõkinku a wajensa, dõmin kada wata hujja ta kasance ga mutãne a kanku, fãce waɗanda suka yi zãlunci daga gare su. Sabõda haka kada ku ji tsõronsu kuma ku ji tsõrõNa kuma dõmin In cika ni'imaTa a kanku, kuma tsammãninku zã ku shiryu.
Kuma aka niƙe duwãtsu, niƙẽwa.
Ya ce: "Lalle akwai Lũɗu a cikinta!"
Kuma ka ambaci ɗan'uwan Ãdãwa a lõkacin da ya yi gargaɗi ga mutãnensa, a Tuddan Rairayi, alhãli kuwa waɗansu mãsu gargaɗi sun shũɗe agaba gare shi da bãya gare shi (da cẽwa) "Kada ku bauta wa kõwa fãce Allah.
Kuma a lõkacin da umurninMu yã je, Muka kuɓutar da Shu'aibu da waɗanda suka yi ĩmãni tãre da shi, sabõda wata rahama daga gare, Mu.
Sa'an nan idan wani alhẽri ya sãme shi, sai ya natsu da shi, kuma idan wata fitina ta sãme shi, sai ya jũya bãya a kan fuskarsa. Yã yi hasãrar dũniya da Lãhira.
Shi ne wanda Ya halitta ku daga lãkã, sa'an nan kuma Ya yanka ajali alhãli wani ajali ambatacce yanã wurinSa.
Ya ce: "Shin kun bã ni bushãra ne a kan tsũfa yã shãfe ni?
Lalle shĩ wanda ya je wa Ubangijinsa yanã mai laifi, to lalle ne yanã da Jahannama, bã ya mutuwa a cikinta kuma bã ya rãyuwa.
"Mulki ga wa ya ke a yau?"
Kuma bãbu laifi a kanku a cikin abin da kuka gitta da shi daga nẽman auren mãtãko kuwa kuka ɓõye a cikin zukatanku. Allah Ya san cẽwa lalle ne ku za ku ambata musu (shi).
Sai wasu' yan bãya suka maye daga bãyansu, sun gaji Littãfin, sunã karɓar sifar wannan ƙasƙantacciya, sunã cẽwa: "Zã a gãfarta mana.
Ashe? Yanzu kuwa, alhãli kun kasance game da shi kunã nẽman gaggãwar aukuwarsa?
"Lalle, Nĩ Ni ne Allah.
Lalle ne kũ, haƙĩƙa, kunã faɗar magana mai girma!
Kuma bã su da wani ilmi game da shi, bã su bin kõme fãce zato alhãli kuwa lalle zato bã ya amfãnar da kõme daga gaskiya.
Rãnar da ƙasa ke raurawa, da duwãtsu kuma duwãtsu su kasance tudun rairayi mai malãlã.
Allah ne da mallakar sammai da ƙasa da abin da ke a cikinsu kuma shi, a kan dukkan kõme Mai ĩkon yi ne.
Kuma lalle ne, wannan al'ummarku ce, al'umma guda, kuma Nĩ, Ubangijinku ne, sai ku bĩ Ni da taƙawa.
Sai suka ji daɗi da rabonsu, sai kuka ji daɗi da rabonku kamar yadda waɗanda suke a gabãninku suka ji dãɗi, da rabonsu, kuma kuka kũtsa kamar kũtsãwarsu.
Don me bã su zuwa da wata hujja bayyananna a kansu (waɗanda ake bautawar)?
Kuma Allah ne ga abin da suke aikatãwa Mai kẽwayẽwa.
Ka ce: "Idan kun kasance kunã son Allah to, ku bĩ ni, Allah Ya sõ ku, kuma Ya gãfarta muku zunubanku.
Sai suka ƙaryata shi, sa'an nan Muka kuɓutar da shi da wanda yake tãre da shi, a cikin jirgi, kuma Muka sanya su mãsu mayẽwa, kuma Muka nutsar da waɗanda suka ƙaryata ãyõyinMu.
Kuma idan sun ga dukan ãyã, bã zã su yi ĩmãni da ita ba, kuma idan sun ga hanyar shiriya, bã zã su riƙe ta hanya ba, kuma idan sun ga hanyar ɓata, sai su riƙe ta hanya.
Ka ce: "To, wane ne ke iya mallakar wani abu daga Allah, idan Yã nufi Ya halakar da Masĩhu ɗanMaryama da uwarsa da wanda yake a cikin ƙasa gabã ɗaya?"
Kuma ka bi abin da ake yin wahayinsa zuwa gare ka, kuma ka yi haƙuri har Allah Ya yi hukunci. Kuma Shĩ ne Mafi alhẽrin mãsu hukunci.
Fanel na tsakiya mai kan x-axis
Lalle shi mai farin ciki ne, mai alfahari.
To, da wane lãbãri a bãyansa suke yin ĩmãni?
To, tir da abin da suke saye!
Kuma waɗanda suka yi ĩmãni sunã cewa: "Shin, waɗannan ne waɗanda suka yi rantsuwa da Allah iyãkar rantsuwõyinsu, cewa su, lalle sunã tãre da ku?"
Ka ce: "Kunnen alhẽri gare ku, Yanã ĩmãni da Allah, kuma Yanã yarda da mũminai, kuma rahama ne ga waɗanda suka yi ĩmãni daga gare ku."Kuma waɗanda suke cũtar Manzon Allah sunã da azãba mai raɗaɗi.
Har idan mutuwa ta jẽ wa ɗayansu, sai ya ce: "Yã Ubangijina, Ku mayar da ni (dũniya)."
Fãce idan Allah Ya so.
Ashe, kun ji tsõron ku gabãtar da sadakõki a gabãnin gãnãwarku?
Ka ce: "Yã Allah Mamallakin mulki, Kanã bayar da mulki ga wanda Kake so, Kanã zãre mulki daga wanda Kake so, kuma Kanã buwãyar da wanda Kake so, kuma Kanã ƙasƙantar da wanda Kake so, ga hannunKa alhẽri yake.
A cikin wasu ginshiƙai mĩƙaƙƙu.
Sa'an nan idan (sãbon mijin, watau na biyu) ya sake ta, to, bãbu laifi a kansu ga su kõma wa (auren) jũna, idan sun (mijin farko da matar) yi zaton cẽwa zã su tsayar da iyãkõkin Allah, kuma waɗancan dõkõkin Allah ne Yana bayyana su ga mutãne waɗanda suke sani.
Kuma abin da kuka gabatar dõmin kanku, na alhẽri, zã ku sãme shi a wurin Allah zai kasance mafifici (daga wanda kuka ajiye) kuma zai fi girma ga sakamako, kuma ku rõƙi Allah gãfara; lalle ne Allah Mai gãfara ne, Mai jin ƙai.
Kuma amma wanda aka bai wa littãfinsa, daga wajen bãyansa.
Kuma Ubangijĩna Yanã musanya waɗansu mutãne, waɗansunku su maye muku. Kuma bã ku cũtar Sa da kõme.
Kuma sũ ne waɗanda suke sãdar da abin da Allah Ya yi umurni da shi dõmin a sãdar da shi kuma sunã tsõron Ubangijinsu, kuma sunã tsõron mummũnan bincike.
Kuma yãyã kuke kãfircẽwa alhãli kuwa anã karanta ãyõyin Allah a gare ku, kuma a cikinku akwai manzonSa?
Kõ wãne ne yake karɓã, kuma ya sanya ku mamãyan ƙasa? Shin akwai wani abin bautawa tãre da Allah?
Kõ sunã da tãrayya ne a cikin sammai?
Kuma sunã tambayar ka: Shin gaskiya ne?
Kuma Mun isa zama Mãsu hisãbi.
Lalle ne waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai lalle ne Mũ bã Mu tõzartar da lãdar wanda ya kyautata aiki.
To, ku yi haƙuri ko kuma kada ku yi haƙuri, dai dai ne a kanku, kawai anã yi muku sakamakon abin da kuka kasance kunã aikatãwa."
Kuma idan kun yi sulhu, kuma kuka yi taƙawa, to, lalle ne Allah Yã kasance Mai gãfara, Mai jin ƙai.
Kuma Ka yãfe daga gare mu, kuma Ka gãfarta mana, kuma Ka yi jin ƙai gare mu.
Allah Ya yi musu tattalin azãba mai tsanani.
Haƙĩƙa Ubangijinki Ya sanya wani marmaro a ƙarƙashinki.
"Kuma kunã barin abin da Ubangijinku Ya halitta muku daga mãtanku?
Da shĩ ake narkar da abin da yake a cikin cikunansu da fãtun jikinsu.
Sai su zõ da wani lãbãri mai misãlinsa idan sun kasance sũmãsu gaskiya ne.
Kuma idan hakki ya kasance a gare su, zã su jẽ zuwa gare shi, snnã mãsu mĩƙa wuya.
Wancan ne addini madaidaici, kuma amma mafi yawan mutãne ba su sani ba."
Sabõda haka, kada wata rãyuwa ta kusa ta rũde ku, kuma kada marũɗin nan ya rũɗẽ ku game da Allah.
Fãce dai waɗanda suke sãduwa zuwa ga wasu mutãne waɗanda a tsakãninku da su akwai alkawari, kõ kuwa waɗanda suke sun je muku (domin) ƙirãzansu sun yi ƙunci ga su yãke ku, kõ su yãƙi mutãnensu.
"Wannan shĩ ne abin da ake yi muku wa'adi da shi ga dukan mai yawan kõmawa ga Allah, mai tsarewar (umurninSa).
Kuma lalle ne idan kun mutu ko kuwa aka kashe ku, haƙĩƙa, zuwa ga Allah ake tãra ku.
To, wanda ya tuba a bãyan zãluncinsa, kuma ya gyãra (halinsa), to, lalle ne Allah Yanã karɓar tubarsa.
Da Samũdãwa, sa'an nan bai rage su ba.
Lalle Shi, Yã kasance Mai sani ga bãyinSa, Mai gani.
Suka ce: "Na'am."
Kuma lalle ne, idan ka tambaye, su haƙĩƙa, sunã cẽwa, "Abin sani kawai, mun kasance munã hĩra kuma munã wãsã.
Waɗancan sunã a cikin wata ɓata bayyananna.
Kuma akwai daga cikin ãyõyinSa, barcinku a cikin dare da rãna, da nẽmanku ga falalarsa.
Ku aikata abin da kuke so! Lalle Shĩ Mai gani ne ga abin da kuke aikatãwa.
Ya ɗaukaka daga abin da suke yi na shirka.
Inã rantsuwa da sama mai taurãrin lissafin shekara.
Kuma lalle, haƙĩƙa, ya yi musu gargaɗin damƙarMu, sai suka yi musu game da gargaɗin.
Sa'an nan kuma Muka sanya shi, ɗigon maniyyi a cikin matabbata natsattsiya.
Ta ce: "Yã Ubangijĩna!
Kuma suka ce: "Tatsũniyõyi ne na farko ya rurrbũta, sai sũ ake shibtarsu a gare shi sãfe da yamma."
Sukace: "Tsarki ya tabbata a gare Ka. Kai ne Majiɓincinmu, bã su ba.
"Kuma idan ba ku yi ĩmãni sabõda nĩ ba, to, ku nĩsance ni."
Ya ku waɗanda suka yi ĩmãni! Kada dũkiyõyinku da ɗiyanku su shagaltar da ku daga ambaton Allah.
Sai suka kãfirta kuma suka jũya bãya, kuma Allah Ya wadãtu (daga gare su). Kuma Allah wadãtacce ne, Gõdadde.
Shin fa, ba ku tunãni?
Kada ku shiga ta ƙõfa guda, ku shiga ta ƙõfõfi dabam-dabam, kuma bã na wadãtar muku kõme daga Allah.
To mẽne ne kuke shãwartãwa?"
Bã su iya yãƙar ku gabã ɗaya, fãce a cikin garũruwa mãsu gãnuwa da gãruna, kõ kuma daga bãyan katangu.
To, kada ku ji tsõron mutãne kuma ku ji tsõroNa kuma kada ku sayi 'yan kuɗi kaɗan da ãyoyiNa. wanda bai yi hukunci ba da abin da Allah Ya saukar, to, waɗannan su ne kafirai.
Bã Mu sassaukar da malã'iku fãce da gaskiya, bã zã su kasance, a wannan lõkacin, waɗanda ake yi wa jinkĩri ba.
Bãbu hukunci fãce daga Allah, a gare Shi na dõgara, kuma a gare Shi mãsu dõgara sai su dõgara."
"Kamar wannan ne Muke bayyana ãyõyi, daki-daki, ga mutãnen da suke sani.
Kõ wãne ne Ya halitta sammai da ƙasa kuma Ya saukar muku, daga, sama, wani ruwa, Muka tsirar, game da shi, gõnaki mãsu sha'awa, ba ya kasancẽwa gare ku, ku tsirar da itãcensu?
To, wanda aka sanya wa lalũra a cikin yunwa mai tsanani, bã yana mai karkata zuwa ga wani zunubi ba, to, lalle ne Allah Mai gãfara ne, Mai jin ƙai.
Kuma ba Mu halicci sammai da ƙasa da abin da yake a tsakãninsu ba fãce da gaskiya. Kuma lalle ne Sã'a (Rãnar Alƙiyãma) haƙĩƙa mai zuwa ce.
Kuma ba ya halatta a gare ku (maza) ku karɓe wani abu daga abin da kuka bã su, fãce fa idan su (ma'auran) na tsõron bã zã su tsayar da iyãkõkin Allah ba, Idan kun (danginsu) ji tsõron bã zã su tsayar da iyãkõkin Allah ba, to, bãbu laifi a kansu a cikin abin da ta yi fansa da shi.
Lalle Mũ, Mun yi maka rinjãye (a kan maƙiyanka), rinjaye bayyananne.
Yã ku waɗanda suka yi ĩmãni! Kada ku riƙi waɗanda suka riƙi addininku bisa izgili da wãsa, daga waɗanda aka bai wa Littãfi daga gabãninku da kãfirai, masõya, Kuma ku bi Allah da taƙawa idan kun kasance muminai.
Kuma ku bi Allah da taƙawa. Kuma ku sani cẽwa lalle ne, Allah Yana tãre da mãsu taƙawa.
Bã zã mu yi ĩmãni ba dõminka, sai munga Allah bayyane," sabada haka tsãwar nan ta kamaku, alhãli kuwa kuna kallo.
Kuma amma waɗanda suka yi ƙyãma, kuma suka yi girman kai, to, zã Ya yi musu azãba, azãba mai raɗɗi kuma bã su samun wani masõyi dõmin kansu, baicin Allah, kuma bã su samun mataimaki.
Kuma idan sun ƙaryata ka, to, lalle, an ƙaryata waɗansu Manzanni a gabãninka, kuma zuwa ga Allah ake mayar da al'amura.
Ku yi aiki a kan hãlinku, lalle nĩ, inã aiki a kan hãlĩna.
Ka yi hukunci da gaskiya.
Kuma ka ambaci Mũsã a cikin Littãfi.
Lalle ne Allah Mahalarci ne a kan dukkan kõme.
Waɗannan da suka kãfirta game da Alkur'ãni a lõkacin da ya je musu, kuma lalle shi haƙĩƙa littãfi ne mabuwãyi.
Suka ce: "Ya Sãlihu! Haƙĩƙa, kã kasance a cikinmu, wanda ake fatan wani alhẽri da shi a gabãnin wannan.
Lalle ne a cikin wannan akwai ãyõyi ga waɗanda suke yin ĩmãni.
Sa'an nan lalle ne za a tambaye ku, a rãnar nan lãbãrin ni'imar (da aka yi muku).
Bãbu wani macẽci fãce a bayan izninSa.
Kuma Allah Mai ƙididdigewa ne ga abin da kuke aikatãwa.
Ba su bin kõme sai fãce ƙaddari-faɗi suke yi.
Kuma aka biyar musu da la'ana a cikin wannan dũniyada Rãnar Kiyãma.
A lõkacin da ya kirãyi Ubangijinsa, kira ɓõyayye.
Kuma daga rãƙuma akwai nau'i biyu, kuma daga shãnu biyu; ka ce: Shin, mazan biyu ne Ya hana ko mãtan biyu Ya hana, kõ abin da mahaifar mãtan biyu suka tattara a kansa?
Shin lalle ne ku, haƙĩƙa, kunã shaidar cẽwa, lalle ne tãre da Allah akwai wasu abũbuwan bautawa?"
Ka ce: "Ku kirãwo abũbuwan shirkinku sa'an nan kuma ku yi mini kaidi, sa'an nan kada ku saurãra mini."
Ya ce: "Ya Ubangijĩna, nĩ inã tsõron su ƙaryata ni.
"Kuma idan kun yi damƙa, sai ku yi damƙar kunã mãsu tanƙwasãwa."
Lalle, Allah Ya kasance Mai labartawa ga abin da kuke aikatawa.
Kuma Muka taimake shi daga mutãnen nan waɗanda suka ƙaryata da ãyõyinMu.
Waɗannan, a cikin gidãjen Aljanna, waɗanda ake girmamãwa ne
Sabõda haka tsarki ya tabbata ga Allah Ubangijin Al'arshi daga abin da suke siffantãwa.
To, idan sun nẽme ka izni sabõda wani sha'aninsu, to, ka yi izni ga wanda ka so daga gare su, kuma ka nẽmã musu gãfara daga Allah.
Ba Mu sanar da shi (Annabi) wãkã ba, kuma wãkã ba ta kamãta da shi (Annabi) ba.
Kuma kace "Shi ne Ya halitta ku daga ƙasã, kuma zuwa gareShi ne ake tãshin ku."
Yã Ubangijinmu! Lalle Kai ne Mai tausayi, Mai jin ƙai.
Kuma zã su yi ta yin rantsuwa da Allah, "Dã mun sãmi dãma, dã mun tafi tare da ku."
Kuma Ka yãfe daga gare mu, kuma Ka gãfarta mana, kuma Ka yi jin ƙai gare mu.
Ya ce: "Yã Ubangijina! Yãya yãro zai sãmu a gare ni, alhãli kuwa, lalle tsũfa ya sãme ni, kuma mãtãta bakarãriya ce?"
Inã rantsuwa da sama da mai aukõwa da dare.
Ya ce: "Za mu dũba shin kã yi gaskiya ne, kõ kuwa kã kasance daga maƙaryata?"
Yã Mutãnen littãfi! Lalle ne, ManzonMu yã je muku, yanã bayyana muku abu mai yawa daga abin da kuka kasance kunã ɓõyewa daga Littãfi, kuma yanã rangwame daga abu mai yawa.
"Kuma kãmar wancan ne, Ubangijinka Yake zãɓen ka, kuma Ya sanar da kai daga fassarar lãbãrai, kuma ya cika ni'imõminSa a kanka, kuma a kan gidan Yãƙũba kãmar yadda ya cika su a kan ubanninka biyu, a gabãni, Ibrãhĩm da Is'hãƙa.
Lalle ne rai, haƙĩƙa, mai yawan umurni ne da mummũnan aiki, fãce abin da Ubangjina Ya yi na; rahama. Lalle Ubangjina Mai gãfara ne, Mai jin ƙai."
Kuma ka ambaci Idrĩsa a cikin Littãfi.
Ya halitta sammai da ƙasã da abin da yake hakkinSa.
Lalle Allah Masani ne ga dukkan kõme.
Shin, (kunã so) in gaya muku a kan wanda Shaiɗãnnu kan sauka?
Ya ku waɗanda suka yi ĩmãni! Ku ciyar daga mai kyaun abin da kuka sanã'anta, kuma daga abin da Muka fitar sabõda ku daga ƙasa, kuma kada ku yi nufin mummuna ya zama daga gare shi ne kuke ciyarwa, alhãli kuwa ba ku zama mãsu karɓarsa ba fãce kun runtse ido a cikinsa.
Kõ Ya halakã su (sũ jirãgen) sabõda abin da mãsu su suka sanã'anta, alhãli kuwa Yanã yãfe (laifuffuka) mãsu yawa.
Kõ kuwa sũ ne mãsu rinjãya?
Kuma Allah ne wakili a kan kõme.
Kuma lalle ne, idan ka tambaye, su haƙĩƙa, sunã cẽwa, "Abin sani kawai, mun kasance munã hĩra kuma munã wãsã.
Shin fa, bã ku hankalta?
Ya ce: "Wancan ne abin da muka kasance munã biɗã."
Shĩ ne wanda Yake tafiyar da ku a cikin tudu da (kuma) tẽku, sai idan kun kasance a cikin jirãge, su gudãna tãre da su da iska mai dãɗi, kuma su yi farin ciki da ita, sai wata gũguwa ta je wa jirãgen, kuma tãguwar ruwa ta jẽ musu daga kõwane wuri, kuma su tabbata cẽwa sũ, an kẽwaye su, sai su kirãyi Allah, sunã mãsu tsarkake addini gare Shi, (sunã cẽwa): Lalle ne idanKa kuɓutar da mu daga wannan, haƙĩƙa munã kasancẽwa daga mãsu gõdiya.
Kuma ba Mu shiryar da shi ga hanyõyi biyu ba?
Ya ce: "Kuma daga zũriyata."
Lalle ne munãfukai sunã yaudarẽwa da Allah, alhãli kuwa Shi ne mai yaudarasu; kuma idan sun tãshi zuwa ga salla, sai su tãshi sunã mãsu kasãla. Suna nũnawa mutãne, kuma ba su ambatar Allah sai kaɗan.
Kuma suka ce: "Gõdiya ta tabbata ga Allah Wanda Ya yi mana gaskiya ga wa'adinSa, kuma Ya gãdar da mu ƙasã, munã zama a cikin Aljanna a inda muke so."
Ya ce: "Lalle ne, Allah Yã zãɓe shi a kanku, kuma Ya ƙãra masa yalwa a cikin ilmi da jiki.
Ku shiga kofõfin Jahannama kunã madawwama a cikinta.
Haƙiƙa, tir daga abin da suka kasance sunã sanã'antãwa.
Kuma idan ma'abũta zumunta da marãyu da matalauta suka halarci rabon, to, ku azurta su daga gare shi, kuma ku faɗa musu magana sananniya ta alhẽri.
Dõmin Allah Ya rarrabe mummũna daga mai kyau, kuma Ya sanya mummũnan, sãshensa a kan sãshe, sa'an nan Ya shirga shi gabã daya, sa'an nan Ya sanyã shi a cikin Jahannama.
A'a, rãyayyu ne su, a wurin bangijinsu. Ana ciyar da su.
"Kuma mẽne ne a gare mu, bã zã mu dõgara ga Allah ba, alhãli kuwa haƙĩƙa Yã shiryar da mu ga hanyõyinmu?
Lalle ne Allah haƙĩƙa Mai yãfẽwa ne, Mai gãfara.
Kuma ka ambaci sũnan Ubangijinka, kuma ka yanke (ƙauna daga kowa ka koma) zuwa gare Shi, yankewa.
Zuwa ga Allah makõmarku take gabã ɗaya. Sa'an nan Ya bã ku lãbãri ga abin da kuka kasance kunã sãɓãwa a cikinsa.
Kõ shin duhu da haske sunã daidaita? ko sun sanya ga Allah waɗansu abõkan tãrayya waɗanda suka yi halitta kamar halittarSa sa'an nan halittar ta yi kama da jũna a gare su?"
Kuma dõmin waɗanda ke jãyayya a cikin ãyõyinMu su sani (cẽwa) bã su da wata mafaka.
Ku yi ɗã'a ga Allah, kuma ku yi ɗã'a ga ManzonSa, da ma'abũta al'amari daga cikinku. Idan kun yi jãyayya a cikin wani abu, to ku mayar da shi zuwa ga Allah da ManzonSa idan kun kasance kunã ĩmãni da Allah da Rãnar Lãhira. wannan ne mafi alhẽri, kuma mafi kyau ga fassara.
Kuma suka ɓõye shi yanã abin sayarwa. Kuma Allah ne Masani ga abin da suke aikatãwa.
Suka ce: "Ã'a, mun zo maka sabõda abin da suka kasance sunã shakka a cikinsa."
Kai ne Majibincinmu, sabõda haka Ka taimake mu a kan mutãnen nan kãfirai."
Kuma in ka ji tsõron wata yaudara daga wasu mutãne, to, ka jẽfar da alkawarin, zuwa gare su, a kan daidaita: Lalle ne Allah, bã Ya son mayaudara.
Lalle ne mutum, haƙĩƙa, mai yawan kãfirci ne, mai bayyanãwar kãfircin.
Kuma aka ɗauki ƙasa da duwãtsu, kuma aka niƙa su niƙãwa ɗaya.
Fir'auna ya ce: "Ashe, kun yi ĩmãni da shi a gabãnin inyi izni a gare ku?
Lalle ne, wannan wata tunãtarwa ce, saboda wanda ya so ya riƙa hanyar kirki zuwa ga Ubangijinsa.
Lalle ne, a cikin wancan akwai ãyã, kuma mafi yawansu, bã su kasance mũminai ba.
Ka ce: "Yã Ubangijina! Ko dai Ka nũna mini abin da ake yi musu wa'adi da shi."
Dã sunã sãmun mafaka kõ kuwa waɗansu ɓulõli, kõ kuwa wani mashigi, da sun, jũya zuwa gare shi, kuma suna gaggawar shiga.
Suka ce: "Allah, Wanda ke sanya kõwane abu ya yi furuci, Shĩ ne Ya sanya mu mu yi furuci, kuma Shĩ ne Ya halitta ku can da farko, kuma zuwa gare Shi ake mayar da ku."
Sa'an nan Mu rarrabe a tsakãninsu, kuma abũbuwan shirkinsu su ce: "Bã mũ kuka kasance kunã bauta wa ba."
A kan karagu, sunã mãsu fuskantar jũna.
Kada maganarsu ta sanya ka a cikin baƙin ciki.
Lalle ne, a cikin wancan akwai ãyã, kuma mafi yawansu ba su kasance mũminai ba.
Kuma llale nĩ a gare shi, haƙĩƙa, mai ƙarfi ne amintacce."
Kada ku riƙi rantsuwõyinku dõmin yaudara a tsakãninku, har ƙafa ta yi sulɓi a bãyan tabbatarta, kuma ku ɗanɗani azãba sabõda abin da kuka kange daga hanyar Allah.
Kai kuma kã shagala ga barinsa!
Kace: "To, wãne ne ke mallakar wani abu daga Allah sabõda kũ, idan Yã yi nufin wata cũta agare ku kõ kuma (idan) Ya yi nufin wani amfãni a gare ku?
Kuma idan ka bijira daga gare su, to, bã zã su cuce ka da kõme ba, kuma idan ka yi hukunci, to, sai ka hukunta a tsakãninsu da ãdalci.
Kuma Allah Mabuwãyi ne, Mai hikima.
To, ku ɗanɗana, sabõda haka bãbu wani mataimaki, ga azzãlumai.
Ka ce: "Ku yi jira! Lalle nĩ tãre da ku, inã daga mãsu jira."
Kuma lalle haƙĩƙa, Mun bai wa Mũsã Littafi, sabõda haka kada ka kasance a cikin shakka daga haɗuwa da shi.
Watau mazõwa dãma.
To, waɗannan da suka yi ĩmãni daga cikinku, kuma suka ciyar, sunã da wani sakamako mai girma.
Kuma akwai daga ãyõyinSa halittar sammai da ƙasã da sãɓã, war harsunanku, da launukanku.
Bãbu hukunci fãce na Allah. Ya yi umurnin kada ku bauta wa kõwa fãce Shi.
Kamar wannan ne, Muke sãkãwa ga mutãne mãsu laifi.
(Su ce musu) "Me ya shigar da ku a cikin Saƙar?"
Mun yi shaida!" (ya ce): "Kada ku ce a Rãnar Kiyãma: Lalle ne mũ, daga wannan, gafalallu ne."
To matuƙar sun tsaya sõsai gare ku, sai ku tsayu sõsai gare su. Lalle ne Allah Yanã son mãsu taƙawa.
Ka ce: "Allah ne shaida a tsakãnina da tsakaninku.
Kuma Allah Yana keɓance da wanda Yake so da rahamarSa.
Kuma ku bi Allah da taƙawa, wanda yake zuwa gare Shi ne ake tãra ku.
Kuma daga gare su akwai wanda yake cẽwa: "Yã Ubangijinmu! Ka bã mu mai kyau a cikin dũniya da mai kyau a cikin Lãhira, kuma Ka tsare mana azãbar Wuta!"
Ka ce: "To, yãya ake sihirce ku?"
Ya yi kyauta kaɗan, kuma ya yi rowa?
Sai Allah Ya saukar da natsuwarSa a kansa, kuma Ya taimake shi da waɗansu rundunõni, ba ku gan su ba, kuma Ya sanya kalmar waɗanda suka kãfirta maƙasƙanciya, kuma kalmar Allah ita ce maɗaukakiya.
Kuma idan an jũyar da gannansu wajen abõkan wuta, su ce: "Yã Ubangijinmu!
Kuma bã ni tsõron abin da kuke yin shirki da shi, fãce idan Ubangijina Yã so wani abu.
Waɗannan sũ ne fãsiƙai.
To, me ya sanar da kai cẽwa watakila shi ne zai tsarkaka.
Kamar wannan ne Allah Yake bayyana muku ãyoyinsa, tsammãninku kunã gõdewa.
KumaAllah ga abin da kuke aikatãwa Masani ne.
Lalle ne muna ƙõne shi, sa'an nan kuma munã shẽƙe shi, a cikin tẽku, shẽƙẽwa."
Kuma bãbu wani abu fãce yanã tasbĩhi game da gõde Masa, kuma amma ba ku fahimtar tasbĩhinsu.
Lalle kai bã zã ka hũda ƙasa ba kuma bã zã ka kai a duwãtsu ba ga tsawo.
Sai suka ƙaiyatã shi, sabõda haka, azãbar rãnar girgije ta kãma su.
Shin akwai wani abin bautawa tãre da Allah?
Lalle ne Shĩ abin gõdewa ne, Mai girma."
Ku dũba zuwa 'ya'yan itãcensa, idan ya yi 'ya'yan, da nunarsa.
Suna gũrin ku kãfirta kamar yadda suka kãfirta, dõmin ku kasance daidai.
To, idan ba ku aikata ba, kuma Allah Ya kõmo da ku zuwa ga sauƙi, sai ku tsai da salla, kuma ku bãyar da zakka, kuma ku yi ɗã'ã ga Allah da ManzonSa.
Lalle mũ, mun ji wani littãfi an saukar da shi a bãyãn Mũsã, mai gaskatãwa ga abin da ke a gaba da shi, yanã shiryarwa ga gaskiya da kuma zuwa ga hanya madaidaiciya.
Lalle waɗanda ke a gabãninsu, sun faɗe ta, sabõda haka abin da suka kasance sunã aikatãwa bai wadãtar da su da kõme ba.
Kuma idan aka ce musu: "Ku zo zuwa ga abin da Allah Ya saukar, kuma zuwa ga Manzo," sai su ce: "Mai isarmu shi ne abin da muka iske ubanninmu a kansa."
Wannan yã fi kusantar da sanyaya idãnunsu, kuma bã zã su yi baƙin ciki ba, kuma su yarda da abin da ka bã su, sũ duka.
Lalle shi, ya kasance mai yawan gaskatãwa, Annabi.
Sai ku kõma, shi ne mafi tsarkaka a gare ku.
Yã kai Annabi! Ka bi Allah da taƙawa, kuma kada ka yi ɗã'ã ga kãfirai da munãfukai.
Kuma Allah bai sanya shi ba, fãce dõmin bushãra a gare ku, kuma dõmin zukãtanku su natsu da shi. Taimako bai kasance ba fãce daga wurin Allah, Mabuwãyi, Mai hikima.
Kuma idan cũta ta shãfi mutãne, sai su kirãyi Ubangijinsu, sunã mãsu mai da al'amari gare Shi, sa'an nan idan Ya ɗanɗana musu wata rahama daga gare Shi, sai gã wani ɓangare daga gare su sunã shirki da Ubangijinsu.
Ã'a, su dai sunã cikin shakka daga hukunciNa Ã'a, ba su i da ɗanɗanar azãba ba.
"Ko kuma (kada) ya ce: 'Da Allah Ya shiryar da ni, dã na kasance daga mãsu taƙawa.'"
Annabi ne mafi cancanta ga mũminai bisa ga su kansu, kuma mãtansa uwãyensu ne.
"Tabbas, waɗanda ake tãrãwa ne a cikin wani yini sananne."
Ya ce: "An bã ni shi a kan wani ilmi wanda yake gare ni ne kawai."
Ka yi musu rahama, kamar yadda suka yi rẽnõna, ina ƙarami."
Sai ka bã ni wani mataimaki daga wajenKa."
Wancan daga ãyõyin Allah ne, tsammãninsu sunã tunãwa!
Da zuwa ga duwãtsu yadda aka kafa su?
Kuma shi ne Mabuwãyi, Mai hikima.
Ba ku zama kamar kõwa ba daga mãtã, idan kun yi taƙawa, sabõda haka, kada ku sassautar da magana, har wanda ke da cũta a cikin zuciyarsa ya yi ɗammani, kuma ku faɗi magana ta alheri.
A cikin zukãtansu akwai wata cũta. Sai Allah Ya ƙãramusu wata cũta, kuma suna da azãba mai raɗaɗi sabõda ãbin da suka kasance suna yi na ƙarya.
Ya ce: "Akwai tsammãnin Ubangijinku, Ya halaka maƙiyanku, kuma Ya sanya ku, ku maye a cikin ƙasa, sa'an nan Ya dũba yadda kuke aikatãwa."
Kuma don me a lõkacin da kuka ji shi, ba ku ce ba, "Bã ya yiwuwa a gare mu, mu yi magana a game da wannan.
To, ku yi dãko. Lalle ne mũ, tãre da ku mãsu dãkon ne."
Kuma sai ya shiga garin a lõkacin da mutãnen garin suka shagala, sai ya sãmu, a cikin garin, waɗansu maza biyu sunã faɗa, wannan daga ƙungiyarsa, kuma ɗayan daga maƙiyansa, sai wannann da yake daga ƙungiyarsa ya nẽmi ãgajinsa, sai Mũsã ya yi masa ƙulli, ya kashe shi.
Sabõda haka Yã karɓi tũbarku, kuma Yã yãfe muku.
Kõ kuna nufin ku tambayi Manzonku, kamar yadda aka tambayi Mũsã a gabãnin haka?
Kuma waccan ita ce hujjarMu, Mun bayãr da ita ga Ibrãhĩma a kan mutãnensa.
To, yãya ake karkatar da ku?
"Shin, kunã bauta wa Ba'al ne, kuma kunã barin Mafi kyautatãwar mãsu halitta?"
Wancan yã kasance a cikin Littafi, rubũtacce.
Kuma rãyayyu bã su daidaita kuma matattu ba su daidaita.
"Wanda Ya saukar da mu a gidan zamã, daga falalarSa, wata wahala bã ta shãfar mu a cikinsa, kuma wata kãsãwa bã ta shãfar mu a cikinsa."
A cikin Aljanna maɗaukakiya.
Kuma Allah Yanã sanin abin da kuke nũnãwa, da abin dakuke ɓãyẽwa.
Saboda haka, bã shi da wani ƙarfi, kuma bã shi da wani mai taimako (da zai iya kãre shi daga azãbar Allah).
Lalle ne a cikin wancan akwai alãma a gare ku (ta naɗin ¦ãlũta daga Allah ne) idan kun kasance mãsu ĩmãni."
To, a lõkacin da ya gan shi matabbaci a wurinsa, ya ce: "Wannan daga falalar Ubangijĩna yake, dõmin Ya jarraba ni: Shin, zan gõde ne, kõ kuwa zan butulce! Kuma wanda ya gõde, to, yanã gõdẽwa ne dõmin kansa, kuma wanda ya kãfirta, to, lalle Ubangijina Wadãtacce ne, Karĩmi."
Sũ zuwa ga kãfirci a rãnar nan, sun fi kusa daga gare su zuwa ga ĩmãni. Sunã cẽwa da bãkunansu abin da bã shi ne a cikin zukãtansu ba.
"Abin da dai kuke bautãwa, baiein Allah, gumaka ne, kuma kun ƙirƙira ƙarya.
Sai ta je wa mutãnenta tanã auke da shi.
Lalle Shĩ Mai ji ne, Makusanci."
Kuma Allah ga abin da kuke aikatawa Masani ne.
Wata gãnãwa ta mutum uku bã zã ta kasance ba fãce Allah Shĩ ne na huɗu ɗinta, kuma bãbu ta mutum biyar fãce Shĩ ne na shida ɗinta, kuma babu abin da ya kãsa wannan kuma babu abin da yake mafi yawa fãce Shĩ Yanã tãre da su duk inda suka kasance, sa'an nan Ya bã su lãbãri game da abin da suka aikata a Rãnar ¡iyãma.
Gõdiya ta tabbata ga Allah Ubangijin halittu.
Daga Fir'auna.
Lalle ne nĩ manzon Allah nezuwa gare ku, gabã ɗaya.
Ya ce: "Kamar wancan ne ãyõyinMu suka jẽ maka sai ka mance su, kuma kamar hakar a yau ake mance ka."
Hanyar Allah wadda ta shũɗe daga gabãnin wannan, kuma bã zã ka sãmi musanya ba ga hanyar Allah (ta taimakon mũminai akan mai zãluntarsu).
Dõmin kada ku yi baƙin ciki a kan abin da ya kuɓuce muku, kuma kada ku yi mumar alfahari da abin da Ya bã ku.
To, a lõkacin da suka karkace, Allah Ya karkatar da zukãtansu. Kuma Allah bã Ya shiryar da mutãne fasiƙai.
Kuma a lõkacin da Ubangijinku Ya sanar, "Lalle ne idan kun gõde, haƙĩƙa, Inã ƙãramuku, kuma lalle ne idan kun kãfirta haƙĩƙa azãbãta, tabbas, mai tsanani ce."
"Kuma wani cẽto bã ya amfãni a wurinSa face fa ga wanda Ya yi izni a gare shi.
Shin fa, wanin Allah nake nẽma ya zama mai hukunci, alhãli kuwa Shĩ ne wanda Ya saukar muku da Littãfi abin rabẽwadaki-daki?
Kuma Yã isa zama Mai ƙididdigewa ga laifuffukan bãyinSa.
Kuma ba ka kasance kanã fãtan a jẽfa Littafin nan zuwa gare ka ba, fãce dai dõmin rahama daga Ubangijinka.
"Kada ku yi ĩmãni fãce da wanda ya bi addininku."
Sauti & Bidiyo
Shin lalle ne ku, haƙĩƙa, kunã shaidar cẽwa, lalle ne tãre da Allah akwai wasu abũbuwan bautawa?"
Dõmin Allah Ya sãka musu da mafi kyaun abin da suka aikata, kuma Ya ƙãra musu daga falalarsa. Kuma Allah Yanã azurta wanda Yake so, bã da lissafi ba.
To, zuwa ga Allah kawai al'amura ke kõmãwa.
Kuma Mu, Muna ganin ta a kusa.
To, mẽne ne ya sãme ku a cikin munãfukai kun zama ƙungiya biyu, alhãli kuwa Allah ne Ya mayar da su sabõda abin da suka tsirfanta?
"Kuma idan kun yi damƙa, sai ku yi damƙar kunã mãsu tanƙwasãwa."
Kuma a lõkacin da Muka baiwa Mũsa Littãfi da rarrabẽwa, tsammãninku, kuna shiryuwa.
Kuma suna tambayar ka daga jirajiran wata.
Kuma a rãnar da Sa'a ke tsayuwa, a rãnar nan mutãne ke farraba.
Sa'an nan idan (wanda aka kashe) ya kasance daga wasu mutãne maƙiya a gare ku, kuma shi mũminine, sai ya 'yanta wuya mũmina. Kuma idan ya kasance daga wasu mutãne ne (waɗanda) a tsakãninku da tsakãninsu akwai alkawari, sai ya bãyar da diyya ga mutãnensa, tare da 'yanta wuya mũmina.
To, lalle waɗanda suka yi zãlunci sunã da masaki (na ɗĩban zunubi) kamar masakin abõkansu, sabõda haka kada su yi Mini gaggãwa.
Aka ce (masa), "Ka shiga Aljanna."
Lalle Alla Ya ji maganar wadda ke yi maka jãyayya game da mijinta, tanã kai ƙãra ga Allah, kuma Allah nã jin muhawararku. Lalle Allah Mai ji ne, Mai gani.
Waɗancan anã ba su lãdarsu sau biyu, sabõda haƙurin da suka yi, kuma da kyautatãwa suna tunkuɗewar mũnanãwa kuma daga abin da Muka azũrtã susunã ciyarwa.
To, a lõkacin da ya je masa, ya gaya masa lãbãrinsa, ya ce: "Kada ka ji tsõro, kã tsĩra daga mutãne azzãlumai."
Ki yi ƙanƙan da kai ga Ubangijinki, kuma ki yi sujada, kuma ki yi rukũ'i tãre da mãsu rukũ'i."
Ka ce: "Ba ku yi ĩmãni ba, amma dai ku ce, 'Mun mĩƙawuya, ĩmani bai gama shiga a cikinzukãtanku ba. Kuma idan kun yi ɗã'a ga Allah da ManzonSa, to, bã zai rage muku kõme daga ayyukanku ba.
Kuma iyãyensa biyu kõwane ɗaya daga cikinsu yanã da ɗaya daga kashi shida ɗin abin da ya bari idan wani rẽshe ya kasance gare shi, to, idan rẽshe bai kasance gare shi ba, kuma iyãyensa ne (kawai) suka gãje shi, to, uwa tanã da sulusi (ɗaya daga cikin kashi uku).
Kuma Muka yi wahayi zuwa ga Mũsã cẽwa: "Ka jẽfa sandarka."
Launin bango
Kada ku zurfafã a cikin addininku. Kuma kada ku faɗa, ga Allah, fãce gaskiya.
Sabõda haka kada ku ji tsõronsu kuma ku ji tsõroNa.
Sa'an nan zã Ni rubũta ta ga waɗanda suke yin taƙawa, kuma sunã bãyar da zakka, da waɗanda suke, game da ãyõyinMu mũminai ne."
Kuma ba ya halatta a gare ku (maza) ku karɓe wani abu daga abin da kuka bã su, fãce fa idan su (ma'auran) na tsõron bã zã su tsayar da iyãkõkin Allah ba, Idan kun (danginsu) ji tsõron bã zã su tsayar da iyãkõkin Allah ba, to, bãbu laifi a kansu a cikin abin da ta yi fansa da shi.
Kuma a lõkcin da Muka jũya waɗansu jama'a na aljamiu zuwa gare ka sunã saurãren Alƙur'ãni. To, alõkacin da suka halarce shi suka ce: "Ku yi shiru."
Lalle mũ, manzannin Ubangijinka ne. Bã zã su iya sãduwa zuwa gare ka ba.
Yanã kiran wanda yake lalle cũtarwarsa ce mafi kusa daga amfãninsa! Lalle ne, tir da shi ya zama majiɓinci, kuma tir da ya zama abõkin zama!
Kuma wannan da ya kuɓuta daga cikinsu ya ce: a bãyan yã yi tunãni a lõkaci mai tsawo, "Nĩ, inã bã ku lãbãri game da fassararsa. Sai ku aike ni."
Kuma haƙĩƙa Mũ, Mãsu cika musu rabon su ne, bã tãre da nakasãwa ba.
Allah ne Yake shimfiɗa arziki ga wanda Yake so, kuma Yanã ƙuntatãwa.
Lalle ne, waɗanda suka yi ĩmãni da waɗanda sukatuba (Yahũdu) da Karkatattu da Nasãra, wanda ya yi ĩmãni da Allahda Rãnar Lãhira, kuma ya aikata aiki na ƙwarai, to, bãbu tsõro a kansu, kuma bã su zamo sunã baƙin ciki ba.
Ya ce: "Nĩ ne mafĩfĩci daga gare shi, Ka halitta ni daga wuta alhãli kuwa Kã halitta shi daga lãka."
Bã a rõƙon Allah sai da sunãyensa mãsu kyau, tis'in da taran nan, sai dai a dunƙule kamar a ce, "Inã rõƙon Allah da sunãyenSa da na sani da waɗanda ban sani ba." Lalle nĩ, na zãlunci kaina, kuma nã sallama al'amari tãre da Sulaiman ga Allah, Ubangijin halittu."
Ku bauta wa Allah; bã ku da wani abin bauta wa wanninSa.
Kuma da Mun so, da Mun juyar da halittarsu a kan halinsu, saboda haka ba zã su iya shuɗewa ba, kuma ba zã su komo ba.
Lalle ne, waɗanda suke biɗar ka izni waɗancan sũ ne suke yin ĩmãni da Allah da ManzonSa.
Kuma bã su da mãsu cẽto daga abũbuwan shirkinsu, kuma snn kasance mãsu kãfircẽwadaga abũbuwan shirkinsu.
Kuma Allah Yã kasance Mai gãfara, Mai Jin ƙai.
Waɗancan ne waɗanda Muke karɓa, daga gare su, mafi kyaun abin da suka aikata, kuma Muke gãfarta mafi mũnanan ayyukansum (sunã) a cikin 'yan Aljanna, a kan wa'adin gaskiya wanda suka kasance anã yi musu alkawari (da shi).
Ashe, kũ ne da ɗa namiji Shĩ (Allah) kuma da ɗiya mace?
"Addininku na garẽ ku, kuma addinina yanã gare ni."
Kuma Muka sanya girgije ya yi inuwa a kanku, kuma Muka saukar da darɓa da tantabaru a kanku; "Ku ci daga mãsu dãɗin abin da Muka azurta ku." kuma ba su zãlunce Mu ba, kuma amma kansu suka kasance suna zãlunta.
Ka ce: (Allah Ya ce): "Yã bãyĩNa waɗanda suka yi barna a kan rãyukansu! Kada ku yanke ƙauna daga rahamar Allah.
Sai (sakamakon) mũnãnan abin da suka aikata ya same su.
Ya ce: "Ya Ubangiji!
Kuma sunã tsõratar da kai ga waɗanda suke waninSa, kuma wanda Allah Ya ɓatar to, bã, shi da mai shiryarwa.
Tir da sũna na fãsicci a bãyãn ĩmãni.
Kuma bã Mu aikãwa da manzãnni fãce mãsu bayar da bushãra, kuma mãsu gargaɗi.
"Kuma yãya zã ka yi haƙuri a kan abin da ba ka kẽwayeda shi ba ga jarrabãwa?"
Kuma daga mutãne akwai mai bauta wa Allah a kan wani gefe.
Ka ce: "Ya Mutãnen Littãfi!
Lalle Allah na son mãsu daidaitãwa.
Lalle ne Allah a kan dukan kõme Mai ĩkon yi ne.
Kuma waɗanda suka yi tsirfar mũnanan ayyuka, sakamakon mummuna da kamarsa yake, kuma ƙasƙanci yanã rufe su. Bã su da wani matsari daga Allah, kamar an rufe fuskokinsu da guntãyen ƙirãruwa daga dare mai duhu.
Kuma lalle sunã ɗaukar kãyan nauyinsu da waɗansu nauyãyan kãya tãre da kãyan nauyinsu, kuma lalle zã a tambaye su a Rãnar ¡iyama game da abin da suka kasance sunã ƙirƙirãwa na ƙarya.
Kuma ku bi Allah da taƙawa Wanda kuke rõƙon jũna da (sũnan), shi, da kuma zumunta.
To, ko zã mu Sanya harãji sabõda kai, a kan ka sanya wani danni a tsakãninmu da tsakãninsu?"
Kuma waɗanda kuke tsõron bijirewarsu, to, ku yi musu gargaɗi, kuma ku ƙaurace musu a cikin wurãren kwanciya, kuma ku dõke su.
Kada ku kãwo wani uzuri a yau. Anã yi muku sakamakon abin da kuka kasance kunã aikatãwa kawai ne.
To amma waɗanda suka yi ĩmãni, kuma sũ, sunã yin bushãra (da ita).
To, a lõkacin da ya bã ta lãbãri da shi, ta ce: "Wãne ne ya gaya maka wannan?"
Kuma dã kã gani a lõkacin da azzãlumai suke abin tsayarwa wurin Ubangijinka, sashensu na mayar wa sãshe maganar maraunana (mabiya) suke cẽwa makangara (shũgabanni) "Ba dõminku ba, lalle, dã mun kasance mũminai."
To, ku kau da kai daga gare su don kõ sũ ƙarantã ne, kuma Jahannama ce matattararsu bisa ga sãkamakon abin da suka kasance sunã tsirfatãwa.
Sai ka bauta Mini, kuma ka tsayar da salla dõmin tuna Ni."
Ya ce: "Lalle akwai Lũɗu a cikinta!"
Kuma idan kun yi ɗã'a ga Allah da ManzonSa, to, bã zai rage muku kõme daga ayyukanku ba. Lalle Allah Mai gãfara ne, Mai jin ƙai."
Kuma Ya ɗaukaka daga abin da suke sifantãwa.
Ka ce: "Ba ni tambayar ku wata ijãra.
Sabõda haka, sai ka yi kira kuma kai ka daidaitu kamar yadda aka umurce ka, kuma kada ka bi son zũciyõyinsu, kumaka ce, "Nã yi ĩmãni da abin da Allah Ya saukar na littãfi, kuma an umurce ni da in yi ãdalci a tsakãninku. Allah ne Ubangijinmu, kuma Shĩ ne Ubangijinku, ayyukanmu nã gare mu, kuma ayyukanku nã gare ku, kuma bãbu wata hujja a tsakãninmu da tsakãninku.
Kuma wa'adin nan tabbatacce ya kusanto, sai gã ta idãnun waɗanda suka kãfirta sunã bayyanannu, (sunã cẽwa), "Yã kaitonmu!
Kuma a rãnar da sama take tsattsãgewa tãre da gizãgizai, kuma a saukar da malã'iku, saukarwa.
An halitta mutum daga gaggãwa, zan nũna muku ãyõyiNa.
Kuma kada ku yãƙe su a wurin Masallãci Tsararre (Hurumin Makka) fãce fa idan sun yãƙe ku a cikinsa.
Lal1e ne shi, yã kasance (a dũniya) cikin iyãlinsa yanã mai raha.
Lalle ne, haƙĩƙa, kã zo da wani babban abu!"
Kuma Muka ƙẽtarar da Banĩ Isra'ila ga tẽku, sai suka jẽ a kan wasu mutãne waɗanda sunã lizimta da ibãda a kan wasu gumãka, nãsu suka ce: "Yã Mũsã!
Kuma lalle, ne haƙĩƙa, kun san halittar farko, to, don me ba zã ku yi tunãni ba?
Lalle ne kashe su yã kasance kuskure babba.
Kuma dã an shige ta (Madĩna) a kansu, daga sasanninta, sa'an nan aka tambaye su fitina (kãfirci), lalle dã sun jẽ mata, kuma dã ba su zauna a cikinta (Madĩna) ba fãce kaɗan.
Misãlin waɗanda suka riƙi waɗansu masõya waɗanda bã Allah ba, kamar misãlin gizõgizo ne wanda ya riƙi wani ɗan gida, alhãli kuwa lalle mafi raunin gidãje, shĩ ne gidan gizogizo, dã sun kasance sunã sane.
Munã ɗaukaka darajõji ga wanda Muka so, kuma a saman kõwane ma'abũcin ilmi akwai wani masani.
Rahamar Allah da albarkarSa su tabbata a kanku, ya mutãnen babban gida! Lalle ne Shĩ abin gõdewa ne, Mai girma."
Dõmin haka kawai Muka sauƙaƙar da shi (Alƙur'ãni) da harshenka, tsammãninsu, su riƙa tunãwa.
Shin ɗayanku nã son cẽwa wani lambu ya kasance a gare shi daga dabĩnai da inabõbi' marẽmari suna gudãna daga ƙarƙashinsa, yana da, a cikinsa daga kõwane 'ya'yan itãce, kuma tsũfa ya sãme shi, alhãli kuwa yana da zũriyya masu rauni sai gũguwa wadda take a cikinta akwai wuta, ta sãme shi, har ta ƙõne?
Alhãli kuwa sũ, ga ambatar Mai rahama, mãsu kãfirta ne.
Wancan umurnin Allah ne, Ya saukar da shi zuwa gare ku.
Zã ni gaya maka fassarar abin da ba ka iya yin haƙuri ba a kansa."
Shin, kun nẽmi gaggawar umurnin Ubangijinku ne?"
Kuma ku sani cewa Allah Mai gãfara ne, Mai haƙuri.
Kuma bãbu wani dalĩli a gare ni a kanku fãce na kirã ku, sa'an nan kun karɓã mini.
Wata al'umma bã ta gabãtar ajalinta, kuma bã zã su jinkirta ba.
Suka ce: "Yã Shu'aibu! Bã mu fahimta da yawa daga abin da kake faɗi, kuma munã ganin ka mai rauni a cikinmu.
Lalle ne abin da suka aikata mãkircin masihirci ne kuma masihirci bã ya cin nasara a duk inda ya je."
Ku yi tsẽre zuwa ga (nẽman) gãfara daga Ubangjinku, da Aljanna fãɗinta kamar fãɗin samã da ƙasã ne, an yi tattalinta dõmin waɗanda suka yi ĩmãni da Allah da ManzanninSa.
Lalle ne Kai, Kai ne Mai ji, Masani."
Shin akwai wani abin bautãwa tãre da Allah.
"Kuma bã ni tambayar wata ijãra a kansa.
Mẽne ne mazõwa dãma?
Kuma da waɗansu alãmõmi, kuma da taurãri sunã mãsu nẽman shiryuwa (ga tafiyarsu ta fatauci).
Lalle ne haƙĩƙa Yã lissafe su, kuma ya ƙidãye su, ƙidãya.
Kuma aka niƙe duwãtsu, niƙẽwa.
Lalle ne Ubangijinku Allah ne, wanda Ya halitta sammai da ƙasa a cikin kwãnaki shida, sa'an nan kuma Ya daidaita a kan Al'arshi, Yanã sanya dare ya rufa yini, yanã nẽman sa da gaggawa, kuma rãnã da watã da taurãri hõrarru ne da umurninSa.
Sa'an nan kuma ka duba yadda ake karkatar da su.
Kuma waɗansu majiɓinta ba su kasance ba a gare su, waɗanda ke iya taimakonsu, baicin Allah.
Sabõda haka Muka hõre masa iska tanã gudu da umurninsa, tãna tãshi da sauƙi, inda ya nufa.
Da wani daga siffarsa nau'i-nau'i.
Haƙĩƙa, Manzo yã je muku da gaskiya daga Ubangijinku. Sabõda haka ku yi ĩmãni yã fi zama alhẽri a gare ku.
Allah bã Ya kãmã ku sabõda yãsassa a cikin rantsuwõyinku, kuma amma Yanã kãmã ku da abin da kuka ƙudurta rantsuwõyi (a kansa).
Waɗanda ke a gabãninsu, sun ƙaryata, sai azãba ta jẽ musu daga inda ba su sani ba.
Lalle sunã cẽwa, "Allah ne." Ka ce: "Gõdiya tã tabbata ga Allah."
Ko sunã zaton lalle Mũ, bã Mu jin asĩrinsu da gãnãwarsu?
To, amma waɗanda suka yi shaƙãwa, to, sunã a cikin wuta. Sunã mãsu ƙãra da shẽka acikinta.
Ka ce: "Ku kãwo hujjarku, wannan shi ne ambaton wanda yake tãre da ni, kuma shi ne ambaton wanda yake a gabãnĩna.
Shin, (kunã so) in gaya muku a kan wanda Shaiɗãnnu kan sauka?
Kuma rãnã tanã gudãna zuwa ga wani matabbaci nãta.
Bãbu hukunci fãce daga Allah, a gare Shi na dõgara, kuma a gare Shi mãsu dõgara sai su dõgara."
Kuma Fir'auna ya ɓatar da mutãnensa, kuma bai shiryar (dasu) ba.
Ko da yaushe Zakariyya ya shiga masallãci, a gare ta, sai ya sãmi abinci a wurinta.
Kuma Allah Yanã tsare ka daga mutãne.
Ko kuna cẽwa: Lalle ne, Ibrãhĩm da Ismã'ĩla da Is'hãƙa da Ya'aƙũbu da Jĩkõki, sun kasance Yahũdãwa kõ kuwa Nasãra?
Kuma Muka yi wahayi zuwa ga Mũsã da ɗan'uwansa, cẽwa: Kũ biyu, ku zaunar da mutãnenku a Masar a cikin wasu gidãje. Kuma ku sanya gidãjenku su fuskanci Alƙibla, kuma ku tsayar da salla.
"Dukiyãta ba ta wadatar da ni ba!"
Haƙĩƙa wani dalĩli daga Ubangijinku yã je muku kuma Mun saukar da wani haske, bayyananne zuwa gare ku.
An yi izni ga waɗanda ake yãƙar su da cẽwa lalle an zãlunce su, kuma lalle ne Allah, haƙĩƙa, Mai ĩkon yi ne a kan taimakonsu.
Sabõda haka, lalle sun ƙaryata (Manzo) game da gaskiya, a lõkacin da ta jẽ musu, to lãbãrun abin da suka kasance sunã izgili da shi, zã su jẽ musu.
Kuma Mun yi wasiyya ga mutum game da mahaifansa biyu da kyautatãwa, uwarsa tã yi cikinsa wahala, kuma ta haife shi wahala. cikinsa da yãyensa watã talãtin. Har a lõkacin da ya kai ga mafi ƙarfinsa, kuma ya kai shẽkara arba'in, ya ce: "Ya Ubangijĩna!
Kuma za Mu sauƙaƙe maka (al'amari) zuwa ga (Shari'a) mai sauƙi.
Kuma waɗannan da ba su sãmi aure ba su kãme kansu har Allah Ya wadãtar da su daga, falalarsa.
Shin fa, wanda ke kãre mũguwar azãba da fuskarsa (yanã zama kamar waninsa) a Rãnar ƙiyãma?
Kuma Shĩ ne ke sassaukar da girgije (ruwa) a bãyan sun yanke ƙauna kuma Yana wãtsa rahamarSa, alhãli kuwa Shĩ ne Majiɓinci, Mai gõdiya.
Kuma idan Jahĩm aka hũra ta
Allah Yã la'ance su! Yãya aka karkatar da su?
Lalle ne, haƙĩƙa kin zo da wani abu mai girma!
Dã Allah zai tambaye ku su (dũkiyõyin) har Ya wajabta muku bãyarwa, zã ku yi rõwa kuma Ya fitar da miyãgun ƙulle-ƙullenku.
Sabõda haka, don me ne wata jama'a daga kowane ɓangare daga gare su ba ta fita (zuwa nẽman ilimi ba) dõmin su nẽmi ilimi ga fahimtar addĩni kuma dõmin su yi gargaɗi ga mutãnensu idan sun kõma zuwa gare su, tsammãninsu, sunã yin sauna?
Ka dũba yadda Muke sarrafaãyõyi, Sa'an nan kuma sũ, sunã finjirẽwa.
Allah yã yi wa'adi ga munãfukai maza da munãfukai mãtã da kãfirai da wutar Jahannama, sunã madawwama a cikinta.
Lalle ne haƙĩƙa Mun aika zuwa ga al'ummomi daga gabãninka, sai Shaiɗan ya ƙawãce musu ayyukansu, sabõda haka shĩ ne majiɓincinsu, a yau, kuma sunã da azãba mai raɗaɗi.
"Waɗanda suke yin ɓarna a cikin ƙasa, kuma bã su kyautatãwa."
Kamar wannan ne Muke rufẽwa a kan zukãtan mãsu ta'addi.
Rãnar da suke bayyanannu, bãbu wani abu daga gare su wanda yake iya bõyuwa ga Allah.
Saukarwa ce daga Mai hikima, Gõdadde.
Suka ce: "Yã kai Azĩzu!
Shin, ana saka musu, fãce da abin da suka kasance suna aikatãwa?
Kuma albarkar wanda ke da mulkin sammai da ƙasã abin da ke a tsakãninsu tã bayyana, kuma a wurinSa ne ilmin Sa'a yake, kuma zuwa gare Shi ake mayar da ku.
Sai wanda Ubangijinka Ya yi wa rahama, kuma dõmin wannan ne Ya halicce su.
To, misãlinsa kamar misãlin kare ne, idan ka yi ɗauki a kansa ya yi lallage, kõ kuwa ka bar shi sai ya yi lallage, wannan ne misãlin mutãne waɗanda suka ƙaryata game da ãyõyinMu: Ka jẽranta karãtun lãbãrun; tsammãninsu sunã tunãni.
Kuma suna tambayar ka game da marãyu.
Waɗancan ne waɗanda Muka bai wa Littãfi da hukunci da Annabci.
Y. S̃.
Ga ku, ya ku waɗannan! Anã kiran ku dõmin ku ciyar ga tafarkin Allah, sa'an nan daga cikinku akwai mai yin rõwa.
Bã ya kasancẽwa ga mutãnen Madĩna da wanda yake a gẽfensu, daga ƙauyãwã, su sãba daga bin Manzon Allah, kuma kada su yi gudu da rãyukansu daga ransa.
Kuma ku bai wa marãyu dũkiyõyinsu, kuma kada ku musanya mummuna da mai kyau. Kuma kada ku ci dũkiyõyinsu zuwa ga dũkiyõyinku.
Kuma lalle ne, idan ka tambaye, su haƙĩƙa, sunã cẽwa, "Abin sani kawai, mun kasance munã hĩra kuma munã wãsã.
Kuma ku yi jiran dãko, lalle ni mai dãko ne tãre da ku."
Ku kasance mãsu tsayuwa da ãdalci, mãsu shaida sabõda Allah, kuma kõ dã a kanku ne kõ kuwa, mahaifa da mafi kusantar zumunta, ko (wanda ake yi wa shaida kõ a kansa) ya kasance mawadãci kõ matalauci, to, Allah ne Mafi cancanta da al'amarinsu. Sabõda haka, kada ku bĩbiyi son zũciya, har ku karkata.
Mãsu farin idãnu da baƙinsu waɗanda aka tsare a cikin haimõmi.
Kuma ba Mu shiryar da shi ga hanyõyi biyu ba?
Kuma Allah Ya kasance Mai ƙarfi, Mabuwãyi.
Abin sani kawai, waɗanda bã sa ĩmãni da Allah, da Rãnar Lãhira, kuma zukãtansu suka yi shakka, sũ ne ke nẽman izininka, sa'an nan a cikin shakkarsu sunã ta yin kai kãwo.
Kuma suka ce: "Shin, gumãkanmu ne mafĩfĩta kõ shi (¦an Maryama)?"
Shin fa, ba ku yin tunãni?"
Kuma wanda ya kashe mũmini bisa ga kuskure, sai ya 'yanta wuya mũmina tare da mĩƙa diyya ga mutãnensa, ãce idan sun bari sadaka.
Shin, to, kunã jẽ wa sihiri, ahãli kuwa kũ, kunã fahimta?"
Kamar wannan ne Allah Yake bayyana muku ãyoyinsa, tsammãninku kunã gõdewa.
Ina rantsuwa da sama ma'abũciyar ruwa mai kõmãwa yana yankẽwa.
To, a lõkacin da, suka gan shi, suka girmamã shi, kuma suka yanyanke hannãyensu, kuma suka ce: "Tsarki yanã ga Allah!
Shin, kuma ba su gani ba cẽwa lalle ne, Muna jẽ wa ƙasar (su), Munã rage ta daga gẽfunanta? Kuma Allah ne Yake yin hukuncinsa.
Kuma Nũhu ya ce: "Ya Ublngijina! Kada Ka bari, a kan ƙasa, daga cikin kãfirai, wanda ke zama a cikin gida."
Ã'a, alhẽri ne gare ku. Kõwane mutum daga gare su na da sakamakon abin da ya sanã'anta na zunubi, kuma wanda ya jiɓinci girmansa, daga gare su, yanã da azãba mai girma.
Ka ce: "Akwai fatan sãshen abin da kuke, nẽman gaggãwarsa, ya kasance yã kuturta a gare ku."
Kuma lalle ne, haƙĩƙa, Mun bai (wa Bãnĩ Isrã'ĩla Littãfi da hukunci da Annabci, Kuma Mun azurta su daga abũbuwa mãsudãɗi, Kuma Mun fĩfta su a kan mutãnen dũniya (a zãmaninsu).
Kuma lalle ne, Mũ idan Mun ɗanɗana wa mutum wata rahama daga gare Mu, sai ya yi farin ciki da ita, kuma idan wata masĩfa ta sãme su sabõda abin da hannayensu suka gabãtar, to, lalle ne mutum mai tsananin kãfirci ne.
Wancan shĩ ne fassarar abin da ba ka iya yin haƙuri ba a kansa."
Ashe bãbu mazauni a cikin Jahannama ga mãsu girman kai?
Ã'a, (malã'iku) bãyi ne mãsu daraja.
Kuma dã dai lalle sũ a lõkacin da suka zãlunci kansu, sun zo maka sa'an nan suka nẽmi gãfarar Allah kuma Manzo ya nẽma musu gãfara, haƙĩƙa, dã sun sãmi Allah Mai karɓar tũba Mai jin ƙai.
Ya ce: "Ga waɗannan, 'ya'yãna idan kun kasance mãsu aikatãwa ne."
Kuma lalle ne, daga gare su akwai wata ƙungiya suna karkatar da harsunansu da Littãfi dõmin ku yi zaton sa daga Littãfin, alhãli kuwa bã shi daga Littãfin.
Gõdiya ta tabbata ga Allah.
Kuma kada ka yi jãyayya dõmin tunkuɗe wa waɗanda suka yaudari kansu.
Ba Mu halitta su ba fãce da manufa ta gaskiya, kuma amma mafi yawansu, ba su sani ba.
Kuma sunã cewa, "Yaushe ne wannan alkawarin zai tabbata in dai kun kasance mãsu gaskiya ne kũ?"
Kuma idan cũta ta shãfe ku, a cikin tẽku, sai wanda kuke kira ya ɓace fãce Shi.
Kuma ba Mu sanya Alƙibla wadda ka kasance a kanta ba, fãce dõmin Mu san wanda yake biyar Manzo daga wanda yake jũyãwa a kan duga-dugansa.
Allah Ya la'ani'yan sa'ĩr!
Kuma Allah yã fĩfĩta mãsu jihãdi a kan mãsu zama da lãda mai girma.
Shin to, bã ku hankalta?"
Kuma da gaskiya Muka saukar da shi, kuma da gaskiya ya sauka.
Shin, ba ka gani ba, zuwa ga waɗanda aka bai wa rabo daga Littafi, suna sayen ɓata, kuma suna nẽman ku ɓace daga hanya?
Da mãsu sauka daga sama da umurnin Allah kamar suna iyo.
Ka ce: "Na wãne ne abin da yake a cikin sammai da ƙasa?"
Kuma bã zã su sãmar wa kansu wani majiɓinci ba, banda Allah, kuma bã zã su sãmar wa kansu wani mataimaki ba.
Fir'auna ya ce: "Ashe, kun yi ĩmãni da shi a gabãnin inyi izni a gare ku?
Kuma idan sun ga kõwace ãyã bã zã su yi ĩmãni da ita ba har idan sunjẽ maka sunã jãyayya da kai, waɗanda suka kãfirta sunã cẽwa: "Wannan bai zama ba fãce tãtsũniyõyin mutãnen farko."
Ko kun amince ga Ya mayar da ku a cikin tẽkun a wani lõkaci na dabam, sa'an na Ya aika wata gũguwa mai karya abũbuwa daga iska, har ya nutsar da ku sabõda abin da kuka yi na kãfirci?
To, idan Allah Ya mayar da kai zuwa ga wata ƙungiyã daga gare su sa'an nan suka nẽme ka izni dõmin su fita, to, ka ce: "Bã zã ku fita tãre da nĩ ba har abada, kuma bã zã ku yi yãƙi tãre da nĩ ba a kan wani maƙiyi.
Ã'a, mafi yawansu ba su sanĩ ba.
"Ban zama mai kõre mũminai ba."
Kuma kada ku manta da falala a tsakãninku.
Wannan ne Allah, Ubangijinku, sai ku bauta Masa.
Kuma an umurce mu, mu sallama wa Ubangijin tãlikai."
Kuma idan kun tũba to kuna da asalin dũkiyõyinku, bã ku zãlunta, kuma bã a zãluntar ku.
Yanã bãyar da 'ya'ya mãtã ga wanda yake so, kuma Yanã bãyar da ɗiya maza ga wanda Yake so.
Ba su da wani ilmi game da wannan magana, kuma iyãyensu bã su da shi, abin da ke fita daga bãkunansu ya girma ga ya zama kalmar faɗa!
Kuma daga cikin ku akwai wanda ke mutuwa, kuma daga gare ku akwai wanda ake mayarwa zuwa ga mafi ƙasƙancin rãyuwa dõmin kada ya san kõme a bãyan ya sani.
Watan Ramalãna ne wanda aka saukar da Alƙur'ãni a cikinsa yana shiriya ga mutãne da hujjõji bayyanannu daga shiriya da rarrabẽwa.
(Ku yi mãmãki) Ga matalauta mãsu hijira waɗanda aka fitar daga gidãjẽnsu da dũkiyõyinsu, sunã nẽman falala daga Allah da kuma yarda, kuma sunã taimakon Allah da ManzonSa!
Lalle mutãnena sun riƙi wannan Alƙur'ãni abin ƙauracẽwa!"
Allah ne Ya sanya muku kasã tabbatacciya, da sama ginanniya, kuma Ya sũranta ku, sa'an nan Ya kyautata sũrõrinku,, kuma Ya azurta ku daga abũbuwa mãsu dãɗi. Wancan Shĩne Allah Ubangijinku.
Wanin Allah, sabõda haka ku shiryar da su zuwa ga hanyar Jahĩm.
Kuma kamar wannan ne, Muka fitini sãshensu da sãshe, dõmin su ce: "Shin waɗannan ne Allah Ya yi falala a kansu daga tsakãninmu?"
Sai ya bayyana a gare ta da siffar mutum madaidaci.
Kwanuka ƙidãyayyu.
Ka sauka da aminci da, a gare Mu da albarka a kanka, kuma rahama ta tabbata a kan waɗansu al'ummõmi daga waɗanda suke tãre da kai.
Suka ce: "Bãbu wata cũta!
Rãnar da mutum zai yi tunãnin abin da ya aikata.
Kuma yã kasance yanã umurnin mutãnens da salla da zakka.
Sun saya da ãyõyin Allah, 'yan kuɗi kaɗan, sa'an nan suka kange daga hanyar Allah.
Kuma suna hana taimako.
