Kõ sunã cẽwa, "Yã ƙirƙira shi?"
Sunã jãyayya da kai a cikin (sha'anin) gaskiya a bãyan tã bayYanã, kamar dai lalle anã kõra su zuwa ga mutuwa ne alhãli kuwa sunã kallo.
(Yãron) ya ce: "Ya, Bãbãna! Ka aikata abin da aka umurce ka, zã ka sãme ni, in Allah Ya so, daga mãsu haƙuri."
Tsarki ya tabbata ga Ubangijinka, Ubangijin rinjãye, daga barin abin da suke siffantãwa.
Kuma haƙĩƙa, idan ka bi son zũciyõyinsu daga bãyan abin da ya zo maka daga ilmi, lalle ne kai, sa'an nan, haƙiƙa, azzãlumi kake.
To, idan ba ku aikata ba, kuma Allah Ya kõmo da ku zuwa ga sauƙi, sai ku tsai da salla, kuma ku bãyar da zakka, kuma ku yi ɗã'ã ga Allah da ManzonSa. Kuma Allah ne Mai ƙididdigewa ga abin da kuke aikatãwa.
Kuma ku yi jihãdi a cikin (al'amarin) Allah, hakkin JihãdinSa. shĩ ne Ya zãɓe ku alhãli kuwa bai sanya wani ƙunci ba a kanku a cikin addĩni. Bisa ƙudurcẽwar ubanku Ibrãhĩm, shĩ ne ya yi muku sũna Musulmi daga gabãnin haka.
Lalle Allah Yanã riƙe sammai da ƙasã dõmin kada su gushe. Kuma haƙĩƙa, idan sun gushe, bãbu wani baicinSa da zai riƙe su.
Shin, kunã ganin wani laifi daga gare mu? Fãce dai dõmin mun yi ĩmãni da Allah da abin da aka Saukar zuwa gare mu da abin da aka saukar daga gabãni, kuma dõmin mafi yawanku fãsiƙai ne."
Da (mũminai) sun tsabbace dã Mun azabtar da waɗanda suka kãfirta daga gare su da azãba mai raɗiɗi.
Lalle mũ, mun kasance ɓatattu."
Kuma idan sunã ƙaryata ka, to, haƙĩƙa, waɗanda suke a gabãninsu sun ƙaryata.
Kuma lalle ne mãsu yawa daga abõkan tarayya, haƙiƙa, sãshensu na zambatar sãshe fãce waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai."
Lalle ne Nĩ Inã sãka musu a yau, sabõda abin da suka yi wa haƙuri.
A'a, kũ nekuke yin farin ciki da kyautarku."
"Kuma idan kun ƙaryata, to, lalle waɗansu al'ummõmi a gabãninku sun ƙaryata, kuma bãbu abin da ke kan Manzo, fãce iyar da manzanci, iyarwa bayyananna."
San'nan kuma zukãtanku, suka ƙẽƙashe daga bãyan wancan.
Kamar haka, kuma Mun aurar da su da mãtã mãsu kyaun idãnu, mãsu girmansu.
Kuma zuwa gare shi ake jũyaku."
Dõmin Ya sãkã wa waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai.
Mãsu yawa daga Ma'abuta Littãfi sunã gũrin dã sun mayar da ku, daga bãyan ĩmãninku, kãfirai, sabõda hãsada daga wurin rãyukansu, daga bayãn gaskiya tã bayyana a gare su.
To, waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, sunã a cikin gidãjen Aljannar ni'ima.
Sa'an nan kuma Mu nwayar da ɗauki a gare ku a kansu, kuma Mu taimake ku da dũkiyõyi da ɗiya kuma Mu sanya ku mafiya yawan mãsu fita yãƙi.
Yanzu kuwa, alhãli kun kasance game da shi kunã nẽman gaggãwar aukuwarsa?
Sa'an nan a lõkacin da ya faɗi, ya ce: "Ba ni son mãsu fãɗuwa."
Kuma waɗanda aka bai wa ilmi sunã ganin abin nan da aka saukar zuwa gare ka daga Ubangijinka, shi ne gaskiya, kuma yanã shiryarwa zuwa ga hanyar Mabuwãyi, Gõdadde.
Kuma mutum yã kasance mai ƙwauro ne."
Rãnar da Allah zai tãyar da su gabã ɗaya, sa'an nan Ya bã su lãbãri game da abin da suka aikata, Allah Yã lissafa shi, alhãli kuwa sũ, sun manta da shi, kuma a kan kõme Allah Halartacce ne.
Kuma a lõkacin da Ubangijin Ibrãhim Ya jarrabẽ shi da wasu kalmõmi, sai ya cika su. Ya ce: "Lalle ne Nĩ, Mai sanya ka shugaba dõmin mutãne ne."
A lõkacin da mãtar Imrãna ta ce: "Ya Ubangijina!
Yã ɗiyan Ãdam!
"Wancan dõmin lalle kũ, kun riƙi ãyõyin Allah da izgili, Kuma rãyuwar dũniya ta rũɗe ku.
Yã ku waɗanda suka yi ĩmãni! Kada ku riƙi waɗanda suka riƙi addininku bisa izgili da wãsa, daga waɗanda aka bai wa Littãfi daga gabãninku da kãfirai, masõya, Kuma ku bi Allah da taƙawa idan kun kasance muminai.
To, a lõkacin da Ya tsira da ku zuwa, ga tudu sai kuka bijire.
Kuma kace "Shi ne Ya halitta ku daga ƙasã, kuma zuwa gareShi ne ake tãshin ku."
Suka ce: "Sun ɓace mana.
Kuma Shĩ ne Mahukunci, Masani."
"Wannan maganar mutum dai ce."
Sa'an nan aka yi hukunci a tsakãninsu da ãdalci, kuma bã zã a zãlunce su ba.
Kuma idan kun kãfirta, to, Allah Yanã da abin da ke cikin sammai da ƙasa. Kuma Allah Yã kasance Masani, Mai hikima.
Dõmin tunãtarwa, kuma ba Mu kasance Mãsu zãlunci ba.
"Kada ku kãwo wani uzuri, haƙĩƙa, kun kãfirta a bãyanĩmãninku.
Kõ kuwa ku ce: "Abin sani kawai, ubanninmu suka yi shirki daga farko, kuma mũ, mun kasance zũriya daga bãyansu.
"Kuma lalle haƙĩƙa, (Shaiɗan) yã ɓatar da jama'a mãsu yawa daga gare ku.
Kuma lalle ne idan Mun ɗanɗana wa mutum wata rahama daga gare Mu, sa'an nan kuma Muka zãre ta daga gare shi, lalle ne shĩ, hakĩka, mai yanke tsammãnine, mai yawan kãfrci.
Kuma ¡ãrũna da Fir'auna da Hãmãna, kuma lalle Mũsaya je musu da hujjõji, sai suka yi girman kai a cikin ƙasã kuma ba su kasance mãsu tsẽrẽwa ba.
Sa'an nan kuma, gã ku, yã waɗannan! Kuna kashe kanku, kuma kuna fitar da wani ɓangare daga gare ku daga gidãjensu, kuna taimakon jũna a kansu da zunubi da zãlunci kuma idan kãmammu suka je muku kuna fansarsu alhãli kuwa shĩ fitar da su abin da aka haramta muku ne.
Kuma azzãlumai bã su da wasu mataimaka.
Sunã halakar da kansu (da rantsuwar ƙarya) ne, kuma Allah Yanã sanin lalle, haƙĩƙa, sumaƙaryata ne.'
To lalle sũ a rãnar nan, mãsu tãrayya ne a cikin azãbar.
Haƙĩƙa wani dalĩli daga Ubangijinku yã je muku kuma Mun saukar da wani haske, bayyananne zuwa gare ku.
Lalle ne Ubangijina Ya sanya shi ya tabbata sõsai, kuma lalle ne Ya kyautata game da ni a lõkacin da Ya fitar da ni daga kurkuku. Kuma Ya zo da ku daga ƙauye, a bãyan Shaiɗan yã yi fisgar ɓarna a tsakãnĩna da tsakãnin 'yan'uwana, Lalle ne Ubangijina Mai tausasawa ne ga abin da Yake so.
Ka cika mana haskenmu, kuma Ka yi mana gãfara.
Yã ku waɗanda suka yi ĩmãni! Idan kun haɗu da wata ƙungiyar yãƙi, to, ku tabbata, kuma ku ambaci Allah da yawa, tsammãninku kunã cin nasara.
To, ku ci daga abin da suka kama sabõda ku, kuma ku ambaci sunan Allah a kansa, kuma ku bi Allah da taƙawa.
Kaɗan ƙwarai kuke yin tunãni.
Ki yi ƙanƙan da kai ga Ubangijinki, kuma ki yi sujada, kuma ki yi rukũ'i tãre da mãsu rukũ'i."
Kuma 'yan Aljanna suka kirãyi 'yan Wuta suka ce: "Lalle ne mun sãmi abin da Ubangijinmu Ya yi mana wa'adi, gaskiya ne.
"Kuma bã ka zargin kõme daga gare mu fãce dõmin mun yi ĩmãni da ãyõyin Ubangijinmu a lõkacin da suka zõ mana!
Bã su tsaron wata zumunta a cikin mũminai, kuma haka bãsu tsaron wata amãna.
A. L̃.R. Waɗancan ãyoyin Littãfi mai bayyanãwa ne.
To, wanda ya sha daga gare shi, to, ba shi daga gare ni, kuma wanda bai ɗanɗane shi ba to lalle ne shi, yana daga gare ni, fãce, wanda ya kamfata, kamfata guda da hannunsa."
_Juya kan fanel masu tsaiwa
Allah ne Hasken sammai da ƙasa, misãlin HaskenSa, kamar tãgã, a cikinta akwai fitila, fitilar a cikin ƙarau, ƙarau ɗin kamar shi taurãro ne mai tsananin haske, anã kunna shi daga wata itãciya mai albarka, ta zaitũni, bã bagabashiya ba kuma bã bayammaciya ba, manta na kusa ya yi haske, kuma kõ wuta ba ta shãfe shi ba, haske a kan haske, Allah na shiryar da wanda Yake so zuwa ga HaskenSa.
Kuma Allah Yã kasance wadãtacce, Gõdadde.
Ba ya yiwuwa ga wani mutum, Allah Ya bã shi Littãfi da hukunci da Annabci, sa'an nan kuma ya ce wa mutãne: "Ku kasance bãyi gare ni, baicin Allah."
Kuma a ce wa azzãlumai, "Ku ɗanɗani abin da kuka kasance kunã aikatãwa."
Sai ãƙibarsu ta kasance cẽwa su biyun duka sunã a cikin wutã, sunã mãsu dawwama a cikinta.
Kuma Muka ba su Littãfi mai iyãkar bayãni.
Sai fa bisa ga wata rahama daga gare Mu, da jiyarwa dãɗi zuwa ga wani ɗan lõkaci.
Sai suka tafi sunã shãwara a ɓõye (sunã cẽwa).
Kuma ka tsananta a kansu. Kuma matattararsu Jahannama ce, kuma tir da makoma, ita.
Lalle ne Nĩ Inã sãka musu a yau, sabõda abin da suka yi wa haƙuri. Dõmin lalle ne sũ sũ ne mãsu sãmun babban rabo.
Lalle ne munãfukai sũ ne fãsiƙai.
Lalle Shi, Yã kasance Mai sani ga bãyinSa, Mai gani.
Ka ce: Abin da kuka ciyar daga alhẽri sai ga mahaifa da mafi kusantar dangantaka da marãyu da matalauta da ɗan hanya.
Kuma kada shaidun su ƙi, idan an kira su. Kuma kada ku ƙõsa ga rubũta shi, ƙarami ya kasance kõ babba, zuwa ajalinsa.
Ã'a, suka ce: "Yãye-yãyen mafarki ne. Ã'a, yã ƙirƙira shi ne.
Da wasu kõfuna da shantula da hinjãlai daga (giya) mai ɓuɓɓuga.
Shin, ana saka musu, fãce da abin da suka kasance suna aikatãwa?
Kuma ku bar bayyanannen zunubi da ɓõyayyensa.
Ka ce: "Shin, kun gani, idan Allah Ya riƙe jinku, da gannanku, kuma Ya sanya hãtimi a kan zukãtanku, wane abin bauttãwa ne, wanin Allah, zai jẽ muku da shi?"
Shi ne wanda ya saukar da Littãfi a gare ka, daga cikinsa akwai ãyõyi bayyanannu, su ne mafi yawan Littãfin, da wasu mãsu kamã da jũna.
Kuma wanda Allah Ya ɓatar to, bãbu wani mai shiryarwa a gare shi!"
Kuma waɗanda suka yi ĩmãni da Allah da MazanninSa waɗannan sũ ne kamãlar gaskatãwa kuma su ne mãsu shahãda awurin Ubangjinsu. sunã da sakamakonsu da haskensu. waɗanda suka kafirta kuma suka ƙaryata game da ãyõyinMu, waɗannan su ne'yan Jahĩm.
Kuma annabinsu ya ce musu: "Lalle ne, Allah ya naɗa muku ¦ãlũta ya zama sarki."
Sai wata ƙungiya daga Banĩ Isrã'ĩla ta yi ĩmãni, kuma wata ƙungiya ta kãfirta.
To, a lõkacin da ya jẽ musu da ãyõyinMu, sai gã su sunã yi musu dãriya.
(Allah) Yã ce: "Lalle ne an karɓi addu'arku.
Wannan wata azãba ce mai raɗaɗi.
Sa'an nan idan kun natsu, to, ku tsayar da Salla.
Sun yarda su kasance tãre da mãtã mamaya (gidãje), kuma Allah Yã danne a kan zukãtansu, dõmin haka sũ, bã su gãnẽwa.
To, lalle ne ita (ciyarwar nan) ibãdar nẽman kusanta ce a gare su.
Ka ce: "Nĩban zama wakĩli a kanku ba."
Kuma lalle idan ka tambaye su: "Wãne ne ya halitta su?" Lalle ne zã su ce Allah ne.
Kuma ku yi shãwara a tsakãninku bisa abin da aka sani. Kuma idan kun nũna talauci to wata mace zã ta shãyar da mãma sabõda shi (mijin).
Lalle sũ abin da suka kasance sunã aikatãwa ya mũnana.
Waɗannan ne wɗanda suka yi hasãrar rãyukansu, kuma abin da suka kasance sunã ƙirƙirawa ya ɓace musu.
"Lalle Allah shi ne Ubangijina, kuma Ubangijinku, sai ku bauta Masa.
To, a lõkacin da (¦ãlũta) ya ƙẽtare shi, shi da waɗanda suka yi ĩmani tãre da shi, (sai waɗanda suka sha) suka ce: "Babu ĩko a gare mu yau game da Jãlũta da rundunõninsa."Waɗanda suka tabbata cẽwa lalle sũ mãsu gamuwa ne da Allah, suka ce: "Da yawa ƙungiya kaɗan ta rinjayi wata ƙungiya mai yawa da iznin Allah, kuma Allah Yana tãre da mãsu haƙuri."
Shin fa, ba ku yin tunãni?"
Kuma daga waɗanda Muka halitta akwai wata al'umma, sunã shiryarwa da gaskiya, kuma, da ita suke yin ãdalci.
Kuma mutum yanã yin addu'a da sharri kamar addu'arsa da alhẽri, kuma mutum ya kasance mai gaggãwa.
Kuma Allah ne Mai ƙididdigewa ga abin da kuke aikatãwa.
"Cẽwa, Ki jẽfa shi a cikin akwatin nan, sa'an nan ki jẽfa shi a cikin kõgi, sa'an nan kogin ya jefa shi a gãɓa, wani maƙiyi Nãwa kuma maƙiyi nãsa ya ɗauke shi.'
Kayya! Lalle ne ita kalma ce, shĩ ne mafaɗinta, alhãli kuwa a bãya gare su akwai wani shãmaki har rãnar da zã a tãyar da su.
Lalle Allah Mai gãfara ne, Mai jin ƙai."
Daga ina wannan yake gare ki?"
Suka ce: "Shin kana riƙon mu ne da izgili?"
To, da ambaton Allah zukãta suke natsuwa.
Kuma suka ce: "Idan mun bi shiriya tãre da kai anã fizge mu daga ƙasamiu."
Yanã jin ãyõyin Allah anã karanta su a kansa, sa'an nan ya dõge yanã makãngari, kamar bai jĩ su ba.
Kuma ka ce: "Gaskiya daga Ubangijinku take."
To, Wancan ne Allah, Ubangijinku Tobbatacce.
Ka bã ni zuriyya mai kyau daga gunKa.
"Sai ku jẽ masa sa'an nan ku ce, Lalle mũ, Manzanni biyune na Ubangijinka, sai ka saki Banĩ Isrã'ĩla tãre da mu. Kuma kada ka yi musu azãba.
"Yã Ubangijina, to, kada Ka sanya ni a cikin mutãne azzãlumai."
Sa'an nan a lõkacin da ta ji lãbãri game da mãkircinsu, sai ta aika kiran liyafa zuwa gare su, kuma ta yi tattalin abincin da ake dõgara wajen cinsa, kuma ta bai wa kõwace ɗaya daga cikinsu wuƙa, kuma ta ce: "Ka fito a kansu."
Ya ce: "Kayya!
Ya ce: "Shin, kuma ba ka yi ĩmãni ba?" Ya ce: "Na'am!
To, shin, akwai mai tunãwa?
Kuma lalle ne waɗanda aka bai wa Littãfi, haƙĩƙa su, sunã sanin lalle ne, shĩ ne gaskiya, daga Ubangijinka.
Sũ ne waɗanda suke cikãwa da alkawarin Allah, kuma bã su warware alkawari.
Lalle ne Allah ga mutãne haƙĩƙa, Mai tausayi ne, Mai jin ƙai.
Suna yaudarayya da Allah da waɗanda suka yi ĩmãni, alhãli bã su yaudarar kõwa fãce kansu, kuma bã su sakankancẽwa!
Kuma Muka fitar da abin da yake a cikin ƙirãzansu, daga ƙiyayya, ƙõramu sunã gudãna daga ƙarƙashinsu, kuma suka ce: "Gõdiya ta tabbata ga Allah, wanda Ya shiryar da mu ga wannan. Kuma ba mu kasance munã iya shiryuwa ba, bã dõmin Allah Ya shiryar da mu ba.
Kuma tabbas haƙĩƙa, Mun aika mãsu gargaɗi a cikinsu.
To, waɗanda suke sãɓãwa daga umurninSa, su yi saunar wata fitina ta sãme su, kõ kuwa wata azãba mai raɗãɗi ta sãme su.
Suka ce: "Lalle ne mũ, da abin daaka aiko shi, mãsu ĩmãni ne."
Hanyar Allah wadda ta gabãta a cikin bãyinSa.
Ka yi haƙuri bisa ga abin da suke faɗa (na izgili), kuma ka ambaci bãwanMu Dãwũda ma'abũcin ƙarfin ibãda. Lalle, shi, mai mayar da al'amari ga Allah ne.
Kuma haƙĩƙa, manzanninMu sun je wa Ibrãhim da bushãra suka ce: "Aminci."
Sa'an nan, a lõkacin da ya jẽ musu da gaskiya daga wurinMu, suka ce: "Ku kashe ɗiyan waɗanda suka yi ĩmãni tãre da shi, kuma ku rãyar da mãtansu." Kuma mugun shirin kãfirai, bai zama ba fãce a cikin bata.
Ka ce: "Ku yi ĩmãni da Shi, ko kuwa kada ku yi ĩmãni, lalle ne waɗanda aka bai wa ilmi daga gabãninsa, idan anã karãtunsa a kansu, sunã fãɗuwa ga haɓõɓinsu, sunã mãsu sujada."
"Kuma waccan ni'ima ce, kanã gõrint a kaina, dõmin kã bautar da Banĩ Isrã'ĩla."
Akwai tsammãnin Allah Ya kange gãfin waɗanda suka kãfirta, kuma Allah ne Mafi tsananin gãfi, kuma Mafi tsananin azabtãwa.
Lalle Alla Ya ji maganar wadda ke yi maka jãyayya game da mijinta, tanã kai ƙãra ga Allah, kuma Allah nã jin muhawararku.
Sai suka yi girman kai ga umurnin Ubangijinsu, sabõda haka tsãwa ta kãma su, alhãli kuwa sunã kallo.
To, ku yi dãko. Lalle ne mũ, tãre da ku mãsu dãkon ne."
Kada ka kashe shi, akwai fatan ya amfane mu, kõ mu riƙe Shi ɗã," alhãli kuwa sũ ba su sansance ba.
zuwa gare Shi makõmarku take gabã ɗaya, wa'adin Allah gaskiya ne.
Da Maryama ɗiyar Imrãna wadda ta tsare farjinta, sai Muka hũra a cikinsa daga rũhinMu.
Kace: "To, wãne ne ke mallakar wani abu daga Allah sabõda kũ, idan Yã yi nufin wata cũta agare ku kõ kuma (idan) Ya yi nufin wani amfãni a gare ku?
Sabõda haka, ka tsarkake sũnan Ubangjinka, mai girma.
Lalle ne Allah Yã kasance Mabuwãyi, Mai hikima.
Kuma me ya sanar da kai (cẽwa anã) tsammãnin Sa'ar kusa take?
Bisa ƙudurcẽwar ubanku Ibrãhĩm, shĩ ne ya yi muku sũna Musulmi daga gabãnin haka.
Ashe idan ya mutu ko kuwa aka kashe shi, zã kujũya a kan dugaduganku?
Ka ce: "Lalle ne wasu manzanni sun je muku, a gabãnĩna, da hujjõji bayyanannu, kuma da abin da kuka faɗa, to, don me kuka kashe su, idan kun kasance mãsu gaskiya?"
Lalle ne Allah a kan dukan kõme Mai ĩkon yi ne.
Kuma majiɓantansu daga mutãne suka ce: "Yã Ubangjinmu! Sãshenmu ya ji dãɗi da sãshe, kuma mun kai ga ajalinmu wanda Ka yanka mana!"
Shin, kuna umurnin mutãne da alhẽri, kuma ku manta da kanku alhãli kuwa kuna karatun littãfi?
Bari wannan, ai bã ku girmama marãya!
Ya ce: "Na, am kuma lalle ne kunã a cikin makusanta."
"Yã ƙaramin ɗãna! Lalle ita idan gwargwadon ƙwãyar kõmayya ce ta kasance, to, ta kasance a cikin wani falalen dũtse, kõ a cikin sammai, kõ a cikin ƙasã, Allah zai kãwo ta Lalle Allah Mai tausasãwa ne, Masani."
Sa'an nan Na kãma waɗanda suka kãfirta. To, yãya musũNa yake?
Ya ce: "Yã Ubangiji!
"Kuma inã nẽman tsari da Kai, ya Ubangijĩna! Dõmin kada su halarto ni, "
Kuma kunã da abũbuwan amfãni a cikinsu, kuma dõmin ku isar da wata buƙãta, a cikin ƙirãzanku a kansu kuma a kansu da a kan jirãge ake, ɗaukar ku.
Kuma lalle ne gidan Lãhira shĩ ne mafi alhẽri ga waɗanda suka yi taƙawa?
Kuma mẽne ne zaton waɗanda suke ƙirƙira ƙarya ga Allah, a Rãnar ¡iyãma?
Sabõda haka ku yi ĩmãni yã fi zama alhẽri a gare ku. Kuma idan kun kãfirta, to, Allah Yanã da abin da ke cikin sammai da ƙasa.
"Amma ni, shĩ ne Allah Ubangijina, kuma bã zan tãra kõwa da Ubangijina ba"
Ka ce: "Abin sani kawai, anã yin wahayi zuwa gare ni ne, cẽwa, lalle ne, Abin bautãwarku, Abin bautãwa ne Guda.
Kuma lalle ne haƙĩƙa Mun halittã ku sa'an nan kuma Mun sũrantã ku, sa'an nan kumaMun ce wa malã'iku: "Ku yi sujada ga Ãdam."
To, idan sun jũya bã ya sai ku ce: "ku yi shaida cẽwa, lalle ne mu masu sallamã wa ne."
A lõkacin da Allah Ya ce: "Yã Ĩsã ɗan Maryama! Ka tuna ni'ima Ta a kanka, kuma a kan mahaifiyarka, a lõkacin da Na ƙarfafa ka da Rũhul ¡udusi, kanã yiwa mutãne magana a cikin shimfiɗar jariri, da kuma kanã dattijo. Kuma a lõkacin da Na sanar da kai rubutu da hikima da Attaura da Injĩla, kuma a lõkacin da kake yin halitta daga lãkã kamar surar tsuntsu da izinĩNa, sa'an nan ka hura a cikinta sai ta zama tsuntsu da izinĩNa, kuma kanã warkar da haifaffen makaho da kuturu, da izinĩNa, kuma a lõkacin da kake fitar da matattu da izinĩNa, kuma a lõkacin da Na kange Banĩ Isrã'ĩla daga gare ka, a lõkacin da ka je musu da hujjõji bayyanannu, sai waɗanda suka kãfirta daga cikinsu suka ce: 'Wannan bã kõme ba ne, fãce sihiri bayyananne.'
To, Allah bai kasance Yanã zãluntar su ba, amma sun kasance rãyukansu suke zãlunta.
Suka ce, "Lalle mũ dai mãsu kafirta ne game da abin da aka aiko ku da shi."
Suka ce: 'Gaskiya', kuma shi ne Maɗaukaki, Mai girma,"
Kuma wanda ya jiɓince su daga gare ku, to, waɗannan sũ ne azzãlumai.
Sai ku nẽme Shi gãfara, sa'an nan kuma ku tũba zuwa gare Shi. Lalle Ubangijina Makusanci ne Mai karɓãwa."
Ya ce: "Ka fita daga gare ta kanã abin zargi kõrarre.
"Lalle dã mun kasance bãyin Allah waɗanda aka tsarkake."
Ã'a, mafi yawansubã su sanin gaskiya, sabõda haka sũ mãsu bijirẽwa ne."
Lalle ne waɗanda suka yi ĩmãni da waɗanda suka tũba (Yahũdu) da waɗanda suka karkace (Saba'ãwa) da Nasãra da Majũsãwa da waɗanda suka yi shirka, lalle ne Allah Yanã yin hukunci a tsakãninsu a Ranãr ¡iyãma.
Suka ce: "Lalle mũ mun kasance a gabãnin wannan (a dũniya) a cikin iyãlanmu munã jin tsõro."
Ba ka kasance kanã sanin su ba, haka kuma mutãnenka ba su sani ba daga gabãnin wannan.
Kõ sunã cẽwa, "Akwai hauka gare shi?"
Wannan ne mafi alhẽri gare ku, tsammaninku, zã ku tuna.
Sai shaiɗan ya sanya waswãsi zuwa gare shi, ya ce: "Yã Ãdamu!
Lalle ne, Allah Yã kasance, a kan dukkan kõme, Mahalarci.
Dõmin kada ku yi baƙin ciki a kan abin da ya kuɓuce muku, kuma kada ku yi mumar alfahari da abin da Ya bã ku.
Ka ce: "Shin, kun gani, idan Allah Ya sanya yini a kanku tutur zuwa Rãnar ¡iyãma, wane abin bautãwa, wanin Allah, zai zo muku da dare wanda kunã natsuwa a cikinsa?
Lalle ne, Mun bayyana ãyõyi ga mutãne masu sakankancewa.
Ka ce: "Wãne ne wanda yake tsare ku daga Allah, idan Yã yi nufin wata cũta game da ku?"
Kuma Mun sanya shi ya zama shiriya ga Banĩ Isrã'ĩla.
A yau Nã kammalã muku addininku, Kuma Nã cika ni'imaTa a kanku, Kuma Nã yarda da Musulunci ya zama addini a gare ku.
Sa'an nan ku tũba zuwa gare Shi, Ya jiyar da ku dãɗi, jiyarwa mai kyau zuwa ga ajali ambatacce, kuma Ya bai wa dukkan ma'abucin, girma girmansa.
Lalle ne ita, tã kasance azãbar yini mai girma.
An haramta muku uwãyenku, da 'yã'yanku, da 'yan'uwanku mãtã, da goggonninku, da innoninku, da 'yã'yan ɗan'uwa, da 'ya'yan 'yar'uwa, da uwãyenku waɗanan da suka shãyar da ku mãma, da 'yan'uwanku mãtã na shan mãma, da uwãyen mãtanku, da agõlolinku waɗanda suke cikin ɗãkunanku daga mãtanku, waɗanda kuka yi duhũli da su, kuma idan ba ku yi duhũli da sũ ba, to, bãbu laifi a kanku, da mãtan 'yã'yanku waɗanda, suke daga tsatsonku, kuma kada ku haɗa tsakanin 'yan'uwa biyu mãtã, fãce abin da ya shige.
Lalle Allah, Shĩ ne Mai ji, Mai gani.
Sai su shiga, game da ita (ƙũrar), a tsakãnin jama'ar maƙiya.
Wanda ya kasance yanã zaton cẽwa Allah bã zai taimake shi ba a cikin dũniya da Lãhira to sai ya mĩƙa wata igiya zuwa sama, sa'an nan kuma ya yanke ta, sa'an nan ya dũba. Shin, ko lalle kaidinsa zai gusar da abin da yake ji na takaici?
Sunã zaton ƙungiyõyin kãfirai ba su tafi ba.
Dukan wancan mli mũninsa yã kasance abin ƙyãma a wurin Ubangijinka.
Ya ce: "Lalle ne inã nufin in aurar da kai ɗayan 'yã'yãna biyu, waɗannan, a kan ka yi mini aikin ijãra shẽkara takwas to, idan ka cika gõma, to, daga, gare ka yake.
Kuma idan waɗanda suka yi zãlunci suka ga azãba, sa'an nan bã za a saukake ta daga gare su ba, kuma bã su zama anã yi musu jinkiri ba.
Ashe bãbu mazauni a cikin Jahannama ga mãsu girman kai?
Waɗanda suka yi ĩmãni da ãyõyinMu, kuma suka kasance mãsu sallamawar al'amari (ga Allah).
Waɗanda suka yi ĩmãni da ãyõyinMu, kuma suka kasance mãsu sallamawar al'amari (ga Allah).
Sabõda haka, ka yi haƙuri, lalle wa'adin Allah gaskiya ne.
Kuma rãnar da Sa'a ke tsayuwa, a rãnar nan mãsu ɓãtãwã (ga hujjõjin Allah dõmin su ki bin sharĩ'arSa) zã su yi hasãra."
Ã'a ga Allah al'amari yake gabã ɗaya!
Wannan bã mutum ba ne!
Kuma matabbata a cikin ilmi sunã cẽwa: "Mun yi ĩmãni da Shi; dukkansa daga wurin Ubangijinmu yake." Kuma bãbu mai tunãni fãce ma'abũta hankula.
Sunã ƙõnuwa a wutar jahannama, kuma tir da matabbatarsu.
Suka ce: "Ashe, Manzanninku ba su jẽ muku da hujjõji bayyanannu ba?"
Ka nũna mini in yi dũbi zuwa gare Ka!"
To, mutum ya dũba, daga mẽ aka halittã shi?
Hawãriyãwa suka ce: "Mu ne mataimakan Allah.
Lalle ne Allah Yã kasance ga dukkan kõme, Masani.
Ka ce: (Allah Ya ce): "Yã bãyĩNa waɗanda suka yi ĩmãni!
Kõ zã Mu sanya waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai kamar waɗanda suke mãsu barna ne a cikin ƙasa?
Sa'an nan Muka yãfe laifi daga wancan. Kuma Mun bai wa Mũsã dalĩli bayyananne.
Kuma ma'abũta cikinna ajalinsu, (shi ne) cewa su haifi cikinnansu.
Kuma Allah Ya yi wa'adi ga waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, daga cikinsu, da gãfara da ijãra mai girma.
Ka ce: "Ashe, kun gani!
"Kuma Na zãɓe ka dõmin Kaina."
Kuma wanda ya sãɓã wa Manzo daga bãyan shiriya tã bayyana a gare shi, kuma ya bi wanin hanyar mũminai, zã Mu jiɓintar masa abin da ya jiɓinta, kuma Mu ƙõne shi da Jahannama. Kuma tã mũnana ta zama makõma.
Sai mashãwarta waɗanda suka kãfirta daga mutãnensa, suka ce: "Wannan ba kõwa ba ne, fãce mutum misãlinku, yanã nufin ya ɗaukaka a kanku.
"Wannan bã kõme ba ne fãce tãtsũniyõyin mutãnen farko."
Lalle ne, a cikin halittar sammai da ƙasa, da sãɓãwar dare da yini, da jirãge wadaɗnda suke gudana a cikin tẽku (ɗauke) da abin da yake amfãnin mutãne, da abin da Allah Ya saukar daga sama daga ruwa, sai Ya rãyar da ƙasa da shi a bãyan mutuwarta, kuma Ya wãtsa, a cikinta, daga dukan dabba, kuma da jũyãwar iskõki da girgije hõrarre a tsakãnin sama da ƙasa; haƙĩƙa, akwaiãyõyi ga mutãne mãsu yin hankali.
Kuma dã Allah Yanã kãma mutãne sabõda abin da suka aikata, dã bai bar wata dabba ba a kanta (kasã).
Nĩ ce nã nẽme shi daga kansa. Kuma lalle ne shĩ, haƙĩƙa, yanã daga mãsu gaskiya.
Kuma bãbu abin da yake a kan Manzo fãce iyarwa bayyananna."
Kuma haƙĩƙa, mãdalla da gidan mãsu taƙawa.
Kuma Muka yi wahayi zuwa ga Mũsã a lõkacin da mutãnensasuka nẽme shi, ga shãyarwa, cẽwa: "Ka dõki dũtsen da sandarka."Sai marmaro gõma shã biyu suka ɓuɓɓuga daga gare shi: Lalle ne kõwaɗanne mutãne sun san mashãyarsu.
Lalle ne waɗanda kalmar yabo tã gabãta a garẽ su daga garẽ Mu, waɗannan waɗanda ake nĩsantarwa daga barinta ne.
Ku bauta wa Allah; bã ku da wani abin bauta wa wanninSa.
Sai ya fita daga gare ta, yanã mai jin tsõro yanã sauna.
Shin, ba su sani ba cẽwa "Lalle ne wanda ya sãɓa wa Allah da ManzonSa, haƙĩƙa Yanã da wutar Jahannama, Yanã madawwami a cikinta?
"Waɗanda kejayayya a cikin ãyõyin Allah, bã da wani dalĩli da ya zo musu ba. Jidalin ya girma ga zamansa abin ki a wurin Allah da wurin waɗanda suka yi ĩmãni.
Kuma ya binciki tsuntsãye, sai ya ce: "Me ya kãre ni bã ni ganin hudhudu, kõ ya kasance daga mãsu fakuwa ne?"
Kuma dũbi dai Munã bã da lãbãri a gare ka daga lãbarun Manzanni, abin da Muke tabbatar da zuciyarka da shi.
Lalle shĩ wanda ya je wa Ubangijinsa yanã mai laifi, to lalle ne yanã da Jahannama, bã ya mutuwa a cikinta kuma bã ya rãyuwa.
Ashe, ba ka ga lalle jirgin ruwa nã gudãna ba a cikin tẽku da ni'imar Allah dõmin Ya nũna muku daga ãyõyinSa?
To, Lãhira da dũniya na Allah kawai ne (wanda ya nẽme su daga wani, yã yi kuskure).
Da tsararrun auren wasu maza, fãce dai abin da hannuwanku suka mallaka.
Lalle, mu mun kasance azzãlumai."
Kuma tir da irin tuzgãwarsu.
To, yãya ake karkatar da ku?
Lalle ne nĩ nã bar addinin mutãne waɗanda ba su yi ĩmãni da Allah ba, kuma game da lãhira, sũ kãfirai ne."
Lalle ne, Yanã shigar da su a wata mashiga wadda zã su yarda da ita.
"Kuma a lõkacin da Na yi wahayi zuwa ga Hawãriyãwa cewa ku yi ĩmãni da Ni, kuma da ManzoNa. Suka ce: "Mun yi ĩmãni, kuma ka shaida da cewa lalle mu, mãsu sallamãwa ne."
Tsarkinsa yã tabbata!
Sabõda haka, a lõkacin da suka yanke tsammãni daga gare shi, sai suka fita sunã mãsu gãnãwa.
Bã su jin yãsassar magana, a cikinta, kuma bã su jin ƙaryatãwa.
Ya ce: "Ya mutãnena! Ashe, jama'ãta ce mafi daraja a gare ku daga Allah, kuma kun riƙẽ Shi a bãyanku abin jẽfarwa?
To, wanda sikẽlansasuka yi nauyi, to, waɗannan sũ ne mãsu cin nasara.
Kuma Ibrahĩm ya ce "Bãbu abin da kuka yi sai dai kub bar Allah kun riƙi gumãka sabõda sõyayyar tsakãninku a cikin rãyuwar dũniya, a'an nan a Rãnar ¡iyãma sãshinku zai kãfirce wa sãshi, kuma makõmarku ita ce wutã kuma bã ku da waɗansu mataimaka."
Suna tambayar ka game da Watan Alfarma: yin yãki a cikinsa.
To, ka yãfe laifi daga gare su, kuma ka kau da kai.
Kuma daga cikinsu akwai waɗanda suke saurare zuwa gare ka. Shin fa, kai kana jiyar da kurma, kuma kõ dã sun kasance bã su hankalta?
Da Lũɗu, a lõkacin daya ce wa mutãnensa: "Shin, kunã jẽ wa alfãsha, bãbu kõwa da ya gabãce ku da ita daga halittu?"
Kõ wãne ne yake fã ra halitta sa'an nan kuma ya mayar da ita, kuma Wãne ne Ya azurta ku daga sama da ƙasa?
Kuma da yawa daga alƙarya, Na yi jinkirin azãba gare ta (da laifinta) sa'an nan Na kãma ta, kuma zuwa gare Ni makõma take.
(Suna) a cikin Aljanna maɗaukakiya.
Dõmin kada ku yi baƙin ciki a kan abin da ya kuɓuce muku, kuma kada ku yi mumar alfahari da abin da Ya bã ku.
"Kuma lalle ne mũ mun tabbatã bã zã mu buwãyi Allah ba, a cikin ƙasa, kuma bã zã mu buwãye Shi da gudu ba."
Ayyukansu sun ɓãci, sabõda haka suka wãyi gari sunã mãsu hasãra.
"Wancan ne, dõmin ya san cẽwa lalle ne ni ban yaudareshi ba a ɓõye, kuma lalle Allah bã Ya shiryar da kaidin mayaudara."
Sai suka sõke ta sa'an nan suka wãyi gari sunã mãsu nadãma.
Kuma haka dai aka ƙawãce wa Fir'auna mũnãnan aikinsakuma aka danne shi daga barin tafarki.
"Kuma ya Ãdam!
"Sai ku jẽ masa sa'an nan ku ce, Lalle mũ, Manzanni biyune na Ubangijinka, sai ka saki Banĩ Isrã'ĩla tãre da mu. Kuma kada ka yi musu azãba.
Kuma ga kõwace al'umma akwai ajali.
Suka ce: "Ka rõƙa mana Ubangijinka Ya bayyana mana abin da yake launinta."
"Kuma, lalle ne shi, a lõkacin da bãwan Allah ke kiran Sa sun yi kusa su zama kamar shirgi a kansa."
Shin, kun sanya shãyar da mahajjata da rãyar da Masallaci Mai alfarma kamar wanda ya yi ĩmãni da Allah da Rãnar Lãhira, kuma ya yi jihãɗi a cikin hanyar Allah?
Kuma Fuskarar Ubangijinka, Mai girman Jalala da karimci, ita ce take wanzuwa.
Kuma suka je, a jikin rigarsa akwai wani jinin ƙarya.
(An saukar da shi) saukarwa daga wanda Ya halitta ƙasa da sammai maɗaukaka.
Wannan yã fi kusantar da sanyaya idãnunsu, kuma bã zã su yi baƙin ciki ba, kuma su yarda da abin da ka bã su, sũ duka.
Ka ce: "Wãne ne Ubangijin sammai bakwai kuma Ubangijin Al'arshi mai girma?"
Kuma suka ce: "Idan mun bi shiriya tãre da kai anã fizge mu daga ƙasamiu." Shin, ba Mu tabbatar musu da mallakar Hurumi ba, ya zama amintacce, anã jãwõwa zuwa gare shi, 'ya'yan itãcen kõwane iri, bisa ga azurtãwa daga gare Mu?
Ka tsai da salla, kuma ka yi umurni da abin da aka sani, kuma ka yi hani daga abin da ba a sani ba, kuma ka yi haƙuri a kan abin da ya sãme ka. Lalle, wancan yanã daga muhimman al'amura."
Kuma Lũɗu Mun bã shi hukunci da ilmi. Kuma Mun tsĩrar da shi daga alƙaryar nan wadda ke aikata mũnãnan ayyuka.
Kuma sunã fãtan sãmun rahamarSa, kuma sunã tsõron azãbarSa. Lalle ne azãbar Ubangijinka ta kasance abar tsõro ce.
Lalle Shi, Mai lãbartãwa ne game da abin da kuke aikatãwa.
To zã su ce "Wãne ne zai mayar da mu?"
Sa'an nan, su zamã iskõki mãsu ƙarfi suna kaɗãwa da ƙarfi.
Don me Ka tãyar da ni makãho alhãli kuwa nã kasance mai gani?"
Kuma ga kõwanne, akwai darajõji daga abin da suka aikata.
Amma Yanã jinkirta musu zuwa ga ajalin da aka ambatã.
Bã su iya amfani da kõme daga abin da suka sanã'anta.
"Yã Ubangijinmu! Kada Ka sanya mu fitina ga waɗanda suka kãfirta, kuma Ka yi gãfara gare Mu.
Mai zunɗe, mai yãwo da gulma.
Shin lãbarin waɗanda suke a gabãninsu bai je musu ba, mutãnen Nũhu da Ãdãwa da Samũdãwa da mutãnen Ibrãhĩm da Ma'abũta Madyana da waɗanda aka birkice?
Kuma da wancan aka umurce ni, kuma ni ne farkon mãsu sallamãwa."
Wancan! sabõda Allah Yanã shigar da dare a cikin yini, kuma Yanã shigar da yini a cikin dare, kuma lalle, Allah Mai jĩ ne, Mai gani.
Wancan sabõda lalle su Manzanninsu sun kasance sunã jẽ musu da hujjõji bayyanannu, sai suka ce: "Ashe, wasu mutane za su shiryar da mũ?"
"Kuma idan na yi jiyya, to, Shĩ ne Yake warkar da ni."
Suka ce: "Kada kaji tsõro." Kuma suka yi masa bushãra da (haihuwar) wani yaro mai ilmi.
"Iadan kuma wata sifa irinta ta zo, za su karɓe ta.
Jerin shaidar abu na fanel
Kuma lalle haƙĩƙa Mun bai wa Luƙmãn hikima.
Iyarwa dai da Manzanci).
Tanã darkake kõwane abu da umurnin Ubangijinta.
Waɗannan anã kiran su daga wuri mai nĩsa."
Sanã mãsu shagaltacin zukãtansu, kuma su asirta gãnãwa: Waɗanda suka yi zãlunce (sunã cẽwa) "Wannan bã Kõwa ba ne fãce mutum misãlinku.
Kuma lalle, Shĩ, Shi ne Ubangijin Shi'ira.
Kuma idan wata mace ta ji tsõron ƙiyo daga mijinta kõ kuwa bijirẽwa to, bãbu laifi a kansu su yi sulhu a tsakãninsu, sulhu (mai kyau) Kuma yin sulhu ne mafi alhẽri.
Kuma annabinsu ya ce musu: "Lalle ne alãmar mulkinSa ita ce akwatin nan ya zo muku, a cikinsa akwai natsuwa daga Ubangijinku da sauran kaya daga abin da Gidan Mũsã da Gidan Hãrũna suka bari malã'iku suna ɗaukarsa.
"Dõmin Ya san lalle, sun iyar da sãƙonnin Ubangijinsu, kuma (Shi Ubangijin) Yã kẽwaye su da sani, kuma Yã lissafe dukan kõme da ƙididdiga."
Lalle ne ni a gare ku mai gargaɗi ne kuma mai bushãrã daga gare Shi.
"Kuma waccan ni'ima ce, kanã gõrint a kaina, dõmin kã bautar da Banĩ Isrã'ĩla."
Kuma ku nẽmi gãfara gun Ubangijinku.
Da waɗanda suka zaunar da gidãjensu (ga Musulunci) kuma (suka zãɓi) ĩmãni, a gabãnin zuwansu, sunã son wanda ya yi hijira zuwa gare su, kuma bã su tunãnin wata bukãta a cikin ƙirãzansu daga abin da aka bai wa muhãjirĩna, kuma sunã fĩfĩta waɗansu a kan kãwunansu, kuma ko dã sunã da wata larũra.
Kuma waɗanda suke mãkirci a cikin ãyõyinMu, sunã nẽman gajiyarwa, waɗannan abin halartãwa ne a cikin azãba.
Kuma lalle ne Mu Muke rãyarwa, kuma Muke kashẽwa kuma Mũ ne magada.
Kuma ba Mu aika ba, a gabãninka daga Manzanni, fãce lalle sũ haƙĩƙa sunã cin abinci kuma sunã tafiya a cikin kasuwõyi.
Yã kũ waɗanda aka bai wa Littãfi! Ku yi ĩmãni da abinda Muka saukar, yana mai gaskatãwa ga abin da yake tãre da ku, tun gabanin Mu shãfe wasu fuskõki, sa'an nan Mu mayar da su a kan bãyayyakinsu, ko Mu la'ane su kamar yadda Muka la'ani masu Asabar.
Kuma idan waɗanda suke yin ĩmãni da ãyõyinMu suka jẽ maka, sai ka ce: "Aminci ya tabbata a gareku; Ubangjinku Ya wajabta rahama ga kanSa, cẽwa lalle ne wanda ya aikata aibi da jãhilci daga cikinku, sa'an nan kuma ya tũba daga bãyansa, kuma ya gyãra, to, lalle Shi, Mai gãfara ne, Mai jin ƙai."
Lalle ne mutãnen, sun ɗauke ni mai rauni, kuma sun yi kusa su kashe ni, sabõda haka kada ka dãrantar da maƙiya game da ni, kuma kada ka sanya ni tãre da mutãne azzãlumai."
Yanã yi muku gargaɗi, ɗammãnin ku, kunã tunãwa.
Lalle ne, wannan wata tunãtarwa ce, sai dai wanda ya so, ya kãma hanyar ƙwarai zuwa ga Ubangijinsa.
Ka ce: "Ranar hukuncin nan, ĩmãnin waɗanda suka kãfirta bã zai amfãne su ba (a cikinta) kuma bã zã a yi musu jinkiri ba."
Wancan ana yin wa'azi da shi ga wanda ya kasance daga gare ku yana ĩmãni da Allah da Rãnar Lãhira.
Waccan ita ce hasãra bayyananna.
Kuma idan waɗanda suke yin ĩmãni da ãyõyinMu suka jẽ maka, sai ka ce: "Aminci ya tabbata a gareku; Ubangjinku Ya wajabta rahama ga kanSa, cẽwa lalle ne wanda ya aikata aibi da jãhilci daga cikinku, sa'an nan kuma ya tũba daga bãyansa, kuma ya gyãra, to, lalle Shi, Mai gãfara ne, Mai jin ƙai."
A'a sũ, sunã wãsã a cikin shakka.
To, waɗanda suka yi hijira kuma aka fitar da su daga gidãjensu, kuma aka cũtar da su a cikin hanyaTa, kuma suka yi yãƙi, kuma aka kashe su, lalle ne zan kankare musumiyagun ayyukansu, kuma lalle ne zan shigar da su gidãjen Aljanna (waɗanda) ƙoramu ke gudãna daga ƙarƙashinsu, a kan sakamako daga wurin Allah. Kuma a wurinSa akwai kyakkyawan sakamako.
"Kuma bã ka zargin kõme daga gare mu fãce dõmin mun yi ĩmãni da ãyõyin Ubangijinmu a lõkacin da suka zõ mana!
Kuma da yawa Muka halakar da mutãnen ƙarnõni a gabãninsu.
Kuma lalle tabbas Mun buga kõwane irin misãli ga mutãne a cikin wannan Alƙur'ãni, kuma lalle idan kã je musu da kõwace ãyã, lalle, waɗanda suka kãfirta zã su ce "Kũ, bã kõme kuke ba fãce mãsu barua."
Kuma ka tunãtar, dõmin tunãtarwa tanã amfãnin mũminai.
Lalle ne a cikin wannan akwai ãyõyi ga waɗanda suke yin ĩmãni.
Kuma lalle ne, haƙĩƙa, (¡uraishi) sun jẽ a kan alƙaryar nan wadda aka yi wa ruwa, ruwan azãba.
Kuma da waɗansu alãmõmi, kuma da taurãri sunã mãsu nẽman shiryuwa (ga tafiyarsu ta fatauci).
Samũdãwa sun ƙaryata game da gargaɗin.
Ku nũna mini, mẽne ne suka halitta daga ƙasã?
Fãce maganar Ibrãhĩm ga ubansa (da yace), "Lalle za ni nẽma maka gãfara kuma ban mallaki kõme ba daga Allah sabõda kai." "Yã Ubangijinmu!
Kuma wannan da ya yi ĩmãni ya ce: "Ya mutãnẽnã! Lallene, nĩ, inã yi muku tsõron kwatankwacin rãnar ƙungiyõyi."
Kuma Shĩ ne Ya kange hannayensu daga gare ku, kuma da hannayenku daga gare su, a cikin Makka, bãyan Ya rinjãyar da ku a kansu.
Sabõda haka zã su sani.
Kamar wancan ne Muke fitar da matattu; tsammãninku, kunã tunãni.
Wannan shĩ ne alhẽri a gare ku idan kun kasance kuna da sani.
Lalle wannan, haƙĩƙa, abu ne mai ban mãmaki!"
Abin da aka sani kawai, Masĩ hu ĩsa ɗan Maryama Manzon Allah ne, kuma kalmarSa, yã jẽfa ta zuwa ga Maryama, kuma rũhi ne daga gare Shi. Sabõda haka, ku yi ĩmãni da Allah da manzanninSa, kuma kada ku ce, "Uku".
Sai ka dũba, yãya ãƙibar azzãlumai ta kasance?
Waɗancan sunã da mummunan bincike kuma matabbatarsu Jahannama ce, kuma tir da ita ta zama shimfida.
Mai rahama, Mai jin ƙai;
Shi ne Ubangijin sammai da ƙasa da abin da yake a tsakãninsu. sai ka bauta Masa, kuma ka yi haƙuri ga bautarsa.
Sa'an nan idan sun jũya, to, ku kãmã su kuma ku kashe su inda duk kuka sãme su. Kuma kada ku riƙi wani masõyi daga gare su ko wani mataimaki.
Kuma ba Mu aika ba a gabãninka fãce mazãje, Munã wahayi zuwa gare su, daga mutãnen ƙauyuka. Shin fa, ba su yi tafiya a cikin ƙasa ba, dõmin su dũbayadda ãƙibar waɗanda suka kasance daga gabãninsu ta zama?
"Baicin Allah?
Kuma lalle ne haƙĩƙa Mun aika Nũhu zuwa ga mutãnensa, sai ya ce: "Yã mutãnẽna!
"Kada ku bautã wa kõwa fãce Allah.
To, a lõkacin da suka karkace, Allah Ya karkatar da zukãtansu. Kuma Allah bã Ya shiryar da mutãne fasiƙai.
Ba ka son kõme fãce ka kasance mai tanƙwasawa a cikin ƙasa kuma bã ka nufin ka kasance daga mãsu kyautatãwa."
Ga waɗanda ba su yi ĩmãni da Lãhira ba akwai sifar cũta kuma ga Allah akwai sifa mafi ɗaukaka.
Har kuka ziyarci kaburbura.
To, lalle ƙungiyar Allah sũ ne mãsu babban rabo.
Suka ce: "Ba ku zama ba fãce mutãne misãlinmu kuma nufinku ku kange mu daga abin da iyãyenmu suka kasance sunã bautãwa sai ku zo mana da dalĩli mabayyani."
Kuma daga cikinsu akwai wanda yake tsõkaci zuwa gare ka.
Lalle ne Fir'auna da Hãmãna da rundunõninsu, sun kasance mãsu aikin ganganci.
A lõkacin da malã'iku suka ce "Yã Maryamu! Lalle ne Allah Yana bã ki bushãra da wata kalma daga gare Shi; sũnansa Masĩhu ĩsa ɗan Maryama, yana mai daraja a dũniya da Lãhira kuma daga Makusanta.
Ka ce: "Allah ne mafi gaggãwar (sakamakon) mãkirci."
Yanã sanin abin da ke a cikin sammai da ƙasã. Kuma Yanã sanin abin da kuke bõyẽwa da abin da kuke bayyanãwa.
Bã a sanya musu cĩwon jirĩ sabõda ita, kuma bã su buguwa.
Ko mafi tsananin ƙeƙashewa. kuma lalle ne daga duwãtsu, haƙĩka, akwai abin da maremari suke ɓuɓɓuga daga gare shi, kuma lalle ne daga gare su, haƙĩƙa, akwai abin da yake tsatstsagewa har ruwa ya fita daga gare shi, kuma lalle ne, haƙĩƙa, daga gare su, haƙĩƙa, akwai da yake fãɗõwa dõmin tsõron Allah, kuma Allah bai zama gãfili ba daga barin abin da kuke aikatãwa.
Kuma Allah Masani ne ga mãsu taƙawa.
Waccan fa ita ce falala mai girma.
Kuma Ubangijinka Yanã halitta abin da Yake so kuma Yake zãɓi.
A rãnar nan, zã ta faɗi lãbãrinta.
Sai suka tafi, har a lõkacin da suka je wa mutãnen wata alƙarya, suka nẽmi mutãnenta da su bã su abinci, sai suka ƙi su yi musu liyãfa.
Kuma an biyar musu da la'ana a cikin wannan dũniyada Rãnar Kiyãma.
Gidãjen Aljannar zama wadda Mai rahama ya yi alkawarin bãyarwa ga bãyinSa (mãsu aikin ĩmãni) a fake.
To, yanzu ku rungume su kuma ku nẽmi abin da Allah yã rubũta muku.
Kuma kada ku kashe kãnku.
Ko sunã zaton lalle Mũ, bã Mu jin asĩrinsu da gãnãwarsu? Na'am!
"Lalle zã Ni cika Jahannama daga gare ka, kuma daga wanda ya bĩ ka daga gare su, gabã ɗaya"
Kuma Allah Mabuwãyi ne, Mai hikima.
Yanã shirya al'amari, Yanã rarrabe ãyõyi daki-daki, mai yiwuwa ne ku yi yaƙĩni da haɗuwa da Ubangijinku.
Ka ce: "Shĩ ne Mai ĩko a kan Ya aika da wata azãba a kanku daga bisanku, kõ kuwa daga ƙarƙashin ƙafãfunku, kõ kuwa Ya gauraya ku ƙungiyõyi, kuma Ya ɗanɗanã wa sãshenku masĩfar sãshe."
Sabõda baka, ka tunãtar, idan tunatarwa zã ta yi amfãni.
"Bã mu cẽwa, sai dai kurum sashen abũbuwan bautawarmu ya sãme ka da cũtar hauka."
Ka ce: Shin kuna jãyayyar hujia ne da mu a cikin al'amarin Allah, alhãli kuwa Shi ne Ubangijinmu kuma Ubangijinku, kuma muna da ayyukanmu, kuma kuna da ayyukanku, kuma mũ, a gare Shi, mãsu tsarkakẽwane?
Ka ce musu "Idan Allah Ya halaka ni nĩ da wanda ke tãre da ni, ko kuma, Yã yi mana rahama, to, wãne ne zai tserar da kafirai daga wata azãba mai raɗaɗi?"
Ga wanda ya so, daga cikinku, ya gabãta ko ya jinkirta.
Kuma Allah ne masani ga azzãlumai
"Lalle ne mun ƙirƙira ƙarya ga Allah idan mun kõma a cikin addininku a bãyan lõkacin da Allah ya tsĩrar da mu daga gare shi, kuma bã ya kasancewa a gare mu, mu kõma a cikinsa, fãce idan Al1ah, Ubangijinmu Ya so.
Kuma zã Mu sãka wa mãsu godiya.
Kuma waɗanda suke mutuwa daga gare ku, alhãli suna barin mãtan aure, wasiyya ga mãtan aurensu da dãɗaɗãwa zuwa ga shekara guda bãbu fitarwa, to, idan sun fita to bãbu laifi a kanku a cikin abin da suka aikata game da kansu daga abin da aka sani, kuma Allah Mabuwayi ne, Mai hikima.
Aka ce mata, "Ki shiga a gidan sarauta."
A lõkacin da mafi shaƙãwarsu ya tafi (wurin sõke rãkumar sãlihu).
Lalle ne Allah, haƙĩƙa, Mai gãfara ne, Mai jin ƙai.
Kada ku ƙirƙira ƙarya ga Allah har Ya tumɓuke ku da wata azãba.
Kuma matsafa suka jẽ wa fir'aunã suka ce: "Lalle ne, shin, Munã da ijãra, idan mun kasance mũ ne marinjaya?"
"Yanã son ya fitar da ku daga ƙasarku game da sihirinSa.
Ku bi Allah da taƙawa, ku yi ĩmãni da ManzonSa Ya bã ku rabo biyu daga rahamarSa, kuma Ya sanya muku wani haske wanda kuke yin tafiya da shi, kuma Ya gãfarta muku.
Kuma lalle haƙĩƙa, Mun aika wasu Manzanni daga gabãninka, daga cikinsu akwai wanda Muka ƙissanta maka lãbãrinsa kuma daga cikinsu akwai wanda ba Mu ƙissanta lãbãrinsa ba a gare ka.
Ku kashe Yũsufu, kõ kuwa ku jẽfa shi a wata ƙasa, fuskar ubanku ta wõfinta sabõda ku, kuma ku kasance a bãyansa mutãne sãlihai.
Kada ka faɗi mafarkinka ga 'yan'uwanka, har su ƙulla maka wani kaidi.
wanda Ya ciyar da su (Ya hana su) daga yunwa, kuma Ya amintar da su daga wani tsõro.
Kuma me ya sãme ku, bã zã ku ciyar ba dõmin ɗaukaka kalmar Allah, alhãli kuwa gãdon sammai da ƙasã na Allah ne?
Kuma da rãnar da Allah Yake cẽwa, "Ku kirãyi abõkan tarayyãTa, waɗanda kuka riya."
Kuma Allah Yanã sanin abin da kuke asirtãwa da abin da kuke bayyanãwa.
Wannan (Alƙur'ãni) shi ne shiryuwa. Kuma waɗanda suka kãfirta game da ãyõyin Ubangijinsu, sunã da wata azãba ta wulãkanci mai raɗaɗi.
Kuma idan waɗanda suka yi shirka suka ga abũbuwan shirkarsu sai su ce: "Yã Ubangijinmu! Waɗannan ne abũbuwanshirkarmu waɗanda muka kasance munã kira baicinKa".
"In dã dai ita, tã kasance mai halakã ni gabã ɗaya ce!
Yace: "Lalle ne nĩ, inã shaida waAllah, kuma ku yi shaidar cẽwa" lalle ne nĩ mai barranta ne dagb abin da kuke yin shirki da shi."
Sai suka ƙaryata shi, sa'an nan Muka tsĩrar da shi da waɗanda suke tãre da shi, a cikin jirgin; kuma Muka nutsar da waɗanda suka ƙaryata shi game da ãyõyinMu.
Alhãli kuwa (ko da suke faɗar maganar) bã su da wani ilmi game da wannan, bã su bin kõme face zato.
Kuma kõ dã ya kasance nauyin ƙwãya daga kõmayya ne Mun zo da ita.
Shin, kuma wanda ya kasance matacce sa'an nan Muka rãyar da shi, kuma Muka sanya wani haske dõminsa, yanã tafiya da shi, yanã zama kamar wanda misãlinsa yanã cikin duffai, shĩ kuma ba mai fita ba daga gare su?
Ka ce: "Lalle, Ubangijĩna Yanã shimfiɗa arziki ga wanda Ya so, kuma Yanã ƙuntatãwa, kuma amma mafi yawan mutãne ba su sani ba."
Waɗannan ãyõyin Allah ne, muna karanta su a gare ka da gaskiya, kuma Allah bã Ya nufin wani zãlunci ga tãlikai.
Ya ce: "Shin to, kunã bautã wa abin da, bã ya, amfãnin ku da Kõme kuma bã ya cũtar da ku baicin Allah?"
Ã'a, sũ dai mutãne ne mãsu girman kai.
Tir da abin shansu, kuma wutar ta yi mũnin zama mahũtarsu.
Yã kũ waɗanda suka yi ĩmãni! An wajabta, a kanku, yin ƙisãsi a cikin kasassu. ɗa da ɗa kuma bãwa da bãwa, kuma mace da mace, to, wanda aka yi rangwamen wani abu gare shi daga ɗan'uwansa to a bi da alhẽri da biya zuwa gare, shi da kyautatãwa.
Lalle mafi mũnin sautuka haƙĩƙa shĩ ne sautin jãkuna. "
Mutãnen Lũɗu ba su zama a wuri mai nĩsa ba daga gare ku."
"Lalle Ubangijinka Yanã yin hukunci a tsakãninsu da hukuncinsa, kuma Shi ne Mabuwãyi, Masani."
Sabõda haka nĩsa ya tabbataga mutãne azzãlumai!
"Shin idan muka mutu kuma muka kasance turɓãya (zã a kõmo da mu)?
Waɗannan su ne mafi ashararancin tãlikai.
A'aha!
Ĩ.
Lalle ne, taimakon Allah yana kusa!
Kayya!
"Wanda aka jũyar da shi daga gare shi, a wannan Rãnar, to, lalle ne, (Allah) Yã yi masa rahama, Kuma wannan ne tsĩra bayyananniya."
Kuma wanda ya ɓãce, to, ka ce: "Ni daga mãsu gargaɗi kawai nake."
Ashe, ba ka gani ba, lalle ne, Allah Yã saukar da ruwa daga sama, sai ƙasa ta wãyi gari kõriya?
Sa'an nan zuwa gare Shi ake mayar da ku."
Sa'an nan kuma kuka jũya daga bayan wancan, to, bã dõmin falalar Allah ba da rahamarSa a kanku, haƙĩƙa, dã kun kasance daga mãsu hasãra."
Kuma rãnar da Yake tãra su, kamar ba su zauna ba fãce sa'a guda daga yini. Sunã gãne jũna a tsakãninsu.
Sai ya ce: "Nĩ ne Ubangijinku mafi ɗaudaka."
Lalle ne Allah Yanã tãre da mãsu haƙuri.
Yã kũ waɗanda suka yi ĩmãni! Idan za ku yi gãnãwa, to, kada ku gãna game da zunubi da zãlunci da sãɓã wa Manzon Allah, kuma ku yi gãnãwa game da alhẽri da taƙawa.
Lalle ne waɗansu ƙungiyoyi daga bãyiNa sun kasance sunã cẽwa, "Yã Ubangijinmu!
Kuma sakamakon cũta shĩ ne wata cũta kamarta, sai dai wanda Ya yãfe kuma ya kyautata, to lãdarsa nã ga Allah.
Suka ce: "Ka rõƙa mana Ubangijinka, Ya bayyana mana, mecẽ ce ita?"
Kuma waɗanda suka yi ĩmãni daga bãya, kuma suka yi hijira kuma suka yi jihãdi tãre da ku, to, waɗannan daga gare ku suke.
Yanã sanin abin da ke gaba gare su da abin da ke bãyansu, kuma zuwa ga Allah ake mayar da al'amura.
Kuma idan kun ji tsõron talauci to, da sannu Allah zai wadãta ku daga falalarSa, idan Ya so.
Ashe fa, wanda ake jẽfãwa a cikin Wutã ne mafĩfĩci kõ kuwa wanda zai je amintacce a Rãnar ¡iyãma?
"Kuma kada ka yi zaton Allah Mai shagalã ne daga abin da azzalumai suke aikatãwã.
Kuma kada ƙiyayya da wasu mutãne ta ɗauke ku, dõmin sun kange ku daga Masallãci Mai alfarma, ga ku yi zãlunci.
Suka ce: "Yã bonenmu!
Sa'an nan idan 'yan'uwa sun kasance gare shi, to, uwarsa tana da sudusi (ɗaya daga cikin kashi shida) daga bayan wasiyya wadda ya yi kõ kuwa bãshi.
Lalle ne ni inã tsõron wata azãba daga Mai rahama ta shãfe ka, har ka zama masõyi ga Shaiɗan."
Da wani daga siffarsa nau'i-nau'i.
Shin, (kunã so) in gaya muku a kan wanda Shaiɗãnnu kan sauka?
Kuma daga cikinsu akwai wanda yake yin ĩmãni da Shi, kuma daga cikinsu akwai wanda bã ya yin ĩmãni da Shi.
Samũdãwa sun ƙaryata game da gargaɗin.
Shin, ba su gani ba, cẽwa, lalle Mũ, Mun sanya dare dõmin su natsu a cikinsa, kuma da yini mai sanya gani?
Dõmin nũna girman kai a cikin ƙasã da mãkircin cũta. Kuma mãkirci na cũta bã ya fãdãwa fãce a kan mutãnensa.
Shĩ ne Ubangijinku, kuma zuwa gare Shi ake mayar da ku."
Kuma ka ce wa waɗanda aka bai wa littãfi da Ummiyyai: "Shin kun sallama?"
Kuma kõwane abu, da suka aikata shi, yanã a cikin littattafai.
Abin da aka sani kawai, Masĩ hu ĩsa ɗan Maryama Manzon Allah ne, kuma kalmarSa, yã jẽfa ta zuwa ga Maryama, kuma rũhi ne daga gare Shi. Sabõda haka, ku yi ĩmãni da Allah da manzanninSa, kuma kada ku ce, "Uku".
Sa'an nan zuwa gare Shi ake mayar da ku."
Ashe idan ya mutu ko kuwa aka kashe shi, zã kujũya a kan dugaduganku?
Kuma dã Ubangijinka Ya so, dã Yã sanya mutãne al'umma guda.
%H:%M
Gaisuwarsu a rãnar da suke haɗuwa da shi "Salãm", kuma Yã yi musu tattalin wani sakamako na karimci.
Kuma ku yãfe ɗin ne mafi kusa da taƙawa.
Kuma wanda ya girmama hukunce-hukuncen Allah to shĩ ne mafĩfĩci a gare shi, a wurin Ubangijinsa.
Kuma lalle haƙĩƙa, Mun aika wasu Manzanni daga gabãninka, daga cikinsu akwai wanda Muka ƙissanta maka lãbãrinsa kuma daga cikinsu akwai wanda ba Mu ƙissanta lãbãrinsa ba a gare ka.
"Kuma Ka sanya mini harshen gaskiya a cikin mutãnen ƙarshe."
Lalle, wancan yanã daga muhimman al'amura."
Sa'an nan ba su sãɓa ba har ilmi ya jẽ musu.
Sai suka tafi, har a lõkacin da suka je wa mutãnen wata alƙarya, suka nẽmi mutãnenta da su bã su abinci, sai suka ƙi su yi musu liyãfa.
Zã a karya tãron, kuma su jũya bãya dõmin gudu.
Lalle Shi, Shi ne Mai ji, Masani.
Sai suka ƙaryata shi, sa'an nan Muka kuɓutar da shi da wanda yake tãre da shi, a cikin jirgi, kuma Muka sanya su mãsu mayẽwa, kuma Muka nutsar da waɗanda suka ƙaryata ãyõyinMu.
Kuma Ubangijinka ne Mafi sani game da wanda yake a cikin sammai da ƙasa.
Lalle ne waɗanda suka kafirta daga mutanen Littafi da mushirikai sana cikin wutar Jahannama suna madawwama a cikinta.
"Kuma nasĩhãta bã zã ta amfãne ku ba, idan nã yi nufin in yi muku nasĩha, idan Allah Yakasance Yanã nufin Ya halaka ku.
Albarkar Allah Ubangijin halittu tã bayyana!
Sai ya saukar da su da rũɗi.
Lalle ne ke, kin kasance daga mãsu kuskure."
Kuma zuwa ga Samũdãwa ɗan'uwansu, Sãlihu, ya ce: "Yã mutãnena!
Idan wannan ya kasancc shĩ ne gaskiya daga wurinKa, sai Ka yi ruwan duwãtsu, a kanmu, daga sama, kõ kuwa Kazõ mana da wata azãba, mai raɗaɗi."
Lalle Mũ, Munã sanin abin da suke asirtãwa da abin da suke bayyanãwa.
Wancan! sabõda Allah Yanã shigar da dare a cikin yini, kuma Yanã shigar da yini a cikin dare, kuma lalle, Allah Mai jĩ ne, Mai gani.
Suka ce: "Mun yi shaida a kan kãwunanmu."
Wancan umurnin Allah ne, Ya saukar da shi zuwa gare ku.
Lalle a cikin wancan akwai ãyõyi ga mutãne mãsu yin tunãni.
Lalle ne yanã da wani ubã, tsoho mai daraja, sabõda haka ka kãma ɗayanmu amatsayinsa. Lalle ne mũ, muna ganin ka daga mãsu kyautatãwa."
TsarkinSa yã tabbata daga wani abin haifuwa ya kasance a gare Shi!
Misãlin waɗanda suka kãfirta da Ubangijinsu, ayyukansu sun yi kama da tõka wadda iska ta yi tsananin bugãwa da ita a cikin yini mai gũguwa.
Waɗannan suna da ijãrarsu a wurin Ubangijinsu.
Waɗanda suke nufin rãyuwar dũniya suka ce: "Inã dai munã da kwatancin abin da aka bai wa ¡ãrũna!
Kuma idan sun ga dukan ãyã, bã zã su yi ĩmãni da ita ba, kuma idan sun ga hanyar shiriya, bã zã su riƙe ta hanya ba, kuma idan sun ga hanyar ɓata, sai su riƙe ta hanya.
Ya ce: "Yã Ubangijina! Lalle ne nĩ, inã nẽman tsari gare Ka da in tambaye Ka abin da bã ni da wani ilmi a kansa.
Zã su ce: "Na Allah ne."
Suka ce: "Idan ya yi sãta, to, lalle ne wani ɗan'uwansa yã taɓa yin sãta a gabãninsa."
Lalle Mũ ne Muka kasanceMãsu aikãwã.
Kada dũkiyõyinku da ɗiyanku su shagaltar da ku daga ambaton Allah.
Kuma mãtarsa tanã tsaye. Ta yi dãriya.
Ka ce: "Allah," sa'an nan ka bar su a cikin sharhõliyarsu sunã wãsã.
Sa, an nan, su kasance masu shirya gudanar da umurni.
Waɗannan tagogi basu goyon bayan "adana tsarin da ake kai yanzu" sabo da haka ana buƙatan ka sake fara tsarin da hannu nan gaba idan za ka sake shiga.
Kuma ba Mu sanya ma'abũta wutã (wãto matsaranta) ba, fãce malã'iku, kuma ba Mu sanya adadinsu (gõma sha tara) ba, fãce dõmin fitina ga waɗanda suka kãfirta domin waɗanda aka bai wa littãfi su sãmi yaƙĩni kuma waɗanda suka yi ĩmãni su ƙãra ĩmãni, kuma waɗanda aka bai wa littãfi da mũminai bã zã su yi shakka ba, kuma domin wa ɗanda a cikin zukatansu akwai wata cuta da kãfirai su ce: "Mẽ Allah Yake nufi da wannan, ya kasance misãli?"
Kuma lalle ne, haƙĩƙa, Munbai wa Mũsã Littãfi, kuma Mun biyar daga bãyansa da wasu Manzanni, kuma Muka bai wa Ĩsã ɗan Maryama hujjõji bayyanannu, kuma Muka ƙarfafa shi da Rũhi mai tsarki.
Kuma rãnar da ake gittar da waɗanda suka kãfirta a kan wutã, (a ce musu) "Ashe, wannan bã gaskiya ba ne?"
Lalle sũ, sun iske ubanninsu batattu.
Kuma aminci ya tabbata ga Manzanni.
Waɗancan ãyõyinAlƙur'ãni ne da Littãfi mai bayyanawa.
Kuma rãnar da Yake kiran su, sa'an nan Ya ce: "Mẽne nekuka karɓa wa Mananni?"
To, ruwan waɗanda ake yi wa gargaɗi ya mũnana.
Sa'an nan kuma Abin bautawarku Abin bautawa ne Guda, sai ku sallama Masa.
Kuma kada lalle ka ce ga wani abu, "Lalle ni, mai aikatãwa ne ga wancan a gõbe."
Kuma suka yi tsẽre zuwa ga ƙõfa. Sai ta tsãge rigarsa daga bãya, kuma suka iske mijinta a wurin ƙõfar.
Kuma idan kun taimaki jũna a kansa to, lalle Allah Shĩ ne Mataimakinsa, da Jibrĩlu da sãlihan mũminai.
Suka ce: "Kuma mẽne ne a gare mu, ba zã mu yi yãƙi ba, a cikin hanyar Allah, alhãli kuwa, haƙiƙa, an fitar da mu daga gidãjenmu da ɗiyanmu?"
Kõ kana tambayar su wata la'ada ne, sabõda haka sũ, daga wannan tãrar, suke jin an nauyaya musu?
Suka ce: "Ya Sãlihu!
Kuma bã Mu aikãwa da ãyõyi fãce dõmin tsõratarwa.
(Allah) Ya ce "Alãmarka ita ce ba zã ka iya yi wa mutãne magana ba har yini uku face da ishãra.
"Kuma kada ka yi zaton Allah Mai shagalã ne daga abin da azzalumai suke aikatãwã.
Lalle Allah Yanã jiyar da wa'azi ga wanda Ya so, kuma ba ka jiyar da waɗanda suke a cikin kaburbura.
Kuma wanda sikẽlansa suka yi sauƙi, to, waɗannan ne waɗanda suka yi hasarar rayukansu, sabõda abin da suka kasance, da ãyõyinMu, sunã yi na zãlunci.
Kuma Wanda Ya saukar da ruwa daga sama, a kan wani gwargwado, sai Muka rãyar da gari matacce game da shi.
Kuma Yahudu suka ce: "Hannun Allah abin yi wa ƙuƙumi ne. "
Sa'an nan kuma idan ka yi niyyar zartarwa, to, ka dõgara ga Allah, lalle ne, Allah Yana son mãsu tawakkali.
Kwanuka ƙidãyayyu.
Shĩ ne wanda Ya halitta ku. Sa'an nan daga gare ku akwai kãfiri kuma daga gare ku akwai mũmini.
To, la'anar Allah ta tabbata a kan azzãlumai."
Waɗanda suka kãfirta sun riya cẽwa bã zã a tãyar da su ba. Ka ce: "Ni, inã rantsuwa da Ubangijĩna.
"Kuma wani dalĩli bai kasance ba gare mu a kanku. Ã'a, kun kasance mutãne ne mãsu kẽtare iyãka."
Waɗannan sunã da gidãjen Aljannar zama, ƙõramu na gudãna daga ƙarƙashinsu, anã sanya musu ƙawa, a cikinsu, daga mundãye na zinariya, kuma sunã tufantar waɗansu tũfãfi kõre, na alharĩni raƙĩƙi da alharini mai kauri sunã kishingiɗe a cikinsu, a kan, karagu. Mãdalla da sakamakonsu.
Kuma Allah ne, ga abin da kuke aikatãwa, Mai gani.
Kuma ku yi ɗã'a ga Allah da ManzonSa, kuma kada ku yi jãyayya har ku raunana kuma iskarku ta tafi, kuma ku yi haƙuri.
Ka ce: "Saninta yanã wurin Allah kawai." Kuma me yã sanar da kai cẽwa anã tsammãnin sa'a ta kasance kusa?
Ya ce: "Lalle ne, Shi, Yana cewa: "Lalle ne ita sãniya ce; bã tsõfuwa ba, bã kuma budurwa ba, tsakãtsaki ce a tsakãnin wancan,' sai ku aikata abin da ake umurninku."
To, akwai tsammãnin waɗannan su kasance daga shiryayyu.
Kuma wanda ya yi shirki da Allah, to, lalle ne ya ɓace ɓata mai nĩsa.
Lalle ne, Allah, Mai ƙididdigewa ne ga abin da suke sanã'antãwa.
"Yã mutãnenmu!
"Kuma inã mai gaskatãwa ga abin da yake a gabãnina daga Taurata. Kuma (nãzo) dõmin in halatta muku sãshen abin da aka haramta muku.
Kuma idan aka ce musu: "Ku bi abin da Allah Ya saukar," sai su ce: Ã'a, muna bin abin da muka iske ubanninmu a kansa." Shin, kuma kõ dã ubanninsu bã su hankaltar kõme, kuma bã su shiryuwa?
Wani marmaro ne, a cikinta, ana kiran sa salsabil.
An wajabta yãƙi a kanku, alhãli kuwa shi abin ƙi ne a gare ku, akwai fãtar cẽwa ku ƙi wani abu, alhãli shi ne mafi alhẽri a gare ku, kumaakwai fãtar cẽwa kuna son wani abu alhãli kuwa shi ne mafi sharri a gare ku.
Wanda zai shiga wutar da tã fi girma.
Shirin Hana Haske
Kuma mazan aurensu su ne mafiya haƙƙi ga mayar da su a cikin wancan, idan sun yi nufin gyãrawa.
Sabõda haka ku bauta Masa kuma ku dõgara a kanSa. Kuma Ubangijinka bai zama Mai gafala daga abin da kuke aikatãwa ba.
Har a lõkacin da suka je a kan rãfin turũruwa wata turũruwa ta ce, "Yã kũ jama'ar turũruwa! Ku shiga gidãjenku, kada Sulaimãn da rundunõninsa su kakkarya ku, alhãli kuwa sũ, ba su sani ba."
Ka bã ni (abõkin zama) daga sãlihan mutãne."
Kuma lalle bãbu kõwa fãce waɗanda ake halartarwa ne a wurinMu.
Kuma dã na kasance inã sanin gaibi, dã lalle ne, nã yawaita daga alhẽri kuma cũta bã zã ta shãfe ni ba, nĩ ban zama ba fĩce mai gargaɗi, kumamai bãyar da bishãra ga mutãne waɗanda suke yin ĩmãni."
To, amma Ãdãwa, sai suka yi girman kai a cikin kasã, bã da wani hakki ba, suka ce: "Wãne ne mafi tsananin ƙarfi daga gare mu?"
Kõ kuma sun riƙi waninSa majiɓinta?
To a lõkacin da ya fãɗi, sai aljannu suka bayyana (ga mutãne) cẽwa dã sun kasance sun san gaibi, dã ba su zauna ba a cikin azãba mai wulãkantarwa.
Kuma ba Mu halicci sammai da ƙasa da abin da yake a tsakãninsu ba fãce da gaskiya.
Kuma kalmar "Ubangijinka" Lalle ne zã Ni cika Jahannama da aljannu da mutãne gaba ɗaya" ta cika.
Suna ĩmãni da Allah da Yinin Lãhira, kuma suna umurui da abin da aka sani kuma suna hani daga abin da ba a sani ba, kuma sunã gaugãwa a cikin alhẽrai.
Kuma dã Mun sassaukar da wani littãfi, zuwa gare ka, a cikin takarda, sa'an nan suka taɓa shi da hannuwansu, lalle dã waɗanda suka kãfirta sun ce: "Wannan bai zama ba, face sihiri bayyananne."
To, a lõkacin da ãyõyinMu suka jẽ musu, sunã mãsu wãyar da kai suka ce wannan sihiri ne bayyananne.
Lalle NĨ Mai karɓar ranka ne, kuma Mai ɗauke ka ne zuwa gare Ni, kuma Mai tsarkake ka daga waɗanda suka kãfirta, kuma Mai sanya waɗanda suka bĩ ka a bisa waɗanda suka kãfirta har Rãnar ¡iyãma.
Kuma dukan kõme Mun bayyana shi daki-dakin bayyanãwa.
Waɗannan ne abũbuwanshirkarmu waɗanda muka kasance munã kira baicinKa".
Kuma suka mayar da malã'iku ('yã'ya) mãtã, alhãli kuwa sũ, waɗanda suke bãyin (Allah) Mai rahama ne!
Da Lũɗu, a lõkacin daya ce wa mutãnensa, "Lalle kũ, haƙĩƙa kunã jẽ wa alfãsha wadda wani mahalũƙi daga cikin dũniya bai riga ku gare ta ba.
Kuma Allah Yã saukar da ruwa daga sama, sa'an nan Ya rãyar da ƙasa da shi a bãyan mutuwarta.
"Kuma Ka sanya mini wani mataimaki daga mutãnena."
Sai suka ƙaryata shi, sabõda haka tsãwa ta kãmã su, dõmin haka suka wãyi gari sunã guggurfãne.
Kuma ka ce: "Lalle nĩ nĩ ne mai gargaɗi bayyananne."
Ka ce: "Idan kun ɓõye abin da ke a cikin ƙirãzanku, kõ kuwa kun bayyana shi, Allah Yana sanin sa.
Shin fa, wanda Allah Ya buɗa ƙirjinsa, dõmin Musulunci sa'an nan shi yanã a kan haske daga Ubangijinsa, (zai zama kamar waninsa)?
"Fãce mãtarsa mun ƙaddara cẽwa lalle ne ita, haƙĩƙa, tanã daga mãsu halaka."
Kuma Shi ne abin gõdiya a cikin ta farko (dũniya), da ta ƙarshe (Lãhira). Kuma Shi ne da hukunci, kuma zuwa gare Shi ake mayar da ku.
Ko kun yi zaton ku shiga Aljanna alhãli kuwa Allah bai bãda sanin waɗanda suka yĩ jihãdi daga gare ku ba, kuma Ya san mãsu haƙuri?
"Kuma lalle nĩ na nẽmi tsari da Ubangijĩna, kuma Ubangijinku, dõmin kada ku jẽfe ni."
"Yã abõkaina biyu na kurkuku!
Sa'an nan a ce musu, "Ina abin da kuka kasance kunã shirki da shi"
Sai su motsar da ƙũra game da shi.
Kuma gõdiya ta tabbata ga Allah Ubangijin halittu.
Kuma abin da kuka ciyar daga ciyarwa, kõ kuka cika alwãshi daga wani bãkance, to, lalle ne, Allah Yana sanin sa.
Kuma kada ku auri abin da ubanninku suka aura daga mãtã, fãce abin da ya shige.
Kuma Yana sanin abin da ke a cikin sammai da ƙasa. Kuma Allah a kan kõwane abu Mai ĩkon yi ne."
Kuma lalle ne, haƙĩƙa, Ya yãfe muku laifinku. Kuma Allah Ma'abucin falala ne ga mũminai.
Ku nũna mini, mẽne ne suka halitta daga ƙasã? Kõ sunã da tãrayya ne a cikin sammai?
Lalle Shĩ, Masani ne ga abin da yake a ainihin zukata.
"Lalle dã mun kasance bãyin Allah waɗanda aka tsarkake."
Kuma a cikin ƙasã akwai ãyõyi ga mãsu yaƙĩni.
Kuma (suka yi niyya), bã su kõ tõgẽwa.
Ranar da zã a kuranye ƙwabri, kuma a kira su zuwa ga yin sujũda, sai bã zã su iyãwa ba.
To, shin, akwai wata hanya zuwa ga fita?"
Ya Mahaliccin sammai da ƙasa!
Sai ku daidaitu zuwa gare Shi, kuma ku nẽmi gafararSa."
Ka ce: "Ya kũ Mutãnen Littãfi!
Lalle ne ni, idan (nã yi haka) dã ina daga cikin azzalumai."
A yanzu! Alhãli kuwa, haƙĩƙa ka sãɓa a gabãni, kuma ka kasance daga mãsu ɓarna?
Ka ce: "Sũ, dõmin waɗanda suka yi ĩmani suke a cikin rãyuwar dũniya, suna keɓantattu a Rãnar Kiyãma.
Kuma idan waɗanda suka kãfirta suka gan ka, bã su riƙon ka fãce da izgili (sunã cẽwa), "Shin, wannan ne ke ambatar gumãkanku?"
Kada ku riƙi Yahudu da Nasãra majiɓinta. Sãshensu majiɓinci ne ga sãshe.
Sai ka yi hakuri da hukuncin Ubangijinka, lalle kai fa kanã idãnunMu, kuma ka tsarkake Ubangijinka da (tasbĩhi) game da gõde Masa a lõkacin da kake tãshi tsaye (dõmin salla kõ wani abu).
Lalle Shi ne Mabuwãyi, Mai hikima.
Ḥ.
Waɗannan su ne mafi ashararancin tãlikai.
Kuma Allah Yã kasance a kan dukkan kõme Mai lissãfi.
Shin, wanda ya kasance a kan hujja bayyananna daga Ubangijinsa, kuma wata shaida tanã biyar sa daga gare Shi, kuma a gabãninsa akwai littãfin Mũsãabin kõyi da rahama? Waɗannan sunã yin ĩmãni da shi, kuma wanda ya kãfirta da shi daga ƙungiyõyi, to, wutã ce makõmarsa.
Sunã la'anannu, inda duka aka sãme su a kãmã su, kuma a karkashe su karkashẽwa.
Dã dai lalle su sun kasance snnã shiryuwa!
Sai Shaiɗan ya mantar da shi tunãwar Ubangijinsa, sabõda haka ya zauna a cikin kurkuku 'yan shekaru.
Ka ce: "Idan nĩ (Nũhu) na ƙirƙira shi to, laifĩnã a kaina yake, kuma nĩ mai barrantã ne daga abin da kuke yi na laifi."
Shĩ ne da mulkin abin da ke a gaba gare mu da abin da ke a bãyanmu da abin da ke a tsakãnin wannan." Kuma (Ubangijinka bai kasance wanda ake mantãwa ba.
Lalle ne, haƙĩƙa, nã iyar muku damanzancin Ubangijina. Kuma nã yi muku nasĩha kuma amma bã ku son mãsu nasĩha!"
Ka ce: "Allah".
Ka ce: "Lalle mutãnen farko da na ƙarshe."
"Zã su zõ maka da dukkan mai yawan sihiri masani."
Kõ kanã tambayar su wani harãji ne (a kan iyar da Manzanci a gare su)?
Kuma da Mun sanya shi abin karãtu na ajamanci, lalle dã sun ce, "Don me ba a bayyana ãyõyinsa ba?
Har ya kasance gwargwadon zirã'i biyu, kõ kuma abin da ya fi kusa.
Dã ka lẽka (a kan) su (dã) lalle ne, ka jũya daga gare su a guje kuma (dã) lalle ne ka cika da tsõro daga gare su.
Kuma har idan ya san wani abu daga ãyõyinMu, sai ya rika su da izgili.
Lalle ne, wannan wata tunãtarwa ce, sai dai wanda ya so, ya kãma hanyar ƙwarai zuwa ga Ubangijinsa.
Lalle ne, mãsu taƙawã nã da wani wurin sãmun babban rabo.
Lalle ne mafi hakkin mutãne da Ibrãhĩma haƙĩƙa, sũ ne waɗanda suka bi shi a (zamaninsa) da wannan Annabi (Muhammadu) da waɗanda suka yi ĩmãni. Kuma Allah ne Majiɓincin mũminai.
"Fãce ga wanda Yã yarda da shi, wato wani manzo sa'an nan lalle ne, zai sanya gãdi a gaba gare shi da bãya gare shi."
Kuma suna tambayar ka daga jirajiran wata.
Kuma a rãnar da Muke tãyar da mai shaida daga kõwace al'umma, sa'an nan kuma bã zã a yi izni ba ga waɗanda suka kãfirta, kuma ba su zama ana nẽman kõmawarsu ba.
Kada ku shiga ta ƙõfa guda, ku shiga ta ƙõfõfi dabam-dabam, kuma bã na wadãtar muku kõme daga Allah.
Lalle waɗanda ke jãyayya a cikin ãyõyin Allah, bã game da wani dalĩli wanda ya jẽ musu ba, bãbu kõme a cikin kirãzansu, fãce girman kai, ba su zama mãsu isa ga gũrinsu ba, sabõda haka ka nẽmi tsari daga Allah.
Kamar wancan ne Allah Yake rufẽwa a kan zukãtan kãfirai.
Kuma wanda ya girmama ibãdõdin Allah, to, lalle ne ita (girmamãwar) tanã daga ayyukan zukãta na ibãda.
Lalle ne mutum an halitta shi mai ciwon kwaɗayi.
Ka ce: "Wãne ne yake azurta ku daga sama da ƙasa?"
Lalle ne Allah Yanã da mulkin sammai da ƙasa, Yanã rãyarwa kuma Yanã matarwa. Kuma bã ku da wani masõyi, kuma bã ku da mataimaki, baicin Allah.
"Kuma lalle ne mũ, akwai sãlaihai a cikinmu, kuma akwai a cikinmu waɗanda ba haka bã mun kasance ƙungiyõyi dabam-dabam."
Idan mãtã mũminai suka zo maka sunã yi maka mubãya'a a kan bã zã su yi shirki da Allah ba ga kõme, kuma bã su yin sãtã, kuma bã su yin zina, kuma bã su kashe, ya'yansu, kuma bã su zuwa da ƙarya da suke ƙirƙirãwa a tsãkanin hannuwansu da ƙafãfunsu kuma bã su sãɓa maka ga wani abu da aka sani na sharĩ'a, to, ka karɓi mubãya'arsu, kuma ka nẽmi Allah Ya gãfarta musu.
(Sai kuwa) ya ce: "Yã Maryamu! Daga ina wannan yake gare ki?"
A'aha!
Rãnar da mutãne za su kasance kamar 'ya'yan fari mãsu wãtsuwa.
Kuma kada idãnunka su jũya daga barinsu, kanã nufin ƙawar rãyuwar dũniya. Kuma kada ka biwanda Muka shagaltar da zũciyarsa daga hukuncinMu, kuma ya bi son zuciyarsa, alhãli kuwa al'amarinsa ya kasance yin ɓarna.
Bã a rõƙon Allah sai da sunãyensa mãsu kyau, tis'in da taran nan, sai dai a dunƙule kamar a ce, "Inã rõƙon Allah da sunãyenSa da na sani da waɗanda ban sani ba." Lalle nĩ, na zãlunci kaina, kuma nã sallama al'amari tãre da Sulaiman ga Allah, Ubangijin halittu."
Kuma idan kun kasance a cikin shakka daga abin da Muka sassaukar ga Bãwanmu, to, ku zõ da sũra guda daga misalinsa (Alƙur'ãni). Kuma ku kirãwo shaidunku baicin Allah, idan kun kasance mãsu gaskiya.
Shin fa, da ni'imar Allah suke musu?
To, ka bãyar da bushãra ga bãyiNa.
Kõ kuma sun riƙi waninSa majiɓinta?
Kuma wanda ya tsarkake, to, yanã tsarkaka ne dõmin kansa. Kuma zuwa ga Allah kawai makõma take.
Lalle ne haƙĩƙa waɗanda suka ce: "Lalle ne Allah, shĩne Masĩhu, ɗan Maryama," sun kãfirta. Alhãli kuwa Masĩhu yã ce: "Yã Banĩ Isrã'ĩla!
Tsarki ya tabbata a gare Ka, wannan ƙiren ƙarya ne mai girma"?
Lalle ne Allah, haƙĩƙa, Mai gãfara ne, Mai jin ƙai.
Kuma suna tambayar ka game da haila Ka ce: Shi cũta ne.
Shin kuma a lõkacin da wata masĩfa, haƙĩƙa, ta sãme ku alhãli kuwa kun sãmar da biyunta, kun ce: "Daga ina wannan yake?"
Lalle, mũ (ba mu yanke ƙauna ba) zuwa ga Ubangijinmu, mãsu kwaɗayi ne."
"Sa'an nan lalle ne, na yi yẽkuwa sabõda su, kuma na gãna da su a cikin asĩri."
Kuma Ubangiwinka, bã Mai zãlunci ga bãyinSa ne ba.
To, waɗannan makõmarsu Jahannama ce.
Kayya! Lalle ne ita kalma ce, shĩ ne mafaɗinta, alhãli kuwa a bãya gare su akwai wani shãmaki har rãnar da zã a tãyar da su.
Kada ku kusanci dũkiyar marãya fãce da wadda take ita ce mafi kyau, har ya kai ga ƙarfinsa.
Kuma kada lalle ka ce ga wani abu, "Lalle ni, mai aikatãwa ne ga wancan a gõbe."
Ba ta zama ba fãce fitinarKa Kanã ɓatarwa, da ita, wanda Kake so kuma kanã shiryarwa da ita, wanda Kake so; Kai ne Majiɓincinmu.
"Shin, zan riƙi waninSa abũbuwan bautãwa?
Kuma a lõkacin da Ĩsã ɗan Maryayama ya ce: "Yã BanĩIsrã'ĩla! Lalle nĩ Manzon Allah ne zuwa gare ku, mai gaskata abin da ke gaba gare ni na Attaura, kuma mai bãyar da bushãra da wani Manzo da ke zuwa a bãyãna, SũnasaAhmad (Mashãyabo)."
Gõdiya ta tabbata ga Allah (a kan bayãni). Ã'a, mafi yawan mutãne ba su sani ba.
Inã rantsuwa da taurãron, a lõkacin da ya faku.
Kuma suka sanya wa Allah kĩshiyõyi, dõmin ɓatarwa daga hanyarSa, Ka ce: "Ku ji dãɗi, sa'an nan, lalle ne, makõmarku Wutar ce."
Ka ce: "Tir da abin da ĩmãninku yake umurnin ku da shi, har idan kun kasance mãsu ĩmãni!"
Kuma mafi yawansu bã su biyar kõme fãce zato. Lalle ne zato bã ya wadãtar da kõme daga gaskiya.
Kuma suna tambayar ka game da marãyu.
Allah Ya sassaukar da mafi kyaun lãbãri, Littãfi mai kama da jũna, wanda ake konkoma karãtunsa fãtun waɗanda ke tsõron Ubangijinsu, sunã tãƙura sabõda Shi, sa'an nan fãtunsu da zukãtansu su yi laushi zuwa ga ambaton Allah.
Ubangijinmu Yã yalwaci dukan kõme ga ilmi.
Bãbu abin da suke yi fãce yanki-faɗi.
Kuma Allah Mai falala ne Mai girma.
Kuma ka nẽmi gãfara ga zunubinka, kuma ka yi tasbĩhi game da gõde wa Ubangijinka, maraice da kuma wãyẽwar sãfiya.
"Kuma ka tsakaita a tafiyarka, kuma ka runtse ga sautinka. Lalle mafi mũnin sautuka haƙĩƙa shĩ ne sautin jãkuna. "
Kada ku kasance kamar waɗanda suka cũci Mũsã sa'an nan Allah Ya barrantar da shi daga abin da suka ce.
Ya Ibrãhĩm!
Lalle Shĩ, Shĩ ne Mai ji, Masani.
Kamar wannan ne Allah Yake bayyana wa mutãne misãlansu.
Waɗannan 'yan wutã ne. Sũ, mãsu dawwama ne a cikinta.
Shin fa, waɗanda suka kãfirta sun yi zaton (daidai ne) su riƙi waɗansu bãyĩNa, majiɓinta baiciNa?
Kõ sunã da idãnu da suke gani da su?
Ka ce: "Abin sani kawai, saninta a wurin Allah yake, kuma amma mafi yawan mutãne bã su sani."
Lalle ne Mũ, Mun yi tattali dõmin azzãlumai wata wuta wadda shãmakunta, sun ƙẽwaye da su.
Dõmin haka kawai Muka sauƙaƙar da shi (Alƙur'ãni) da harshenka, tsammãninsu, su riƙa tunãwa.
Waɗanda suke ambatar Allah a tsaye da zaune da a kan sãsanninsu, kuma suna tunãni a kan halittar sammai da ƙasa: "Yã Ubangijinmu! Ba Ka halitta wannan a kan banza ba.
Waccan falalar Allah ce, Yanã bãyar da ita ga wanda Yake so. Kuma Allah Mayalwaci ne, Mai ilmi.
Lalle Ubangijĩna Mai Jin ƙai ne, Mai nũna sõyayya."
Ka ce: "Ku yi ĩmãni da Shi, ko kuwa kada ku yi ĩmãni, lalle ne waɗanda aka bai wa ilmi daga gabãninsa, idan anã karãtunsa a kansu, sunã fãɗuwa ga haɓõɓinsu, sunã mãsu sujada."
To, daga cikin mutãne akwai wanda yake cẽwa: "Ya Ubangjinmu!
Wancan ne abin gargaɗi ga wanda ya ji tsõron matsayiNa, kuma ya ji tsõron ƙyacẽwãTa.
"Sai muka yi nufin Ubangijinsu Ya musanya musu mafi alhẽri daga gare shi ga tsarkakuwa, kuma mafi kusantar tausayi."
Kã yalwaci dukan kõme da rahama da ilmi to Ka yi gãfara ga waɗanda suka tũba kuma suka bi hanyarKa, kuma Ka tsare musu azãbar Jahĩm."
"Sai ku gaya masa magana mai laushi, tsammãninsa yanã tunãwa kõ kuwa ya ji tsõro."
" Yanã son ya fitar da ku daga ƙasarku: To, mẽne ne kuke shawartawa?"
Yã kũ waɗanda suka yi ĩmani! Kada ku ce: 'Rã'inã' kuma ku ce: 'Jinkirtã manã', kuma ku saurara.
Dã Yana bin ku ga (hãlãye) mãsu Yawa na al'amarin, dã kun auku a cikin zunubi, kuma amma Allah Yã sõyar da ĩmãni a gare ku, kuma Yã ƙawãta shi a cikin zukãtanku kuma Yã ƙyãmantar da kãfirci da fãsicci da sãɓo zuwa gare ku.
Idan Yã hukunta wani al'amari sai kawai Ya ce masa, "Kasance." Sai ya dinga kasan cẽwa.
Ya ce wa ubansa da mutanensa, "Mẽne ne waɗannan mutummutumai waɗanda kuke mãsu lazimta a kansu?"
Lalle ne waɗanda suka yi ĩmãni, da waɗanda suka tũba, da Nasãra da Makarkata, wana ya yi ĩmani da Allah da Yinin Lãhira, kuma ya aikata aikin ƙwarai, to, suna da ijãrarsu a wurin Ubangijinsu, kuma bãbu tsõro a kansu, kuma ba su zama suna yin baƙin ciki ba.
Lalle ne waɗanda suka kãfirta, sunã ciyar da dũkiyõyinsu, dõmin su kange daga hanyar Allah; to, zã a su ciyar da ita, sa' an nan kuma ta kasance nadãma a kansu, sa'an nan kuma a rinjãye su.
Ka ce: "Lalle ne Allah Mai ĩko ne a kan Yasaukar da ãyã, kuma amma mafi yawansu, ba su sani ba."
Wannan bai zama ba fãce ƙiren ƙarya."
"Ko kuma (kada) ya ce: 'Da Allah Ya shiryar da ni, dã na kasance daga mãsu taƙawa.'"
Sa'an nan kuma Muka musanya mai kyau a matsayin mummũna, har su yi yawa, kuma su ce: "Cũta da azãba sun shãfi ubanninmu." (sai su kõma wa kãfirci).
To, wãne ne mafi zãlunci daga wanda ya ƙãga ƙarya ga Allah?"
Bã ya kasancẽwa ga Allah Ya riƙi wani ɗã.
Waɗancan manzannin Mun fĩfĩta sãshensu a kan sãshe: Daga cikinsu akwai wanda Allah Ya yi masa magana; kuma Ya ɗaukaka sãshensu da darajõji; kuma Muka bai wa Ĩsã dan Maryama hujjõji bayyanannu, kuma Muka ƙarfafã shi da Rũhi mai tsarki.
Kuma lalle, abin da yake akwai tsãwatarwa a cikinsa na lãbãraiya zo musu.
Mũ ne mafi sani game da abin da suke faɗi, kuma bã zã ka zama mai tĩlasta su ba.
Kuma Ubangijinka Ya zo, alhãli malã'iku na jẽre, safũ- safu.
Zã su ce: "Na Allah ne."
Kuma bã dõmin kalmar hukunci ba, da lalle, an yi hukunci a tsakãninsu.
Sunã yi maka fatawa.
Bãbu abin bautãwa, fãce Shi. Shĩ ne Ubangijin Al'arshi, mai daraja.
Kuma Allah Ya kasance Mai yawan ĩkon yi ne a kan dukan kõme.
Allah Yanã nufin Ya bayyana muku, kuma Ya shiryar da ku hanyõyin waɗanda suke a gabãninku kuma Ya karɓi tũbarku.
Shin, kun gani idan na kasance a kan wata hujja bayyananna daga Ubangijina, kuma Yã bã ni wata Rahama daga wurinSa, Sa'an nan aka rufe ta (ita Rahamar) daga gare ku, shin, zã mu tĩlasta mukuita, alhãli kuwa kũ mãsu ƙi gare ta ne?
Da waɗannan sabõda azãbar Ubangijinsu, suna jin tsõro.
(Wanda Ya saukar da Alƙur'ani) Shi ne Allah, wanda bãbu wani abin bautãwa fãce Shi Masanin fake da bayyane, Shĩ ne Mai rahama, Mai jin ƙai.
Kuma abin da kuka ciyar daga alhẽri, to, lalle Allah gare shi Masani ne.
Kõwane mutum daga gare su na da sakamakon abin da ya sanã'anta na zunubi, kuma wanda ya jiɓinci girmansa, daga gare su, yanã da azãba mai girma.
"In dã dai ita, tã kasance mai halakã ni gabã ɗaya ce!
Kuma sukace: "Waɗannan dabbõbi da shũka hanannu ne; bãbu mai ɗanɗanar su fãce wanda muke so," ga riyãwarsu. Da wasu dabbõbi an hana bãyayyakinsu, da wasu dabbõbi bã su ambatar sũnan Allah a kansu, bisa ƙirƙiren ƙarya gare Shi.
Kuma ba Mu sanya su jiki, bã su cin abin ci ba, kuma ba su kasance madawwama ba.
Ya shar'anta muku, game da addini, abin da Ya yi wasiyya da shi ga Nũhu da abin da Muka yi wahayi da shi zuwa gare ka, da abin da Muka yi wasiyya da shi ga Ibrãhĩm da Mũsã da Ĩsã, cẽwa ku tsayar da addini sõsai kuma kada ku rarrabu a cikinsa. Abin da kuke kira zuwa gare shi, ya yi nauyi a kan mãsu shirki.
Kuma a lõkacin da Allah Yake yi muku alkawari da ɗayan ƙungiya biyu, cẽwa lalle ita tãku ce: kuma kunã gũrin cẽwa lalle ƙungiya wadda bã ta da ƙaya ta kasance gare ku, kuma Allah Yanã nufin Ya tabbatar da gaskiya da kalmõminSa, kuma Ya kãtse ƙarshen kãfirai;
To, wanda ya yi ĩmãni kuma yagyãra aiki, to, babu tsõro a kansu, kuma ba su yin baƙin ciki.
Shin, ba su kasance sun gan ta ba?
Waɗanda suke jiran dãko game da ku; har idan wata nasara daga Allah ta kasance a gare ku, sai su ce: "Ashe, ba mu kasance tãre da kũ ba?"
Kuma idan sun ga kõwace ãyã bã zã su yi ĩmãni da ita ba har idan sunjẽ maka sunã jãyayya da kai, waɗanda suka kãfirta sunã cẽwa: "Wannan bai zama ba fãce tãtsũniyõyin mutãnen farko."
Kuma suka ce: "Mẽne ne ga wannan Manzo, yanã cin abinci, kuma yanã tafiya a cikin kãsuwanni!
Kuma Muka ƙẽtarar da Banĩ Isra'ila ga tẽku, sai suka jẽ a kan wasu mutãne waɗanda sunã lizimta da ibãda a kan wasu gumãka, nãsu suka ce: "Yã Mũsã!
Kuma a lõkacin da Mũsã ya ce wa mutãnensa: "Yã mutãnena! sabõda me kuke cũtar da ni, alhãli kuwa lalle kun sani cẽwa lalle nĩ Manzon Al1ah ne zuwa gare ku?"
Kuma kuna tsammãni, daga Allah, abin da bã su tsammãni. Kuma Allah Yã kasance Masani Mai hikima.
Waɗancan ne waɗanda suka kãfirta da ãyõyin Ubangijinsu, da kuma haɗuwa da Shi, sai ayyukansu suka ɓãci.
Sunã da wata hargõwa a cikinta, alhãli kuwa sũ, a cikinta, bã su saurãren kõme.
Kuma ka tsai da salla a gẽfe guda biyu na yini da wani yanki daga dare.
Kuma haƙĩƙa Mun aika Nũhu zuwa ga mutanensa, (ya ce): "Lalle ne ni, a gare ku mai gargaɗi bayyananne ne."
Sai suka kira abokinsu, sai ya karɓa, sa'an nan ya sõke ta,
"Kuma ka jẽfa sandarka."
To, kõ dai lalle Mu nũna maka sãshen abin da Muka yi musu wa'adi da shi kõ kuwa lalle Mu karɓi ranka, to, zuwa gare Mu ake mayar da su.
Wannan dõmin lalle ne su, mutãne ne (waɗanda) bã su hankalta.
Allah ne, da abin da yake a cikin sammai da abin da yake a cikin ƙasa, kuma idan kun bayyana abin da yake a cikin zukatanku (na shaida), ko kuka ɓõye shi, Allah zai bincike ku da shi, sa'an nan Ya yi gãfara ga wanda Yake so, kuma Ya azabta wanda Yake so.
Sabõda haka kada jũyãwarsu a cikin garũruwa ta rũɗe ka
Wannan maɓalli na ƙayyade yawan sakan da za'a nuna ko wacca firam.
Ya ce: "AzãbaTa Inã sãmu, da ita, wanda Nike so, kuma rahamaTa, ta yalwaci dukan kõme. Sa'an nan zã Ni rubũta ta ga waɗanda suke yin taƙawa, kuma sunã bãyar da zakka, da waɗanda suke, game da ãyõyinMu mũminai ne."
Kuma a lõkacin da ya isa mashãyar Madyana, ya sãmi wata jam'ar mutãne sunã shãyarwa, kuma a bãyansu ya sãmi waɗansu mãtã biyu sunã kõrar (tumãkinsu).
Waɗanda suka ce wa 'yan'uwansu kuma suka zauna abinsu: "Dã sun yi mana ɗã'a, dã ba a kashe su ba."
Kuma ku nẽmi gãfara gun Ubangijinku. Sa'an nan ku tũba zuwa gare Shi, Ya jiyar da ku dãɗi, jiyarwa mai kyau zuwa ga ajali ambatacce, kuma Ya bai wa dukkan ma'abucin, girma girmansa.
Kuma a lõkacin da waɗanda suka kãfirta sukẽ yin mãkirci game da kai, dõmin su tabbatar da kai, kõ kuwa su kashe ka, kõ kuwa su fitar da kai, sunã mãkirci kuma Allah Yanã mayar musa da mãkirci kuma Allah ne Mafificin mãsu mãkirci.
Lalle ne, Allah Yanã yin faɗa sabõda waɗanda suka yi ĩmãni.
"Kuma yã mutãnena! Bã zan tambaye ku wata dũkiya ba akansa, ijãrata ba ta zama ba, fãce daga Allah, kuma ban zama mai kõrar waɗanda suka yĩ ĩmãni ba.
Lalle ne Safã da Marwa suna daga wurãren ibãdar Allah, to, wanda ya yi hajin ¦ãki kõ kuwa ya yi Umra, to, bãbu laifi a kansa ga ya yi ɗawãfi gare su, su biyu.
Sa'an nan a ce: "Wannan shi ne abin da kuka kasance kuna ƙaryatãwa game da shi."
Lalle Allah Mai tausasawa ne, Mai ƙididdigewa.
Fãce dai duk wanda ya jũya bãya, kuma ya kãfirta.
Lalle ne, Mun bayyana ãyõyi ga mutãne masu sakankancewa.
To, lalle ne zan kakkãtse hannayenku da ƙafãfunku a tarnaƙi kuma lalle zan tsĩre ku a cikin kututturan itãcen dabĩno, kuma lalle zã ku sani wanenmu ne mafi tsananin azãba kuma wãne ne mafi wanzuwar (azãba)."
Lalle mafĩfĩcinku daraja a wurin Allah, (shĩ ne) wanda yake mafĩfĩcinku a taƙawa.
Yana gaya wa Metaciti yanda yakamata ya aiwatar da indiketa wanda ana gani, mai nuna cewa an danna ƙararrawar na'ura ko kuma an danna wata indiketa na shirin ayuka 'ƙararrawa' daban. A yanzu, akwai kima guda biyu masu inganci, "cikakkenfuska", mai jawo wata filash mai fari-baƙi ga cikakken fuska, da kuma "filash na_firam" da ke sa layin sunan shirin ayuka, wanda ya aika da alamar ƙararrawa ya yi filash. Idan ba'a san da shirin ayuka wanda ya aika da ƙararrawar ba (yawanci matsalar da ke shafi difwalt "ƙarar na'ura"), layin sunan taga da aka zura wa ido a lokacin zai yi filash.
Ka ce: "Wãne ne ya saukar da Littãfi wanda Mũsã ya zo da shi, yanã haske da shiriya ga mutãne, kunã sanya shi takardu, kũna bayyana su, kuma kunã ɓõye mai yawa, kuma an sanar da ku abin da ba ku sani ba, ku da ubanninku?"
Suka ce: "Ashe ƙasar Allah ba ta kasance mayalwaciya ba, dõmin ku yi hijira a cikinta?"
Sunã tambayar ka ga rũhi.
Ya ce: "Shu'umcinku a wurin Allah yake.
"Wannan ita ce Jahannama wadda kuka kasance anã yi muku wa'adi da ita."
Kuma ãƙiba mai kyau tanã ga taƙawa.
Lalle ne Mun kasance Mãsu aikatãwa.
Yã wanda ya lulluɓa da mayãfi.
Ka ce: "Ashe fa, kun riƙi waɗansu masõya baicin Shi, waɗanda ba su mallaka wa kansu wani amfãni ba kuma haka bã su tũre wata cũta?"
Kada dũkiyõyinku da ɗiyanku su shagaltar da ku daga ambaton Allah. Kuma wanda ya yi haka, to, waɗannan sũ ne mãsu hasãra.
Lalle ne kanã daga mãsu ƙasƙanci."
Abin sani kawai sakamakon waɗanda suke Yãƙin Allah da Manzonsa, kuma sunã aiki a cikin ƙasa dõmin ɓarna a kashe su ko kuwa a ƙere su, kõ kuwa a kakkãtse hannuwansu da ƙafãfunsu daga sãɓãni, ko kuwa a kõre su daga ƙasa.
Lalle ne, hãƙĩƙa, kõme yã yanyanke a tsakãninku, kuma abin da kuka kasance kunã riyãwa ya ɓace daga gare ku.
Lalle ne mũ mãsu jũyãwa ne zuwa ga Ubangijinmu."
"Kuma ku mayar da al'amari zuwa ga Ubangijinku, kuma ku sallama Masa, a gabãnin azãba ta zo muku, sa'an nan kuwa bã zã a taimake ku ba."
Kuma dã dai su lalle sun yarda da abin da Allah Ya bã su, da ManzonSa kuma suka ce: "Ma'ishinmu Allah ne, zai kãwo mana daga falalarSa kuma ManzõnSa (zai bã mu). Lalle ne mũ, zuwa ga Allah mãsu kwaɗayi ne."
Ku bi Allah da taƙawa, kuma ku nemi tsari zuwa gare shi, kuma ku yi jihãdi a cikin hanyarsa, tsammãninku, za ku ci nasara.
Shi (Al-ƙur'ãni) bai zama ba fãce tunãtarwa ce, da abin karãtu bayyananne.
Waɗanda suka kãfirta kuma suka kange mutãne daga tafarkin Allah, (Allah) Ya ɓatar da ayyukansu.
"Ashe, lalle kũ kunã je wa maza, kuma ku yi fashin hanya kuma ku je, a cikin majalisarku da abin da bã shi da kyau?
Kada ku kãwo wani uzuri a yau.
Kuma idan aka ce musu: "Ku bi abin da Allah Ya saukar," sai su ce: Ã'a, muna bin abin da muka iske ubanninmu a kansa."
Ka ce: "Allah kuma lalle mũ kõ ku, wani yanã a kan shiriya, kõ yana a cikin ɓata bayyananniya."
Kada mũminai su riƙi kãfirai masõya, baicin mũminai. Kuma wanda ya yi wannan, to, bai zama a cikin kõme ba daga Allah, fãce fa dõmin ku yi tsaro daga gare su da 'yar kãriya.
Ba su faɗan kõme fãce ƙarya.
Ã'a, kun riya cẽwa bã zã Mu sanya mukuwani lõkacin haɗuwa ba."
Ka ce: "Allah," sa'an nan ka bar su a cikin sharhõliyarsu sunã wãsã.
Nĩ inã ganin abin da bã ku gani; ni inã tsõron Allah: Kuma Allah Mai tsananin uƙũba ne."
To, me ya sanar da kai cẽwa watakila shi ne zai tsarkaka.
Ã'a ku mutãne ne daga waɗanda Ya halitta, Yanã gãfartãwa ga wanda Yake so, kuma Yanã azabta wanda Yake so. Kuma Allah ne da mulkin sammai da ƙasa da abin da ke tsakãninsu kuma zuwa gare shi makomã take."
A. L̃.R. Littãfi ne mun saukar da shi zuwa gare ka dõmin ka fitar da mutãne daga duhunhuna zuwa ga haske, da iznin Ubangijinsu, zuwa ga tafarkin Mabuwãyi, Abin gõdẽwa.
Munã rantsuwa da wanda Ya ƙãga halittarmu sai ka hukunta abin da kake mai hukuntãwa, ai kanã ƙãre wannan rãyuwar dũniya kawai ne."
Suka ce: "Yãye-yãyen mafarki ne, kuma ba mu zamo masana ga fassarar yãye-yãyen mafarki ba."
Ma'abũta Aljanna a rãnar nan sũ ne mafi alhẽri ga matabbata kuma mafi kyaun wurin ƙailũla.
Lalle ne Shi shĩ ne Mai ji, Mai gani.
Lalle ne waɗanda suka rarraba addininsu, kuma suka kasance ƙungiyã-ƙungiyã, kai ba ka zama daga gare su ba, a cikin kõme: abin sani kawai al'amarinsu zuwa ga Allah yake.
To sai su hau a cikin sammai (dõmin, su hana saukar Alƙur'ãni ga Muhammadu).
Fãce da rahama daga Ubangijinka.
Kuma Ubangijinka, sai ka girmama Shi,
Munã bã ka lãbãrinsu, daga gare su akwai wanda ke tsaye da kuma girbabbe.
Ƙiƙiro wani sabon shirin mai gabatar da
Sa'an nan mãsu yin tsãwa dõmin gargaɗi.
To, idan sun yi wanka sai ku je musu daga inda Allah Ya umurce ku.
Kõ wãne ne Ya halitta sammai da ƙasa kuma Ya saukar muku, daga, sama, wani ruwa, Muka tsirar, game da shi, gõnaki mãsu sha'awa, ba ya kasancẽwa gare ku, ku tsirar da itãcensu?
Kuma ba ya halatta ga mũmini kuma haka ga mũmina, a lõkacin da Allah da Manzonsa Ya hukunta wani umurni, wani zãɓi daga al'amarinsu ya kasance a gare su.
Ã'a, shi mawãƙi ne. Sai ya zo mana da wata ãyã kamar yadda aka aiko manzanni na farko."
Kuma waɗanda Muka bai wa Littãfi sunã sanin cẽwa lalleshi (Alƙur'ãni) abin saukarwa ne daga Ubangijinka, da gaskiya? Sabõda haka kada ku kasance daga mãsu shakka.
Kuma amma zukatansu sun ƙẽƙashe kuma shaiɗan yã ƙawãta musu abin da suka kasance sunã aikatãwa.
Kuma Shĩ ne Allah a cikin sammai, kuma a cikin ƙasa Yanã sanin asĩrinku da bayyanenku, kuma Yanã sanin abin da kuke yi na tsirfa.
Kuma Allah Ya fifita sãshenku a kan sãshe a arziki. Sa'an nan waɗanda aka fĩfĩta ba su zama mãsu mayar da arzikinsu a kan abin da hannãyensu na dãma suka mallaka ba, har su zama daidai a cikinsa.
Allah ne wanda Ya halicci sammai da ƙasa kuma Ya saukar da ruwa daga sama, sa'an nan Ya fitar game da shi, daga 'ya'yan itãce arziki dõminku kuma Ya hõrẽ jirgin ruwa dõmin ya yi gudu a cikin tẽku da umurninSa, kuma Ya hõrẽ muku kõguna.
Kuma Allah ne Masani ga abin da suke aikatãwa.
Yã kũ mutãne! Kũ ne mãsu bukãta zuwa ga Allah, kuma Allah, Shĩ ne Mawadãci, Gõdadde.
Kuma kada ka bazzara dũkiyarka, bazzarãwa.
Lalle ne Allah Yã kasance, game da ku, Mai jin ƙai ne.
Shĩ ne Ya ƙãga halittarku daga ƙasa, kuma Ya sanya ku mãsu yin kyarkyara a cikinta.
To, da ambaton Allah zukãta suke natsuwa.
Kuma amma zukatansu sun ƙẽƙashe kuma shaiɗan yã ƙawãta musu abin da suka kasance sunã aikatãwa.
Lalle nĩ, inã ganin ka kai damutã- nenka, a cikin ɓata bayyananniya."
Lalle ne waɗanda suka kãfirta, sunã ciyar da dũkiyõyinsu, dõmin su kange daga hanyar Allah; to, zã a su ciyar da ita, sa' an nan kuma ta kasance nadãma a kansu, sa'an nan kuma a rinjãye su. Kuma waɗanda suka kãfirta zuwa ga Jahannama ake tãra su;
Wato su yi iƙrãri da laifinsu.
Ka ce: "Lalle ne Allah Mai ĩko ne a kan Yasaukar da ãyã, kuma amma mafi yawansu, ba su sani ba."
Kuma ku kyautata; lalle ne, Allah Yana son mãsu kyautatãwa.
Kuma sunã da waɗansu amfãnõni a cikinsu, da abũbuwan shã. Ashe fa, bã zã; su gõdẽ ba?
Kuma Ya sanya sõyayya a tsakãnin zukãtansu.
Mũ, Munã bãyar da lãbãri a gare ka, mafi kyãwon lãbãri ga abin da Muka yi wahayin wannan Alƙur'ãni zuwa gare ka. Kuma lalle ne kã kasance a gabãninsa, haƙĩƙa, daga gafalallu.
Kamar haka Muka hõre muku su, tsammãninku kunã gõdẽwa.
Kuma waɗanda suke taskacẽwar zĩnãriya da azurfa, kuma bã su ciyar da ita a cikin hanyar Allah, to, ka yi musu bushãra da azãba mai raɗaɗi.
Kuma ku ci daga abin da Allah Ya azurta ku, halat mai daɗi, kuma ku bi Allah da taƙawa, wanda yake ku, mãsu ĩmãni ne da shi.
Ko kuma za Mu sanya masu bin Allah da taƙawa kamar fãjirai makarkata?
Kuma waɗanda ke nẽman fansa daga abin da hannuwanku na dãma suka mallaka, to, ku ɗaura musu fansã idan kun san akwai wani alhẽri a cikinsu kuma ku bã su wani abu daga dũkiyar Allah wannan da Ya bã ku.
Wata ƙungiya (Allah) Yã shiryar, kuma wata ƙungiya ɓata tã wajaba a kansu; lalle ne sũ, sun riƙi shaiɗanu majiɓinta, baicin Allah, kuma sunã zaton, lalle sũ, mãsu shiryuwa ne.
Alhãli kuwa sau nawa Muka aika wani Annabi a cikin mutãnen fãrko!
Kuma idan kun faɗi magana, to, ku yi ãdalci, kuma ko dã yã kasance ma'abũcin zumunta ne.
Lalle ne Shi, Shĩ ne Mai karɓar tũba, Mai jin ƙai.
Sai ku cika mũdu da sikeli kumakada ku nakasa wa mutãne kãyansu, kuma kada ku yi fasãdi a cikin ƙasa a bãyan gyaranta. Wannan ne mafi alhẽri a gare ku, idan kun kasance mũminai."
Yanã mai karkatar da sãshensa dõmin ya ɓatar (da wasu) daga tafarkin Allah!
Tsarin awa
Ku yi tsẽre zuwa ga (nẽman) gãfara daga Ubangjinku, da Aljanna fãɗinta kamar fãɗin samã da ƙasã ne, an yi tattalinta dõmin waɗanda suka yi ĩmãni da Allah da ManzanninSa.
Sai Mu kãmã su kwatsam! alhãli kuwa sũ, bã su sansancẽwa."
Na'am, lalle Shi, Mai ĩkon yi ne a kan kõme.
Lalle ne Allah ba Ya son wanda ya kasance mai yawan hã'inci mai yawan zunubi.
Ka ce: "Idan na ƙirƙira shi ne, to bã ku mallaka mini kõme daga Allah.
Da wata ayaba mai yawan 'ya'ya.
Kuma Lũɗu Mun bã shi hukunci da ilmi. Kuma Mun tsĩrar da shi daga alƙaryar nan wadda ke aikata mũnãnan ayyuka.
Lalle haƙĩƙa waɗanda suka ce: "Lalle Allah Shĩ ne Masĩhu ɗan Maryama," sun kãfirta.
Sa'an nan kuma zuwa gare Ni makõmarku take, sa'an nan in yi hukunci a tsakãninku, a cikin abin da kuka kasance kuna sãɓã wa jũna.
Kuma Ubangijinmu Mai rahama ne Wanda ake nẽman taimakonSa a kan abinda kuke siffantãwa."
Lalle ne Allah Yanã shigar da waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai a cikin gidãjen Aljanna, ƙoramu na gudãna daga ƙarƙashinsu.
Ya ce: "Lalle ne, nĩ bãwan Allah ne Allah Yã bã ni Littãfi kuma Ya sanya ni Annabi."
Kuma a lõkacin da Shaiɗan ya ƙawãce musu ayyukansu, kuma ya ce: "Bãbu marinjayi a gareku a yau daga mutãne, kuma nĩ maƙwabci ne gare ku."
Ka ce: "Yã ku mutãnena!
"Kõ kuwa a jẽfo wata taska zuwa gare shi, kõ kuwa wata gõna ta kasance a gare shi, yanã ci daga gare ta?"
Idan ba ku taimake shi ba, to, lalle ne Allah Yã taimake shi, a lõkacin da waɗanda suka kãfirta suka fitar da shi, Yanã na biyun biyu, a lõkacin da suke cikin kõgon dũtse, a lõkacin da yake cẽwa da sãhibinsa: "Kada ka yi baƙin ciki, lalle ne Allah Yanã tãre da mu."
Kayya! Lalle Allah ne Masani ga abin da kuka kasance kunã aikatãwa.
Waɗancan sunã da ãƙibar gida mai kyau.
Kuma idan ya kasance mũshe, to, a cikinsa sũ abõkan tãrayya ne, zai sãka musu sifantãwarsu.
Sunã son su musanya maganar Allah ne.
Lallene Ubangijĩna Mai kẽwayẽwa nega abin da kuke aikatãwa."
A lõkacin da Muka tsĩrar da shi, da mutãnensa gabã ɗaya.
Ka ce: "Abin da na rõƙe ku na wani sakamako, to, amfãninsa nãku ne.
To, idan sãshenku ya amince wa sãshe, to, wanda aka amincẽ wannan sai ya bãyar da amãnarsa, kuma ya bi Allah, Ubangijinsa, da taƙawa.
¡arshen kurɓinta miski ne.
Lalle zã su ce, "Mabuwãyi Mai ilmi ne Ya halitta su."
Sabõda haka ku yi ĩmãni da Allah da manzanninSa Kuma idan kun yi ĩmãni kuma kuka yi taƙawa, to, kunã da lãdã mai girma.
To, Mun kuranye maka rufinka, sabõda haka ganinka a yau, mai kaifi ne."
Sãbõda haka madalla da ni'imar ãƙibar gida."
Lalle Mũ, hakĩka, Munã taimakon ManzanninMu da waɗanda suka yi ĩmãni, a cikin rãyuwar dũniya da rãnar da shaidu ke tsayãwa.
To, idan kun ƙãre ayyukan hajji, sai ku ambaci Allah kamar ambatarku ga ubanninku, kõ kuwa mafi tsanani ga ambato. To, daga cikin mutãne akwai wanda yake cẽwa: "Ya Ubangjinmu!
A cikin ruwan zãfi, sa'an nan a cikin wutã anã babbaka su.
Kuma waɗanda suka yi zãlunci, zã su sani a wace majũya suke jũyãwa.
Da Ismã'la da Ilyasa, a da Yũnusa da Luɗu, kuma dukansu Mun fĩfĩtã su a kan tãlikai.
"Kuma bã ka zargin kõme daga gare mu fãce dõmin mun yi ĩmãni da ãyõyin Ubangijinmu a lõkacin da suka zõ mana!
Kuma suka yi mãmãki dõmin Mai gargaɗi, daga cikinsu, ya je musu.
Lalle shi (Sulaimãn) mai mayar da al'amari ne ga Allah.
Kuma idan na shiryu, to, sabõda abin da Ubangijina Yake yõwar wahayi ne zuwa a gare ni.
Don me bã ku nẽman Allah gãfara, tsammãninku, zã a yi muku rahama?"
Lalle ne Mũ, Mãsu mayar da shi ne zuwa gare ki, kuma Mãsu sanya shi ne a cikin Manzanni
Haka Ãdãwa suka kasance, sun yi musun ãyõyin Ubangijinsu, kuma sun sãɓa wa ManzanninSa, kuma sun bi umurnin dukan mai girman kai, makangari.
Ka sanya mana wani abin bautawa kamar yadda suke da abũbuwan bautãwa " Ya ce: "Lalle ne kũ, mutãne ne kunã jahilta."
Kuma lalle idan Mun ɗanɗana masa wata rahama daga gareMu, daga bãyan wata cũta ta shãfe shi, lalle zai ce, "Wannan (ni'ima) tãwa ce kuma bã ni zaton Sã'a mai tsayuwa ce, kuma lalle idan aka mayar da ni zuwa ga Ubangijĩna, haƙĩƙa, inã da makõma mafi kyau, a wurinSa."
To, Shĩ ne Mabuwãyi, Mai gãfara.
Shĩ ne Allah, Makaɗaici, Mai tĩlastãwa.
Ka ce: "Shin makãho da mai gani sunã daidaita?
Babu abin bautãwa fãce Shi.
An haramta muku mũshe da jini da nãman alade da abin da aka ambaci sũnan wanin Allah a gare shi, da mãƙararriya da jefaffiya da mai gangarõwa da sõkakkiya, da abin da mãsu dãgi suka ci, fãce abin da kuka yanka, da abin da aka yanka a kan gunki (shĩ ma an haramta).
Wadda ta zo da alfãsha bayyananna daga cikinku zã a ninka mata azãba ninki biyu. Kuma wancan yã kasance mai sauƙi ga Allah.
Kuma Allah ne wanda ake nẽman taimako (a gunSa) a kan abin da kuke siffantãwa."
Kuma lalle, Mun yi ni'ima ga Mũsã da Hãrũna.
Lalle, Allah bã Ya son dukan mai tãƙama, mai alfahari."
Kuma Allah ne Ma'abũcin dukan falala mai girma.
Da wata ni'ima da suka kasance a cikinta sunã mãsu hutu.
Kuma da wadda ta tsare farJinta daga alfãsha.
Lalle ne Kai, Kai ne Mai karɓar tũba, Mai rahama.
Wannan ne mafi alhẽri gare ku, tsammaninku, zã ku tuna.
Kuma Allah Masani ne ga mãsu taƙawa.
Kuma abin da kuka sãɓã wa jũna a cikinsa kõ mêne ne, to, hukuncinsa (a mayar da shi) zuwa ga Allah.
Kuma idan suka warware rantsuwõyin amãna daga bãyan alkawarinsu, kuma suka yi sũka a cikin addininku, to, ku yaki shũgabannin kãfirci. Lalle ne sũ, bãbu rantsuwõyin amãna a gare su.
Suka ce: "Lalle mũ munã shu'umci da ku! Haƙĩƙa idan ba ku, hanu ba, haƙĩƙa, zã mu jẽfe ku, kuma haƙĩƙa wata azãba mai raɗaɗi daga gare mu zã ta shãfe ku."
Ka ce: "Shin, kun gani, idan (Alƙur'ãni) ya kasance daga wurin Allah yake, kuma kuka kãfirta da shi, kuma wani mai shaida daga Banĩ Isrã'ĩla ya bãyar da shaida a kan kwatankwacinsa, sa'an nan ya yi ĩmãni, kuma kuka kangare?
To, bã zã ka sãmi musanya ba ga hanyar Allah. Kuma bã zã ka sãmi jũyarwa ba ga hanyar Allah.
Lalle ne, wata hujja bayyananniya daga Ubangijinku tã zõ muku!
Zã ni gaya maka fassarar abin da ba ka iya yin haƙuri ba a kansa."
Kuma zuwa ga Ãdãwa, ɗan'uwansu Hudu, ya ce: "Ya mutãnena!
Sai ya jũya zuwa ga iyãlinsa, sa'an nan ya zo da maraƙi tutturna,
A lõkacin da ya ga wata wuta, sai ya ce wa iyãlinsa, "Ku dãkata.
Kuma a lõkacin da Muka ce wa malãiku, "Ku yi sujada ga Ãdamu."
Dã sun kasance sunã fahimta!
Ka sanyã wannan gari amintacce kuma Ka nĩsanta ni, nĩ da ɗiyãna daga bauta wa gumãka.
Sai a lõkacin da suka hangi azãbarMu, sai gã su sunã gudu daga gare ta.
Kuma shin, lãbarin Mũsã yãje maka?
Kuma idan yã kasance cewa finjirewarsu tã yi nauyi a gare ka, to, idan kana iyãwa, ka nemi wani ɓullõ a cikin ƙasa, kõ kuwa wani tsãni a cikin sama dõmin ka zo musu da wata ãyã, (sai ka yi).
Yã kũ waɗanda suka yi ĩmãni! Ku nĩsanci abu mai yãwa na zato.
"Kuma kada ku nẽmi ɗaukaka a kan Allah. Lalle nĩ mai zo muku ne da dalĩli bayyananne."
Kuma ka bauta wa Ubangijinka, har mutuwa ta zo maka.
Da (mũminai) sun tsabbace dã Mun azabtar da waɗanda suka kãfirta daga gare su da azãba mai raɗiɗi.
"Kuma mẽne ne a gare mu, bã zã mu dõgara ga Allah ba, alhãli kuwa haƙĩƙa Yã shiryar da mu ga hanyõyinmu?
Lalle shĩ, haƙĩƙa, babbanku ne wanda ya sanar da ku sihirin!
Ku bauta waAllah!
Kuma sunã rantsuwa da Allah cẽwa, lalle ne sũ, haƙĩƙa, daga gare ku suke, alhãli kuwa ba su zamo daga gare ku ba.
Kuma dã dai lalle Mũ, Mun wajabta musu cẽwa, "Ku kashe kanku, ko kuwa ku, fita daga gidãjenku," dã ba su aikata shi ba, fãce kaɗan daga gare su.
"Kuma amma bangon, to, yã kasance na waɗansu yãra biyu ne, marãyu a cikin birnin, kuma akwai wata taska tãsu a ƙarƙashinsa, kuma ubansu ya kasance sahĩhin mutum ne, dõmin haka Ubangijinka Ya yi nufin su isa iyãkar ƙarfinsu, kuma sũ, su fitar da taskarsu, sabõda rahama ne daga Ubangijinka.
A kan zũciyarka, dõmin ka kasance daga mãsu gargaɗi.
Ku kira su ga ubanninsu, shi ne mafi ãdalci a wurin Allah.
Shi ne wanda Yake suranta ku a cikin mahaifu yadda Yake so.
Ya ce (masa), "Wallahi, lalle, kã yi kusa, haƙĩƙã, ka halakãni."
Lalle ne Ubangijinka Mai hikima ne, Masani."
Ka ce: "Shin wanin Allah nake nẽma ya zama Ubangiji, alhãli kuwa Shĩ ne Ubangijin dukan kõme?
Yã Dãwũda! Lalle Mũ Mun sanya ka Halĩfa a cikin ƙasã.
Ku sani cẽwa Allah Yanã rãyar da ƙasã a bãyan mutuwarta.
To, wanda ya halarta daga gare ku a watan, sai ya azumce shi, kuma wanda ya kasance majinyaci ko kuwa a kan tafiya, sai ya biya adadi daga wasu kwanuka na dabam.
Ka ce: "Bãbu abin da yake sãmun mu fãce abin da Allah Ya rubũta sahõda mu.
Kuma lalle ne abin da aka saukar zuwa gare ka yanã ƙãra wa mãsu yawa daga gare su, girman kai da kãfirci.
Sai ya wãyi gari daga mãsu nadãmã.
Waɗanda Muka bã su Littãfi, suna saninsa kamar yadda suke sanin ɗiyansu.
"Wanda Ya halitta ni, sa'an nan Yanã shiryar da ni."
Cẽwã kunã da, a cikinsa lalle (duk) abin da rãyukanku suka zãɓa?
Lalle ne, wata hujja bayyananniya daga Ubangijinku tã zõ muku!
Kuma zuwa ga Allah al'amurra ake mayar da su.
Lalle, a cikin wancan akwai ãyã ga dukan bãwã mai maida al'amarinsa ga Allah.
Kuma wanda Allah Ya ɓatar to bã zã ka sãmi wata hanya ba zuwa gare shi.
"Ya Ubangijnmu! Ka sanyã mu, mu biyu, waɗanda suka sallama (al'amari) gare Ka, kuma daga zuriyarmu (Ka sanya) al'umma mai sallamãwa zuwa gare Ka, Kuma Ka nũna mana wurãren ibãdar hajjinmu, kuma Ka karɓi tũba a kanmu.
Dõmin su kãfirce wa abin da Muka bã su kuma dõmin su ji dãɗi sa'an nan kuma zã su sani.
Waɗanda aka bari zã su ce idan kun tafi zuwa ga waɗansu ganĩmõmi dõmin ku karɓo su, "Ku bar mu, mu bĩ ku."
Lalle nĩ mai zo muku ne da dalĩli bayyananne."
Sa'an nan kuma Muka yi wahayi zuwa gare ka (cẽwa), "Ka bi aƙĩdar Ibrahĩm, mai karkatã zuwa ga gaskiya, kuma bai kasance daga mãsu shirki ba.'
To! Lalle ne, taimakon Allah yana kusa!
To ĩmaninsu bai kasance yanã amfaninsu ba a lõkacin da suka ga azãbarMu.
To, a lõkacin da suka jẽfa, Mũsa ya ce: "Abin da kuka zo da shi sihiri ne.
Kuma wadda yake a cikin ɗãkinta, ta nẽme shi ga kansa, kuma ta kukkulle ƙõfõfi, kuma ta ce, "Yã rage a gare ka!" ya ce: "Ina neman tsarin Allah!
"Abin da dai kuke bautãwa, baiein Allah, gumaka ne, kuma kun ƙirƙira ƙarya.
Kuma dã kã gani, a lõkacin da azzãlumai suke cikin mãyen mutuwa, kuma malã'iku sunã mãsu shimfiɗa hannuwansu, (sunã ce musu) "Ku fitar da kanku; a yau anã sãka muku da azãbar wulãƙanci sabõda abin da kuka kasance kunã faɗa, wanin gaskiya, ga Allah kuma kun kasance daga ãyõyinSa kunã yin girman kai."
Lalle Ubangijinka ne Masani, Mai hikima."
Sa'an nan da aka ƙãre, suka jũya zuwa ga jama'arsu sunã mãsu gargaɗi.
Kuma sakamakon cũta shĩ ne wata cũta kamarta, sai dai wanda Ya yãfe kuma ya kyautata, to lãdarsa nã ga Allah.
Lalle ne, ManzonMu yã je muku, yanã bayyana muku abu mai yawa daga abin da kuka kasance kunã ɓõyewa daga Littãfi, kuma yanã rangwame daga abu mai yawa. Haƙĩƙa, wani haske da wani Littafi mai bayyanãwa yã je muku daga Allah.
To, ko zã mu Sanya harãji sabõda kai, a kan ka sanya wani danni a tsakãninmu da tsakãninsu?"
Kõ sunã da abõkan tãrẽwa (ga wannan ra'ayi)?
Ka ce: "Shin, daga abũbuwan shirkinku akwai wanda yake shiryarwa zuwa ga gaskiya?"
Sai Muka aika rũhinMu zuwa gare ta. Sai ya bayyana a gare ta da siffar mutum madaidaci.
Kuma Muka ce: daga bãyansa ga Banĩ Isrã'ĩla, "Ku zauni ƙasar.
Inã rantsuwa da sama da mai aukõwa da dare.
To, ka dũbi yadda ãƙibar maɓarnata ta kasance.
Kuma wanda ya kõma, to, Allah zai yi azãbar rãmuwa daga gare shi, kuma Allah Mabuwãyi ne, ma'abũcin azabãr rãmuwa.
Lalle shi Mai gani ne ga dukan kõme.
Kuma waɗanda zaka kashe a cikin tafarkin Allah, to, bã ai ɓatar da ayyukansu ba.
Allah ne ke karɓar rãyuka a lõkacin mutuwarsu, da waɗannan da ba su mutu ba, a cikin barcinsu.
Kamar wannan ne Muka ƙawãta ga kõwace al'umma aikinsu, sa'an nan zuwa ga Ubangijinsu makõmarsu take, sa'an nan Ya ba su lãbari da abin da suka kasance sunã aikatãwa.
Kuma waɗanda suka kãfirta suka ce: "Wannan bã kõme ba ne fãce ƙiron ƙarya da (Muhammadu) ya ƙirƙira shi, kuma waɗansu mutãne na dabam suka taimake shi a kansa."
Kuma wanda ya yi haka, to, waɗannan sũ ne mãsu hasãra.
Wasu huskõki, a rãnar nan, akwai ƙũra a kansu.
Kuma ka yi bushãra ga mãsu kyautata yi.
Yã ku waɗanda suka yi ĩmãni! Kada ku ci riba ninkininki, riɓanye, kuma ku bi Allah da taƙawa, tsammãninku zã ku ci nasara.
Ya ce: "Ya mutãnena!
Lalle Allah ne Masani ga abin da kuka kasance kunã aikatãwa.
Wanda ya sãɓã wa rõwar ransa, to, waɗannan sũ ne mãsu babban rabo.
Kuma kãfirai suna da azãba mai raɗaɗi.
"Lalle mũ mun kasance, a gãbanin haka, munã kiran sa.
Shin fa, da ni'imar Allah suke musu?
"Kuma kada ka kirãyi, baicin Allah, abin da bã ya amfãnin ka kuma bã ya cũtar ka.
Kuma Allah bai gushe daga abin da kuke aikatãwa ba yana Masani."
Kuma Allah bã Ya shiryar da mutãne azzãlumai.
Lokacin UNIX
Lalle Mũ, Mun sanya ƙuƙumma a cikin wuyõyinsu, sa'an nan sũ (ƙuƙumman sun kai) har zuwa ga haɓõɓinsu, sabõda haka, sũ banƙararru ne.
Kuma sakamakon cũta shĩ ne wata cũta kamarta, sai dai wanda Ya yãfe kuma ya kyautata, to lãdarsa nã ga Allah.
Yin ɗã'a da magana mai kyau.
Lalle ne mũ, Munã ganin taa cikin ɓata bayyanãnna."
Kuma idan kun tũba to kuna da asalin dũkiyõyinku, bã ku zãlunta, kuma bã a zãluntar ku.
Sabõda haka Ka gãfarta mana zunubanmu, kuma Ka kankare miyãgun ayyukanmu daga gare mu. Kuma Ka karɓi rãyukanmu tãre da mutãnen kirki.
Abin sani kawai, nũminai sũ ne waɗanda suke idan an ambaci, Allah, zukãtansu su firgita, kuma idan an karanta ãyõyinSa a kansu, su ƙãrã musu wani ĩmãni, kuma ga Ubangijinsu suke dõgara.
Lalle ne, waɗanda suka sayi kãfirci da ĩmani, ba zã su cũci Allah da kõme ba.
Waccan ƙissa tanã daga lãbãran gaibi, Munã yin wahayinsu zuwa gare ka (Muhammadu).
Ƙiƙiro wani sabon shirin mai gabatar da
Allah Mafi sanin inda Yake sanya manzancinSa.
Kuma sai mũminai su dogara ga Allah.
Idan sun yi nufin gyãrãwa, Allah zai daidaita tsakãninsu (ma'auran). Lalle ne Allah Yã kasance Masani Mai jarrabãwa.
Kuma ba Mu aika wani manzo ba a gabãninka, kuma ba Mu umurci wani Annabi ba fãce idan ya yi bũri, sai Shaiɗan ya jẽfa (wani abu) a cikin bũrinsa, sa'an nan Allah Ya shãfe abin da Shaiɗan ke jefãwa. Sa'an nan kuma Allah Ya kyautata ãyõyinSa.
Lalle ne, a cikin wancan, akwai tunãtarwa ga wanda zũciyarsa ta kasance gare shi, kõ kuwa ya jẽfa saurãro, alhãli kuwa yanã halarce (da hankalinsa).
Sai ka yi haƙuri. Lalle ne ãƙiba tanã ga mãsu taƙawa,
Kai mai gargaɗi kawai ne ga mai tsõron ta.
Wancan ne, dõmin lalle ne sũ, sunã sãɓa wa Allah da ManzonSa.
Lalle ne, waɗanda suke ƙirƙira ƙarya ga Allah bã zã su ci nasara ba.
Kuma Al lah bai kasance Yanã sanar da ku gaibi ba. Kuma amma Allah Yana zãɓen wanda Ya so daga manzanninSa.
Kuma Ya arzũta shi daga inda bã ya zato.
Sunã sanin bayyanannar rãyuwar dũniya, alhãli kuwa sũ shagalallu ne daga rãyuwar Lãhira.
Sunã tufanta daga tufãfin alharĩni raƙĩƙi, da mai kauri, sunã mãsu zaman fuskantar jũna.
Ashe, ba Mu sanya ƙasa matattarã ba.
Kamar wancan ne Muka aika ka a cikin al'umma wanda take waɗansu al'ummai sun shũɗe daga gabaninta, dõmin ka karanta musu abin da Muka yi wahayi zuwa a gare ka, alhãli kuwa sũ, sunãkãfirta da Rahaman.
Kuma lalle ne, haƙĩƙa, an ƙaryata manzanni daga gabãninka, sai suka yi haƙuri a kan abin da aka ƙaryata su, kuma aka cũtar da su, har taimakonMu ya je musu, kuma babu mai musanyãwa ga kalmõmin Allah.
Kuma aka ce: "Ku shiga, kũ biyu, wutã tãre da mãsu shiga."
Kada ku yi tambaya ga abubuwa, idan an bayyana muku (hukuncinsu) su ɓãta muku rai.
Kuma ga Allah sai mũminai su dõgara.
Wancan ne, dõmin lalle ne su, sun ƙaryata da ãyõyinMu, kuma sun kasance, daga barinsu gãfilai.
Shĩ ne wanda Ya halitta sammai da ƙasa a cikin wasu kwãnuka shida, sa'an nan Ya daidaitu a kan Al'arshi, Yanã sanin abin da ke shiga cikin ƙasa da abin da ke fita daga gare ta, da abin da ke sauka daga sama da abin da ke hawa cikinta, kuma Shĩ yanã tareda ku duk inda kuka kasance.
Kuma sunã sanyã wa Allah abin da suke ƙi, kuma harsunansu na siffanta ƙarya cẽwa lalle ne sunã da abũbuwa mãsu kyau.
Lalle Mũ Mun sanya ka Halĩfa a cikin ƙasã. To, ka yi hukunci tsakãnin mutãne da gaskiya, kuma kada ka biye wa son zũciyar, har ya ɓatar dakai daga hanyar Allah.
Sai ka dũbi yaddaãƙibar azzãlumai ta kasance.
Wancan ne shiryarwar Allah, Yanã shiryar da wanda Yake so daga bayinSa.
Suka ce: "Muna bauta wa Abin bautawarka kuma Abin bautawar ubanninka lbrãhĩm da lsmã'ĩla da Is'hãƙa, Ubangiji Guda, kuma mu a gare Shi mãsu miƙa wuya ne."
Kuma sulaimãn ya gãji Dãwũda ya ce: "Yã ku mutãne!
Shin fa, Ubangijinku Ya zãɓe ku da ɗiya maza ne, kuma Ya riƙi 'ya'ya mãta daga malã'iku?
Sai suka ce: "Ga Allah muka dõgara.
Ka ce: "Abin da na rõƙe ku na wani sakamako, to, amfãninsa nãku ne.
To, mẽ yã sanar da kai abin da ake cẽwa mai aukõwa da dare?
Da waɗanda suke, game da ãyõyin Ubangijinsu sunã ĩmãni,
Munã ɗaukaka wanda Muka so da darajõji.
"Kuma kunã sassaƙa gidãje daga duwãtsu, kunã mãsu alfãhari?"
Sa'an nan kuma Mun aika Musa, daga bãyansu, da ãyõyinMu zuwa ga Fir'auna da majalisarsa, sai suka yi zãlunci game da su.
"Kõ kuwa wata halitta daga abin da yake da girma a cikin ƙirazanku."
Lalle Allah Mai iyar da umurninSa ne.
To, a lõkacin da Ĩsa ya gane kãfirci daga gare su, sai ya ce: "Su wãne ne mataimakãna zuwa ga Allah?"
Kuma waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, zã mu shigar da su gidãjen Aljanna (waɗanda) ƙõramu sunã gudãna a ƙarƙashinsu, sunã mãsu dawwama a cikinsu har abada bisa ga wa'adin Allah tabbatacce.
Yã ku waɗanda suka yi ĩmãni! Ku kasance mãsu tsayin daka dõmin Allah mãsu shaida da ãdalci.
Ka ce: "Wanda ya ƙãga halittarsu a farkon lõkaci Shĩ ke rãyar da su, kuma Shi, game da kõwace halitta, Mai ilmi ne."
"Kuma lalle ne akwai la'ana a kanka har ya zuwa rãnar sakamako."
Shin, ba Mu tabbatar musu da mallakar Hurumi ba, ya zama amintacce, anã jãwõwa zuwa gare shi, 'ya'yan itãcen kõwane iri, bisa ga azurtãwa daga gare Mu?
Shin kanã jin mõtsin wani guda daga gare su, kõ kuwa kanã jin wata ɗuriya tãsu?
Ya halicci sammai da ƙasa da gaskiya.
Ka tambayi Banĩ Isrã'ila, da yawa Muka bã su daga ãyõyi bayyanannu.
Wannan ita ce hanya madaidaciya."
Sai ku cika mũdu da sikeli kumakada ku nakasa wa mutãne kãyansu, kuma kada ku yi fasãdi a cikin ƙasa a bãyan gyaranta. Wannan ne mafi alhẽri a gare ku, idan kun kasance mũminai."
Kuma Ya yi azãba ga munãfikai maza da munãfikai mãtã da mushirikai maza da musbirikai mãtã, mãsu zaton mugun zato game da Allah, mugunyar masĩfa mai kẽwayẽwa ta tabbata a kansu, kuma Allah Ya yi hushi da su, kuma Ya la'ane su, kuma Ya yi musu tattlain Jahannama kuma ta mũnana ta zama makõma (gare su).
Kuma abin da Muka yi wahayi zuwa gare ka, daga Littãfi,
Kuma ga kõwa, Mun sanya magada daga abin da mahaifa da mafiya kusancin zumunta suka bari.
Kuma kunã da kyau a cikinsu a lõkacin da suke kõmõwa daga kĩwo da maraice da lõkacin da suke sakuwã.
Ã'a, yã ƙirƙira shi ne.
To, a lõkacin da Ya kuɓutar da su, sai, gã su sunã zãlunci a cikin ƙasa, bã da wanĩ hakki ba.
Suka ce, "Lalle mũ dai mãsu kafirta ne game da abin da aka aiko ku da shi."
Sabõda haka Allah Ya tsare musu sharrin wannan yini, kuma Ya hlɗa su da annũrin huska da farin ciki,
Kuma daga cikinsu akwai wadɗanda suka yi wa Allah alkawari, "Lalle ne idan ya kãwo mana daga falalarSa, haƙĩƙa, munãbãyar da sadaka, kuma lalle ne munã kasancẽwa, daga sãlihai."
To, shin, akwai mai tunãwa?
Kuma Ubangijĩna Yanã musanya waɗansu mutãne, waɗansunku su maye muku. Kuma bã ku cũtar Sa da kõme.
Kuma kãfircin kãfirai bã ya kãra musu kõme fãce baƙin jini, kuma kãfircin kãfirai bã ya kãra musu kõme face hasãra.
Shin, wanda ya zama mũmini yanã kamar wanda ya zama fãsiƙi?
Wancan ne Ĩsã ɗan Maryamu, maganar gaskiya wadda suke shakka a cikinta.
Kuma dã Mun sassaukar da wani littãfi, zuwa gare ka, a cikin takarda, sa'an nan suka taɓa shi da hannuwansu, lalle dã waɗanda suka kãfirta sun ce: "Wannan bai zama ba, face sihiri bayyananne."
Kõ waɗanda ke aikata miyãgun ayyuka sun yi zaton su tsẽre Mana?
Akwai malã'iku da yawa a cikin sammai cẽtonsu bã ya wadãtar da kõme fãce bãyan Allah Yã yi izni (da shi) ga wanda Yake so, kuma Yake yarda.
Allah Mai tausasãwa ne ga bãyinsa.
Allah Yã buga wani misali da wani bãwa wanda bã ya iya sãmun ĩko a kan yin kõme, da (wani bãwa) wanda Muka azurtã shi daga gare Mu da arziki mai kyau.
Da waɗansu ganĩmõmi mãsu yawa da zã su karɓo su.
Kuma waɗanda suka ƙaryata game da ãyõyinMu, zã Mu yi musu istidrãji daga inda ba su sani ba.
To, sai Muka tsĩrar da shi, shĩ da waɗanda suke tãre da shi sabõda wata rahama daga gare Mu, kuma Muka katse ƙarshen waɗanda suka ƙaryata game da ãyõyinMu, kuma ba su kasance mũminaiba.
Kuma haƙĩƙa idan ka ce: "Lalle kũ waɗanda ake tãyarwa ne a bãyan mutuwa," haƙĩƙa waɗanda suka kãfirta sunã cẽwa: "Wannan bai zama ba fãce sihiri bayyananne."
To, wanda ya yi ta'addi a bãyan wannan, to, yanã da azãba mai raɗaɗi.
A lõkacin da mãtar Imrãna ta ce: "Ya Ubangijina! Lalle ni, nã yi bãkancen abin da ke cikin cikĩna gare Ka; ya zama 'yantacce, sai Ka karɓa daga gare ni.
Ka ce: Shin kuna jãyayyar hujia ne da mu a cikin al'amarin Allah, alhãli kuwa Shi ne Ubangijinmu kuma Ubangijinku, kuma muna da ayyukanmu, kuma kuna da ayyukanku, kuma mũ, a gare Shi, mãsu tsarkakẽwane?
Kuma waɗanda suka yi mãkirci ga ãyõyinMu, sunã mãsu gajiyarwa, waɗannan sunã da wata azãba daga azãba mai raɗaɗi.
Fãce Iblĩs, ya ƙi kasancẽwa daga mãsu yin sujadar.
Ka ce: "Idan na ɓace, to, inã ɓacẽwa ne kawai a kan kaina. Kuma idan na shiryu, to, sabõda abin da Ubangijina Yake yõwar wahayi ne zuwa a gare ni.
Wannan kuwa dõmin sãɓãwar da suka yi ne, kuma sun kasance suna yin ta'adi.
Allah Shĩ ne mafi sani ga ĩmãninsu.
Kuma bãbu abin da ya hana a karɓi ciyarwarsu daga gare su fãce dõmin sũ, sun kãfirta da Allah da ManzonSa, kuma bã su zuwa ga salla fãce Luma sunã mãsu kasãla, kuma bã su ciyarwa fãce sunã mãsu ƙyãma.
Ka ce: "Shin, wanin Allah nike riƙo majiɓinci, (alhãli Allah ne) Mai ƙãga halittar sammai da ƙasa, kuma Shi, Yanã ciyarwa, kuma ba a ciyar da Shi?"
Yana ƙayyade yawan pixel da ana iya gani idan an ɓoye fanel farat ɗaya cikin wata lungu. Wannan maɓalli na da amfani kawai idan maɓallin ɓoyewa_farat ɗaya na gaske ne.
Allah bai halitta wannan ba, fãce da gaskiya, Yanã bayyana ãyõyi daki-daki dõmin mutãne waɗanda suke sani.
Kuma Ubangijinka Yanã halitta abin da Yake so kuma Yake zãɓi.
"To, ku bi Allah da taƙawa, kuma ku yi mini ɗã'ã."
Kuma daga cikinsu akwai ummiyyai, bã su da sanin Littãfi, fãce tãtsuniyoyi, kuma sũ bã kõme suke yi ba fãce suna yin zato.
toolbar position string
Wancan ne mafi ãdalci a wurin Allah kuma mafi tsayuwa ga shaida, kuma mafi kusa ga rashin shakkarku.
Wancan ne. Kuma wanda ya girmama hukunce-hukuncen Allah to shĩ ne mafĩfĩci a gare shi, a wurin Ubangijinsa.
Yana bãyar da hikima (ga fahimtar gaskiyar abubuwa) ga wanda Yake so.
An la'ani waɗanda suka kãfirta daga Banĩ Isrã'ĩla a kan harshen Dãwuda da Ĩsa ɗan Maryama. wannan kuwa sabõda sãɓãwar da suka yi ne, kuma sun kasance suna ta'addi.
Gõdiyarku kaɗan ce ƙwarai.
Ya ce: "Kuma daga zũriyata."
Ƙiƙiro wani sabon shirin mai gabatar da
Bãbu mai bayyana ta ga lõkacinta fãce shĩ Tã yi nauyi a cikin sammai da ƙasa.
Shĩ ne Mai rai, bãbu abin bautãwa fãce Shi. Sabõda haka ku kira Shi, kunã mãsu tsarkake addini a gare Shi.
Na rantse da alƙalami da abin da (marubũta) suke rubũtãwa.
Kuma waɗancan ba mũminai ba ne.
Kuma Shĩ ne wanda Ya halitta sammai da ƙasa da mulkinSa, kuma a Rãnar da Yake cẽwa: "Ka kasance," sai abu ya yi ta kasancẽwa.
Wancan ne: "Ku ɗanɗane shi, kuma lalle ne akwai azãbar wuta ga kãfirai."
"Kuma don me, a lõkacin da ka shiga gõnarka, ka, ce, 'Abin da Allah ya so (shi ke tabbata) bãbu wani ƙarfi fãce game da Allah.'
Shin, sunã jira, fãce fassararsa, a rãnar da fassararsa take zuwa, waɗanda saka manta da Shi daga gabãni, sunã cẽwa: "Lalle ne, Manzannin Ubangijin mu svun jẽ da gaskiya.
Mũsã ya ce: " Shin, kunã cẽwa ga gaskiya a lõkacin data zo muku?
Rãnar da sama zã ta kasance kamar narkakkar azurfa.
Kuma wanda bãshin yake a kansa sai ya yi shibta, kuma ya ji tsõron Allah, Ubangijinsa, da taƙawa, kuma kada ya rage wani abu daga gare shi. To, idan wanda bãshin yake a kansa yã kasance wãwã ne kõ kuwa rarrauna, kõ kuwa shi bã ya iya shibta, to, sai waliyyinsa ya yi shibtar da ãdalci.
Sai suka kõma a kan gurãbunsu, sunã bĩbiya.
Sa'an nan a lõkacin da suka shiga gare shi suka ce: "Yã kai Azĩzu!
Kuma ãyã ce a gare su: Dare Muna feɗe rãna daga gare shi, sai gã su sunã mãsu shiga duhu.
Kuma, Muka sanya, a cikinta, kafaffun duwãtsu maɗaukaka, kuma Muka shayar da ku ruwa mai dãɗi?
Shin bã ku hankalta?
Kuma waɗanda suka yi bũrin matsayinsa a jiya suka wãyi gari sunã cẽwa, "Wai! Allah Yanã shimfiɗa arziki, ga wanda Yake so daga bãyinsa, kuma Yanã ƙuntatãwa.
Sã'an nan Muka nutsar da waɗansunsu.
Kuma, Muka sanya, a cikinta, kafaffun duwãtsu maɗaukaka, kuma Muka shayar da ku ruwa mai dãɗi?
Yãya kuke yin hukunci?"
Lalle, tabbas, (Annabinku) ya ga waɗanda suka fi girma daga ãyõyin Ubangijinsa.
Lalle mãsu taƙawa, sunã a cikin lambunan itãce da marẽmari.
Gidãjen Aljannar zama, alhãli kuwa tanã abar buɗe wa kõfõfi sabõda su.
Idan kun kyautata, kun kyautata dõmin kanku, kuma idan kun mũnana to dõmĩnsu.
To, a lõkacin da aka wajabta yãƙin a kansu, suka jũya, sai kaɗan daga gare su. Kuma Allah Masani ne ga azzãlumai.
Kuma Muka sanya girgije ya yi inuwa a kanku, kuma Muka saukar da darɓa da tantabaru a kanku; "Ku ci daga mãsu dãɗin abin da Muka azurta ku." kuma ba su zãlunce Mu ba, kuma amma kansu suka kasance suna zãlunta.
Lalle nĩ, mai nasĩha ne a gare ka."
Kamar dai ba su zauna a cikinta ba. To!
Bone yã tabbata a rãnar nan ga mãsu ƙaryatãwa.
Kuma lalle ne shi (Alƙarãni) wallahi baƙin ciki ne ga kãfirai.
Waɗancan, waɗanda suke kiran, sunã nẽman tsãni zuwa ga Ubangijinsu. Waɗanne ne suke mafĩfĩta a kusanta?
To, Ka yi mini jinkiri zuwa ga rãnar da ake tãyar da su."
Waɗannan rabonsu daga Littãfi yanã sãmunsu, har a lõkacin da ManzanninMu suka je musu, sunã karɓar rãyukansu, su ce: "Ĩnã abin da kuka kasance kunã kira, baicin Allah?"
Wãne ne wanda zai ranta wa Allah rance mai kyau dõmin Allah Ya ninka masa shi (a dũniya) kuma Yanã da wani sakamako na karimci (a Lãhira)?
Kuma Allah bã Ya shiryar da mutãne fãsiƙai."
Kuma makãho da mai gani bã su daidaita kuma waɗanda suka yi ĩmãni suka, aikata ayyukan ƙwarai da mai mũnanãwa bã su daidaita.
Sa'an nan wanda ya nẽmi shiriya, to, dõmin kansa, kuma wanda ya ɓace, to, yanã ɓacẽwa ne a kanta.
Ashe!
Kuma a ranar nan aka zo da Jahannama. A ranar nan mutum zai yi tunãni.
Kuma waɗannan da suke gaugãwa a cikin kãfirci kada su ɓãta maka rai.
To, wãne ne mafi zãlunci daga wanda ya ƙirƙira ƙarya ga Allah, dõmin ya ɓatar da mutãne bã da wani ilmi ba?
"Lalle ne ku, haƙĩƙa kunã jẽ wa maza da sha'awa, baicin mata; Ã'a, kũ mutãne ne maɓarnata."
To, lalle ne waɗanda ke shakka a cikin Sa'a, haƙĩƙa, sunã a cikin ɓata Mai nĩsa.
Kuma aka hũra a cikin ƙaho.
Kuma kada tausayi ya kãma ku game da su a cikin addinin Allah idan kun kasance kunã yin ĩmãni da Allah da Rãnar Lãhira. Kuma wani yankin jama, a daga mũminai, su halarci azãbarsu.
Lalle ne, waɗanda uke kãfirta da Allah da ManzonSa kuma sunã nufin su rarrabe a tsakãnin Allah da manzanninSa, kuma sunã cẽwa: "Munã ĩmãni da sãshe, kuma munã kãfirta da sãshe."
Sai Ubangijinta Ya karɓe ta karɓa mai kyau. Kuma Ya yabanyartar da ita yabanyartarwa mai kyau, kuma Ya sanya rẽnonta ga Zakariyya.
Shin, kun sanya shãyar da mahajjata da rãyar da Masallaci Mai alfarma kamar wanda ya yi ĩmãni da Allah da Rãnar Lãhira, kuma ya yi jihãɗi a cikin hanyar Allah?
Kuma Allah ne Mafi sani ga maƙiyanku, kuma Allah Yã isa Ya zama Majibinci, kuma Yã isa Ya zama Mataimaki.
"Game da gãfarar da Ubangijjĩna ya yi mini, kuma Ya sanya ni a cikin waɗanda aka girmama."
Lalle ne, Allah bã ya shiryar da mutãne azzãlumai.
Kuma idan Muka yi ni'ima ga mutum, sai ya bijire, kuma ya nĩsantar da gẽfensa, kuma idan sharri ya sãme shi, sai ya zama ma'abũcin addu'a mai fãɗi.
Suka ce: "Ya Ubangijinmu!
Don haka sai ku ɗanɗani azãba sabõda abin da kuka kasance kuna yi na kãfirci."
Sa'an nan Muka sanya ka a kan wata sharĩ'a ta al'amarin. Sai ka bĩ ta, Kuma kada kã bi son zũciyõyin waɗannan daba su sani ba.
"Ka dũba yadda Muke sarrafa ãyõyi, tsammãninsu sunã fahimta!"
Mun barranta zuwa gare Ka, ba su kasance mũ suke bautã wa ba."
Maƙaskanta ga idanunsu, wani walakanci yana rufe su. wannan shi ne yinin da suka kasance ana yi musa alkawari (a kansa.)
shin, sũ ne mafĩfĩta kõ kuwa mutãnen Tubba'u, kuma da waɗanda ke a gabãninsu?
Ya ce: "Mẽne ne ya hana ka, ba ka yi sujada ba, alõkacin da Na umurce ka?"
Sai suka kõma wa jũnansu suka ce: "Lalle ne kũ, kũ ne azzãlumai."
Sa'an nan idan kun ƙãre salla, to ku ambaci Allah tsaye da zaune da a kan sãsanninku.
Sai ya ce: "Lalle nĩ, na fĩfĩta son dũkiya daga tunãwar Ubangijina, har (rãnã) ta faku da shãmaki!"
Kuma suka yi musunsu, alhãli zukãtansu sun natsu da su dõmin zãlunci da girman kai.
Kuma Wanda Ya halitta ma'aura dukansu, kuma Ya sanya muku, daga jirgi da dabbõbin ni'ima, abin da kuke hawa.
Rãnar da Muke cẽwa ga Jahannama "Shin, kin cika?"
To, albarkar Allah Ubangijin halittu tã bayyana.
Kuma wanda ya ji tsõron tsayãwa a gaba ga Ubangijinsa yanã da Aljanna biyu.
Sun kasance mafiya ƙarfi daga gare su kuma suka nõmi ƙasa suka rãya ta fiye da yadda suka raya ta, kuma manzanninsu suka je musu da hujjoji bayyanannu.
Kuma ku yi yãƙi a cikin hanyar Allah, kuma ku sani cẽwa lalle ne, Allah Mai jĩ ne, Masani.
Ina rantsuwa da rãnã da hantsinta.
A kan mẽ suke tambayar jũna?
Bã mu rarrabẽwa a tsakãnin daya daga manzanninSa. Kuma (mũminai) suka ce: "Mun ji kuma mun yi dã'a; (Muna nẽman) gãfararKa, yã Ubangijinmu, kuma zuwa a gare Ka makõma take "
Kuma a lõkacin da Muka riƙi alkawarinku kuma Muka ɗaukaka dutse a bisa gare ku, (Muka ce:) "Ku riƙi abin da Muka kãwo muku da ƙarfi kuma ku ji" Suka ce: "Mun ji kuma mun ƙi."
Sai suka sãmi wani bango a cikinta yanã nufin ya karye, sai (Halliru) ya tãyar da shi mĩƙe.
Kuma bã ya kasancẽwa ga mũmini ya kashe wani mũmini, fãce bisa ga kuskure.
To, yanzu ku rungume su kuma ku nẽmi abin da Allah yã rubũta muku.
Lalle ne kai, kanã a kan hanya madaidaiciyl.
M̃.R. Waɗancan ayõyin littãfi ne kuma abin da aka saukar gare ka daga Ubangijinka ne gaskiya, kuma amma mafi yawan mutãne bã su yin ĩmãni.
Kõ wãne ne Ya halitta sammai da ƙasa kuma Ya saukar muku, daga, sama, wani ruwa, Muka tsirar, game da shi, gõnaki mãsu sha'awa, ba ya kasancẽwa gare ku, ku tsirar da itãcensu?
Kuma waɗannan su ne mãsu taƙawa.
Ka bã ni (abõkin zama) daga sãlihan mutãne."
Sa'an nan, Muka mayar da shi mafi ƙasƙantar masu rauni
Da zuwa ga ƙasa yadda aka shimfiɗã ta?
Kuma waɗanda suka kãfirta suka ce wa waɗanda suka yi ĩmãni: "Da (Alƙur'ãni) ya kasance, wani alhẽri ne," dã ba su riga muzuwa gare shi ba.
Ga Allah muka dõgara. Yã Ubangijinmu!
A kan karagu, suna ta kallo.
Bã su tsaron wata zumunta a cikin mũminai, kuma haka bãsu tsaron wata amãna.
Kãmar haka dai, dõmin Mu karkatar da mummũnan aiki da alfãsha daga gare shi.
Wannan shi ne dãɗin rãyuwar dũniya. Kuma Allah a wurinsa kyakkyãwar makõma take.
To shin sunã jiran (wani abu ne) fãce dai hanyar (kãfiran) farko.
Da zuwa ga ƙasa yadda aka shimfiɗã ta?
To, a yau Munã mantãwa da su, kamar yadda suka manta da haɗuwa da yininsu wannan, da kuma abin da suka kasance da ãyoyinMu sunã musu.
Kuma waɗanda suka kãfirta suka ce wa Manzanninsu, "Lalle ne munã fitar da ku daga ƙasarmu, kõ kuwa haƙĩƙa, kunã kõmowã acikin addininmu."
Sabõda haka, lalle, Allah Yanã ɓatar da wanda Yake so, kuma Yanã shiryar da wanda Yake so, sabõda haka kada ranka ya halaka a kansu dômin baƙin ciki.
Kuma ya saukar muku daga dabbõbin gida nau'i takwas Yanã halitta ku a cikin cikunnan uwayenku, halitta a bãyan wata halitta, a cikin duffai uku. Wannan shĩ ne Allah Ubangijinku.
Ka ce: "Ku kãwo hujjarku, wannan shi ne ambaton wanda yake tãre da ni, kuma shi ne ambaton wanda yake a gabãnĩna.
Kuma ya ce: "Ya bãbãna!
Lalle Shi Mai gãfara ne, Mai gõdiya.
"Lalle ne ita ta mũnana ta zama wurin tabbata da mazauni."
Da itãcen lambuna mãsu lillibniya?
Fãce waɗanda suka yi ĩmani, kuma suka aikata ayyukan ƙwarai, kuma suka yi wa juna wasiyya da bin gaskiya, kuma suka yi wa juna wasiyya da yin haƙuri (su kam, basu cikin hasara).
Lalle ne, Ubangijinka Yã sani cẽwa, kai kana tsayuwa a kusan kashi biyu daga uku na dare, da rabinsa, da sulusinsa, tãre da wani ɓangare na waɗanda ke tãre da kai.
Shĩ ne Mai rai, bãbu abin bautãwa fãce Shi.
Ga kõwane mutum daga cikinsu, a rãnar nan akwai wani sha'ani da ya ishe shi.
"Kuma ka ce: 'Ya Ubangijĩna!
Ki kãme."Kuma aka faƙar da ruwan kuma aka hukunta al'amarin, kuma Jirgin ya daidaita a kan Jũdiyyi, kuma aka ce: "Nĩsa ya tabbata ga mutãne azzãlumai."
To, wãne ne mafi zãlunci daga wanda ya ƙirƙira ƙarya ga Allah, dõmin ya ɓatar da mutãne bã da wani ilmi ba?
Kuma wadannan da suka yi ƙõƙari ga nẽman yardarMu, lalle Munã shiryar da su ga hanyõyinMu, kuma lalle Allah, tabbas, Yanã tãre da mãsu kyautatãwa (ga addĩninsu).
Shi ne da hukunci kuma zuwa gare Shi ake mayar da ku.
Bisa ga falala daga Allah da ni'ima.
Ya ce: "Bã zã ka gan Ni ba, kuma amma ka dũba zuwa ga dũtse, to, idan ya tabbata a wurinsa, to, zã ka gan Ni."
Gõdiya ta tabbata ga Allah (a kan bayãni). Ã'a, mafi yawan mutãne ba su sani ba.
Ya halicci sammai da ƙasa da gaskiya.
Ya ce: "Lalle ne, Shi Yana cewa: "Ita wata saniya ce fatsa-fatsa, mai tsan-tsan launi, tana faranta ran mausu kallonta."
Waɗanda ke nĩsantar manyan zunubai da abũbuwan alfãsha, fãce ƙanãnan laifuffuka, lalle Ubangijinka Mai yalwatattar gãfara ne, Shĩ ne Ya fi sani ga abinda ke gare ku a lõkacin da Ya ƙãga halittarku daga ƙasa, kuma a lõkacin da kuke tãyuna a cikin cikannan uwãyenku.
Kuma waɗancan misãlan Munã bayyana su ga mutãne kuma bãbu mai hankalta da su sai mãsu ilmi.
Lalle ne waɗanda suka kãfirta, lalle dã sunã da abin da ke a cikin ƙasa gabã ɗaya da misãlinsa tãre da shi, dõmin su yi fansa da shi daga azãbar Rãnar ¡iyãma, bã a karɓarsa daga gare su, kuma sunã da azãba mai raɗadi.
Lalle ne munãfukai sũ ne fãsiƙai.
Kuma a lõkacin da Ubangijinka ya ce wa malã'iku: "Lalle Nĩ mai halittar wani jiki ne daga ƙẽƙasasshen yumɓu wanda ya canja."
Wannan kuwa, dõmin lalle ne su sun ce: "Wutã bã zã ta shãfe mu ba, fãce a 'yan kwãnaki ƙidãyayyu."
Kuma suka sãmi abin da suka aikata halarce. Kuma Ubangijinka bã Ya zãluntar kõwa.
Idan kun saki mãtã, sai ku sake su ga iddarsu, kuma ku ƙididdige iddar.
"Kuma ka rikitar da wanda ka sãmi ĩko a kansa, daga gare su, da sautinka, kuma ka yi hari a kansu da dawãkinka da dãkãrunka kuma ka yi tãrẽwa da su a cikin dũkiyõyi da ɗiyã, kumaka yi musu wa'adi.
Kuma wanda ya yi ɗã'a ga Allah da ManzonSa, to, lalle, yã rabbanta, babban rabo mai girma.
Kuma suka ce: "Ba ta zama ba, fãce rayuwarmu ta duniya, kuma ba mu zama waɗanda ake tãyarwa ba."
Kuma abin da kuka ciyar, kõ mẽne ne, to, lalle ne Allah, gare shi, Masani ne.
Kuma ka ce: "Gaskiya daga Ubangijinku take." Sabõda haka wanda ya so, to, ya yi ĩmãni, kuma wanda ya so, to, ya kãfirta.
Mai hana alhẽri mai zãlunci, mai zunubi.
Kamar wannan ne Allah Yake bayyana ãyõyinSa a gare ku. Kuma Allah Masani ne, Mai hikima.
Lalle ne, haƙĩƙa, ta yi kusa ta bayyanar da shi, bã dõmin Mun ɗaure zũciyarta ba, dõmin ta kasance daga mũminai.
A kan hanyar Allah (ta gyaran jama'a) a cikin waɗanda suka shũɗe gabãninka, kuma bã zã ka sãmi musanyãwa ba ga hanyar Allah.
Kunã mãsu mai da al'amari gare Shi, kuma ku bĩ Shi dataƙawa, kuma ku tsayar da salla, kuma kada ku kasance daga mushirikai.
Mẽ ya hane ka, sa'ad da kagan su sun ɓace."
"Kuma idan rigarsa ta kasance an tsãge ta daga bãya, to, tã yi ƙarya, kuma shĩ ne daga mãsu gaskiya."
Sai suka kõma wa jũnansu suka ce: "Lalle ne kũ, kũ ne azzãlumai."
Lalle, haƙĩƙa, akwai ãyã ga saba'ãwa a cikin mazauninsu: gõnakin lambu biyu, dama da hagu. "Ku ci daga arzikin Ubangijinku, kuma ku yi gõdiya gare shi.
Mai nẽma da wanda ake nẽman gare shi sun raunana."
Kuma Allah Yã kasance Masani, Mai hikima.
To, a lõkacin da Mũsã ya yi nufin ya damƙi wanda yake maƙiyi ne a gare su, (mai nẽman ãgajin) ya ce, "Ya Mũsã!
Kuma kunã da abũbuwan amfãni a cikinsu, kuma dõmin ku isar da wata buƙãta, a cikin ƙirãzanku a kansu kuma a kansu da a kan jirãge ake, ɗaukar ku.
Ba ya yiwuwa ga wani mutum, Allah Ya bã shi Littãfi da hukunci da Annabci, sa'an nan kuma ya ce wa mutãne: "Ku kasance bãyi gare ni, baicin Allah." Amma (zai ce): "Ku kasance mãsu aikin ibãda da abin da kuka kasance kuna karantar da Littãfin, kuma da abin da kuka kasance kuna karantãwa."
¡auyãwã ne mafi tsananin kãfirci da munãfinci, kuma sũne mafi kamanta ga, rashin sanin haddõjin abin da Allah Ya saukar a kan ManzonSa.
Kuma a lõkacin da Ĩsã ɗan Maryayama ya ce: "Yã BanĩIsrã'ĩla! Lalle nĩ Manzon Allah ne zuwa gare ku, mai gaskata abin da ke gaba gare ni na Attaura, kuma mai bãyar da bushãra da wani Manzo da ke zuwa a bãyãna, SũnasaAhmad (Mashãyabo)."
Gaba gare su (a Lãhira) akwai Jahannama, kuma abin da suka sanã'anta bã ya wadãtar da su daga kõme, kuma abũbuwan da suka riƙa majiɓinta, baicin Allah, bã su wãdatar da su daga kõme.
Ya ce: "Ka sanya ni a kan taskõkin ƙasa. Lalle ne nĩ, mai tsarẽwa ne, kuma masani."
Wanda Allah Ya so Yanã ɓatar da shi, kuma wanda Ya so zai sanya shi a kan hanya madaidaiciya.
Kuma ku tsarkake shi, a sãfiya da maraice.
Kuma ka shiga AljannaTa (a Lãhira).
Kuma sunã tsõratar da kai ga waɗanda suke waninSa, kuma wanda Allah Ya ɓatar to, bã, shi da mai shiryarwa.
Ka ce: "Kõwa ya yi aiki a kan hanyarsa.
Sai waɗanda suke sayar da rayuwar dũniya su karɓi ta Lãhira su yi yãƙi, a cikin hanyar Allah. Kuma wanda ya yi yãki a cikin hanyar Allah to a kashe shi ko kuwa ya rinjãya, sa'an nan zã Mu ba shi ijãra mai girma.
"Kuma Nĩ Nã zãɓe ka.
To, idan ka aikata haka, sa'an nan lalle kai, a lõkacin, kanã daga mãsu zãlunci."
Kuma ga Allah madaidaiciyar hanya take kuma daga gare ta akwai mai karkacẽwa.
Lalle wa'adin Allah gaskiya ne.
Kuma Allah, ga abin da kuke aikatãwa, Mai labartawa ne.
Lalle mutum, haƙĩƙa, mai kãfirci ne.
Suka ce: "Dã mun san (yadda ake) yãƙi dã mun bĩ ku."
Ka ce: "Abin sani kawai, saninta a wurin Ubangijina yake.
Haƙiƙa, tir daga abin da suka kasance sunã sanã'antãwa.
Ashe, ba ka ganĩ ba, lalle ne Allah Yanã kõra girgije, sa'an nan kuma Ya haɗa a tsakãninsa sa'an nan kuma Ya sanya shi mai hauhawar jũna? Sai ka ga ruwa yanã fita daga tsattsakinsa, kuma Ya saukar daga waɗansu duwãtsu a cikinsa na ƙanƙarã daga sama, sai ya sãmu wanda Yake so da shi, kuma Ya karkatar da shi daga barin wanda Yake so.
Sai (wannan magana) ta ƙara musu ĩmãni, kuma suka ce: "Mai isarmu Allah ne kuma mãdalla da wakili Shĩ."
Da shĩ ake narkar da abin da yake a cikin cikunansu da fãtun jikinsu.
Sabõda haka, Muka kama shi tãre da rundunarsa, sa'an nan Muka jẽfa su a cikin tẽku, alhãli kuwa yanã wanda ake zargi.
Ya kai Annabi! Idan kun saki mãtã, sai ku sake su ga iddarsu, kuma ku ƙididdige iddar.
Kuma waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai, waɗannan, 'yan Aljanna ne, sũ a cikinta madawwama ne.
Lalle ne, kãfirai bã su cin nasara.
Ku nẽma da dukiyõyinku, kunã mãsu yin aure, bã mãsu yin zina ba. sa'an nan abin da kuka ji daɗi da shi daga gare su, to, ku bã su ijãrõrinsu bisa farillar sadãki. Bãbu laifia gare ku ga abin da kuka yi yardatayya da shi a bãyan farillar sadãki.
Akwai tsammãnin Allah Ya kange gãfin waɗanda suka kãfirta, kuma Allah ne Mafi tsananin gãfi, kuma Mafi tsananin azabtãwa.
Ku bauta wa Allah; bã ku da wani abin bauta wa waninSa.
Kuma ku yi haƙuri shi ne mafi alhẽri a gare ku.
Kuma idan sun yi niyyar saki, to, lalle ne, Allah Mai ji ne, Masani.
Kuma kãfircin kãfirai bã ya kãra musu kõme fãce baƙin jini, kuma kãfircin kãfirai bã ya kãra musu kõme face hasãra.
Shin, ba ka gani ba zuwa ga wanda ya yi hujjatayya da Ibrãhĩm a cikin (al'amarin) Ubangijinsa dõmin Allah Yã bã shi mulki, a lõkacin da Ibrãhĩm ya ce: "Ubangijina Shi ne Wanda Yake rãyawa kuma Yana matarwa." Ya ce: "Nĩ ina rãyarwa kuma ina matarwa."
Ya ce: "Masani, Mai labartãwa, Ya gaya mini."
Lalle ne shi mai shaida ne a kan laifinsa dl haka.
Kõ kuma sun riƙi waninSa majiɓinta?
Ka gaya musu sũnãyensu." To, a lokacin da ya gaya musu sũnãyensu, (Allah) Ya ce: "Ashe, ban ce muku ba, lalle Ni, Inã sane da gaibin sammai da ƙasa, kuma (Inã sane da) abin da kuke bayyanawa da abin da kuka kasance kuna ɓõyewa?"
Lalle ne a dã sun kasance anã kiran su zuwa, yin sujũdar, alhãli kuwa sunã lãfiya lau, (suka ƙi yi).
Kuma Muka hõre su, sabõda su, sabõda haka daga gare su abin hawansu yake, kuma daga gare su suke ci.
To a lõkacin da ya fãɗi, sai aljannu suka bayyana (ga mutãne) cẽwa dã sun kasance sun san gaibi, dã ba su zauna ba a cikin azãba mai wulãkantarwa.
Lalle haƙĩƙa waɗanda suka ce: "Lalle Allah Shĩ ne Masĩhu ɗan Maryama," sun kãfirta.
Suka ce: "Ubangijinku ne Mafi sani ga abin da kuka zauna.
Kuma Ubangijinka Ya isa Ya zama wakĩli."
Don me Ka wajabta yãƙi a kanmu?
Ka ce: "Allah ne mafi gaggãwar (sakamakon) mãkirci." Lalle ne ManzanninMu sunã rubũta abin da kuke yi na mãkirci.
Kuma akwai daga mutãne wanda ke yin jidãli ga al'amarin Allah, bã da wani ilmi ba, kuma bã da wata shiriya ba, kumã ba da wani littãfi mai haskakãwa ba.
"Kuma kãmar wancan ne, Ubangijinka Yake zãɓen ka, kuma Ya sanar da kai daga fassarar lãbãrai, kuma ya cika ni'imõminSa a kanka, kuma a kan gidan Yãƙũba kãmar yadda ya cika su a kan ubanninka biyu, a gabãni, Ibrãhĩm da Is'hãƙa.
Sabõda haka Muka yi musu azãbar rãmuwa.
Shin, ba ka gani ba, zuwa ga waɗanda suke tsarkake kansu?
Lalle ne, Allah, Mai ƙididdigewa ne ga abin da suke sanã'antãwa.
Kuma wanda ya aikata gwargwadon nauyin zarra na sharri, zai gan shi.
Shin, to, ba su yi dubi ba zuwa ga samã a bisa gare su, yadda Muka gĩna ta, kuma Muka ƙawãce ta, kuma bã ta da waɗansu tsãgogi?
Kuma idan aka ce musu, "Ku ciyar daga abin da Allah Ya azurta ku," sai waɗanda suka kãfirta su ce ga waɗanda suka yi ĩmãni, "Ashe, zã mu ciyar da wanda idan Allah Ya so Yanã ciyar da shi?
Kuma daga mutãne da dabbõbi da bisãshen gida, mãsu sãɓãnin launinsu kamar wancan.
Kuma wani mutum ya zo daga mafi nĩsan birnin yanã taliya da gaggãwa, ya ce: "Ya Mũsã!
Idan ka gan ni, ni ne mafi ƙaranci daga gare ka a wajen dũkiya da ɗiya."
Kuma lalle ne Ubangijinka, haƙĩƙa, Ma'abũcin gãfara ne ga mutãne a kan zãluncinsu, kuma lalle ne Ubangijinka, haƙĩƙa, Mai tsananin uƙũba ne.
Kuma Muka ɓuɓɓugar da ƙasã ta zama idãnun ruwa, daɗa ruwa ya haɗu a kan wani umurni da aka riga aka ƙaddara shi.
Lalle ne, waɗanda suke cĩn dũkiyar marãyu da zãlunci, to, wuta kawai suke ci a cikin cikkunansu, kuma za su shiga cikin wata wuta mai tsanani.
Lalle Allah ne Mai gãfara Mai haƙuri.
Kuma akwai daga cikin ãyõyinSa, Ya nũna muku walƙiya a kan tsõro da ɗammãni kuma Ya dinga saukar da ruwa daga sama Sa'an nan Ya rãyar da ƙasã game da shi a bãyan mutuwarta.
Wannan shĩ ne siffarsu a cikin Attaura. Kuma siffarsu, a cikin Injĩla ita ce kamar tsiron shũka wanda ya fitar da rẽshensa, sa'an nan ya ƙarfafa shi, ya yi kauri, sa'an nan ya daidaita a kan ƙafãfunsa, yanã bãyar da sha'awa ga mãsu shũkar' dõmin (Allah) Ya fusãtar da kãfirai game da su.
Waɗanda suka kyautata a cikin wannan dũniya sunã da sakamako mai kyau, kuma ƙasar Allah mai fãɗi ce.
Tana kusa ta tsãge domin hushi, ko da yaushe aka jẽfa wani ɓangaren jama'a a cikinta, matsaranta na tambayar su da cewa, "Wani mai gargaɗi bai je muku ba?"
Kuma bãbu abin da ya hana mutãne su yi ĩmãni, a lõkacin da shiriya ta jẽ musu, fãce sunce, "Shin, Allah zai aiko mutum ya zamo yana Manzo."
Dukan Kõwanensu mãsu Kõmõwa zuwa gare Ni
Sai ka ga waɗanda a cikin zukatansu akwai cuta, sunã tseren gaugawa a cikinsu, sunã cewa: "Munã tsõron kada wata masĩfa ta sãme mu."
lnda hanyar zargi kawai take, shĩ ne a kan waɗanda ke zãluntar mutãne kuma sunã ƙẽtare haddin shari'a cikin ƙasa bã tare da haƙƙi ba. Waɗannan sunã da azãba Mai raɗaɗi.
Mutãnen Nũhu sun ƙaryata, a gabãninsu, sai suka ƙaryata BawanMu, kuma suka ce: "Shi mahaukaci ne." Kuma aka tsãwace shi.
Sai aka ɗimautar da wanda yakãfirta.
Ãdãwa sun ƙaryata Manzanni.
Lalle ne Allah Yã zãɓi Ãdama da Nũhu da Gidan Ibrãhĩma da Gidan Imrãna a kan tãlikai.
Wanda ya kau da kai daga gare shi, to, lalle shĩ, yanãɗaukar wani nauyi a Rãnar ¡iyãma.
Kuma waɗanda bã su kiran wani ubangiji tãre da Allah, kuma bã su kashe rai wanda Allah Ya haramta fãce da hakki kuma bã su yin zina. Kuma wanda ya aikata wancan, zai gamu da laifuffuka,
To, idan ba ku sãmi kõwa a cikinsu ba, to, kada ku shige su, sai an yi muku izni.
Bãbu shakka lalle ne sunã da wuta, kuma lalle sũ, waɗanda ake ƙyãlẽwa ne (a cikinta).
Ya ce: "Ashe, kun yi ĩmãni sabõda shĩ, a gabãnin in yi muku izni?
Kuma mẽ ya sanar da kai abin da ake cẽwa kiran gaskiya?
Makangara suka ce wa maraunana, "Ashe, mũ ne muka kange ku daga shiriya a bãyan ya zo muku?
"Lalle ne, shi ya kasance ba ya yin ĩmãni da Allah, Mai girma!"
"To! Idan kun jũya, haƙĩƙa, nã iyar muku abin da aka aiko ni da shi zuwa gare ku.
Ashe fa, ba su yi tafiya a cikin ƙasã ba, dõmin su dũba yadda ãƙibar waɗanda ke a gabãninsu ta kasance?
Bã ya kasancewa a gare ni, in faɗi abin da bãbu wani hakki a gare ni.
Kuma Allah Yã kasance Mai ji, Masani.
Kuma bone yã tabbata ga kãfirai daga azãba mai tsanani.
A lõkacin da Ubangijinka Ya ce wa malã'iku, "Lalle Nĩ Mai halitta mutum ne daga lãkã.
Kuma Kai ne Mafi alhẽrin mãsu saukarwa.'"
Yã kũ mutãne! Kũ ne mãsu bukãta zuwa ga Allah, kuma Allah, Shĩ ne Mawadãci, Gõdadde.
Kuma wãne ne ya fi zãlunci bisa ga wanda ya ƙirƙira ƙarya ya jingina ta ga Allah, kõ kuma ya ƙaryata gaskiya a lõkacin da ta je masa?
Kuma Fir'auna ya yi kira a cikin mutãnensa, ya ce: "Ya mutãnẽna! Ashe mulkin Masar bã a gare ni yake ba, kuma waɗannan kõguna sunã gudãna daga ƙarƙashĩna?
An la'ani mutãnen rãmi.
Lalle ne haƙĩƙa Allah Ya gaskata wa ManzonSa mafarkinsa da gaskiya: Lalle zã ku shiga Masallacin Harami, in Allah Ya so, kunã mãsu natsuwa, mãsu aske kawunanku da mãsu suisuye, bã ku jin tsõro, dõmin (Allah) Ya san abin da ba ku sani ba, sa'an nan Ya sanya wani cin nasara makusanci a bãyan wannan.
Lalle Shi, Shi ne Mai ji, Masani.
Kada ku jiɓinci waɗansu mutãne da Allah Ya yi hushi a kansu.
Idan kunã iya zarcẽwa daga sãsannin sammai da ƙasã to ku zarce. Bã za ku iya zarcẽwaba fãce da wani dalĩli.
Ashe, ba ka gani ba ga waɗanda ke jãyayya a cikin ãyõyin Allah, yadda ake karkatar da su?
Shin, kuma ba su gani ba cẽwa Allah na shimfida arziki ga wanda Yake so kuma Yanã ƙuntatãwa?
To, waɗanda suka yi hijira kuma aka fitar da su daga gidãjensu, kuma aka cũtar da su a cikin hanyaTa, kuma suka yi yãƙi, kuma aka kashe su, lalle ne zan kankare musumiyagun ayyukansu, kuma lalle ne zan shigar da su gidãjen Aljanna (waɗanda) ƙoramu ke gudãna daga ƙarƙashinsu, a kan sakamako daga wurin Allah. Kuma a wurinSa akwai kyakkyawan sakamako.
Kuma bãbu mai tunãni fãce ma'abũta hankula.
Har sa'ad da aka bũde Yãjũju da Mãjũju alhãli kuwa sunã gaggãwa daga kõwane tudun ƙasa.
Kuma wancan shi ne babban rabo, mai girma.
Kuma Allah Yanã buga misãli ga mutãne, mai yiwuwã ne, sunã tunãwa.
Sabõda haka idan kun haɗu da waɗanda suka kãfirta, sai ku yi ta dũkan wuyõyinsu har a lõkacin da suka yawaita musu kisa, to, ku tsananta ɗaurinsu sa'an nan imma karimci a bãyan' haka kõ biyan fansa, har yãƙi ya saukar da kayansa mãsu nauyi. Wancan, dã Allah nã so da Ya ci nasara a kansu (ba tare da yaƙin ba) kuma amma (ya wajabta jihadi) dõmin Ya jarraba sãshenku da sãshe.
Mun halaka su, lalle sũ, sun kasance mãsu laifi.
Kuma Allah yã kasance Mabuwãyi, Mai hikima.
Kuma idan kuka sãka wa uƙũba to ku sãka wa uƙũba da misãlin abin da aka yi muku uƙũbar da shi. Kuma idan kun yi haƙuri, lalle shĩ ne mafi alhẽri ga mãsu haƙuri.
Sai gã igiyoyinsu da sandunansu anã sũranta su a gare shi, daga sihirinsu, lalle sunã tafiya da sauri.
Kuma lalle ne Allah bai zama mai zãlunci ga bãyinsa ba."
Ka bã mu a cikin dũniya!
A can taimako da jiɓinta ga Allah yake.
Kuma dã Allah Yanã kãma mutãne sabõda abin da suka aikata, dã bai bar wata dabba ba a kanta (kasã).
To, idan sun jũya bã ya sai ku ce: "ku yi shaida cẽwa, lalle ne mu masu sallamã wa ne."
"Kuma Allah Ya sanya muku ƙasa shimfidaɗɗiya."
Zũciyar (Annabi) bata ƙaryata abin da ya gani ba.
Lalle ne waɗanda bã su yin ĩmãni da ãyõyin Allah, Allahbã zai shiryar da su ba, kuma sunã da azãba mai raɗaɗi.
Lalle ne, wãjibi ne a gare Mu, Mu tãra shi. Mu (tsare maka) karãtunsa.
Lalle Allah ne Mai gãfara, Mai jin ƙai.
Suka ce: "Kaitonmu!
Lalle ne haƙĩƙa waɗanda suka ce: "Lalle ne Allah, shĩne Masĩhu, ɗan Maryama," sun kãfirta. Alhãli kuwa Masĩhu yã ce: "Yã Banĩ Isrã'ĩla!
Lalle ne waɗanda sauka sãɓã wa jũna a cikin sha'aninsa lalle ne, sunã shakka daga gare, shi, bã da wani ilmi fãce bin zato kuma ba su kashe shi ba bisa ga yaƙĩni.
To, wanda ya tuba a bãyan zãluncinsa, kuma ya gyãra (halinsa), to, lalle ne Allah Yanã karɓar tubarsa. Lalle Allah Mai gãfara ne, Mai jin ƙai.
Haƙĩƙa, tir da abin da suka kasance suna aikatãwa.
Kuma mẽne ne ya sãme ku, bã zã ku ci ba daga abin da aka ambaci sũnan Allah a kansa, alhãli kuwa, haƙĩƙa, Ya rarrabe, muku daki-daki, abin da Ya haramta a kanku, fãce fa abin da aka bukãtar da ku bisa lalũra zuwa gare shi?
To, lalle ne su, sũ ne wãwãye, kuma amma bã su sani.
"Kuma lalle ne mũ haƙĩƙa gabã ɗaya mãsu sauna ne."
Kuma waɗanda suka yi ĩmãni, kuma suka aikata ayyukan ƙwarai, zã mu shigar da su gidãjen Aljanna (waɗanda) ƙõramu sunã gudãna a ƙarƙashinsu, sunã mãsu dawwama a cikinsu har abada bisa ga wa'adin Allah tabbatacce.
Allah Yã la'ance su! Yãya aka karkatar da su?
Kuma kada ku aibanta kanku, kuma kada ku jẽfi jũna da miyãgun sunãye na laƙabõbĩ.
Lalle waɗannan mutãne ne waɗanda bã zã su yi ĩmãni ba."
Yã kũ waɗanda suka yi ĩmãni! Ku bi Allah da taƙawa kuma ku faɗi magana madaidaiciya.
Allah Yanã nufin Ya bayyana muku, kuma Ya shiryar da ku hanyõyin waɗanda suke a gabãninku kuma Ya karɓi tũbarku. Kuma Allah Masani ne Mai hikima.
Lalle Allah Yã kasance Mai tausasãwa Mai labartawa.
Kuma waɗannan ne mãsu ta'adi.
Akwai malã'iku da yawa a cikin sammai cẽtonsu bã ya wadãtar da kõme fãce bãyan Allah Yã yi izni (da shi) ga wanda Yake so, kuma Yake yarda.
Jidalin ya girma ga zamansa abin ki a wurin Allah da wurin waɗanda suka yi ĩmãni.
Suka ce: "Wane ne ya aikata wannan ga gumãkanmu?
Kuma Allah bai kasance mai ɓatar da mutãne a bãyan Yã shiryar da su ba, sai Ya bayyanã musu abin da zã su yi taƙawa da shi. Lalle ne Alllh, ga kõme, Masani ne.
Yã kũ waɗanda suka yi ĩmãni! Ku nĩsanci abu mai yãwa na zato.
Sunã gincire a kan waɗansu shimfiɗu cikinsu tufãfin alharĩni mai kauri ne kuma nũnannun 'yã'yan itãcen Aljannar biyu kusakusa suke.
Kuma lalle ta ƙarshe ce mafi alheri a gare ka daga ta farko.
Kuma Muka sanya su shugabanni, sunã shiryarwa da umurninMu.
Kuma mashawarta daga mutãnen Fir'auna suka ce: "Shin, zã ka bar Mũsã da mutãnensa dõmin su yi ɓarna a cikin ƙasa, kuma ya bar ka, kai da gumãkanka?"
Lalle, shi, mai mayar da al'amari ga Allah ne.
Bãbu laifi a kanku kuma bãbu a kansu a bãyansu. Sũ mãsu kẽwaya ne a kanku sãshenku a kan sãshe.
Ya ce: "Kayya!
Kuma kanã ganin duwãtsu, kanã zaton su sandararru, alhãli kuwa sũ sunã shũɗẽwa shũɗewar girgije, bisa sanã'ar Allah wanda Ya kyautata kõwane abu.
Lalle Ubangjina Mai gãfara ne, Mai jin ƙai."
Iramawa mãsu sakon ƙĩrar jiki.
Lalle Allah Mai gãfara ne, Mai jin ƙai.
To, wanda ya kãfirta da Allah da malã'ikunSa, da LittattafanSa, da ManzanninSa, da Rãnar Lãhira, to, lalle ne yã ɓace, ɓata mai nĩsa.
Waɗanda suka ce wa 'yan'uwansu kuma suka zauna abinsu: "Dã sun yi mana ɗã'a, dã ba a kashe su ba."
Sũ mãtan bã su halatta ga aurensu, sũ kuma kãfiran bã su halatta ga auren mãtan.
Ya ce: "Kuma wãne ne yake yanke tsammãni daga rahamar Ubangijinsa, fãce ɓatattu?"
Bã su jin wata yãsassar magana a cikinta, kuma bã su jin sun yi laifi.
Kuma mutãnensa suka je masa sunã gaggãwa zuwa gare shi, kuma a gabãni, sun kasance sunã aikatãwar mũnãnan ayyuka.
Kuma sai mutãnen injĩla su yi hukunci da abin da Allah ya saukar a cikinta. Kuma wanda bai yi hukunci ba da abin da Allah ya saukar, to, waɗannan su ne fãsiƙai.
Bãbu kõme a gare ka game da al'amarin (shiryar da su banda iyar da manzanci). Ko Allah Ya karɓi tũbarsu, kõ kuwa Ya yimusu azãba, to lalle ne sũ, mãsu zãlunci ne.
(Sai a ce masa): "Lalle ne, haƙĩƙa, ka kasance a cikin gafala daga wannan. To, Mun kuranye maka rufinka, sabõda haka ganinka a yau, mai kaifi ne."
Lalle haƙĩƙa waɗanda suka ce: "Lalle Allah Shĩ ne Masĩhu ɗan Maryama," sun kãfirta.
Kuma a Rãnar ¡iyãma kanã ganin waɗanda suka yi ƙarya ga Allah fuskõkinsu sunã mãsu yin baƙi.
Ya ɗaukaka rufinta, sa'an nan Ya daidaita ta.
Fir'auna ya ce: "Ashe, kun yi ĩmãni da shi a gabãnin inyi izni a gare ku?
Shĩ ne wanda Ya aiki ManzonSa da shiriya da addinin gaskiya dõmin Ya rinjãyar da shi a kan addinai dukansu.
(Allah) Shĩ ne Wanda ke tsarkake ku, da mala'ikunSa (sunã yi muku addu'a), dõmin Ya fitar da ku daga duffai zuwa ga haske. Kuma (Allah) Yã kasance Mai Jĩn ƙai ga mũminai.
Shin, akwai ilmin gaibi a wurinsa, Sabõda haka yanã ganin gaibin?
Yã kũ waɗanda suka yi ĩmãni!
Sai Ubangijinsa Ya karɓa masa sabõda haka Ya karkatar da kaidinsu daga gare shi.
Ba su sãɓa ba fãce bãyan ilmi ya jẽ musu, sabõda zãlunci a tsakãninsu. Lalle ne, Ubangijinka zai yi hukunci a tsakãninsu, a Rãnar ƙiyãma a cikin abin da suka kasance sunã sãɓa wa (jũna).
Kamar haka Muka hõre muku su, tsammãninku kunã gõdẽwa.
Ya ce: "Na zauna yini ɗaya ko kuwa rabin yini."
Aka ce, "Ku shiga ƙõfõfin Jahannama, kaunã madawwama a cikinta.
Kuma bãbu wata al'umma fãce wani mai gargaɗi yã shũɗe a cikinta.
Kuma idan kun kwance harama, to, ku yi farauta.
Kuma a lõkacin da muka tsĩrar da ku daga mutãnen Fir'auna, su na taya muku muguntar azãba, su na yayyanke ɗiyanku maza su na rãyar da mãtanku.
"Fãce wanda ya jẽ wa Allah da zũciya mai tsarki."
Yi tafiyar shirin ayuka ta shigar da wata umarni
Kuma mutãnenka sun ƙaryata (ka) game da Shi, alhãli kuwa Shi ne gaskiya.
Ka bai wa bãyiNa lãbari cẽwa lalle ne Ni, Mai gãfarane, Mai jin ƙai.
Kuma Ya sako, a kansu, wasu tsuntsãye, jama'a-jama'a.
A lõkacin da suka zo muku daga samanku da kuma ƙasa daga gare ku, kuma a lõkacin da gannai suka karkata kuma zukãta suka kai ga maƙõsai, kuma kuka yi zaton zace-zace, game da Allah.
Sai tsãwa ta kãmã su, sabõda haka suka wãyi gari a cikin gidansu guggurfãne!
Shi ne wanda ya saukar da Littãfi a gare ka, daga cikinsa akwai ãyõyi bayyanannu, su ne mafi yawan Littãfin, da wasu mãsu kamã da jũna.
Kuma lalle kanã sanin su ga shaguɓen magana, alhali kuwa Allah Yanã sanin ayyukanku.
Kuma abin da kuka gabãtar dõmin kanku daga alhẽri, zã ku sãme shi a wurin Allah. Lalle ne Allah, ga abin da kuke aikatãwa Mai gani ne.
Zã mu yi awo. Kuma lalle ne, haƙĩƙa mũ, mãsu lũra da Shi ne."
Kuma wata ƙungiya daga gare su na nẽman izni ga Annabi sunãcẽwa, "Lalle gidãjenmu kuranye suke," alhãli kuwa bã kuranye suke ba, bã su da nufin kome fãce gudu.
Mãsu haƙuri kawai ake cika wa ijãrarsu, bã da wani lissãfi ba.
Da Zakariyya da Yahaya da Isa da Ilyasu dukansu daga sãlihai suke.
Haƙĩƙa, lalle ne sũ daga Ubangijinsu, rãnar nan, waɗanda ake shãmakancẽwa ne.
(Kuma kada ku yi ĩmãni) cẽwa an bai wa wani irin abin da aka bã ku, kõ kuwa su yi musu da ku a wurin Ubangijinku."
Mũsã ya ce wa mutãnensa: "Ku nẽmi taimako da Allah, kuma ku yi haƙuri; Lalle ne ƙasa ta Allah ce, Yãna gãdar da ita ga wanda Yake so daga bãyinSa, kuma ãƙiba ta mãsu taƙawa ce."
Kuma Allah Ya kasance Mai gani ga abin da kuke aikatãwa.
Ka ce: "Ku yi ĩmãni da Shi, ko kuwa kada ku yi ĩmãni, lalle ne waɗanda aka bai wa ilmi daga gabãninsa, idan anã karãtunsa a kansu, sunã fãɗuwa ga haɓõɓinsu, sunã mãsu sujada."
A yau an halatta muku abũbuwa mãsu dãɗi kuma abincin waɗanda aka bai wa Littãfi halal ne a gare ku, kuma abincinku halal ne a gare su, da mãtã mãsu kãmun kai daga muminai da mãtã 'yã'ya daga waɗanda aka bai wa Littãfi a gabãninku idan kun je musu da sadãkõkinsu, kuna mãsu yin aure, ba masu yin zina ba, kuma bã mãsu riƙon abõkai ba.
Kuma a cikin sama arzikinku (yake fitõwa) da abin da ake yi muku alkawari.
Kuma kãfirai zã su sani, ga wane ãƙibar gida take.
Sun riƙi rantsuwõwinsu garkuwa, sai suka taushe daga tafarkin Allah.
Ashe, kuma mutum bai ga (cẽwa) lalle Mũ, Mun halitta shi daga maniyyi ba, sai gã shi mai yawan husũma, mai bayyanãwar husũmar.
Shin, a wurinsu akwai ilmin gaibi, sabõda haka sunã rubũtãwa?
Kuma idan kun yi haƙuri, kuma kuka yi taƙawa, to lalle ne, wannan yana daga manyan al'amurra.
Kuma Muka yi albarka a gare shi, kuma ga Is'hãka.
Kuma wanda ya bi Allah da taƙawa, Allah zai kankare masa mũnãnan ayyukansa, kuma Ya girmama masa sãkamako.
Sai ka ga ruwa yanã fita daga tsattsakinsa, kuma Ya saukar daga waɗansu duwãtsu a cikinsa na ƙanƙarã daga sama, sai ya sãmu wanda Yake so da shi, kuma Ya karkatar da shi daga barin wanda Yake so. Hasken walƙiyarsa Yanã kusa ya tafi da gannai.
Kuma a lõkacin da Mũsã yace wa mutãnensa, "Ku tuna ni'imar Allah a kanku a lõkacin da Ya tsĩrar da ku daga mutãnen Fir'auna, sunã yi muku mummunar azãba, kuma sunã yanyanka ɗiyanku, kuma sunã rãyar da mãtanku.
Lalle Mũ, Mun ƙãga halittarsu ƙãgãwa.
Kuma zuwa gare Mu ake mayar da ku.
To, da wace daga ni'imõmin Ubangijinka kake yin shakka?
Kuma dã Allah Yanã kãma mutãne sabõda abin da suka aikata, dã bai bar wata dabba ba a kanta (kasã).
Sai Yũsufu ya bõye ta a cikin ransa. Kuma bai bayyana ta ba a gare su, ya ce: "Kũ ne mafi sharri ga wuri.
A lõkacin da kuke nẽman Ubangijinku tairnako, sai Ya karɓa muku cẽwa: "Lalle ne Nĩ, Mai taimakon ku ne da dubu daga malã'iku, jẽre."
Allah ba Ya kãmã ku da laifi sabõda yãsasshiya a cikin rantsuwõyinku. Kuma amma Yana kama ku sabõda abin da zukãtanku suka sanã'anta.
Allah na nufin Ya tafiyar da ƙazamta kawai daga gare ku, yã mutãnen Babban Gida! Kuma Ya tsarkake ku, tsarkakẽwa.
Kuma a Rãnar ¡iyãma ana mayar da su zuwa ga mafi tsananin azãba.
Dõmin Allah Ya shãfe abin da ya gabãta na laifinka da abin da ya jinkirta, kuma Ya cika ni'imarSa a kanka, kuma Ya shiryar da kai ga hanya madaidaiciya.
Lalle ne waɗanda suka zo da ƙiren ƙarya waɗansu jama'a ne daga gare ku, kada ku yi zatonsa sharri ne a gare ku.
Kuma rãnar da Yake tãra su, kamar ba su zauna ba fãce sa'a guda daga yini. Sunã gãne jũna a tsakãninsu.
Kuma suka ɓõye shi yanã abin sayarwa.
Sa'an nan kuma bã za ka sãmi wani wakĩli ba dõminka game da shi a kanMu.
"Yã kũ mutãnẽna!
Ka ce: "Ku zo, in karanta abin da Ubangijinku Ya haramta." wãjibi ne a kanku kada ku yi shirkin kõme da Shi, kuma ga mahaifa biyu (ku kyautata) kyautatãwa, kuma kada ku kashe ɗiyanku sabõda talauci, Mũ ne Muke azurta ku, kũ da su, kuma kada ku kusanci abũbuwa alfãsha, abin da ya bayyana daga gare ta da abin da ya ɓõyu, kada ku kashe rai wanda Allah Ya haramta, fãce da hakki. Wannan ne (Allah) Ya yi muku wasiyya da Shi: Tsammãninku, kunã hankalta.
Mãtar Azĩz ta ce: "Yanzu fagaskiya ta bayyana.
Kuma a lõkacin da muka yi wa'adi ga Mũsa, dare arba'in, sa'an nan kuma kuka riƙi maraƙi daga bãyansa, alhãli kũ, kuna mãsu zãlunci (da bauta masa).
Mẽne ne ya yi jinsu, kuma mẽne ne ya yi ganinsu a rãnar da suke zo Mana!
Ma'abũcin ƙarfi da kwarjini, sa'an nan ya daidaita.
Kada mũminai su riƙi kãfirai masõya, baicin mũminai. Kuma wanda ya yi wannan, to, bai zama a cikin kõme ba daga Allah, fãce fa dõmin ku yi tsaro daga gare su da 'yar kãriya.
Kuma dũbi dai Munã bã da lãbãri a gare ka daga lãbarun Manzanni, abin da Muke tabbatar da zuciyarka da shi.
Shin, ba ka gani ba cẽwa lalle ne Allah Yã halicci sammai bakwai da ƙasa da mallakarSa.
"Sa'an nan idan ba ku zo mini da shĩ ba, to, bãbu awoa gare ku a wurĩna, kuma kada ku, kasance ni."
To, bã zã ka sãmi musanya ba ga hanyar Allah. Kuma bã zã ka sãmi jũyarwa ba ga hanyar Allah.
Alhãli kuwa su suna ɗaukar kayansu masu nauyi a kan bayayyakinsu. To, abin da suke ɗauka yã mũnana.
Sai ya ce: "Lalle nĩ, na fĩfĩta son dũkiya daga tunãwar Ubangijina, har (rãnã) ta faku da shãmaki!"
Ayyukansu sun ɓãci, sabõda haka suka wãyi gari sunã mãsu hasãra.
Kai muke bauta wa, kuma Kai muke neman taimakonKa.
Kuma Allah ne Masani ga mãsu taƙawa.
Ashe, ba ku gani ba, cẽwa Allah Yã hõre muku abin da ke a cikin sammai da abin da ke a cikin ƙasã, kuma Ya zuba ni'imõminsa a kanku, bayyanannu da ɓõyayyu?
Kuma kada ku kasance kamar wadda ta warware zarenta a bãyan tukka, ya zama warwararku, kunã riƙon rantsuwõyinku dõmin yaudara a tsakãninku, dõmin kasancẽwar wata al'umma tãfi rĩba daga wata al'umma!
Sa'an nan kuma muka yãfe muku daga bãyan wancan, tsammãninku, kuna gõdẽwa.
"Waɗanda suke kangẽwa daga hanyar Allah, kuma sunã nẽman ta ta zama karkatacciya,. kuma sũ, game da Lãhira, kãfirai ne."
Ku bauta wa Allah.
Kuma waɗanda suke riƙẽwa da laittãfi kuma suka tsayar da salla, lalle ne Mũ, bã Mu tõzarta lãdar mãsu gyãrãwa.
Kuma ku tsaĩ da salla, kuma ku bãyar da zakka, ku yi ɗã, ã ga Allah da ManzonSa.
Kuma kun kasance nau'i uku.
Akwai gidãjen Aljanna a wurin Ubangiji sabõda waɗanda suka bi Shi da taƙawa, kõguna suna gudãna daga ƙarƙashinsu, suna madawwama a cikinsu, da mãtan aure tsarkakakku, da yarda daga Allah.
Lalle Mũ Mun saukar da littãfi a gare ka dõmin mutãne da gaskiya.
To, ka dũba mẽ ka gani?"
Kuma lalle, haƙĩƙa, Mun bai wa Dãwũda wata falala dagagare Mu. Yã duwatsu, ku konkõma sautin tasbihi tãre da shi kuma da tsuntsãye.
Ã'a, waɗancan sũ ne azzãlumai.
Shin, kuma a kõ da yaushe suka ƙulla wani alkawari sai wani ɓangare daga gare su ya, yi jĩfa da shi?
To, a lõkacin da ta haife ta sai ta ce: "Ya Ubangijina!
Zã a karya tãron, kuma su jũya bãya dõmin gudu.
Shin, ka ga wannan da ya jũya baya?
Shin kuma kun ga abin da kuke fitarwa na maniyyi?
Kuma a lõkacin da suka bũɗe kãyansu, suka sãmi hajjarsu an mayar musu da ita, suka ce: "Yã bãbanmu!
Kuma Muka bar (yabo) a gare su a cikin mutãnen karshe.
Shin, a cikin zukãtansu akwai cũta ne, ko kuwa sunã tsõron Allah Ya yi zãlunci a kansu da ManzonSa?
Mãsu rassan itãce.
Shin, kunã jãyayya da ni a cikin wasu sunãye waɗanda kũ ne kuka yi musu sunãyen, kũ da ubanninku, Allah bai saukar da wani dalili ba a gare su? To, ku yi jira.
Kuma manzannin Mu na tãre da su sunã rubũtãwa.
Lalle ne munãfukai sũ ne fãsiƙai.
Sabõda rahama daga Ubangijinka.
Ka sanyã ni mai tsayar da salla. Kuma daga zũriyyata.
Kuma kunã da rabin abin da mãtanku na aure suka bari idan rẽshe bai kasance gare su ba.
Dã ka lẽka (a kan) su (dã) lalle ne, ka jũya daga gare su a guje kuma (dã) lalle ne ka cika da tsõro daga gare su.
Manzo, yanã karãtun ãyõyin Allah bayyananu a kanku dõmin Ya fitar da waɗanda suka yi ĩmãni kuma suka aikata ayyukan ƙwarai daga duffai zuwa ga haske.
Lalle Allah Yã kasance Mai tausasãwa Mai labartawa.
Kuma daga cikinsu akwai waɗanda suke saurare zuwa gare ka.
Kuma kada ku aibanta kanku, kuma kada ku jẽfi jũna da miyãgun sunãye na laƙabõbĩ.
Kuma lalle ne Sã'a (Rãnar Alƙiyãma) haƙĩƙa mai zuwa ce. Sabõdahaka ka yi rangwame, rangwame mai kyau.
Kuma lalle shi (Alƙur'ãni), haƙĩƙa, saukarwar Ubangijinhalittu ne.
Lalle ne mũ, zuwa ga Allah mãsu kwaɗayi ne."
Kuma wanda ya kãfirta da ãyõyin Allah, to, lalle ne Allah Mai gaugãwar sakamako ne.
Kiransu a cikinta, "TsarkinKa yã Allah!"
Lalle ne Shĩ, Yã kasance a gare ku Mai jin ƙai.
Lalle, a cikin wancan akwai ãyã ga dukan bãwã mai maida al'amarinsa ga Allah.
Yã bãyiNa, waɗanda suka yi ĩmãni! Lalle fa ƙasãTa mai yalwã ce, sabãda haka ku bauta Mini.
Kada ku ce ga waɗanda ake kashẽwa a cikin hanyar Allah: "Matattu ne."
Amma kuma bãbu waɗanda suka yi ĩmãni tãre da shi fãce kaɗan."
Dã Yanã kãma su sabõda abin da suka sanã'anta, lalle ne, dã Ya gaggauta azãba a gare su.
Ku yi ĩmãni da Allah da ManzonSa, kuma ku ciyar daga abin da Allah Ya wakilta ku a cikinsa (na dũkiya).
Ya ce: "Shin, kan san abin da kuka aikata ga Yũsufu da ɗan'uwansa a lõkacin da kuke jãhilai?"
Sai suka kõmo da fushi game da wani fushi.
Sabõda haka, ka bar su!
Ya ku waɗanda suka yi ĩmãni! Ku ciyar daga mai kyaun abin da kuka sanã'anta, kuma daga abin da Muka fitar sabõda ku daga ƙasa, kuma kada ku yi nufin mummuna ya zama daga gare shi ne kuke ciyarwa, alhãli kuwa ba ku zama mãsu karɓarsa ba fãce kun runtse ido a cikinsa.
Sai Muka yi wahayi zuwa gare shi. "Ka sana'anta jirgin bisa ga idonMu, da wahayinMu.
Lalle, Allah Shĩ ne Mawadãci, Gõdadde.
To, kada ka yi baƙin ciki a kan mutãne kãfirai.
Suka ce: "Na'am."
Ya ce: "Aminci ya tabbata a gare ka! zan nẽmi Ubangijina Ya gãfarta maka.
"Kwatankwacin al'adar mutãnen Nũhu da Ãdãwa da Samũdãwa da waɗanda ke a bãyansu.
Dukan abinci yã kasance halal ne ga Bani lsrã'ĩla, fãce abinda Isrã'ĩla ya haramta wa kansadaga gabãnin saukar da Attaura.
Idan an goge wani durowa, za'a rasa durowar da kewayen sa
Kamar dai sũ, a rãnar da suke ganin (sakamako) abin da ake yi musu wa'adi ba su zauna ba, fãce sa'a guda daga yini.
Lalle ne Shĩ ne Masani, Mai hikima."
Ashe, ba ka ga cẽwa lalle Allah Yanã sane da abin da yake a cikin sammai da abin da ke cikin ƙasa ba?
Da waɗanda suka zaunar da gidãjensu (ga Musulunci) kuma (suka zãɓi) ĩmãni, a gabãnin zuwansu, sunã son wanda ya yi hijira zuwa gare su, kuma bã su tunãnin wata bukãta a cikin ƙirãzansu daga abin da aka bai wa muhãjirĩna, kuma sunã fĩfĩta waɗansu a kan kãwunansu, kuma ko dã sunã da wata larũra. Wanda ya sãɓã wa rõwar ransa, to, waɗannan sũ ne mãsu babban rabo.
Lalle nĩmai aiki ne. Da sannu zã ku san wãne ne azãba zã ta zo masa, ta wulakanta shi, kuma wãne ne maƙaryaci.
Kuma wanda ya riƙi Shaiɗan majiɓinci, baicin Allah, to, haƙĩƙa yã yi hasara, hasara bayyananniya.
Kuma mutum yanã yin addu'a da sharri kamar addu'arsa da alhẽri, kuma mutum ya kasance mai gaggãwa.
Sabõda wata rahama ce daga Allah ka yi sanyin hali a gare su.
Sũ mãsu kẽwaya ne a kanku sãshenku a kan sãshe. Kamar wannan ne Allah Yake bayyana ãyõyinSa a gare ku.
(Sai kuwa) ya ce: "Yã Maryamu! Daga ina wannan yake gare ki?"
Wasu huskõki a rãnar nan mãsu ni'ima ne.
Kuma Allah Yã kasance Mai gãfara, Mai Jin ƙai.
To, yãya musũNa (gare su) ya kasance?
Ubangijina Ya yalwaci dukkan kõme da ilmi.
Ashe, wanda Ya yi halitta bã zai iya saninta ba, alhãli kuwa shi Mai tausasãwa ne, kuma Mai labartawa?
Bã ku da, baicin Shi, wani majiɓinci kuma babu wani maceci.
Ya halitta sammai da ƙasã da gaskiya. Yanã shigar da dare a kan rãna, kuma Yanã shigar da rãnã a kan dare kuma Yã hõre rãnã da watã, kõwannensu yanã gudãna zuwa ga ajali ambatacce.
Ka sauka da aminci da, a gare Mu da albarka a kanka, kuma rahama ta tabbata a kan waɗansu al'ummõmi daga waɗanda suke tãre da kai. Da waɗansu al'ummõmi da zã Mu jiyar da su dãɗi, sa'an nan kuma azãba mai raɗaɗi ta shafe su daga gare Mu."
Yã kũ waɗanda suka yi ĩmãni! Abin sani kawai, mushirikai najasa ne, sabõda haka kada su kusanci Masallaci Mai alfarma a bãyan shẽkararsu wannan.
A cikinta bãbu jirĩ kuma ba su zama mãsu mãye daga gare ta ba,
Sai ku bi Allah da taƙawa, kuma kada ku wulãkantã ni a cikin bãƙĩna.
Ya ce: "Kada ku ji tsõro. Lalle Nĩ, Inã tãre da ku, Inaji, kuma Inã gani."
Haƙĩƙa wani dalĩli daga Ubangijinku yã je muku kuma Mun saukar da wani haske, bayyananne zuwa gare ku.
Sabõda haka, amma marãya, to, kada ka rinjãye shi.
Kuma da kã gani a lõkacin da mãsu laifi suke mãsu sunkuyar da kawunansu a wurin Ubangijinsu, "Ya Ubangijinmu! Mun gani, kuma mun ji, to, Ka mayar da mu mu aikata aiki na ƙwarai.
Ka ce: "Shin, daga abũbuwan shirkinku akwai wanda yake shiryarwa zuwa ga gaskiya?"
Shin, ba su ga cẽwa, lalle Mun sanya Hurumi amintacce ba alhãli kuwa anã fisge mutãne a gẽfensu?
Suka ce: "Yãya ne sarauta zã ta kasance a gare shi, a kanmu, alhãli kuwa mũ ne mafi cancanta da sarauta daga gare shi, kuma ba a bã shi wata wadata ba daga dũkiya?"
Kuma Allah bã Ya shiryar da mutãne azzãlumai.
Yã kũ waɗanda suka yi ĩmãni! An wajabta, a kanku, yin ƙisãsi a cikin kasassu. ɗa da ɗa kuma bãwa da bãwa, kuma mace da mace, to, wanda aka yi rangwamen wani abu gare shi daga ɗan'uwansa to a bi da alhẽri da biya zuwa gare, shi da kyautatãwa.
Kuma Shĩ ne Wanda Yake rãyarwa, kuma Yanã matarwa, kuma a gare Shi ne sãɓawar dare da yini take.
Kuma Allah Shi ne ke damƙewa, kuma yana shimfiɗawa, kuma zuwa a gare Shi ake mayar da ku.
Da Lũdu, a lõkacin da ya ce wa mutãnensa, "Shin kunã jẽ wa alfasha ne, alhãli, kuwa kunã gani?"
Sa'an nan lalle makomarsu, haƙĩƙa, zuwa ga Jãhĩm take.
Kuma a cikin wannan (Littãfi ya yi muku sũna Musulmi), dõmin Manzo ya kasance mai shaida a kanku, kũ kuma ku kasancemãsu shaida a kan mutãne. Sabõda haka ku tsayar da salla kuma ku bãyar da zakka kuma ku amince da Allah, Shi ne Majiɓincinku.
Ḥ.
Ya ce: "Abin sani kawai, ni Manzon Ubangijinki ne dõmin in bãyar da wani yãro tsarkakke gare ki."
To shin sunã jiran (wani abu)? Fãce S'a ta jẽ musu bisa abke, dõmin lalle sharuɗɗanta sun zo.
"Kuma bã ni ce muku a wurĩna taskõkin Allah suke kuma bã inã sanin gaibi ba ne. Kuma ba inã cẽwa ni Malã'ika ba ne.
To, idan kun ƙãre ayyukan hajji, sai ku ambaci Allah kamar ambatarku ga ubanninku, kõ kuwa mafi tsanani ga ambato.
ƘaramiSize
Kuma suka dinga nadãma a lõkacin da suka ga azãba. Sa'an nan aka yi hukunci a tsakãninsu da ãdalci, kuma bã zã a zãlunce su ba.
Kuma lalle ne, mãsu yawa daga mutãne, haƙĩƙa, fãsiƙai ne.
Tsarki ya tabbata ga Allah, kuma Ya ɗaukaka bisa ga abin da suke yi na shirki.
Ka ce wa waɗanda suka kãfirta, idan sun hanu, zã a gãfarta musu abin da ya riga ya shige, kuma idan sun kõma, to, hanyar kãfiran farko, haƙĩƙa, ta shũɗe.
Mu ne ke arzũta su, su da ku.
Kuma lalle ne Ubangijinka, haƙĩƙa, Yanã yin hukunci a tsakaninsu a Rãnar ¡iyãma a cikin abin da suka kasance a cikinsa sunã sãɓã wa jũnã.
Kuma wancan shi ne babban rabo, mai girma.
Sun kasance mafiya ƙarfi daga gare su kuma suka nõmi ƙasa suka rãya ta fiye da yadda suka raya ta, kuma manzanninsu suka je musu da hujjoji bayyanannu.
Ku bauta wa Allah; bã ku da wani abin bauta wa wanninSa. Haƙĩƙa hujja bayyananniya tã zo muku daga Ubangijinku! wannan rãƙumar Allah ce, a gare ku, wata ãyã ce.
Dã Yana bin ku ga (hãlãye) mãsu Yawa na al'amarin, dã kun auku a cikin zunubi, kuma amma Allah Yã sõyar da ĩmãni a gare ku, kuma Yã ƙawãta shi a cikin zukãtanku kuma Yã ƙyãmantar da kãfirci da fãsicci da sãɓo zuwa gare ku.
Kuma kada ku aibanta kanku, kuma kada ku jẽfi jũna da miyãgun sunãye na laƙabõbĩ.
Ubangijinku ne Mafi sani ga abin da yake a cikin rãyukanku.
Kuma sunã danganta 'ya'ya mãta ga Allah. Tsarkinsa yã tabbata!
Mãsu tũba, mãsu bautãwa, mãsu gõdẽwa, mãsu tafiya, mãsu ruku'i, mãsu sujada mãsu umurni da alhẽri da mãsu hani daga abin da aka ƙi da mãsu tsarẽwaã ga iyãkõkin Allah.
Waɗanda suka yi girman kai suka ce: "Lalle ne mu, ga abin da kuka yi ĩmãni da shi kãfirai ne."
Sai ya yi kira a cikin duffai cẽwa, "Bãbu abĩn bautãwa fãce Kai.
Kuma Allah Yanã tsare ka daga mutãne.
A cikin dũniya da Lãhira.
Kuma wannan ambato ne mai albarka Mun saukar da shi.
Lalle ne nĩ, na kasance daga azzãlumai."
Sai ku yi tafiya a cikin ƙasa, sa'an nan ku dũba yadda ãƙibar mãsu ƙaryatãwa ta kasance.
Kuma bã ya da wani dalĩli a kansu fãce dai dõmin Mu san wanda yake yin ĩmãni da Lãhira daga wanda yake a cikin shakka daga gare ta.
Yã kũ waɗanda suka yi ĩmãni! Idan fãsiƙi Yã zo muku da wani babban lãbãri, to, ku nẽmi bayãni, dõmin kada ku cũci waɗansu mutãne a cikin jãhilci, sabõda haka ku wãyi gari a kan abin da kuka aikata kunã mãsu nadãma.
Sai Muka yi wahayi zuwa ga Mũsã cẽwa "Ka dõki tẽku da sandarka."
Ka ce: "Saninta yanã wurin Allah kawai."
Sa'an nan Ya karɓi tuba a kanku. lalle ne Shi, Shi ne Mai karɓar tũba, Mai jin ƙai.
To, ka zo mana da abin da kake yi mana wa'adin, idan kã kasance daga mãsu gaskiya."
Kuma ta ce wa 'yar'uwarsa, "Ki bĩ shi."
To, abin da suke ɗauka yã mũnana.
Mẽne ne a gare ku, idan ance muku, "Ku fita da yãƙi a cikin hanyar Allah," sai ku yi nauyi zuwa ga ƙasa.
Shin, zai umurce ku da kãfirci ne a bãyan kun riga kun zama mãsu sallamãwa (Musulmi)?
Rãnar da munafikai maza da munãfikai mãtã ke cẽwa waɗanda suka yi ĩmãni: "Ku dũbẽ mu, mu yi makãmashi daga haskenku!"
"Ka shigar da hannunka a cikin wuyan rĩgarka, ya fita fari, ba da wata cũta ba, kuma ka haɗa hannuwanka ga kãfaɗunka, dõmin tsõro (ya gushe daga gare ka).
Mala'iku da Rũhi suna sauka a cikinsa da iznin Ubangijinsu sabõda kowane umurni.
Ka yi wa munãfukai bushãra da cẽwa lalle ne sunã da azãba mai raɗaɗi.
Ba ku zama kamar kõwa ba daga mãtã, idan kun yi taƙawa, sabõda haka, kada ku sassautar da magana, har wanda ke da cũta a cikin zuciyarsa ya yi ɗammani, kuma ku faɗi magana ta alheri.
Ku ci daga 'ya'yan itãcensa, idan ya yi 'yã'yan, kuma ku bãyar da hakkinSa a rãnar girbinsa, kuma kada ku yi ɓarna. Lalle ne Shĩ, ba Ya son mafarauta.
Shin fa, wanda Muka yi wa wa'adi, wa'adi mai kyau, sa'an nan shĩ mai haɗuwa da shi ne, yanã zama kamar wanda Muka jiyar da shi ɗan dãɗi, dãɗin rãyuwar dũniya, sa'an nan shi a Rãnar ¡iyãma yanã daga mãsu shiga wuta?
Kuma Muka sallaɗar da mabiya a gare su, sai suka ƙawãta musu abin da ke a gabansu da abin da ke a bãyansu.
To, wanda ya kasance majinyaci daga cikinku, kõ kuwa akwai wata cũta daga kansa (ya yi aski) sai fansa (fidiya) daga azumi ko kuwa sadaka ko kuwa yanka.
Haƙĩƙa, tir da abin da suka kasance suna aikatãwa.
To, idan sun hanu to lalle ne, Allah ia abin da kuke aikatãwa Mai gani ne.
Sai ku yi tsẽre zuwa ga ayyukan alhẽri, inda kuka kasance duka Allah zai zo da ku gabã ɗaya.
Kuma ka yi kira zuwa ga Ubangijinka lalle kai kana a kan shiriya madaidaiciya.
Kuma rãnar da yake tãra su gaba ɗaya (Yanã cẽwa): "Yã jama'ar aljannu! Lalle ne kun yawaita kanku daga mutãne."
Kuma bãbu wani laifi a kan mãsu kyautatãwa.
Kuma ku bi Allah da taƙawa. Lalle Allah Mai karɓar tũba ne, Mai jin ƙai.
Kuma suka yi mãmãki dõmin Mai gargaɗi, daga cikinsu, ya je musu.
Kuma a lõkacin da ka yi sauko daga iyãlanka kana zaunar da mũminai a wurãren zamadõmin yãƙi, kuma Allah Mai ji ne, Masani.
Lalle ne shi, daga bãyinMu zaɓaɓɓu yake.
Kuma idan sun nẽmi taimako sai a taimake su da wani ruwa kamar dabzar mai, yanã sõye fuskõki.
Bã ku da wani abin bautã wa, waninSa. Shin fa, bã zã ku yi taƙawa ba?"
"Ku tafi da rĩgãta wannan, sa'an nan ku jẽfa ta a kan fuskar mahaifina, zai kõma mai gani. Kuma ku zo mini da iyãlinku bãki ɗaya."
Yã Banĩ Isrã'ĩla! Ku tuna ni'imaTa wadda Na ni'imtar da ita a kanku, kuma lalle ne Nĩ, Nã fĩfĩtã ku a kan tãlikai.
Babbar Mazaɓa
Ka yi karatu, kuma UbangiJinka shi ne Mafi karimci.
Ya ce: "Shin to, kun ga abin da kuka kasance kunã bautã wa?"
Ka ce: "Abin da na rõƙe ku na wani sakamako, to, amfãninsa nãku ne.
"Kada ku yi ĩmãni fãce da wanda ya bi addininku."
Lalle Mun bayyanamuku ãyõyi da fatan zã ku yi hankali.
Kuma ka buga musu misãli da waɗansu maza biyu.
Na rantse da Ubangijĩna, lalle, zã ta zõ muku." Masanin gaibi, gwargwadon zarra bã ta nĩsanta daga gare Shi a cikin sammai kuma bã ta nĩsanta a cikin ƙasã, kuma bãbu mafi ƙaranci daga wancan kuma bãbu mafi girma fãce yanã a cikin Littãfi bayyananne.
Suka ce: "Bã zã mu fĩfĩta ka ba faufau a kan abin da ya zo mana na hujjõji.
Kuma aka kusantar da Aljanna ga mãsu taƙawa.
Suka ce: "Shin kai ne ka aikata wannan ga gumãkanmu? Yã Ibrahĩm!"
Lalle ne, a cikin wancan, akwai tunãtarwa ga wanda zũciyarsa ta kasance gare shi, kõ kuwa ya jẽfa saurãro, alhãli kuwa yanã halarce (da hankalinsa).
Kuma sarkin ya ce: "Ku zo mini da shi in kẽɓe shi ga kaina."
Kuma lalle ne, haƙĩƙa, Allah Yã taimake ku a Badar, alhãli kuwa kunã mafiya rauni, sabõda haka ku bi Allah da taƙawa tsammãninku, kuna gõdẽwa.
A cikinsu, akwai wasu mãtã mãsu kyaun hãlãye, mãsu kyaun halitta.
Kuma Shi ne Wanda Ya ƙãga halittar ji da gani da zukãta dominku. Kaɗan ƙwarai kuke gõdẽwa.
Ya bũga muku wani misãli daga kanku.
Sai ya dũba wanne ne mafi tsarki ga abin dafãwa, sai ya zo muku da abinci daga gare shi.
Bã a rõƙon Allah sai da sunãyensa mãsu kyau, tis'in da taran nan, sai dai a dunƙule kamar a ce, "Inã rõƙon Allah da sunãyenSa da na sani da waɗanda ban sani ba." Lalle nĩ, na zãlunci kaina, kuma nã sallama al'amari tãre da Sulaiman ga Allah, Ubangijin halittu."
Kuma daga 'ya'yan itãcen dabĩno da inabi. Kunã sãmudaga gare shi, abin mãye da abinci mai kyau.
Sai Muka aika a kansu da cikõwa, da fãra, da ƙwarƙwata da kwãɗi, da jini; ãyõyi abũbuwan rarrabẽwa; Sai suka kangare, kuma suka kasance mutãne mãsu laifi.
Kuma Allah Yanã azurta wanda Yake so, bã da lissafi ba.
Sai Allah Ya gãfarta muku zunubbanku, kuma Ya shigar da ku gidãjen Aljanna, ƙoramu na gudãna daga ƙarƙashinsu, da waɗansu ɗãkuna mãsu dãɗi a cikin gidãjen Aljannar zama.
Allah Ya ce: "Wannan ce rãnar da mãsu gaskiya, gaskiyarsu take amfãninsu.
Sa'an nan idan sãsanninsu suka fãɗi, to, ku ci daga gare su, kuma ku ciyar da mai wadar zũci da mai bara.
Lalle Allah ne Mai gãfara, Mai jin ƙai.
Kamar wannan ne aka ƙawãta ga maɓannata, abin da suka kasance sunã aikatãwa.
Gari mai dãɗin zama, da Ubangiji Mai gãfara."
Kuma ku yi daidami da igiyar Allah gabã ɗaya, kuma kada ku rarraba.
Ka ce: "Allah Yã isa zama shaida a tsakãnina da ku.
"Ya Mũsã! Ka fuskanto, kuma kada ka ji tsõro lalle ne kanã daga waɗanda ke amintattu."
Kuma tir da abin da suka sayar da rãyukansu da shi, dã sun kasance suna sani.
Wancan ita ce ɓata mai nĩsa.
Ka ce: "Gõdiya tã tabbata ga Allah." Ã'a, mafi yawansu bã su hankalta.
Kuma idan kun kasance a kan tafiya, kuma ba ku sami marubũci ba, to, a bãyar da jingina karɓaɓɓiya (ga hannu).
Ka ce: Shin kuna jãyayyar hujia ne da mu a cikin al'amarin Allah, alhãli kuwa Shi ne Ubangijinmu kuma Ubangijinku, kuma muna da ayyukanmu, kuma kuna da ayyukanku, kuma mũ, a gare Shi, mãsu tsarkakẽwane?
Ga wanda ya so, daga cikinku, ya gabãta ko ya jinkirta.
Kuma suna tambayar ka daga jirajiran wata.
Kuma idan Muka musanya wata ãyã a matsayin wata ãyã, kuma Allah ne Mafi sani ga abin da Yake saukarwa sai su ce: "Abin sani kawai, kai, aƙirƙiri ne."
"Kuma lalle Allah ne Ubangijina kuma Ubangijinku, sai ku bauta Masa.
Mun yi shaida!" (ya ce): "Kada ku ce a Rãnar Kiyãma: Lalle ne mũ, daga wannan, gafalallu ne."
Sa'an nan idan Manzonsu ya je, sai a yi hukunci a tsakãninsu da ãdalci, kuma sũ, bã a zãluntar su.
(Allah Ya ce): "To, ka yi tafiyar dare da bayiNa, da dare. Lalle kũ, waɗanda ake bĩ ne (dõmin a kãma ku.)"
Bã su wata ibãda fãce kamar yadda ubanninsu ke aikatãwa a gabani.
Kuma a cikin ƙasa akwai yankuna mãsu maƙwabtaka, da gõnaki na inabõbi da shũka da dabĩnai iri guda, da waɗanda bã iri guda ba, anã shayar da su da ruwa guda.
Ã'a, sun yi mãmãki, cewa mai gargaɗi, daga gare su, yã zo musu, sai kãfirai suka ce: "Wannan wani abu ne mai ban mãmãki."
Abin sani kawai waɗanda bã su yin ĩmãni da ãyõyin Allah, sũ ne suke ƙirƙira ƙarya.
Ka ce: "Yã kũ waɗandasuka tũba (Yahũdu)!
Ya ce: "Bã zan sake shi tãre da kũ ba, sai kun kawo mini alkawarinku baga Allah, haƙĩƙa, kunã dawo mini da shi, sai fa idan an kẽwaye ku."
Waɗanda suke nufin rãyuwar dũniya suka ce: "Inã dai munã da kwatancin abin da aka bai wa ¡ãrũna!
Sunã gincire a kansu, sunã mãsu kallon jũna.
Ka ce: "Shin, makãho da mai gani sunã daidaita? Shin fa, ba ku yin tunãni?"
Kuma Allah ba Ya shiryar da mutãne fãsiƙai.
Shin, kuma kõ dã ubanninsu sun kasance bã su sanin kõme kuma bã su shiryuwa?
Wannan, sabõda lalle sũ, sun ƙi abin da Allah Ya saukar dõmin haka Ya ɓata ayyukansu.
Kuma waɗanda suke a cikin wutã suka ce wa matsaran Jahannama, "Ku rõki Ubangijinku Ya sauƙaƙa mana, a yini ɗaya, daga azãba."
Kuma ku sanya gidãjenku su fuskanci Alƙibla, kuma ku tsayar da salla. Kuma ku bãyar da bushãra ga mãsu ĩmãni.
Sai ta ce: "Yã kaitõna!
To, ku ji dãɗi, sa'an nan da sannu zã ku sani.
Ka ce: "Allah ne mafi gaggãwar (sakamakon) mãkirci." Lalle ne ManzanninMu sunã rubũta abin da kuke yi na mãkirci.
Kunã mãsu mai da al'amari gare Shi, kuma ku bĩ Shi dataƙawa, kuma ku tsayar da salla, kuma kada ku kasance daga mushirikai.
Da wata ayaba mai yawan 'ya'ya.
Suka ce: "Yanzu kã zo da gaskiya.
(Kowannenku) Yanã da waɗansu malã'iku mãsu maye wa jũna a gaba gare shi da bãya gare shi, sunã tsare shi daga umurnin Allah.
Shĩ ne Mafi sani ga abin da kuke kũtsãwa a cikinsa na magana.
Kuma lalle ne haƙĩƙa Mun halitta, a samanku, hanyõyi bakwai, kuma ba Mu kasance, daga barin halittar, Mãsu shagala ba.
"Kuma ka rikitar da wanda ka sãmi ĩko a kansa, daga gare su, da sautinka, kuma ka yi hari a kansu da dawãkinka da dãkãrunka kuma ka yi tãrẽwa da su a cikin dũkiyõyi da ɗiyã, kumaka yi musu wa'adi.
Da waɗanda suka zaunar da gidãjensu (ga Musulunci) kuma (suka zãɓi) ĩmãni, a gabãnin zuwansu, sunã son wanda ya yi hijira zuwa gare su, kuma bã su tunãnin wata bukãta a cikin ƙirãzansu daga abin da aka bai wa muhãjirĩna, kuma sunã fĩfĩta waɗansu a kan kãwunansu, kuma ko dã sunã da wata larũra.
Kamar wancan ne Allah ke nũna musu ayyukansu, suna da nadãmõmi a kansu, kuma ba su zama mãsu fita daga wutar ba.
Haƙĩƙa Allah Ya sanyama'auni ga dukan kõme.
Waɗannan ne ba su kasance mabuwãya ba a cikin ƙasa, kuma waɗansu masõya ba su kasance ba a gare su, baicin Allah.
Ã'aha! waɗanda suka yi zã1unci sun bi son zũciyõyinsu, bã tãre da wani ilmi ba.
Maƙaskanta ga idanunsu, wani walakanci yana rufe su. wannan shi ne yinin da suka kasance ana yi musa alkawari (a kansa.)
Sai Muka yi wahayi zuwa ga Mũsã cẽwa "Ka dõki tẽku da sandarka."
Kuma ku sani cẽwa lalle ne, Allah Mawadãci ne, Gõdadde.
Kuma Ubangijinka Ya zo, alhãli malã'iku na jẽre, safũ- safu.
Kuma Munã kõra mãsu laifi zuwa Jahannama, gargaãwa.
Ko zã a sãka muku fãce da abin da kuka kasance kũnã aikatãwa?
Sabõda haka ku bi Allah da taƙawa, yã ma'abuta hankula ko la'alla zã ku ci nasara."
Lalle Allah Mai gãfara ne, Mai jin ƙai."
Shin, bã ku ji?"
Idan sun yi nufin gyãrãwa, Allah zai daidaita tsakãninsu (ma'auran).
Lalle ni inã tsõron Allah Ubangijin halitta!"
Waɗanda suke ambatar Allah a tsaye da zaune da a kan sãsanninsu, kuma suna tunãni a kan halittar sammai da ƙasa: "Yã Ubangijinmu! Ba Ka halitta wannan a kan banza ba.
Suka ce: "Ã'a, ku ne bãbu marãba a gare ku, kũ ne kuka gabãtar da shi a gare mu." To, matabbatar tã mũnana (ita wutar).
Sabõda haka kada ku kasance daga mãsu shakka.
Kuma lalle ne, Mũ idan Mun ɗanɗana wa mutum wata rahama daga gare Mu, sai ya yi farin ciki da ita, kuma idan wata masĩfa ta sãme su sabõda abin da hannayensu suka gabãtar, to, lalle ne mutum mai tsananin kãfirci ne.
Kuma kada ku kashe rai wanda Allah Ya haramta fãce da haƙƙi, kuma wanda aka kashe, yanã wanda aka zãlunta to, haƙĩƙa Mun sanya hujja ga waliyyinsa, sai dai kada ya ƙẽtare haddi a cikin kashẽwar. Lalle shĩ ya kasance wanda ake taimako.
"To! Idan kun jũya, haƙĩƙa, nã iyar muku abin da aka aiko ni da shi zuwa gare ku.
Lalle ne, Allah bã Ya son mãsu ƙetare haddi.
Shin kã san wani takwara a gare shi?
Wancan sabõda lalle su, sun kasance suna kãfirta da ãyõyin Allah, kuma suna kashe Aannabãwa, bãda hakki ba.
To, sãlihanmãtã mãsu ɗã'a ne, mãsu tsarẽwa ga gaibi sabõda abin da Allah Ya tsare.
Kuma Allah ne Masani, Mai hikima.
Akwai tsammãnin Allah Ya kange gãfin waɗanda suka kãfirta, kuma Allah ne Mafi tsananin gãfi, kuma Mafi tsananin azabtãwa.
Kuma lalle ne, sũ, sunã faɗin abin da bã su aikatãwa?
Sa'an nan ba su sãɓa ba har ilmi ya jẽ musu.
Ashe to bã zã su dũbãwa ba ga rãƙumã yadda aka halitta su?
Kuma Munã jarraba ku da sharri da alhẽri dõmin fitina. Kuma zuwa gare Mu ake mayar da ku.
Sannan gare su wulakanci ne a cikin rãyuwar duniya, kuma a Lãhira sunã da wata azãba mai girma.
Da wasu 'ya'yan itacen marmari mãsu yawa.
Ya ce: "Lalle mũ, daga gare ku, mãsu firgita ne."
Allah ne Ubangijinmu, kuma Shĩ ne Ubangijinku, ayyukanmu nã gare mu, kuma ayyukanku nã gare ku, kuma bãbu wata hujja a tsakãninmu da tsakãninku.
Allah Yã la'ance su!
Kuma kõ dã kõwace ãyã ta jẽ musu, sai sun ga azãba mai raɗaɗi.
Yã ku Manzanni! Ku ci daga abũbuwa mãsu dãɗi kuma ku aikata aikin ƙwarai.
Lalle wannan, haƙĩƙa, gaskiya ne, husũmar mutãnen wutã.
Sunã kiran su, "Ashe, bã tãre muke da ku ba?"
Kuma a lõkacin da Muka riƙi alkawarinku kuma Muka ɗaukaka dutse a bisa gare ku, (Muka ce:) "Ku riƙi abin da Muka kãwo muku da ƙarfi kuma ku ji" Suka ce: "Mun ji kuma mun ƙi."
A kõyaushe suka yi nufin fita daga gare ta, daga baƙin ciki, sai a mayar da su a cikinta, (a ce musu) "Ku ɗanɗani azãbar gõbara."
Kuma kada ku yi ɓarna a cikin ƙasa a bãyan gyaranta.
Sai Fir'auna ya bi su game da rundunarsa. Sai abin da ya rufe su daga tẽku ya rufe su.
Kuma bãbu kõwa daga Mutãnen Littafi, fãce lalle yanã ĩmãni da shi a gabãnin mutuwarsa, kuma a Rãnar ¡iyãma yana kasancẽwa mai shaida, a kansu.
Kuma Muka shigar da shi a cikin rahamarMu. Lalle ne shĩ, yanã daga sãlihai.
Rãnar da za ta zo wani rai ba ya iya magana fãce da izninSa. Sa'an nan daga cikinsu akwai shaƙiyyi da mai arziki.
Mẽ yã yi kãfircinsa!
Lalle Shĩ Mai gani ne ga abin da kuke aikatãwa.
Kuma a lõkacin da Muka baiwa Mũsa Littãfi da rarrabẽwa, tsammãninku, kuna shiryuwa.
Ku ci daga abin da yake a cikin ƙasa, wanda yake halal, mai dãɗi. Kuma kada ku bi zambiyõyin Shaiɗan.
Amma kuma bãbu waɗanda suka yi ĩmãni tãre da shi fãce kaɗan."
Lalle Mũ, Munã sanin abin da suke asirtãwa da abin da suke bayyanãwa.
Allah Mafi sanin inda Yake sanya manzancinSa.
To, don mẽne ne waɗanda suka riƙa, baicin Allah, abũbuwan yi. wa baiko, gumaka, ba su taimake su ba?
Sabõda haka ku nĩsanci mãta a cikin wurin haila kuma kada ku kusance su sai sun yi tsarki.
Yã kai Annabi! Ka yãki kãfirai da munãfwkai.
Ashe, bai sani ba cewa Allah Yanã gani?
Kuma a rãnar da Yake kiran su ya ce: "Inã abõkan tarayya Ta, waɗanda kuka kasance kunã riyãwa"
Fãce waɗanda suka yi ĩmãni suka aikata ayyukan ƙwarai, kuma suka ambaci Allah da yawa, kuma suka rãma zãlunci, daga bãyan an zãlunce su.
Shin fa, wanda shĩ Yake tsaye a kan kõwane rai game da abin da ya tanada (zai zama kamar wanda ba haka ba)?
Lalle Allah bã Ya shiryar da mutãne azzãlumai."
Sa'an nan ka sake maimaita, dũbãwa, ganinka zai komo maka, gajiyayye, ba da ganin wata naƙasa bã.
Ã'a, waɗancan sũ ne azzãlumai.
Lalle wannan (Mai wannan aiki), tabbas, Mai rãyar da halitta ne, kuma Shi Mai ikon yi ne a kan kõme.
Hikima cikakka!
Kuma waccan ita ce Aljannar, wannan da aka gãdar da ku ita sabõda abin da kuka kasance kunã aikatãwa.
Ko kun amince ga Ya mayar da ku a cikin tẽkun a wani lõkaci na dabam, sa'an na Ya aika wata gũguwa mai karya abũbuwa daga iska, har ya nutsar da ku sabõda abin da kuka yi na kãfirci? Sa'an nan kuma bã ku sãmun mai bin hakki sabõda ku, a kanMu, game da Shi.
Kuma mũ, zuwa gare Shi mãsu sallamãwa ne."
Kuma wani mutum ya zo daga mafi nĩsan birnin yanã taliya da gaggãwa, ya ce: "Ya Mũsã!
Kuma kãfirai sun yi hasãra a can.
Jerin shaidar abu na fanel
Kuma (Kãfirai) suka yi mãkirci, Allah kuma Ya yi musu (sakamakon) makircin, kuma Allah ne Mafi alhẽrin mãsu sãka wamãkirci.
Kuma Muka kiyãye ta daga dukan Shaiɗani wanda ake jĩfa.
Lalle kũ ne kuka fi bãyar da firgita a cikin zukãtansu bisa ga Allah, wannan kuwa dõmin sũ lalle waɗansu irin mutãne ne da bã su gãnẽwa.
Kuma da Ismãĩla da Idrĩsa da Zulkifli, dukansu sunã daga mãsu haƙuri.
Kuma Allah Ma'abũcin falala mai girma ne.
Allah nã ɗaukaka waɗanda suka yi ĩmãni daga cikinku da waɗanda aka bai wa ilim wasu darajõji mãsu yawa, kuma, Allah Mai ƙididdigewa ne ga dukan kõme.
Suka ce: "Ubangijinmu Yã sani, lalle mũ, haƙiƙa Manzanni nezuwa gare ku."
Kuma lalle ne, haƙĩkƙa, Mun sauƙaƙe Alƙur'ãni, dõmin tunãwa. To, shin, akwai mai tunãwa?
Lalle ne, a cikin wancan akwai ãyõyi ga mãsu hankula.
Kada ku ce: 'Rã'inã' kuma ku ce: 'Jinkirtã manã', kuma ku saurara. Kuma kãfirai suna da azãba mai raɗaɗi.
Tsarkin Allah ya tabbata, kuma Ya ɗaukaka daga abin da suke yi na shirka.
Idan Mun yãfe laifi ga wata ƙungiya daga gare ku, zã Mu azabta wata ƙungiya sabõda, lalle, sun kasance mãsu laifi."
Ã'a ku mutãne ne daga waɗanda Ya halitta, Yanã gãfartãwa ga wanda Yake so, kuma Yanã azabta wanda Yake so.
Tsarki ya tabbata ga Wanda Ya halitta nau'uka, namiji da mace, dukansu, daga abin da ƙasã ke tsirarwa, kuma daga kansu, kuma daga abin da ba su sani ba.
Su biyu suka ce: "Ya Ubangijinmu!
Sai ku cika mũdu da sikeli kumakada ku nakasa wa mutãne kãyansu, kuma kada ku yi fasãdi a cikin ƙasa a bãyan gyaranta. Wannan ne mafi alhẽri a gare ku, idan kun kasance mũminai."
Shaiɗan ya rinjaya a kansu, sai ya mantar da su ambaton Allah, waɗannan ƙungiyar Shaiɗan ne.
Dõmin Ya bayyana musu abin da suke sãɓã wa jũna a cikinsa, kuma dõmin waɗanda suka kãfirta su sani cẽwa lalle sũ ne suka kasance maƙaryatã.
Kuma Shi ne Ya halitta mutum daga ruwa, sai Ya sanya shi nasaba da surukuta, kuma Ubangijinka Ya kasance Mai ĩkon yi.
Kuma Yanã da manyan jirãge, waɗanda ake ƙãgãwa a cikin tẽku kamar manyan duwãtsu.
Lalle ne, mafi sharrin dabbõbi a wurin Allah, sũ ne kurãme, bẽbãye, waɗanda bã, su yin hankali.
Kuma dũkiyarku ba ta zamo ba, haka ɗiyanku ba su zamo abin da yake kusantar da ku ba a wurinMu, kusantarwar muƙãmi fãce wanda, ya yi ĩmãni kuma ya aikata aikin ƙwarai. To, waɗannan sunã da sakamakon ninkawa sabõda abin da suka aikata.
Shin, kun sanya shãyar da mahajjata da rãyar da Masallaci Mai alfarma kamar wanda ya yi ĩmãni da Allah da Rãnar Lãhira, kuma ya yi jihãɗi a cikin hanyar Allah?
A. L̃.
Sa'an nan ta riƙi wani shãmaki daga barinsu.
Sabõda haka kada ka kasance a cikin shakka daga gare shi.
Mẽne ne Allah zai amfãna da yi maku azãba idan kun gõde, kuma kun yi ĩmãni?
Lalle ne Mũ, Mun sanyaShaiɗan majiɓinci ga waɗanda bã su yin ĩmãni.
Ka ce: "Ku kãwo dalĩlinku idan kun kasance mãsu gaskiya."
Kuma Muka yi ruwa a kansu da wani irin ruwa.
Ya ce: "Ya Mutãnena!
Kuma da waɗanda suke, ga shaidarsu, mãsu dãgẽwa ne.
Suka ce: "Mun yi ĩmãni da Ubangijin halittu."
Lalle Ubangijĩna Mai Jin ƙai ne, Mai nũna sõyayya."
Ka ce: "Ku tafi a cikin ƙasã sa'an nan ku dũbi yadda ãƙibar waɗanda suka kasance a gabãninku ta kasance.
Sai ka saurãra ga abin da ake yin wahayi."
"Wannan maganar mutum dai ce."
Tanã darkake kõwane abu da umurnin Ubangijinta.
Kuma lalle ne haƙĩƙa, Mun halaka irin gayyarku.
Kuma bã zã a sãka muku ba fãce da abin da kuka kasance kunã aikatãwa.
Ashe, ba ka gani ba, lalle ne, Allah Yã saukar da ruwa daga sama, sai ƙasa ta wãyi gari kõriya?
To, don mẽne ne waɗanda suka riƙa, baicin Allah, abũbuwan yi. wa baiko, gumaka, ba su taimake su ba?
Ya ɗaukaka daga abin da suke yi na shirka.
Kuma a lokacin da Mũsa ya nemi shãyarwa domin mutãnensa, Muka ce; "Ka dõki dũtsen da sandarka." Sai marmaro gõma sha biyu suka ɓuɓɓugo, haƙĩƙa, kõwaɗanne mutãne sun san wurin shansu.
Kuma Allah Yana son mãsu kyautatãwa.
Shin ba su ga tsuntsãye ba sunã hõrarru cikin sararin sama bãbu abin da yake riƙe su fãce Allah?
Dõmin (Allah) zai cika musu sakamakonsu, kuma Ya ƙarã musu daga falalarSa.
Ya ce: "Ya ƙaramin ɗãna!
Mãsu hankali kawai ke yin tunãni.
Abin da ke a cikin sammai, da abin da ke a cikin ƙasa, Nasa ne, kuma lalle ne Allah, haƙĩƙa, Shi ne wadatacce, Gõdadde.
Wancan fa domin lalle ne su, mutãne ne waɗanda ba su sani ba.
Shin, ba ka gani ba zuwa ga wanda ya yi hujjatayya da Ibrãhĩm a cikin (al'amarin) Ubangijinsa dõmin Allah Yã bã shi mulki, a lõkacin da Ibrãhĩm ya ce: "Ubangijina Shi ne Wanda Yake rãyawa kuma Yana matarwa."
Haƙĩƙa, tir da abin da suka kasance suna aikatãwa.
Kuma wanɗanda suka kãfirta, sunã cẽwa, "Don me ba a saukar da wata ãyã ba a kansa daga Ubangijinsa?"
Da sãfiya idan ta wãye.
Ya ce: "Kun yi ĩmãni sabõda shi a gabãnin in yi muku izni?
To, waɗanda suka kãfirta an yanka musu waɗansu tufafi daga wata irin wuta, anã zuba tafasasshen ruwa daga bisa kãwunansu.
Wannan ne addini madaidaici. Sabõda haka kada ku zãlunci kanku a cikinsu.
Kuma lalle ne haƙĩƙa Mun sarrafa shi (Alƙur'ãni) a tsakãninsu, dõmin su yi tunãni, sai dai mafi yawan mutãnen sun ƙi fãce kãfirci.
Ashe bãbu mazauni a cikin Jahannama ga mãsu girman kai?
Kuma Ubangijinmu Mai rahama ne Wanda ake nẽman taimakonSa a kan abinda kuke siffantãwa."
Kuma dã kanã gani, a lõkacin da aka tsayar da su a kan wuta, sai suka ce: "Yã kaitõnmu!
Waɗanda suka rinjãya a kan al'amarinsu suka ce: "Lalle mu riƙi masãllãci a kansu."
Ya kũ waɗanda suka yi ĩmãni! kada ku halattar da ayyukan ibãdar Allah game da hajji, kuma da watã mai alfarma, kuma da hadaya, kuma da rãtayar raƙuman hadaya, kuma da mãsu nufin ¦ãki mai alfarma, sunã neman falala daga Ubangijinsu da yarda.
"Ku tafi da rĩgãta wannan, sa'an nan ku jẽfa ta a kan fuskar mahaifina, zai kõma mai gani. Kuma ku zo mini da iyãlinku bãki ɗaya."
Ba ku da wani abin bautãwa fãce Shi. Ba ku kasance ba fãce kunã mãsu ƙirƙirãwa.
Kuma Muhammadu bai zama ba face manzo lalle ne manzanni sun shũɗe a gabãninsa.
Ã'a, Shĩ ne Allah, Mabuwãyi, Mai hikima."
Sabõda haka, ka tsayar da fuskarka ga addini, kanã mai karkata zuwa ga gaskiya, halittar Allah da Ya halitta mutãne a kanta.
Sai ya jẽfa sandarsa, sai gã ta kumurci bayyananne!
To, a lõkacin da Ya kuɓutar da su, sai, gã su sunã zãlunci a cikin ƙasa, bã da wanĩ hakki ba. Yã ku mutãne!
Kuma waɗanda suke idan suka aikata wata alfãsha ko suka zãlunci kansu sai su tunã da Allah, sabõda su nẽmi gãfarar zunubansu ga Allah. Kuma wãne ne ke gãfara ga zunubai, fãce Allah?
Lalle mutum, haƙĩƙa, mai kãfirci ne.
Suka ce: "Ku gina wani gini sabõda shi, sa'an nan ku jẽfa shi a cikin Jahĩm."
Shin fa, Kanã halaka mu, sabõda abin da mãsu ɓãtãwa suka aikata?"
Kada ku yi tambaya ga abubuwa, idan an bayyana muku (hukuncinsu) su ɓãta muku rai. Kuma idan kuka yi tambaya a gare su a lõkacin da ake saukar da Alƙur'ãni, zã a bayyana maku.
Sabõda haka idan kun haɗu da waɗanda suka kãfirta, sai ku yi ta dũkan wuyõyinsu har a lõkacin da suka yawaita musu kisa, to, ku tsananta ɗaurinsu sa'an nan imma karimci a bãyan' haka kõ biyan fansa, har yãƙi ya saukar da kayansa mãsu nauyi.
Lalle ne Shĩ, Shi ne Mai ƙãga halitta, kuma Ya mayar da ita (bãyan mutuwa).
To, yãya ake jũyar da su?
Shĩ ne Mai rai, bãbu abin bautãwa fãce Shi.
Allah ne Wanda ke aika iskõki, sai su mõtsar da girgije, sa'an nan Ya shimfiɗa shi a cikin sama yadda Yake so, kuma Ya sanya shi wani ɓaɓɓake, sa'an nan ka ga ruwa na fita daga tsakãninsa. Sa'an nan idan Allah Ya sãmi waɗanda Ya so daga bãyinsa, Sai gã su suna bushãra da shi.
A lõkacin da mafi shaƙãwarsu ya tafi (wurin sõke rãkumar sãlihu).
Sa'an nan, ya tafi zuwa ga mutãnensa, yana tãƙama.
Kada ka bi dukkan mai yawan rantsuwa, walãkantacce.
To, lalle ƙungiyar Allah sũ ne mãsu babban rabo.
Sa'an nan Muka tãyar da su, dõmin Mu san wane ɗayan ƙungiyõyin biyu suka fi lissãfi ga abin da suka zauna na lõkacin.
Sai tsãwa ta kãma su da gaskiya, sai Muka sanya su tunkuɓa.
Kuma kanã ganin ƙasa shiru, sa'an nan idan Muka saukar da ruwa a kanta, sai ta girgiza kuma ta kumbura, kuma ta tsirar da tsirrai daga kõwane nau'i mai ban sha'awa.
Sai aka ɗimautar da wanda yakãfirta. Kuma Allah ba Ya shiryar da mutãne azzãlumai.
Allah Ya yi musu tattalin wata azãba mai tsanani. Sabõda haka ku bi Allah da taƙawa, yã ma'abũta hankula, waɗanda suka yi ĩmãni!
Kuma akwai daga ãyõyinSa halittar sammai da ƙasã da sãɓã, war harsunanku, da launukanku. Lalle a cikin wannan akwai ãyõyi ga mãsu ilmi.
Yã Banĩ Isrã'ĩla! Ku tuna ni'imaTa wadda Na ni'imtar da ita a kanku, kuma lalle ne Nĩ, Nã fĩfĩtã ku a kan tãlikai.
Lalle Allah, haƙĩƙa, Ma'abũcin falala ne a kan mutãne, kuma amma mafi yawan mutãne bã su gõdẽwa.
Sa'an nan, lalle kũ, a Rãnar ¡iyãma, a wurin Ubangijinku, zã ku yi ta yin husũma.
Sa'an nan, ya gintse huska? kuma ya yi murtuk.
To, a yau bã zã su fita daga gare ta ba, Kuma bã zã su zama waɗanda ake nẽman yardarsu ba."
Lalle Allah Mai tausasawa ne, Mai ƙididdigewa.
Lalle ne, Masallaci wanda aka yi harsãshinsa a kan taƙawa tun farkon yini, shĩ ne mafi cancantar ka tsaya a cikinsa.
Kõ sunã da idãnu da suke gani da su?
To, a lõkacin da ya je masa, ya gaya masa lãbãrinsa, ya ce: "Kada ka ji tsõro, kã tsĩra daga mutãne azzãlumai."
Yãya Allah zai shiryar da mutãne waɗanda suka kãfirta a bãyan ĩmãninsu, kuma sun yi shaidar cẽwa, lalle Manzo gaskiya ne, kuma hujjõji bayyanannu sun je musu?
Ya ce: "Ku jẽfa."
Da wata (falala) da yake kunã son ta; taimako daga Allah da cin nasara wanda yake kusa.
Kunã nufin sifar dũniya kuma Allah Yanãnufin Lãhira.
Lalle ne, Mun bayyana ãyõyi ga mutãne masu sakankancewa.
Kuma Ubangijinka Ya zo, alhãli malã'iku na jẽre, safũ- safu.
Kuma ya yi musu rantsuwa; Lalle ne nĩ, a gare ku, haƙĩƙa, daga mãsu nasĩha ne.
Ba Mu yi sakacin barin kõme ba a cikin Littãfi, sa'an nan kuma zuwa ga Ubangjinsu ake tãra su.
Kuma mazan aurensu su ne mafiya haƙƙi ga mayar da su a cikin wancan, idan sun yi nufin gyãrawa.
Shin kanã jin mõtsin wani guda daga gare su, kõ kuwa kanã jin wata ɗuriya tãsu?
Rãnar da mutum yake gudu daga ɗan'uwansa.
Masĩhu bã ya ƙyãmar ya kasance bãwa ga Allah, kuma haka malã'ikun nan makusanta. Kuma wanda ya yi ƙyãmar bautarSa kuma yi yi girman kai, to, zai tãra su zuwa gare shi gabã ɗaya.
Ga kõwanne daga gare ku Mun sanya sharĩa da hanya (ta bin ta).
Kuma kamar wannan ne Muka tãyar da su, dõmin su tambayi jũna a tsakãninsu.
Kuma sunã tambayar ka: Shin gaskiya ne?
Haƙĩƙa lalle ne littãfin fãjirai dãhir, yana a cikin Sijjĩn.
Kuma lalle idan Mun ɗanɗana masa wata rahama daga gareMu, daga bãyan wata cũta ta shãfe shi, lalle zai ce, "Wannan (ni'ima) tãwa ce kuma bã ni zaton Sã'a mai tsayuwa ce, kuma lalle idan aka mayar da ni zuwa ga Ubangijĩna, haƙĩƙa, inã da makõma mafi kyau, a wurinSa."
Kuma suka ce wa fãtunsu, "Don me kuka yi shaida a kanmu?"
Ka ce: "Godiya ta tabbata ga A1lah, kuma aminci ya tabbata bisa ga bãyinSa, waɗanda Ya zãɓa."
Bãbu musanyãwa ga halittar Allah, wannan shĩ ne addini madaidaici kuma amma mafi yawan mutãne ba su sani ba.
Ya ce: "To, ka sauka daga gare ta; dõmin bã, ya kasancẽwa a gare ka ga ka yi girman kai a cikinta. Sai ka fita.
Kuma mummunai maza da mummunai mãtã sãshensu majiɓincin sãshe ne, sunã umurni da alhẽri kuma sunã hani daga abin da bã a so, kuma sunã tsayar da salla, kuma sunã bãyar da zakka, kuma sunãɗã'a ga Allah da ManzonSa.
Kuma idan wata ãyã ta je musu sai su ce: "Ba zã mu yi ĩmãni ba, sai an kãwo mana kamar abin da aka kãwo wa manzannin Allah."
Kuma da waɗansu waɗanda aka jinkirtar ga umurnin Allah, kõ dai Ya yi musu azãba kõ kuma Ya karɓi tũba a kansu.
Idan Yã so zai tafiyar da ku, kuma Ya zo da wata halitta sãbuwa.
Kuma Allah bai gushe daga abin da kuke aikatãwa ba yana Masani."
Kuma Mũsã ya ce: "Ubangijĩna ne Mafi sanin wanda ya zo da shiriya daga gare Shi, da wanda ãƙibar gida take kasancẽwa agare shi.
"Kuma idan haƙĩƙa, aka saukar da wata sũra, sai sãshensu ya yi dũbi zuwa ga wani sãshe, (su ce): "Shin, wani mutum yanã ganin ku?"
Allah Yã buga misãli; wani mutum (bãwa) a cikinsa akwai mãsu tarayya, mãsu mũgun hãlin jãyayya, da wani mutum (bãwa) dukansa ga wani mutum. Shin, zã su daidaita ga misãli?
Lalle mũ mun bi shugabanninmu da manyanmu! Sai suka ɓatar da mu daga hanya!
Lalle a cikin wancan akwai ãyõyi. Shin, ba su jĩ ne?
Suka ce: "Daidai ne a kanmu: Kã yi wa'azi kõ ba ka kasance daga mãsu wa'azi ba."
Kuma kamar wancan ne Muka sanya wa kõwane Annabi maƙiyi; shaiɗãnun mutãne da aljannu, sãshensu yanã yin ishãra zuwa sãshe da ƙawãtaccen zance bisa ga rũɗi.
Ga Mu musanya waɗanda suke mafi alhẽri, daga gare su.
Allah Ya yi musu tattalin wata azãba mai tsanani.
Ita (wutar) ɗayan manyan masĩfũ? ce.
Kuma idan aka saukar da wata sũra, to, daga gare su akwai waɗanda suke cẽwa: "Wãne a cikinku wannan sũra ta ƙãra masa ĩmãni?"
Kuma dã dai lalle Mũ, Mun wajabta musu cẽwa, "Ku kashe kanku, ko kuwa ku, fita daga gidãjenku," dã ba su aikata shi ba, fãce kaɗan daga gare su.
(Ka ce): "An umurce ni, in bauta wa Ubangijin wannan Gari, Wanda Ya mayar da shi Hurumi, kuma Yanã da dukan kõme.
Lalle ne zuwa ga Ubangijinka makoma take.
Ka ce: "Yã ku Mutanen Littãfi!
Kuma sunã cẽwa, "Yaushe wannan hukunci yake, aukuwa idan kun kasance mãsu gaskiya?"
Sa'an nan ya yi wahayi zuwa ga bãwan Allah (Muhammadu) da abin da ya faɗa (masa).
"Kuma lalle mu, haƙĩƙa, mũ ne mãsu yin sahu-sahu (dõmin ibãda)."
Madalla da Mu, Mãsu nũna iyãwa.
Gaba gare su (a Lãhira) akwai Jahannama, kuma abin da suka sanã'anta bã ya wadãtar da su daga kõme, kuma abũbuwan da suka riƙa majiɓinta, baicin Allah, bã su wãdatar da su daga kõme. Kuma sunã da wata azãba mai girma.
Ka ce: "Bãbu abin da yake sãmun mu fãce abin da Allah Ya rubũta sahõda mu.
Shin fa, da ƙarya suke yin ĩmãni, kuma da ni'imar Allah sũ, suke kãfirta?
Sa'an nan da yawa daga alƙarya, Muka halaka ta, alhãli kuwa tanã mai zalũnci sai ta zama fãɗaɗɗa a kan rassanta, da yawa daga rĩjiya wadda aka wõfintar, da kuma gidãjen sarauta maɗaukaka.
Bã ya halatta a gare ku, ku gãji mãtã a kan tĩlas kuma kadaku hana su aure dõmin ku tafi da sãshen abin da kuka ba su, fãce idan suka zo da wata alfãsha bayya nanniya kuma ku yi zamantakẽwa da su da alhẽri sa'an nan idan kun ƙĩ su, to akwai tsammãnin ku ƙi wani abu alhãli kuwa Allah Ya sanya wani alhẽri mai yawaa cikinsa.
Kuma Muka tsirar da wata itãciya ta kankana a kusa da shi.
Sa'an nan zã ku san su wa ne ma'abũta tafarki madaidaici, kuma wane ne ya nẽmi shiryuwa."
Kuma a cikin wannan (Littãfi ya yi muku sũna Musulmi), dõmin Manzo ya kasance mai shaida a kanku, kũ kuma ku kasancemãsu shaida a kan mutãne.
"Mai yiwuwa ne Ubangijinmu Ya musanya mana da wani abu da yã fi ta. Lalle, mũ (ba mu yanke ƙauna ba) zuwa ga Ubangijinmu, mãsu kwaɗayi ne."
Sunã cẽwa, "Yaushe ne wannan wa'adi zai auku idan kun kasance mãsu gaskiya?"
Ka dũba yadda Muke sarrafaãyõyi, Sa'an nan kuma sũ, sunã finjirẽwa.
Kuma Fir'auna ya ce: "Ku bar ni in kashe Mũsã, kuma shĩ, ya kirãyi Ubangijinsa.
Ku ji tsõron wani yini, (a cikinsa) wani rai bã ya tunkuɗe wa wani rai kõme kuma bã a karɓar fansa daga gare shi, kuma wani cẽto bã ya amfanin sa, kuma ba su zama ana taimakon su ba.
Sa'an nan a lõkacin da Ubangijinsa, Ya kuranye zuwa ga dũtsen, Ya sanyã shi niƙaƙƙe.
Waɗancan manzannin Mun fĩfĩta sãshensu a kan sãshe: Daga cikinsu akwai wanda Allah Ya yi masa magana; kuma Ya ɗaukaka sãshensu da darajõji; kuma Muka bai wa Ĩsã dan Maryama hujjõji bayyanannu, kuma Muka ƙarfafã shi da Rũhi mai tsarki.
(Kowannenku) Yanã da waɗansu malã'iku mãsu maye wa jũna a gaba gare shi da bãya gare shi, sunã tsare shi daga umurnin Allah.
Kuma Allah ne da mallakar sammai da ƙasa da abin da ke a tsakãninsu, Yanã halitta abin da Yake so.
KursiyyunSa ya yalwaci sammai da ƙasa.
Sunã tambayar ka game da sa'a, wai yaushe ne matabbatarta?
Kuma suna ciyar da abinci, a kan suna bukãtarsa, ga matalauci da marãya da kãmamme.
Sa'an nan kuma, gã ku, yã waɗannan! Kuna kashe kanku, kuma kuna fitar da wani ɓangare daga gare ku daga gidãjensu, kuna taimakon jũna a kansu da zunubi da zãlunci kuma idan kãmammu suka je muku kuna fansarsu alhãli kuwa shĩ fitar da su abin da aka haramta muku ne.
Ḥ.
Kuma idan Muka yi ni'ima a kan mutum, sai ya hinjire, kuma ya nĩsanta da gefensa, kuma idan sharri ya shãfe shi, sai ya kasance mai yanke ƙauna.
Lalle ne a cikin sammai da ƙasa akwai ãyõyi ga mãsu ĩmãni.
Lalle Allah Mai gãfara ne, Mai jin ƙai.
Kuma idan kuka yi tambaya a gare su a lõkacin da ake saukar da Alƙur'ãni, zã a bayyana maku.
Allah yanã nufin cẽwa, bã zai sanya musu wani rabo ba a cikin Lãhira kuma suna da wata azãba mai girma.
Kuma Allah bã zai jinkirta wa wani rai ba idan ajalinsa ya je.
Kada ku karkata zuwa ga waɗanda suka yi zãlunci har wuta ta shãfe ku. Kuma bã ku da waɗansu majiɓinta baicin Allah, sa'an nan kuma bã zã a taimake ku ba.
"Bã ka ganin karkata a cikinsa, kuma bã ka ganin wani tudu."
Ya ce: "Lalle ne, Shi Yana cewa: "Ita wata saniya ce fatsa-fatsa, mai tsan-tsan launi, tana faranta ran mausu kallonta."
To, lalle Mũ, Mãsu tukkãwa ne.
Waɗannan ne waɗanda Allah bai yi nufin Ya tsarkake zukãtansu ba.
Kuma wãne ne mafi zãlunci daga wanda ya ƙirƙira ƙarya ya Jingina ta ga Allah, alhãli kuwa shĩ, anã kiran sa zuwa ga Musulunci?
Bã zan tambaye ku wata dũkiya ba akansa, ijãrata ba ta zama ba, fãce daga Allah, kuma ban zama mai kõrar waɗanda suka yĩ ĩmãni ba.
Kuma an yiwo wahayin wannan Alƙur'ãni dõmin in yi muku gargaɗi da shi, da wanda lãbãri ya kai gare shi.
Kuma mutãnensa suka je masa sunã gaggãwa zuwa gare shi, kuma a gabãni, sun kasance sunã aikatãwar mũnãnan ayyuka.
Kanã gargaɗi kawai ne ga waɗanda ke tsoron Ubangijinsu a fake, kuma suka tsayar da salla. Kuma wanda ya tsarkake, to, yanã tsarkaka ne dõmin kansa.
Sunã cẽwa, "Yaushe ne wannan wa'adi zai auku idan kun kasance mãsu gaskiya?"
Lalle mũ, mun ji wani littãfi an saukar da shi a bãyãn Mũsã, mai gaskatãwa ga abin da ke a gaba da shi, yanã shiryarwa ga gaskiya da kuma zuwa ga hanya madaidaiciya.
Kuma Muka bar (yabo) a gare shi, a cikin mutãnen ƙarshe.
kuma me ya same ku, bã zã ku yi ĩmãni ba da Allah, alhãli kuwa manzonSa na kiran ku dõmin ku yi ĩmãni da Ubangijinku, kuma lalle Allah Ya karɓi alkawarinku (cẽwa zã ku bauta Masa)? (Ku bauta Masa) idan kun kasance mãsu ĩmãni.
Kuma Allah Mawadãci ne, Masani.
Sũ, darajõji ne a wurin Allah, kuma Allah Mai gani ne ga abin da suke aikatawa.
Shin, bã ku tunãni?
Sabõda haka, kada ka kira wani abin bautãwa na dabam tãre da Allah, sai ka kasance daga waɗanda ake yi wa azãba.
Ka ce: "To, ku zo da Attaura sa'an nan ku karantã ta, idan kun kasance mãsu gaskiya ne.
Kuma waɗansu 'yã'yan itãce bã su fita daga kwasfõfinsu, kuma wata mace bã ta yin ciki, kuma bã ta haihuwa, fãce da saninSa, kuma a rãnar da Yake kiran su (Ya ce): "Inã abõkan tãrayyaTa?" Sai su ce, "Mun sanar da Kai bãbu mai bãyar da shaida da haka nan daga gare mu."
Sai ya nũna masa ãyar nan mafi girma.
Allah Ya sanya Ka'aba ¦aki Tsararre, ma'aunin addini ga mutane, kuma Yã sanya watã Mai alfarma da hadaya da rãtayõyin Allah Yã san abin da yake a cikin sammai da abin da yake a cikin ƙasa, kuma cewa lalle Allah, ga dukkan, kõme, Masani ne.
Kuma zã ka ga kõwace al'umma tanã gurfãne, kõwace al'umma anã kiran ta zuwa ga littãfinta. (A ce musu) "A yau anã sãka muku da abin da kuka kasance kunã aikatãwa."
"Aminci ya tabbata a kanku sabõda abin da kuka yi wa haƙuri.
To, lalle Mũ, Mãsu tukkãwa ne.
Lalle ne Allah mãdalla da abin da Yake yi muku wa'azi da shi. Lalle ne Allah Yã kasance Mai ji ne, Mai gani.
Ya ce: "To ku ɗanɗani azaba sabõda abin da kuka kasance kuna yi na kãfirci."
Lalle ne Fir'auna da Hãmãna da rundunõninsu, sun kasance mãsu aikin ganganci.
Ã, a' kun dai kasance mãsu laifi."
Sa'an nan Allah Mamallaki, Tabbatacce Yã ɗaukaka.
Kuma ba Mu sanya abin da ya gani wanda Muka nũna maka ba, fãce dõmin fitina ga mutãne, da itãciya wadda aka la'anta a cikin Alƙur'ani.
Ka ce: "Ku yi tafiya cikin ƙasa, sa'an nan ku dũba yadda (Allah) Ya fãra yin halitta, sa'an nan kuma Allah Yanã ƙãga wata halittar mayarwa.
Kuma idan kuka yi kira zuwa ga salla, sai su riƙe ta bisa izgili da wãsa.
Kuma waɗanda bã su fatan haɗuwa da Mu suka ce: "Don me ba a saukar da malã'ĩku ba a kanmu, kõ kuwa mu ga Ubangijinmu?"
Don me kuke kãfirta da ãyõyin Allah, alhãli kuwa Allah Mai shaida ne a kan abin da kuke aikatãwa?"
Hanyar Allah wanda ke da mulkin abin da ke cikin sammai da abin da ke cikin ƙasa.
"Amma Jirgin, to, ya zama na waɗansu matalauta ne sunã aiki a cikin tẽku, sai na yi niyyar in aibanta shi, alhãli kuwa wani sarki ya kasance a gaba gare su, yanã karɓẽwar kõwane jirgi (lãfiyayye) da ƙwãce.
Ta ce: "Kamar dai shĩne.
Kuma wanda yake wadãtacce, to, ya kãma kãnsa, kuma wanda yake faƙĩri, to, ya ci, gwargwadon yadda ya kamata.
To, shin, akwai wani abu a kan Manzanni, fãce iyarwa bayyananniyã?
To, mẽne ne sakamakon wanda ke aikata wancan daga gare ku fãce wulãkanci a cikin rãyuwar dũniya? Kuma a Rãnar ¡iyãma ana mayar da su zuwa ga mafi tsananin azãba.
Ashe, ba Mu halakar da (mãsu ƙaryatãw) na farko ba.
Kuma dõmin Ya tsarkake abin da ke cikin zukãtanku.
Zã Ni karkatar da waɗanda suke yin girman kai a cikin ƙasa, bã da wani hakki ba, daga ãyõyiNa.
Alhãli kuwa su suna ɗaukar kayansu masu nauyi a kan bayayyakinsu.
To, lalle ne waɗanda ke shakka a cikin Sa'a, haƙĩƙa, sunã a cikin ɓata Mai nĩsa.
Suka ce: "Mun yi ĩmãni, kuma ka shaida da cewa lalle mu, mãsu sallamãwa ne."
Kuma a lõkacin da aka ce masu: "Ku zauna ga wannan alƙarya, kuma ku ci daga gare ta, inda kuka so, kuma ku ce: 'Saryarwa,' kuma ku shiga kõfa kuna mãsu sujada; Mu gãfarta muku laifuffukanku, kuma zã Mu ɗãra wa mãsu kyautatãwa."
Lalle ne muna ƙõne shi, sa'an nan kuma munã shẽƙe shi, a cikin tẽku, shẽƙẽwa."
Kuma idan Allah Ya shãfe ka da wata cũta, to, bãbu mai yãyẽ ta fãce shi, kuma idan Yanã nufin ka da wani alhẽri, to, bãbumai mayar da falalarSa.
Ku bi abin da aka saukar zuwa gare ku daga Ubangijinku, kuma kada ku dinga bin wasu majiɓinta baicinSa.
Ã'a, kã yi mãmãki, alhãli kuwa sunã ta yin izgili.
Yanã shirya al'amari, Yanã rarrabe ãyõyi daki-daki, mai yiwuwa ne ku yi yaƙĩni da haɗuwa da Ubangijinku.
Kuma lalle ne idan wata falala daga Allah ta sãme ku haƙĩƙa, tabbas, yanã cẽwa, kamar wata sõyayya ba ta kasance a tsakãninku da shi ba: "Yã kaitona!
Lalle Allah, Shĩ ne Mai azurtãwa, Mai ĩkon yi, Mai cikakken ƙarfi.
Kuma suka bi abin da shaiɗãnu ke karantawa a kan mulkin Sulaimãnu, kuma Sulaimãnu bai yi kãfirci ba, kuma Shaidãnun, sũ ne suka yi kãfirci, suna karantar da mutãne sihiri.
Ã'a ku mutãne ne daga waɗanda Ya halitta, Yanã gãfartãwa ga wanda Yake so, kuma Yanã azabta wanda Yake so.
Kuma wanda ya jũya bãya, to, ba Mu aike ka ba don ka zama mai tsaro a kansu.
(Ka ce): "An umurce ni, in bauta wa Ubangijin wannan Gari, Wanda Ya mayar da shi Hurumi, kuma Yanã da dukan kõme.
Lalle ne inã gani, a ciki barci, lalle inã yanka ka. To, ka dũba mẽ ka gani?"
Akwai tsammãnin Allah Ya karɓi tũba a kansu.
Kada ku riƙi maƙiyĩNa kuma maƙiyinku masõyi, 845.
To, sabõda warwarewarsu ga alkawarinsu Muka la'ane su, kuma Muka sanya zukãtansu ƙeƙasassu, sunã karkatar da magana daga wurãrenta, kuma suka manta da wani yanki daga abin da aka tunãtar da su da shi, kuma bã zã ka gushe ba kana tsinkãyar yaudara daga gare su fãce kaɗan daga gare su.
Kuma lalle ne shi (Alƙur'ãni) tanãtarwa ce ga mãsu taƙawa.
Kuma Allah Yã sanya muku mãtan aure daga kãwunanku, kuma Ya sanya muku daga mãtan aurenku ɗiyã da jĩkõki, kuma Ya arzũta ku daga abũbuwa mãsu dãɗi. Shin fa, da ƙarya suke yin ĩmãni, kuma da ni'imar Allah sũ, suke kãfirta?
To, a lõkacin da Mũsã ya jẽ musu da ãyõyinMu bayyanannu, suka ce: "Wannan ba kõme ba sai sihiri, wanda aka ƙãga, kuma ba mu ji wannan ba daga wajen ubanninmu na farko."
To, zã su gyaɗa kansu zuwa gare ka, kuma sunã cẽwa, "A yaushene shi?"
Ana shayarwa da su, a cikinta, finjalan giya, wadda abin gaurayarta ya kasance zanjabil ne.
Ya ce: "Kuma bã ni da sani ga abin da suka kasance sanã aikatãwa."
Lalle ne samũdãwa sun kãfirce wa Ubangijinsu.
Kuma dukansu Allah Ya yi musu wa'adi da (sakamako) mai kyau, kuma Allah Masani ne ga abin da kuke aikatãwa.
Kuma ka yi gargaɗi ga mutãne ga rãnar da azãba take jẽ musu, sai waɗanda suka yi zãlunci su ce: "Yã Ubangijinmu!
Kuma lalle ne wanda ya turbuɗe shi (da laifi) ya tãɓe.
Kuma a lõkacin da wani manzo (Muhammadu) daga wurin Allah ya je musu, mai gaskatãwa ga abin da yake tãre da su, sai wani ɓangare daga waɗanda aka bai wa Littãfi, suka yar da Littãfin (Alƙur'ãnin) Allah a bãyan bãyansu, kamar dai sũ ba su sani ba.
Kuma kiran kãfirai (ga wanin Allah) bai zama ba fãce yanã a cikin ɓata.
Kuma kamar wancan, Muka sanya ku al'umma matsakaiciya dõmin ku kasance mãsu bãyar da shaida a kan mutãne. Kuma Manzo ya kasance mai shaida a kanku.
To, wanda ya jũya a kan dugadugansa, bã zai cũci Allah da kõme ba.
To, bone ya tabbata ga waɗanda suke rubũta littãfi da hannuwansu sa'an nan kuma su ce wannan daga wurin Allah yake, dõmin su sayi kuɗi kaɗan da shi, san nan bone ya tabbata a gare su daga abin da hannayensu ke rubũtãwa, kuma bone ya tabbata a gare su daga abin da suke sanã'antãwa.
Kuma Mũsã ya ce: "Lalle nĩ, nã nẽmi tsari da Ubangijĩna kuma Ubangijinku, daga dukan makangari, wanda bã ya ĩmani da rãnar Hisãbi."
Kuma sun kõma da fushi daga Allah, kuma aka dõka talauci a kansu. Wannan kuwa dõmin sũ, lalle sun kasance suna kãfirta da ãyõyin Allah, kuma suna kashe annabãwa, bã da wani haƙƙi ba.
Kuma waɗanda suke taskacẽwar zĩnãriya da azurfa, kuma bã su ciyar da ita a cikin hanyar Allah, to, ka yi musu bushãra da azãba mai raɗaɗi.
Bãbu abin bautãwa fãce shi.
